// =============================================================
// trials81_part1.js - 八十一难数据（第一部分：TRIAL_LIB 81难剧情）
// 从 trials81.js 拆分，第1-1264行
// 外部接口 NDX.* 保持不变，调用方无需修改
// 拆分日期: 2026-09-14
// =============================================================

﻿// ============================================================================
//  八十一难数据库（劫难剧情库 + 难名表）
//  独立维护：本文件包含全部 81 难的剧情与命名数据。
//  数据表：NDX.TRIAL_LIB（1~81 难剧情条目：name/act/type/icon/dark/intro/options/treasure/hidden）
//          NDX.TRIAL_BOSS（难号 1~81 → 登场敌方/劫难名 映射）
//  服务函数：NDX.trialBossName（按难号取登场敌方名，回退用劫难名本身）
//  2026-09-01 原著地理重排：难号按 17 地区原著地理重新编号；原 57-80 返程段移至 NDX.RETURN_TRIALS（隐藏保留·后续开发）。
//  修改某一难的名称/章节(act)/类型(type)/黑暗独白(dark)/选项(options)/隐藏职(hidden)，
//  直接编辑 NDX.TRIAL_LIB 中对应 id 即可；修改战斗中登场的敌名，编辑 NDX.TRIAL_BOSS。
// ============================================================================

NDX.TRIAL_LIB = {
  1: { id: 1, name: '金蝉遭贬', act: 1, type: 'story', icon: '✦',
    portrait: '灵吉菩萨',
    fate: '渡', echo: '逆线→弃经金蝉(取经人)种子；二周目转生既定伏笔',
    // V8.27 follow-up：三段合并为一页，去掉「第一段｜金光」等分段提示词，让叙事一气呵成。
    // V8.33 难1文案重写：初始即「灵山遭贬·轮回道口」当下场景，接引使者持鞭拦路——去掉旧「出长安第一夜·破庙入梦」结构（送行事件已后移，出长安不再发生于首难前）。
    dark: '灵山讲经台上，你问如来："大乘度己，小乘度人——若经书本身便是枷锁，度的是谁？"满座无声。上座执事合掌，袖中账簿滑出一角，你瞥见了上面的字。法判你"轻慢"，贬你十世轮回。你被贬下界，接引使者持鞭拦在轮回道口，皮笑肉不笑——"金蝉子投的胎，还得爷送。"可你下界时，天庭仍给你留了"取经人"的牌子——没人敢真断了这条香火。你摸了摸自己的脸，确认这世还是这世。前世那句问话还在耳边，你把它收进行囊，抬脚往西。',
    intro: '灵山云端，金蝉子一句问话触怒灵山法统，被贬下凡十世轮回。轮回道口，接引使者持鞭拦路——这第一难，先识六道、习战斗。', sixdaoSelect: true,
    options: [
      // —— V8.58 六道直选：取消顺命/争胜/避世三分组，六道长横条直接展示 ——
      { key: '渡', label: '双手捧钵，承佛之命', fate: '渡',
        tip: '双手捧钵——成佛之命。你将踏上渡道，观音好感结缘；得「紫金钵盂·虚」基座，善+10',
        guanyinTip: '观音菩萨：渡者，慈悲顺命，渡己渡人。诵经可渡敌，钵盂可承佛之命——此道仁厚绵长，然杀伐不足，遇强魔时需借法宝之力。',
        longDesc: '渡道 · 慈悲顺命 · 诵经渡敌 · 观音结缘 · 紫金钵盂',
        effect: { alignGood: 10, favor: '观音', material: '紫金钵盂·虚' } },
      { key: '缘', label: '指尖触钵，惜众生缘', fate: '缘',
        tip: '指尖触钵——惜众生缘。你将踏上缘道；得「紫金钵盂·虚」基座（不结缘观音），善+8',
        guanyinTip: '观音菩萨：缘者，广结善缘，随缘而安。防御加身，肉生成圣——此道稳如磐石，然进取不足，需借劫印突破瓶颈。',
        longDesc: '缘道 · 广结善缘 · 防御加身 · 肉生成圣 · 稳如磐石',
        effect: { alignGood: 8, material: '紫金钵盂·虚' } },
      { key: '战', label: '夺鞭立威，驱而不伤', fate: '战', noFight: true,
        tip: '夺鞭立威——驱而不伤。你将走上战道，恶+8，落定首枚战印',
        guanyinTip: '观音菩萨：战者，以力破局，杀伐果断。以杀止杀，以力破法——此道威猛却折寿，每战需速战速决，久战必亏。',
        longDesc: '战道 · 以力破局 · 杀伐果断 · 以杀止杀 · 威猛折寿',
        effect: { alignEvil: 3 } },
      { key: '夺', label: '抽走鞭梢，掠走物证', fate: '夺', noFight: true,
        tip: '掠走物证——你将走上夺道；得「青驴鞭影」兵刃 1 件，恶+10',
        guanyinTip: '观音菩萨：夺者，巧取豪夺，利益至上。夺取宝物，万宝附体——此道富贵险中求，然失道寡助，心魔易涨，需持正念压之。',
        longDesc: '夺道 · 巧取豪夺 · 万宝附体 · 富贵险求 · 心魔易涨',
        effect: { alignEvil: 10, material: '青驴鞭影', equipPick: 1, slot: 'weapon' }, setFlag: 'n1_duodao' },
      { key: '隐', label: '任碎石盖身，避世无痕', fate: '隐',
        tip: '任碎石盖身——避世无痕。你将走上隐道；闪避 +8、善+6、心魔不涨',
        guanyinTip: '观音菩萨：隐者，避世潜行，明哲保身。万物成空，无道无我——此道身法卓绝，然正面交锋乏力，需借闪避与暴击制敌。',
        longDesc: '隐道 · 避世潜行 · 明哲保身 · 身法卓绝 · 闪避暴击',
        effect: { alignGood: 1, eva: 8 } },
      { key: '逆', label: '我问一句：账簿上我值几文', fate: '逆',
        tip: '我问一句——你将踏上逆道；触发「直问天条」经文洞察，恶+6',
        guanyinTip: '观音菩萨：逆者，逆天改命，不走寻常。我命由我，普度众人——此道最为凶险，须先炼成一世正果（完美通关）方得入此道，然一旦入道，天地皆为之侧目。',
        longDesc: '逆道 · 逆天改命 · 我命由我 · 最为凶险 · 天地侧目',
        effect: { alignEvil: 6, sutraInsight: '直问天条' } },
    ],
    hidden: { hero: 'tangseng', cond: '逆 + 紫金钵', job: '弃经金蝉', hint: '序章碎金钵、走逆——你自弃经那一刻，便已入逆道之始', desc: '愿伤+30%，但每战恶+5' },
    // 序章叙事劫难也应有收获：金蝉子前世遗泽——金蝉舍利（温和续命法宝，非战斗回约50%气血，无本心代价）
    treasure: { id: 'jinchan', type: 'treasure', note: '金蝉舍利·序章机缘（原著：金蝉子十世余泽）' } },
  2: { id: 2, name: '出胎几杀', act: 1, type: 'fight', icon: '⚔',
    portrait: '刘洪',
    fate: '战', echo: '',
    // V8.33 去掉「第一段｜金光」等分段提示词（与难1 V8.27 统一，三段叙事一气呵成）
    dark: '襁褓之中，你借这具不足满月的身睁眼。江声入耳，你合眼，忽入一梦——出生这一夜，你的状元父亲接旨赴任——灵山连"爹"都替你选好了：一个注定活不过上任途中、也没活过你满月的宿世故人。你睁眼，见母亲殷温娇跪在血水里；窗外一个黑衣官差领着水卒，正一道一道数她身上那道帘。他腰牌上，刻着灵山的莲花纹。\n' +
      '刘洪不是来抢位子的，是来"验货"的。货单上写得分明：金蝉子 · 第一世，该死于满月。他奉命，让你死在难簿记该记的那一页。可他漏算了一样——你的娘，是个甘愿把整条命押上，也要跟你换一个"活"字的人。\n' +
      '木盆浮在水上，你娘把你放进江里。她不哭，她哭着求的只有三个字——"别回头"。江流暗涌，岸上仪仗敲锣打鼓，像在送一具货。你忽然懂了：这世上的爹不止陈光蕊一个人；牌上那朵莲，也从不只挂在他一个人的腰上。梦醒时，你正攥着那领袈裟，指节发白。你摸了摸鬓角，那里已添一缕霜白——西行路上，每历一难，寿数便短一分；寿尽之日，便是大限坐化之时。此身有尽，须惜命而行。',
    intro: '襁褓之中，江声入耳。刘洪水卒破府，刀光漫过廊下，母亲殷温娇将你护在怀中。满月未至，杀机先至——这一夜，你借这具不足满月的身，走你十世里的第一笔。战或渡，随你。',
    options: [
      { key: '战', label: '护母突围，夺路而走', fate: '战', fight: true, battleFlags: { openingMomentum: 1 },
        effect: { alignGood: 4 } },
      { key: '渡', label: '随江流漂走，顺命入劫', fate: '渡',
        effect: { alignGood: 10 } },
      { key: '隐', label: '藏入棺椁，权且避世', fate: '隐', noDao: true,
        effect: { alignEvil: 2 } },
      // 网状叙事（P0）新增：难2 第四选项「隐忍待发」——落 n2_yinren 印记，解锁难4「逼问真相」分支。
      // 硬约束：原三选项（战/渡/隐）文本一字未动，仅在其后追加此第四项。
      { key: '忍', label: '隐忍待发，暗中记下仇人', fate: '隐', noDao: true,
        effect: { alignGood: 2 }, setFlag: 'n2_yinren' }
    ],
    // 第2难必掉袈裟基座（取经人只走袈裟单一路线：袈裟胚→+金线/佛纹→锦襕袈裟）
    treasure: { id: 'ts_robe_base', type: 'armor', hp: 90, dr: 0.05, mdef: 0.05, note: '袈裟胚·取经人专属基座' } },
  3: { id: 3, name: '满月抛江', act: 1, type: 'story', icon: '✦',
    portrait: '江流儿',
    fate: '渡', echo: '战副→前世金身暗线(与第70难回扣)；渡副→弃经链；宿慧记忆伏笔',
    // V8.33 去掉「第一段｜金光」等分段提示词（与难1 V8.27 统一）
    dark: '满月当空，母亲把你放进木盆，推入江中。江水拍岸，木盆顺流而下，你睁着眼看天，天上那轮满月，像法统簿上盖的印。她笑着推你走，眼里是解脱——她知道留你必死。\n' +
      '江心浮起一具若有似无的金身，是你前世的残影——它正等你回头，替你把余生走完。你伸手去够，指尖却穿过那光，只捞起一捧江水。\n' +
      '江水东去，你漂过无人渡口，身侧那领袈裟被露水打湿。江声依旧，月影沉在水底。你望着那轮月，忽然懂了：木盆里的孩子与此刻的你，原是同一人。你起身，披上袈裟，继续往西。',
    intro: '满月当空，母亲将你放入木盆，推入江中。江水东去，这一漂从死处漂到活处——你借襁褓之身，睁眼看那轮满月。渡或战，随你。',
    options: [
      { key: '渡', label: '听江声，认这一漂', fate: '渡', effect: {alignGood: 10} },
      { key: '战', label: '召唤前世金身，与之一战', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignEvil: 8 } },
      { key: '隐', label: '合眼不看那轮满月印', fate: '隐', noDao: true, effect: {alignGood: 1} }
    ],
    // 序章漂流叙事也应有收获：江流浮木中裹着一领袈裟胚（与取经人单一袈裟线一致）
    treasure: { id: 'ts_robe_base', type: 'armor', hp: 90, dr: 0.05, mdef: 0.05, note: '袈裟胚·序章机缘' } },
  4: { id: 4, name: '寻亲报冤', act: 1, type: 'fight', icon: '⚔',
    portrait: '刘洪',
    fate: '战', echo: '渡/逆副→弃经链；血溅公堂杀戮+',
    branchKey: 'n4_choice',   // 网状叙事（P0）：五选一落印，难5/6/7 据此渲染五种路径
    dark: '十八年后你持血书寻母。母亲已成刘洪之妻，见你如见鬼。你明白：复仇救不了任何人，只把你也变成"上面的人"。',
    // V8.33 丰富难4 intro：第一章关隘Boss叙事铺垫（十八年寻亲·江州公堂·刘洪的末路）
    intro: '十八年后，你持血书入江州。公堂之上，刘洪身着状元官服，端坐如旧——他占了你爹的位子、娶了你娘、用了你爹的名字，十八年。他见你，先是一愣，随即笑了："又来一个取经人。"你娘站在屏风后，指尖掐进掌心，不敢出声。这一战，是你西行前最后的人间债。蓄力重击时可识破反制。',
    options: [
      { key: 'shouren', label: '少年提剑，手刃刘洪', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignEvil: 6, ti: { atk: 9, hp: 56 } }, setFlag: 'n4_choice:shouren', consequence: '此选择将影响：难5-7江州余党路线' },
      { key: 'rao', label: '饶他一命，归隐山林', fate: '渡', effect: { alignGood: 15, ti: { eva: 3 } }, setFlag: 'n4_choice:rao' },
      { key: 'guanfu', label: '交官府查办，依法定罪', fate: '缘', effect: { alignGood: 10, gold: 30 }, setFlag: 'n4_choice:guanfu' },
      { key: 'biwen', label: '逼问真相，追查幕后', fate: '逆', ni: true, effect: { alignEvil: 15, rel: { 妖王: +3 } }, setFlag: 'n4_choice:biwen', requireFlag: 'n2_yinren' },
      { key: 'jiaoyi', label: '交易放走，各取所需', fate: '夺', effect: { alignEvil: 10, gold: 50 }, setFlag: 'n4_choice:jiaoyi', requireFlag: 'n1_duodao' },
      // 跨周目回响（P3）：二周目以上、且上周目难4曾选「逼问真相(biwen)」时，此世浮现「前世记忆」选项
      //   requireFlag __echo_n4_biwen 由 enterNode 在加载难4前依上周目 echo 落印开门（见 game_core_2.js）
      { key: 'echo', label: '前世记忆浮现——你记得刘洪的下场', fate: '隐', noDao: true, effect: { alignGood: 5, gold: 20 }, setFlag: 'n4_choice:echo', requireFlag: '__echo_n4_biwen', consequence: '前世回响：你记得逼问真相的后果，此世选择不同', tip: '二周目专属：上周目曾选「逼问真相」，此世你带着记忆而来' }
    ],
    // 第4难必掉袈裟基座（取经人只走袈裟单一路线）
    treasure: { id: 'ts_robe_base', type: 'armor', hp: 90, dr: 0.05, mdef: 0.05, note: '袈裟胚·取经人专属基座' } },
  5: { id: 5, name: '出城逢虎', act: 2, type: 'fight', icon: '⚔',
    fate: '缘', echo: '战副→伯钦之缘(人伦线)',
    branchKey: 'n4_choice',
    // 网状叙事（P0）：出城逢虎的五种面目——依难4「寻亲报冤」之抉择渲染
    branches: {
      shouren: { dark: '你斩了刘洪，血还没干。出城这只虎，眼里映的不是兽性，是人的怨——它是刘洪帐下旧卒，当年同死江中，怨气寄在虎身上。它不扑，只盯着你腰间那柄染血的剑。',
        intro: '长安城外，猛虎伏在路心，虎瞳里映出你手刃刘洪那一剑的残影。猎户伯钦按住弓，低声道："师父，这虎……认得你。"',
        options: [
          { key: '战', label: '趁它未扑，先斩此僚以绝后患', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignEvil: 6, ti: { atk: 7, hp: 38 } } },
          { key: '夺', label: '剥它虎魄，祭刘洪旧部之怨', fate: '夺', effect: { alignEvil: 10, gold: 40 } },
          { key: '渡', label: '合掌超度那旧卒，怨散虎归山', fate: '渡', effect: { alignGood: 8, ti: { hp: 25, dr: 0.04 } } },
          { key: '逆', label: '问它——刘洪腰牌上那朵莲，你可认得', fate: '逆', ni: true, effect: { alignEvil: 6, rel: { 妖王: +5 } } },
        ] },
      rao: { dark: '你饶了刘洪。他归隐前托人送来一封谢帖、一包金。出城这虎，颈上系着红绫——是被人驯过的，见你便伏低，像在替那隐居老者谢你留恩。',
        intro: '长安城外，猛虎颈系红绫，伏地不起。伯钦收弓叹道："这虎三日前被一隐居老者驯了，说要等一位取经人路过——莫非，就是你？"',
        options: [
          { key: '渡', label: '受这虎一拜，放它守山', fate: '渡', effect: { alignGood: 10, rel: { 观音: +3 } } },
          { key: '缘', label: '收下刘洪谢礼，结这善缘', fate: '缘', effect: { alignGood: 5, gold: 60 } },
          { key: '隐', label: '不惊不扰，绕路而行', fate: '隐', effect: { alignGood: 4, ti: { eva: 4 } } },
        ] },
      guanfu: { dark: '你把刘洪交了官府，依法定罪。官差护你出城，开道锣声未歇。这虎本是山中精怪，不识人事，只被锣声惊了——它挡的不是你，是这一身官威。',
        intro: '长安城外，两排官差鸣锣开道。那猛虎本是山妖，被锣声惊起，拦在路心。伯钦在旁道："师父，官府的脸面，今天你得借一借。"',
        options: [
          { key: '缘', label: '借官府之势，令山妖退散', fate: '缘', effect: { alignGood: 4, gold: 20 } },
          { key: '战', label: '官差助阵，合力降妖', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignGood: 3, gold: 22 } },
          { key: '渡', label: '为山妖说情，逐而不杀', fate: '渡', effect: { alignGood: 8, ti: { dr: 0.03, eva: 7 } } },
        ] },
      biwen: { dark: '你逼问出真相——刘洪背后，是灵山的手。这只虎不是虎，是灵山再派来"验货"的一桩。它等在城外，只为确认你是不是那个坏了规矩的取经人。',
        intro: '长安城外，猛虎伏在路心，竟开口人言："灵山有令——坏规矩的取经人，不必再往西。"伯钦色变，退后三步。你握紧了腰间的剑。',
        options: [
          { key: '逆', label: '灵山的狗，也配拦我', fate: '逆', ni: true, effect: { alignEvil: 10, treasure: 'ni_sanshou' } },
          { key: '战', label: '斩了这灵山爪牙', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignEvil: 6, ti: { atk: 6, dr: 0.03 } } },
          { key: '缘', label: '虚与委蛇，探它口风', fate: '缘', effect: { alignGood: 2, ti: { hp: 50 } } },
        ] },
      jiaoyi: { dark: '你与刘洪做了交易，放他一条生路，各取所需。可他不信你——出城这只虎，是他雇来杀你灭口的。生意人，从不留活口。',
        intro: '长安城外，猛虎眼露凶光，颈间藏着一截江州官坊的丝绦。伯钦低声："师父，这虎脖子上的丝绦……是江州官坊的货色。"你笑了——刘洪果然不信你。',
        options: [
          { key: '夺', label: '将计就计，反杀这杀手', fate: '夺', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignEvil: 8, gold: 50 } },
          { key: '战', label: '先下手为强', fate: '战', fight: true, effect: { alignEvil: 5, ti: { hp: 41 } } },
          { key: '渡', label: '点破刘洪阴谋，放虎归山传话', fate: '渡', effect: { alignGood: 6, yuan: { mdef: 0.03 } } },
          { key: '逆', label: '告诉刘洪：这笔买卖，我记下了', fate: '逆', ni: true, effect: { alignEvil: 6, gold: 12 } },
        ] },
    },
    dark: '长安城外，猛虎实为城隍所化——它吃的是"逾期未归的取经人魂"。猎户伯钦救你，他爹也是取经人，没回来。',
    // V8.33 丰富难5 intro：第二章首战叙事铺垫（长安城外·猛虎·猎户伯钦）
    intro: '长安城外，荒草齐腰。一只吊睛白额虎伏在路心，不吼不扑，只是盯着你——它眼里没有兽性，只有一种"等了很久"的疲惫。山后转出猎户伯钦，弓已拉满："师父快走，这虎，吃过九世取经人。"',
    options: [
      { key: '战', label: '猎户助阵，双人杀虎', fate: '战', effect: { alignGood: 3, ti: { atk: 6 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '放虎归山，为伯钦爹立一坟', fate: '渡', effect: { alignGood: 10, ti: { hp: 40 } } },
      { key: '缘', label: '受伯钦赠刀，结这一山之缘', fate: '缘', effect: { alignGood: 6, equipPick: 3 } },
      { key: '逆', label: '问它一句——九世取经人，是谁叫你吃的', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_sanshou' } },
    ],
    // 第5难必掉袈裟基座（取经人只走袈裟单一路线）
    treasure: { id: 'ts_robe_base', type: 'armor', hp: 90, dr: 0.05, mdef: 0.05, note: '袈裟胚·取经人专属基座' } },
  6: { id: 6, name: '落坑折从', act: 2, type: 'event', icon: '✦',
    fate: '缘', echo: '逆副→逆鳞白龙(小白龙)种子；避水珠前置',
    branchKey: 'n4_choice',
    // 网状叙事（P0）：落坑折从的五种遭遇——太白金星的态度随难4抉择而变
    branches: {
      shouren: { dark: '双叉岭陷坑，两个随从被寅将军吞了。你刚斩了刘洪，杀气未散。太白金星化身老者，看你的眼神像看一把迟早要卷刃的刀——这坑是按难簿挖的，你这把刀，也在簿上。',
        intro: '太白金星拄杖而立，见你满身血煞，眉头微皱："取经人，你这一身的杀气，比岭上的妖还重。"他指了指坑底被啃剩的衣袍，"这坑，原是给你挖的。"',
        options: [
          { key: '战', label: '拔刀护住剩下那两个从人', fate: '战', fight: true, effect: { alignGood: 3, ti: { atk: 5, hp: 54 } } },
          { key: '逆', label: '既然坑是给我挖的——我倒要挖回去', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +5 } } },
          { key: '渡', label: '为随从收尸立碑', fate: '渡', effect: { alignGood: 8, ti: { hp: 26, dr: 0.04 } } },
        ] },
      rao: { dark: '双叉岭陷坑，你饶刘洪的那点善念似乎护着你——寅将军扑来时，被一阵山风卷走。太白金星化身老者，点头道："留一线恩，得一线命。"',
        intro: '太白金星化身老者引路，见你眼底有未散的温善，含笑点头："取经人，善有善报——这一坑，你掉得比旁人轻。"坑底，两个随从虽伤未死。',
        options: [
          { key: '渡', label: '为伤者敷药，谢金星引路', fate: '渡', effect: { alignGood: 12, ti: { hp: 52, dr: 0.03 } } },
          { key: '缘', label: '受老者指引，继续西行', fate: '缘', effect: { alignGood: 4, gold: 20 } },
        ] },
      guanfu: { dark: '双叉岭陷坑，两个随从慌乱呼救。你身后还跟着官差仪仗，太白金星化身老者，见这阵仗便知你走了官府门路——他冷笑："取经人也学会拿官府压妖了。"',
        intro: '太白金星拄杖而立，瞥了你身后的官差一眼，淡淡道："靠官府的脸面过岭，过得了初一，过不了灵山。"坑底，寅将军闻官威而退。',
        options: [
          { key: '缘', label: '令官差护从人，过岭', fate: '缘', effect: { alignGood: 4, gold: 30 } },
          { key: '渡', label: '为从人收尸立碑', fate: '渡', effect: { alignGood: 8, ti: { dr: 0.03, eva: 6 } } },
        ] },
      biwen: { dark: '双叉岭陷坑，你盯着太白金星：灵山连刘洪都安排了，这坑，是不是也是他们挖的？老者沉默良久，忽然叹了口气——这是他第一次，没把你当"取经人"看。',
        intro: '太白金星化身老者，被你一句"灵山的人，凭什么怜悯"问得久久无言。末了他压低声音："取经人，有些话，说了我这星便做不成了……但你既已查到刘洪背后，我便告诉你一句——簿子上，不止你一个取经人。"',
        options: [
          { key: '逆', label: '记下这句，继续往西查', fate: '逆', ni: true, effect: { alignEvil: 8, yuan: { matk: 6, mdef: 0.02 } } },
          { key: '缘', label: '谢金星透露，结一线情', fate: '缘', effect: { alignGood: 3, yuan: 3 } },
          { key: '渡', label: '为随从收尸，把话埋在心里', fate: '渡', effect: { alignGood: 6, yuan: { mdef: 0.03 } } },
        ] },
      jiaoyi: { dark: '双叉岭陷坑，你一眼看出不对——这坑壁上的削痕太新，不是寅将军的爪子，是人为。刘洪雇人挖的。他要灭口，灭口在半路上。',
        intro: '太白金星尚未开口，你已蹲下身，摸了摸坑壁——新土、削痕、一截江州官坊的木楔。你冷笑：刘洪的买卖，做到双叉岭来了。',
        options: [
          { key: '夺', label: '拆了这陷阱，反埋一层', fate: '夺', effect: { alignEvil: 8, gold: 40 } },
          { key: '战', label: '顺着木楔，找出埋伏的杀手', fate: '战', fight: true, effect: { alignEvil: 5, yuan: { mdef: 0.03 } } },
          { key: '逆', label: '把木楔留作证，将来与刘洪算账', fate: '逆', ni: true, effect: { alignEvil: 5, ti: { atk: 5 } } },
        ] },
    },
    dark: '双叉岭陷坑，两个随从被寅将军吃掉。你发现坑是"按难簿挖好的"——你每一步，都被写好了。',
    intro: '太白金星化身老者引路（金星是灵山眼线，但这次他心生怜悯）。',
    options: [
      { key: '渡', label: '为随从收尸立碑', fate: '渡', effect: { alignGood: 10, ti: { hp: 35 } } },
      { key: '缘', label: '受老者指引', fate: '缘', effect: { alignGood: 4, gold: 20 } },
      { key: '战', label: '拔刀护住剩下那两个从人', fate: '战', effect: { alignGood: 3, ti: { atk: 10, dr: 0.04 } } },
      { key: '逆', label: '不信老者——灵山的人，凭什么怜悯', fate: '逆', ni: true, effect: { alignEvil: 5, yuan: { matk: 9 } } },
    ],
    hidden: { hero: 'xiaobailong', cond: '逆 + 避水珠', job: '逆鳞白龙', hint: '鹰愁涧择「逆」取避水珠，龙族的逆鳞只认逆路之人', desc: '闪避+25%，水战无敌' },
    // 太白金星引路——避水珠·黯（8.11 难6 专属·小白龙逆鳞白龙转职持有门槛件）
    treasure: { id: 'bis_an', type: 'treasure', note: '避水珠·黯·落坑机缘（8.11 难6 专属）' } },
  7: { id: 7, name: '双叉岭上', act: 2, type: 'fight', icon: '◐',
    fate: '战', echo: '渡副→残魂路标呼应第58难',
    branchKey: 'n4_choice',
    // 网状叙事（P0）：双叉岭残魂路标的五种面目——按难4抉择显不同残魂
    branches: {
      shouren: { dark: '岭上魔影重叠，历代取经人残魂筑的路标。其中一缕不穿僧衣——是刘洪的怨念。他不甘心被你一剑斩了，缠着你，要你也尝尝横死江中、不得超生的滋味。',
        intro: '雾里残魂浮动，其中一缕血袍人影上前，面目扭曲——是刘洪。他嘶声道："你斩我一剑，我缠你一路。取经人，你的剑沾过我的血，就洗不干净了。"',
        options: [
          { key: '战', label: '再斩刘洪怨念一次', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignEvil: 6, ti: { atk: 12, hp: 46 } } },
          { key: '逆', label: '告诉他：血债，你认', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +4 } } },
          { key: '渡', label: '为他念一段往生咒', fate: '渡', effect: { alignGood: 10, ti: { hp: 42, dr: 0.02 } } },
        ] },
      rao: { dark: '岭上残魂路标浮动。其中一缕不穿僧衣，却低着头——是刘洪的忏悔。你饶过他，他多活了几年，却夜夜梦见那一夜血书。他来，是替你开路。',
        intro: '雾里残魂中，一缕血袍人影合十而立，声音沙哑："取经人，你留我一命，我却用余生夜夜赎罪。这双叉岭的残魂，我替你拦着——你走。"',
        options: [
          { key: '渡', label: '受他一拜，继续西行', fate: '渡', effect: { alignGood: 15, rel: { 观音: +3 } } },
          { key: '缘', label: '问他一句当年实情', fate: '缘', effect: { alignGood: 6, gold: 30 } },
        ] },
      guanfu: { dark: '岭上残魂浮动，见你身后官差仪仗，竟纷纷退避——它们生前，都是被官府冤死的取经人。你借的官府势，此刻成了你的路障，也是你的护身符。',
        intro: '太白金星已去。双叉岭残魂见你腰间官凭，雾竟散了三分。你忽然明白：官府的脸面，在这鬼地方，比佛经还管用。',
        options: [
          { key: '缘', label: '亮明官凭，借势过岭', fate: '缘', effect: { alignGood: 4, gold: 20 } },
          { key: '渡', label: '为冤死的残魂念一卷经', fate: '渡', effect: { alignGood: 12, yuan: { matk: 7, mdef: 0.03 } } },
        ] },
      biwen: { dark: '岭上残魂路标中，一缕穿锦襕袈裟的上前——他是上一个取经人，你十世之一。他不劝你走，也不劝你停，只把账簿的一角亮给你看：你这一世，是第九个。',
        intro: '雾里，一个穿锦襕袈裟的残魂上前，声音像从水底传来："取经人，你查到刘洪背后是灵山——那我告诉你，灵山脚下，埋着八个和你一模一样的取经人。这第九世，你打算怎么走？"',
        options: [
          { key: '逆', label: '第九世？那我走第十条路', fate: '逆', ni: true, effect: { alignEvil: 10, yuan: { matk: 9, mdef: 0.02 } } },
          { key: '渡', label: '问他可愿随你同行', fate: '渡', effect: { alignGood: 8, yuan: { mdef: 0.03 } } },
          { key: '战', label: '斩这令人心冷的路标', fate: '战', fight: true, effect: { alignEvil: 5, gold: 23 } },
        ] },
      jiaoyi: { dark: '岭上残魂浮动，却齐齐朝你围来——刘洪用最后一笔钱，买通了这些怨魂，要你死在双叉岭。生意人，生意做到了阴司。',
        intro: '雾里残魂不诵"别走快走"，反而齐声扑来。你闻见一股江州官坊的香灰味——刘洪把最后的银子，烧给了它们。',
        options: [
          { key: '夺', label: '反买通它们，指刘洪的死路', fate: '夺', effect: { alignEvil: 10, gold: 60 } },
          { key: '战', label: '杀出血路', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignEvil: 6, ti: { atk: 12, dr: 0.03 } } },
          { key: '逆', label: '告诉残魂：刘洪的钱，买得动你们，买不动我', fate: '逆', ni: true, effect: { alignEvil: 6, gold: 30 } },
        ] },
    },
    dark: '岭上魔影重叠，是历代取经人残魂筑的"路标"。它们求你别走，又求你快走——走是死，不走也是死，它们只是想有人替它们把这句话说出口。',
    // V8.33 丰富难7 intro：双叉岭残魂路标叙事
    intro: '双叉岭上，雾里浮着无数半透明的人影——他们穿着不同朝代的僧衣，朝同一个方向走，又在同一个地方停下。你听见他们在念同一句话，声音叠在一起，像风穿过破庙："别走……快走……"这是历代取经人残魂筑的路标。',
    options: [
      { key: '战', label: '斩残魂开路', fate: '战', effect: { alignEvil: 8, ti: { hp: 33 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '听它们说完名字，再走', fate: '渡', effect: { alignGood: 15, ti: { hp: 23 } } },
      { key: '隐', label: '绕行，不惊动这些残魂', fate: '隐', effect: { alignGood: 4, ti: { eva: 8 } } },
      { key: '逆', label: '把那句「别走」替它们说完——这路，我接着走', fate: '逆', ni: true, effect: { alignEvil: 6, yuan: { matk: 9 } } },
    ],
    // 第7难必掉装备（修复"劫难打怪不掉装备"）
    treasure: { id: 'ss_skull_base', type: 'treasure', hp: 18, dr: 0.04, note: '骷髅串基座·沙僧专属' } },
  8: { id: 8, name: '两界山头', act: 2, type: 'story', icon: '✦',
    fate: '渡', echo: '逆副→孙悟空双线(紧箍/弃箍)·斗战胜佛 vs 混世魔王',
    dark: '五行山下压着的不只是猴，是一句没说完的"我不服"。揭帖是你自己前世写的——金蝉子曾许诺救他，十世都忘了。',
    // V8.33 丰富难8 intro：收悟空关键剧情叙事（五行山·揭帖·十世之约）
    intro: '五行山根，一只毛脸雷公嘴的猴子被压在石匣里，只露一颗头。他见你，先是一愣，随即笑了："金蝉子？你终于来了。我等了你十世——你前世写的揭帖，还贴在我头顶。"山风揭动那帖，金光一闪，是你自己的笔迹。',
    options: [
      { key: '渡', label: '与他立约同行', fate: '渡', effect: { alignGood: 10, flag: '取经同行', ti: { hp: 20, dr: 0.04 } } },
      { key: '逆', label: '以"保命"为条件', fate: '逆', effect: { alignEvil: 8, wukongMorale: true, rel: { 妖王: +3 } } },
      { key: '缘', label: '许他自由', fate: '缘', effect: {ally: 'wukong', alignGood: 8 } }
    ],
    // 两界山收悟空——紧箍（原著如来帖压五行山，后观音赐紧箍约束；此处作为剧情机缘），非战斗叙事也有收获
    treasure: { id: 'jingu', type: 'treasure', note: '紧箍·两界山机缘（原著：五行山收悟空，观音赐金箍）' } },
  9: { id: 9, name: '两界山·鹰愁涧', act: 2, type: 'fight', icon: '🐉',
    fate: '缘', echo: '战副→龙太子归呼应(第59难)；白龙初现',
    dark: '过了两界山，涧水横在路前。鹰愁涧下盘着一条玉龙——西海龙王三太子，因纵火烧了殿上明珠，被贬在此等候取经人。它见你驮马行李，忽起贪念，欲吞了马再走："我本是龙，凭什么驮经？"',
    intro: '涧水翻涌，一条玉龙破水而出，口衔马缰。它问你：你那马，驮得动几卷经？',
    options: [
      { key: '战', label: '降龙，强收为脚力', fate: '战', effect: { alignEvil: 6, ti: { atk: 9, hp: 58 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '点化白龙，随行驮经', fate: '渡', effect: { alignGood: 10, yuan: { matk: 10, mdef: 0.03 } } },
      { key: '缘', label: '放它归海，白龙衔珠相赠', fate: '缘', effect: { alignGood: 8, ti: { hp: 47 } } },
      { key: '逆', label: '不让它受鞍——它烧的是自家殿上的珠子', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_yulong' } },
    ],
    hidden: { hero: 'wukong', cond: '战 + 战≥3 + 战x3', job: '斗战明王', hint: '连战三场且一贯以战收场——战意不灭者，可窥明王之路', desc: '以战正道，战意化刃' },
    treasure: { id: 'lm_scale_base', type: 'armor', hp: 40, dr: 0.02, eva: 0.05, note: '逆鳞胚·鹰愁涧机缘（龙马·鳞基座）' } },
  10: { id: 10, name: '虎先锋前哨', act: 3, type: 'fight', icon: '⚔',
    portrait: '虎仔',
    fate: '战', echo: '战副→黄风逆吹呼应(第62难)；黄风岭前哨',
    dark: '黄风岭前哨，虎先锋横刀拦路。它原是黄风怪座下先锋，专吃"过岭的取经人"——风起时，它比风先到。',
    intro: '虎先锋立在风沙里，刀尖挑着半截经幡："过岭的，先过我这关。"',
    options: [
      { key: '战', label: '斗虎先锋，夺这半截经幡', fate: '战', effect: { alignGood: 3, yuan: { matk: 5, mdef: 0.03 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '渡化绕行，化风而过', fate: '渡', effect: { alignGood: 10, ti: { eva: 4 } } },
      { key: '隐', label: '潜行避其锋芒', fate: '隐', effect: { alignGood: 2, ti: { eva: 4 } } },
      { key: '逆', label: '问它守的是什么——替人守关，你得到过什么', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_huxianfeng' } },
    ],
    treasure: { id: 'set_weapon_base', type: 'weapon', atk: 10, note: '破军·兵刃基座（黄风岭前哨）' } },

  11: { id: 11, name: '黄风卷沙', act: 3, type: 'fight', icon: '🌪',
    portrait: '黄风怪',
    fate: '隐', echo: '战副→黄风逆吹呼应(第62难)；黄风岭首战',
    dark: '黄风岭的风不是风，是一只貂鼠的怨。它原是灵山脚下守酥陀的貂，偷抿了一口香油便被打下界——一勺油，换满山黄沙。它吹的不是风，是那句「我守了一辈子，却连尝一口都不配」。风卷着你转了九圈，像要把你这句话也嚼碎。',
    intro: '风眼里，一只貂鼠盘着尾，问你：三藏，你这一路取经，到头来是给谁点的灯？',
    options: [
      { key: '战', label: '踏风穿云，一拳定住风眼', fate: '战', effect: { alignGood: 3, ti: { atk: 9, hp: 29 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '请灵吉念一卷还香油经', fate: '渡', effect: { alignGood: 10, yuan: { matk: 11, mdef: 0.04 } } },
      { key: '夺', label: '趁风眼大开，夺它定风丹', fate: '夺', effect: { alignEvil: 6, ti: { atk: 11, hp: 58 } } , fight: true, bossDiff: 1.58, duo: 'T0', treasure: 'tre_dingfengdan' , chain: 'hf_dan' },
      { key: '逆', label: '它偷的不过一盏清油——佛门不认它修的道', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_huangfeng' } , chain: 'hf_ni' },
    ],
    treasure: { id: 'dingfeng', type: 'treasure', note: '定风珠·黄风大圣首次掉落（原著：灵吉菩萨定风丹）' } },
  12: { id: 12, name: '三昧神风', act: 3, type: 'fight', icon: '🌀',
    portrait: '黄风怪',
    fate: '隐', echo: '战副→黄风逆吹回扣(第62难)',
    dark: '黄风怪吹的不是沙，是"遗忘"——被吹过的人，连自己为何取经都忘了。风停时，你发现同行的随从正互相问："我们这是要去哪？"这一吹，连火眼金睛也睁不开。',
    intro: '黄风怪现出真身，张口一吹——三昧神风，天地无色。',
    options: [
      { key: '战', label: '请灵吉收风', fate: '战', effect: { alignGood: 3, ti: { atk: 5, hp: 52 } }, fight: true, battleFlags: { openingMomentum: 1 }, chainMul: ['hf_dan', 0.85] },
      { key: '渡', label: '借风势渡岭', fate: '渡', effect: { alignGood: 10, ti: { hp: 49, dr: 0.02 } } },
      { key: '夺', label: '逆风而上，夺它风袋', fate: '夺', effect: { alignEvil: 6, ti: { atk: 11, hp: 39 } } , fight: true, bossDiff: 1.45, duo: 'T1', treasure: 'tre_fengdai' , chainMul: ['hf_dan', 0.85] },
      { key: '逆', label: '不借风也不收它——让它把这一场吹完', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +4 } } },
    ],
    // 第12难必掉装备（修复"劫难打怪不掉装备"）
    treasure: { id: 'bj_robe_base', type: 'treasure', hp: 120, dr: 0.07, note: '僧衣基座·八戒专属' } },
  13: { id: 13, name: '黄风大圣', act: 3, type: 'fight', icon: '👑',
    portrait: '黄风怪',
    fate: '战', echo: '战副→黄风逆吹呼应(第62难)；黄风岭终战',
    dark: '黄毛貂鼠现出本相，三目齐开。风起时天地无声——它想起来了：它本是灵山养在笼中的"风"，今日要撕碎这笼子。灵吉菩萨的飞龙宝杖已在半空，可这一战，终究要你自己走完。',
    intro: '黄风大圣立在风眼，金目赤红："过岭的取经人，都该被吹成沙。"',
    options: [
      { key: '战', label: '决战黄风大圣', fate: '战', effect: { alignGood: 3, ti: { atk: 5, hp: 39 } }, fight: true, battleFlags: { openingMomentum: 1 }, chainMul: ['hf_dan', 0.78] },
      { key: '渡', label: '请灵吉菩萨收风', fate: '渡', effect: { alignGood: 10, ti: { hp: 23, dr: 0.03 } } },
      { key: '夺', label: '夺它那颗定风珠', fate: '夺', effect: { alignEvil: 6, ti: { atk: 5, hp: 45 } } , fight: true, bossDiff: 1.48, duo: 'T1', treasure: 'tre_dingfengzhu' , chainMul: ['hf_ni', 1.12] },
      { key: '逆', label: '夺其风源，反吹灵山', fate: '逆', ni: true, effect: { alignEvil: 8, ti: { atk: 6, hp: 36 } } },
    ],
    hidden: { hero: 'tangseng', cond: '渡 + 日记装备≥1', job: '定风金蝉', desc: '缘路拾奇，风不能迷其眼（唐僧·定风金蝉）', hint: '走「渡」收黄风，并把路上事件所得的奇物记进日记——日记载物愈多，风愈迷不了你' },
    treasure: { id: 'dingfeng', type: 'treasure', note: '黄风大圣·定风珠（原著：灵吉菩萨定风丹）' } },
  // 【2026-09-13 PHASE 4 · 按 81 难重排】第 2 章（14-22）重构：
  //   原著行程顺序为 高老庄收八戒(18-19回) → 流沙河收沙僧(22回) → 四圣试禅心(23回) → 五庄观(24-26回) → 白骨(27回)。
  //   原表缺「收八戒」（原著难簿第 12 难）且把流沙河铺成 5 难，挤压了章末白骨的位置。
  //   现收敛为 9 难：高老庄 2 + 流沙河 2 + 四圣 1 + 五庄观 1 + 白骨 3。
  //   取舍（用户授权「内部劫难前后适当调整」）：原 16「流沙九颅」并入 16 初遇（沙僧 hidden 钩子随迁）、
  //   原 17「河神问渡」（原创填充·无钩子）与 15「四圣试禅心」占位互调 → 四圣后移至 18。
  14: { id: 14, name: '高老庄·闻妖', act: 2, type: 'event', icon: '✦',
    portrait: '高太公',
    fate: '缘', echo: '原著地理重排·新增（收八戒·第18回）',
    dark: '高老庄三年招亲，招来一个能吃三百斤米的"女婿"。庄里人夜里不敢开门，只听见后园有东西在拱地。高太公捧着当年的婚书，手抖得像风里的纸——他要的从来不是女婿，是个能把那东西带走的人。',
    intro: '高老庄借宿，太公哭诉求退婚；后园妖气冲天，那是天蓬投的猪胎。',
    options: [
      { key: '缘', label: '细问庄中旧事，记下婚书始末', fate: '缘', effect: { alignGood: 6, ti: { hp: 31 } } },
      { key: '渡', label: '应下此事，先礼后兵', fate: '渡', effect: { alignGood: 10, ti: { hp: 42, dr: 0.02 } } },
      { key: '战', label: '直闯后园，先打一场', fate: '战', effect: { alignEvil: 3, ti: { atk: 12, hp: 24 } }, fight: true },
      { key: '逆', label: '问一句——他投了猪胎，是谁判的', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +5 } } },
    ] },
  15: { id: 15, name: '云栈洞·收八戒', act: 2, type: 'fight', icon: '⚔',
    portrait: '猪八戒',
    fate: '渡', echo: '渡副→天蓬归位(八戒)种子；收八戒（原著难簿第12难）',
    branchKey: 'n15_bajie',   // 网状叙事（P1）：收八戒四选一落印，难16据此渲染四种态度
    dark: '云栈洞的洞门是卵形的，天蓬躲在里面睡了三年。他先骂，再哭，最后跪下——他说：取经的，你带我走，我不想再当猪了。可你分明看见，他跪着的膝下，压着一枚天河的旧印。',
    intro: '云栈洞前妖气翻腾，天蓬元帅据洞而守；你战、你渡，或夺他钉钯。',
    options: [
      { key: '战', label: '一战降之', fate: '战', effect: { alignGood: 3, rel: { 玉帝: 3 } }, fight: true, battleFlags: { openingMomentum: 1 }, setFlag: 'n15_bajie:shou', consequence: '此选择将影响：流沙河八戒态度（心不服，易抱怨）' },
      { key: '渡', label: '受他一个正果，收归队中', fate: '渡', effect: { alignGood: 15, ally: 'bajie', rel: { 玉帝: 5 } }, setFlag: 'n15_bajie:du', consequence: '此选择将影响：流沙河八戒态度（感恩，主动相助）' },
      { key: '夺', label: '夺他九齿钉钯', fate: '夺', effect: { alignEvil: 6, ti: { atk: 7, hp: 22 } }, fight: true, bossDiff: 1.42, duo: 'T1', treasure: 'tre_jiuchidingpa', setFlag: 'n15_bajie:duo', consequence: '此选择将影响：流沙河八戒态度（记恨，消极避战）' },
      { key: '逆', label: '问天蓬——调戏嫦娥是罪，还是你挡了谁的路', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +5 } }, setFlag: 'n15_bajie:ni', consequence: '此选择将影响：流沙河八戒态度（吐露天庭内幕）' },
    ] },
  16: { id: 16, name: '流沙河畔·流沙九颅', act: 2, type: 'fight', icon: '⚔',
    fate: '缘', echo: '缘副→九世因果回扣；沙僧·卷帘镇妖前置',
    branchKey: 'n15_bajie',   // 网状叙事（P1）：读难15收八戒四分支，改写 intro/态度
    dark: '流沙河八百里，弱水三千，鹅毛飘不起。岸边残舟半沉，舟底压着一串人头骨。沙僧项上九颗骷髅，是九世取经人的颅骨。你问他：第十颗，是不是你的？他低头数河底：已经数不清了。',
    intro: '初到流沙河，河声如诉。渡口无人，河中妖气翻涌，河底九颅与水鬼翻涌——这一程，从渡河开始。',
    options: [
      { key: '缘', label: '细察残舟，拾得渡河旧物', fate: '缘', effect: { alignGood: 6, ti: { hp: 27 } } },
      { key: '渡', label: '合掌渡那九颅，送其转生', fate: '渡', effect: { alignGood: 10, ti: { hp: 29, dr: 0.03 } } },
      { key: '战', label: '夺那骷髅串，与河底怨灵一战', fate: '战', effect: { alignEvil: 8, ti: { atk: 5, hp: 46 } }, fight: true},
      { key: '隐', label: '绕开河底，避其锋芒', fate: '隐', effect: { alignEvil: 2, ti: { eva: 6 } } },
      { key: '夺', label: '摘下那串九骷髅——九个没走完的取经人', fate: '夺', effect: { alignEvil: 6, treasure: 'ni_jiukulou' } , fight: true, bossDiff: 1.42, duo: 'T1', treasure: 'ni_jiukulou' },
      { key: '逆', label: '问那九世因——你吞的九世，哪一世最悔', fate: '逆', ni: true, effect: { alignEvil: 4, jiushiyin: true } },
      // —— P1 复合联动：依难15收八戒分支浮现/锁定 ——
      { key: 'hechi', label: '呵斥八戒——他一路嘟囔，断他嘴', fate: '战', effect: { alignGood: 4, gold: 12 }, requireFlag: 'n15_bajie:shou', consequence: '此选择将影响：流沙河军心' },
      { key: 'zhuibian', label: '追问天蓬被贬真相', fate: '逆', ni: true, effect: { alignEvil: 3, rel: { 玉帝: -2 } }, requireRel: { 玉帝: 5 }, consequence: '此选择将影响：天庭线暗子' },
      { key: 'tanlu', label: '唤八戒先下水探路', fate: '缘', effect: { alignGood: 4, rel: { 玉帝: +3 } }, requireLock: ['n15_bajie:duo'], consequence: '此选择将影响：流沙河渡河方式' },
    ],
    // P1 分支：难15收八戒四选一 → 难16 intro/态度实质不同
    branches: {
      shou: { intro: '八戒被你一战降了，嘴上服了，心里不服。行到流沙河畔，他嘟哝着"早知道跟那妖怪拼了"——你若呵斥他，他才噤声。' },
      du: { intro: '八戒受了正果，一路上感恩戴德。到流沙河畔，他自告奋勇先下河探路："师父你歇着，老猪去把那九个骷髅捞上来。"——此去多一分稳妥。' },
      duo: { intro: '八戒的九齿钉钯被你夺了，他空着手跟在队后，一路铁青着脸。流沙河水急，他磨磨蹭蹭不肯先下水——唤他探路，他只当没听见。' },
      ni: { intro: '你问出了天蓬被贬的内幕，八戒一路沉默。到流沙河畔，他忽然低声道："师父，那天庭里的事……你真要听？"——玉帝若肯信你三分，他便肯多说三分。' },
    },
    hidden: { hero: 'shaseng', cond: '问九世因 + 降妖念珠', job: '卷帘镇妖', hint: '流沙河择「问九世因」、持降妖念珠——九世尸骨，等你镇压', desc: '问九世因，镇压河妖（沙僧·卷帘镇妖前置）' } },
  17: { id: 17, name: '流沙河收沙僧', act: 2, type: 'fight', icon: '⛓️',
    portrait: '沙僧',
    fate: '渡', echo: '战副→卷帘复权(沙僧)种子；善≥30门槛',
    dark: '沙僧项下九颗骷髅，是九世取经人的头。他每吃一世金蝉，就多一颗——这是灵山让他"记住债"。他跪在河滩叩首："小僧，你若渡我上岸，我便不吃第十世。"',
    intro: '流沙河浊浪翻涌，卷帘大将项挂九颅，拦在渡口。',
    options: [
      { key: '战', label: '一战降之', fate: '战', effect: { alignGood: 3, ti: { atk: 11, hp: 24 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '木吒说降，归他一个正果', fate: '渡', effect: { alignGood: 15, ally: 'shaseng' } },
      { key: '夺', label: '夺他降妖宝杖', fate: '夺', effect: { alignEvil: 6, ti: { atk: 7, hp: 31 } } , fight: true, bossDiff: 1.42, duo: 'T1', treasure: 'tre_baozhang' },
      { key: '逆', label: '问罪卷帘，索回九颅', fate: '逆', ni: true, effect: { alignEvil: 8, gold: 13 } },
    ],
    // 第17难必掉装备（修复"劫难打怪不掉装备"）
    treasure: { id: 'ss_skull_base', type: 'treasure', hp: 18, dr: 0.04, note: '骷髅串基座·沙僧专属' },
    hidden: { hero: 'shaseng', cond: '渡 + 善≥30', job: '卷帘复权', hint: '踏实走「渡」、善行满三十——顺命者不必积恶也能复权', desc: '愿法防+25%，可复活一次' } },
  18: { id: 18, name: '四圣试禅心', act: 2, type: 'event', icon: '✦',
    fate: '渡', echo: '原著地理重排·新增（第23回·流沙河后）',
    dark: '山间一座庄院凭空而起，三女一母笑迎投宿。你知这是黎山老母与菩萨设的局——试的从来不是色心，是取经的心。',
    intro: '黎山老母与三菩萨化身庄院，试师徒禅心。',
    options: [
      { key: '渡', label: '合掌谢过，不入庄门', fate: '渡', effect: { alignGood: 10, ti: { hp: 42, dr: 0.03 } } },
      { key: '缘', label: '借宿一夜，点破机关', fate: '缘', effect: { alignGood: 6, ti: { hp: 49 } } },
      { key: '逆', label: '拂袖而去，讥其设局', fate: '逆', effect: { alignEvil: 8, rel: { 妖王: +4 } } },
    ] },
  19: { id: 19, name: '五庄观人参', act: 5, type: 'event', icon: '✦',
    portrait: '镇元大仙',
    fate: '缘', echo: '逆副→五庄观根回扣(第65难)',
    branchKey: 'n19_wuzhuang',   // 网状叙事（P1）：五庄观四选一落印，难20据此渲染四种因缘
    dark: '镇元子的人参果，吃一颗活四万七千年——但果树的根，缠着千万取经人的尸骨当肥。',
    intro: '五庄观中，镇元子人参果树三千年一果；你窃果推树，或赔树医根。',
    options: [
      { key: '渡', label: '与镇元子论道', fate: '渡', effect: { alignGood: 10, rel: { 太上老君: 3 } }, setFlag: 'n19_wuzhuang:lundao', consequence: '此选择将影响：白骨战时镇元子赠符镇邪' },
      { key: '缘', label: '往南海求观音甘露医树', fate: '缘', effect: { alignGood: 8, rel: { 观音: 5 } },
        favorGate: '观音',
        favorText: '观音念你昔日捧钵承命，净瓶甘霖救活人参果树，连根也搭了三分情——愿 +3、善 +2。',
        favorEffect: { yuan: 3, alignGood: 2 },
        setFlag: 'n19_wuzhuang:yishu', consequence: '此选择将影响：白骨战时观音暗中相助' },
      { key: '夺', label: '偷摘一枚人参果带在路上', fate: '夺', effect: { alignEvil: 8, yuan: { matk: 5, mdef: 0.04 } } , fight: true, bossDiff: 1.6, duo: 'T0', treasure: 'tre_renshenguo', setFlag: 'n19_wuzhuang:touguo', consequence: '此选择将影响：白骨战时镇元子追杀、白骨趁火打劫' },
      { key: '逆', label: '拔树看根——三千年一果，凭什么只许佛门吃', fate: '逆', ni: true, effect: { alignEvil: 10, rel: { 妖王: +4 } }, setFlag: 'n19_wuzhuang:bashu', consequence: '此选择将影响：白骨战时树根尸骨真相震动' },
    ],
    // 五庄观人参——芭蕉扇（镇元子与芭蕉扇渊源，后文借芭蕉扇灭火；此处作为剧情机缘），非战斗事件也有收获
    treasure: { id: 'baojiao', type: 'treasure', note: '芭蕉扇·五庄观机缘（原著：镇元子与芭蕉扇同源）' },
    hidden: { hero: 'tangseng', cond: '缘 + 缘≥3', job: '金蝉了缘', hint: '多走「缘」、缘路连三——了却因果，方得自在', desc: '缘了缘续，因果自了（唐僧·金蝉了缘前置）' } },
  20: { id: 20, name: '白骨三戏', act: 5, type: 'fight', icon: '⚔',
    fate: '渡', echo: '战副→悟空空(悟空)种子；立坟超度',
    branchKey: 'n19_wuzhuang',   // 网状叙事（P1）：读难19五庄观分支；本难选项另落 n20_baigu 供难21读取
    dark: '白骨精是"被写死的角色"——她知道自己只是难簿上第19笔，求你杀了她，好投个明白胎。',
    intro: '白骨夫人三戏取经人，只为求你杀她投明白胎；你三打，或听遗言。',
    options: [
      { key: '战', label: '三打', fate: '战', fight: true, rounds: 3, battleFlags: { openingMomentum: 1 }, effect: { alignGood: 3, ti: { atk: 9, hp: 23 } }, setFlag: 'n20_baigu:sanda', consequence: '此选择将影响：贬退心猿紧箍咒更狠' },
      { key: '渡', label: '听她遗言', fate: '渡', effect: function(flags, s) {
          // 增强联动（P1）：依难15收八戒分支动态追加效果
          const e = { alignGood: 15, rel: { 妖王: 5 } };
          if (flags['n15_bajie'] === 'du') { e.alignGood += 5; e.rel['妖王'] += 3; }
          if (flags['n15_bajie'] === 'ni') { e.gold = 20; }
          return e;
        }, setFlag: 'n20_baigu:yiyan', consequence: '此选择将影响：贬退心猿悟空抗命' },
      { key: '逆', label: '撕了难簿这一页', fate: '逆', effect: {alignEvil: 10, treasure: 'ni_baigu' }, setFlag: 'n20_baigu:sinabu', consequence: '此选择将影响：贬退心猿成灵山追杀' }
,
      { key: '隐', label: '隐去真身，辨白骨三戏', fate: '隐', effect: {"alignGood":4}, setFlag: 'n20_baigu:bianxi', consequence: '此选择将影响：未贬退，分支跳过' },
      // —— P1 复合联动：依难19五庄观分支 / NPC 关系浮现 ——
      { key: 'zhenfu', label: '用镇元子赠符镇白骨', fate: '渡', effect: { alignGood: 8, rel: { 妖王: 2 } }, requireFlag: 'n19_wuzhuang:lundao', consequence: '此选择将影响：白骨战时一符定邪' },
      { key: 'jingping', label: '请观音净瓶收白骨', fate: '渡', effect: { alignGood: 12, rel: { 观音: 2 } }, requireRel: { 观音: 8 }, consequence: '此选择将影响：白骨渡化圆满' },
    ],
    // P1 分支：难19五庄观四选一 → 难20 intro/因缘实质不同
    branches: {
      lundao: { intro: '镇元子临行赠你一道镇邪符——白骨夫人若再幻化，符纸可定她一瞬。你袖中那道符，此刻微微发烫。' },
      yishu: { intro: '观音甘露医树结缘，她暗中随你至此。白骨夫人三戏，袖中净瓶似有若无地应着——你若肯低眉，她便肯出手。' },
      touguo: { dark: '你偷果在先，镇元子一路追来。白骨夫人趁你两线受敌，妖气更盛——她借着镇元子的怒火，把这一戏演得格外狠。',
        intro: '身后镇元子追兵未远，身前白骨三戏开场。两头受敌，此战凶险倍增。' },
      bashu: { dark: '你拔树看根，见根上缠着千万取经人尸骨——镇元子的道，是用人肥浇出来的。白骨夫人在风里笑：你也看见了？这西天的果子，哪一颗不是人养的。',
        intro: '你已知树根尸骨之秘。白骨夫人三戏之间，多了一层戏外之戏——她求你把这真相，也撕进难簿。' },
    },
    hidden: { hero: 'wukong', cond: '第3打选渡 + 救命毫毛', job: '悟空的空', hint: '三打白骨时择「渡」立坟、持救命毫毛——空而不空', desc: '体物伤+20%，分身替死' } },
  21: { id: 21, name: '贬退心猿', act: 5, type: 'event', icon: '✦',
    fate: '逆', echo: '渡副→贬退反转回扣(第72难)',
    branchKey: 'n20_baigu',   // 网状叙事（P1）：读难20白骨三戏四分支，改写贬退心猿走向
    dark: '取经人念紧箍咒逐悟空——不是糊涂，是他怕：悟空越近真相，越活不成。',
    intro: '叙事抉择（悟空离队）。',
    options: [
      { key: '渡', label: '忍痛放行', fate: '渡', effect: { alignGood: 10, ti: { hp: 42, dr: 0.05 } } },
      { key: '逆', label: '悟空抗命不走', fate: '逆', effect: { alignEvil: 10, loosenCirclet: true, yuan: { matk: 15, mdef: 0.04 } } }
,
      { key: '夺', label: '夺那紧箍，自此无束', fate: '夺', effect: {"alignEvil":6} , fight: true, bossDiff: 1.62, duo: 'T0', treasure: 'tre_jingu' },
    ],
    hidden: { hero: 'wukong', cond: '逆 + 紧箍 + 夺宝≥1', job: '齐天残念', hint: '贬退心猿择「逆」、持金箍、且夺过至宝——紧箍化敌血', desc: '紧箍改为敌方减血10%，自身不掉血' },
    // 8.11 难22 专属：金箍·束缚（悟空齐天残念转职持有门槛件）
    treasure: { id: 'jingu_shu', type: 'treasure', note: '金箍·束缚·贬退心猿机缘（8.11 难22 专属）' },
    // P1 分支：难20白骨三戏四选一 → 难21贬退心猿实质不同
    branches: {
      sanda: { intro: '你三打白骨，取经人念紧箍咒念得更狠——悟空头上的箍，勒得他眼冒金星。这一逐，比哪一回都决绝。' },
      yiyan: { intro: '你听了白骨遗言，悟空感激在心。此刻取经人要逐他，他却抗命不走："师父，她求的不是死，是明白。你既听了，我便不走。"' },
      sinabu: { dark: '你撕了难簿，灵山震怒。贬退心猿不再是逐——是追杀。一道法旨自西天落下：悟空若去，连你一起问罪。',
        intro: '灵山法旨已下。贬退心猿，成了直接追杀——这一走，便是背了西天的罪。' },
      bianxi: { intro: '你识破白骨三戏，未为所惑。悟空未被逐——他仍在你身侧，取经人那道逐客令，终究没念出口。' },
    } },
  // 【2026-09-13 PHASE 4】第 22 难原为「黄袍掳公主」——与章末 Boss 白骨夫人冲突（黄袍在原著第 28-31 回，
  //   晚于第 27 回白骨）。现该难改为章末三段变身 Boss「白骨夫人·五行归墟」，黄袍事件（含逆线宝物 ni_kui）
  //   回迁至第 23 难「黑松林失」（原著第 28 回黑松林三藏逢魔 = 黄袍事件开局）。
  //   叙事链：20 三戏（人形态） → 21 贬退心猿 → 22 真身（五行归墟），三戏为前戏，章末为真身。
  22: { id: 22, name: '白骨夫人·五行归墟', act: 2, type: 'fight', icon: '👑',
    portrait: '白骨夫人',
    fate: '战', echo: '章末三变·第五档红劫印；白骨三戏真身回扣',
    dark: '三戏散尽，她才从土里站起来——不是人形，不是白骨，是五行的残骸拼起来的一个"她"。她说：你杀我三次，我谢你三次；这一回，我不必再演人了。风从她的骨缝里穿过去，发出来的，是经文的声音。',
    intro: '白骨夫人真身现世，五行归墟成形："演了二十回人，今日演一回真的。"',
    options: [
      { key: '战', label: '硬打——不借外物，直面五行归墟', fate: '战', effect: { alignGood: 3, ti: { atk: 20, hp: 76 } }, fight: true, battleFlags: { openingMomentum: 1 } },
      { key: '渡', label: '持照妖镜破其形，渡她入灭', fate: '渡', effect: { alignGood: 12, ti: { hp: 52, dr: 0.04 } } },
      { key: '夺', label: '夺她骨里那点执念', fate: '夺', effect: { alignEvil: 6, ti: { atk: 19, hp: 67 } }, fight: true, bossDiff: 1.48, duo: 'T1', treasure: 'tre_zhinian' },
      { key: '逆', label: '撕了难簿这一页——她本不必死三次', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +4 } } },
    ] },
  // 【2026-09-13 PHASE 4】承接第 22 难迁出的黄袍事件（原著第 28 回黑松林三藏逢魔 = 黄袍怪开局）：
  //   黄袍怪（二十八宿奎木狼）掳走宝象公主、天条与私情对峙在此展开；逆线宝物 ni_kui 由第 22 难迁入本难。
  23: { id: 23, name: '黑松林·黄袍掳僧', act: 3, type: 'fight', icon: '⚔',
    portrait: '黄袍怪',
    fate: '隐', echo: '战副→黄袍放情回扣；逆线宝物 ni_kui 迁入（第22难→第23难）',
    dark: '黄袍怪趁悟空不在掳走取经人，八戒沙僧才知：没有那只猴，他们连"被写进经书"的资格都没有。可这妖怪本是二十八宿奎木狼，私下凡间只为陪一个被贬的情人——天条比妖狠。',
    intro: '黑松林里取经人被掳，宝象国中天条与私情对峙；你战，或放其私奔。',
    options: [
      { key: '战', label: '召回悟空', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignGood: 8, yuan: { matk: 12, mdef: 0.05 } }},
      { key: '隐', label: '放他们私奔', fate: '隐', effect: { alignGood: 6, yuan: { mdef: 0.03 } } },
      { key: '夺', label: '夺回被掳行囊，趁乱而行', fate: '夺', effect: {"alignEvil":6} },
      { key: '渡', label: '为宝象公主传书，送它归天', fate: '渡', effect: { alignGood: 10, ti: { hp: 86, dr: 0.05 } } },
      { key: '逆', label: '不上天庭——他下界只为续一段缘，天条管得着么', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_kui' } }
    ],
    // 2026-09-01 八戒·血反伤路线：以背承山，以伤还伤（渡道·善≥30）
    hidden: { hero: 'bajie', cond: '渡 + 善≥30', job: '天蓬·负岳', hint: '走「渡」、善行满三十——以背承山，以伤还伤', desc: '以背承山，以伤还伤（八戒·血反伤路线）' } },
  24: { id: 24, name: '平顶山宝', act: 6, type: 'fight', icon: '⚔',
    fate: '夺', echo: '战副→吞天净坛(八戒)种子；真葫芦夺',
    dark: '金角银角是太上老君看炉童子，奉旨下界"演一出被收"——法宝都是道具，戏演完了你得配合。',
    intro: '平顶山莲花洞，金角银角持真葫芦装人；你斗法，或夺宝。',
    options: [
      { key: '战', label: '以假葫芦诓它，教它装了自己', fate: '战', effect: { alignGood: 3, ti: { atk: 10, hp: 74 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '上天请老君亲至，收二童归炉', fate: '渡', effect: { alignGood: 10, ti: { hp: 54, dr: 0.03 } } },
      { key: '夺', label: '夺紫金红葫芦与羊脂玉净瓶', fate: '夺', effect: { alignEvil: 6, ti: { atk: 20, hp: 86 } } , fight: true, bossDiff: 1.6, duo: 'T0', treasure: 'tre_hulu' },
      { key: '逆', label: '说破它们只是老君的库——宝贝不是你们的，命也不是', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_lutong' } },
    ],
    // 8.11 难18：八戒「吞天净坛」隐藏职 = 逆 + 净坛宝盂（八戒初始即持 bj_bowl）
    hidden: { hero: 'bajie', cond: '逆 + 净坛宝盂', job: '吞天净坛', hint: '平顶山择「逆」夺紫金红葫芦——吞食万物，饱食成盾', desc: '吞食万物，饱食成盾（净坛宝盂持有门槛）' },
    treasure: { id: 'zijinhu', type: 'treasure', note: '紫金红葫芦·金角银角机缘' } },
  25: { id: 25, name: '乌鸡井龙', act: 6, type: 'event', icon: '✦',
    fate: '缘', echo: '渡副→乌鸡立新王(重排后难25 fuxinwang 标记源)',
    dark: '乌鸡国王被青狮推井，狮王扮国王坐了三年——妖坐龙椅，比人像样。井底龙王托梦诉冤，井水都带着龙泪的咸。',
    intro: '乌鸡国井底，真王尸身沉了三年；井龙王诉冤，你背尸，或先问价。',
    options: [
      { key: '逆', label: '先问价，扶立新王', fate: '逆', effect: { alignEvil: 8, gold: 30, fuxinwang: true, treasure: 'ni_qingshi' } },
      { key: '渡', label: '亲下井背尸', fate: '渡', effect: { alignGood: 10, ti: { hp: 61, dr: 0.03 } } },
      { key: '缘', label: '八戒背尸', fate: '缘', effect: { alignGood: 6, ti: { hp: 83 } } }
,
      { key: '隐', label: '隐入井底，探乌鸡真相', fate: '隐', effect: {"alignGood":4} },
    ],
    hidden: { hero: 'bajie', cond: '逆 + 扶新王', job: '天蓬复称', hint: '乌鸡井龙择「立新王」——你扶的王，记得你', desc: '重称天蓬，倒海翻江（八戒·天蓬复称前置，须于本难择「扶立新王」）' } },
  26: { id: 26, name: '黑水鼍龙', act: 6, type: 'fight', icon: '⚔',
    fate: '隐', echo: '战副→避水珠抗水(第9难链)',
    dark: '西海龙王外甥，因"血统不纯"被贬管黑水河——龙族内部，比妖界更讲出身。',
    intro: '黑水河底，鼍龙因"血统不纯"被贬；你解咒，或灭之。',
    options: [
      { key: '战', label: '河神助战，擒那鼍龙', fate: '战', effect: { alignGood: 3, ti: { atk: 14, hp: 41 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '往西海请摩昂太子来收，归它一个龙族正籍', fate: '渡', effect: { alignGood: 10, ti: { hp: 53, dr: 0.03 } } },
      { key: '夺', label: '夺它颔下夜明珠', fate: '夺', effect: { alignEvil: 6, ti: { atk: 20, hp: 74 } } , fight: true, bossDiff: 1.4, duo: 'T1', treasure: 'tre_yemingzhu' },
      { key: '逆', label: '不归西海——穷亲这门，认它做什么', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_tuolong' } },
    ],
    // 2026-09-01 小白龙·血防路线：御水成甲，潜渊自守（隐道·隐≥3）
    hidden: { hero: 'xiaobailong', cond: '隐 + 隐≥3 + 隐x3', job: '白龙·御水', hint: '一贯以「隐」收场三难——藏身水脉，龙归其渊', desc: '御水成甲，潜渊自守（小白龙·血防闪避路线）' },
    // 8.11 难21 专属：避水珠·潜流（龙马成长件）
    treasure: { id: 'bis_qian', type: 'treasure', note: '避水珠·潜流·黑水河机缘（8.11 难21 专属）' } },
  27: { id: 27, name: '红孩真火', act: 6, type: 'fight', icon: '⚔',
    fate: '战', echo: '渡副→火云逆父回扣(第70难)',
    dark: '红孩儿的三昧真火，是他爹悟空当年在八卦炉里偷学的——子承父"业"，却认了牛魔王。',
    intro: '火云洞中，红孩儿三昧真火困住悟空；你战，或认亲。',
    options: [
      { key: '战', label: '硬闯火云洞，三昧真火里走一遭', fate: '战', effect: { alignGood: 3, ti: { atk: 13, hp: 61 } },
        favorGate: '观音',
        favorText: '观音曾受你捧钵之诚，净瓶真火一覆，红孩三昧便哑了三分——愿 +3、善 +2，起手势 +1。',
        favorEffect: { yuan: 3, alignGood: 2, momentum: 1 }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '往南海请观音，收它做个善财童子', fate: '渡', effect: { alignGood: 12, ti: { hp: 45, dr: 0.05 } } },
      { key: '夺', label: '夺它三昧真火', fate: '夺', effect: { alignEvil: 10, ti: { atk: 16, hp: 43 } } , fight: true, bossDiff: 1.62, duo: 'T0', treasure: 'tre_sanmei' },
      { key: '逆', label: '不叫它去受那一炉香火——牛魔王的儿子，凭什么叫童子', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_honghai' } },
    ],
    // 第20难必掉装备（修复"劫难打怪不掉装备"）
    treasure: { id: 'zy_w_base', type: 'weapon', atk: 20, note: '镇妖棍·镇妖套武器基座' } },
  28: { id: 28, name: '车迟求雨', act: 7, type: 'event', icon: '✦',
    fate: '渡', echo: '原著地理重排·新增（第28难·地区7）',
    dark: '车迟国大旱三年，虎力大仙登坛求雨。你见那雨水里掺着香灰——求来的不是雨，是香火钱。',
    intro: '车迟国斗法始——虎力登坛，求雨争胜。',
    options: [
      { key: '战', label: '破坛断香，激怒虎力——力战求雨台', fate: '战', fight: true, align: 'good', effect: {'alignGood':3} },
      { key: '渡', label: '罢斗诵经，劝虎力体察民情', fate: '渡', align: 'good', effect: {'alignGood':8} },
      { key: '隐', label: '避战脱身，潜行查探三清观', fate: '隐', align: 'evil', effect: {'alignEvil':12} },
    ],
    hidden: { hero: 'tangseng', cond: '渡 + 善≥25', job: '车迟·谕道', hint: '车迟国三场斗法择「渡」、善行满二十五——谕道于民，僧亦可帅', desc: '车迟三场斗法立坛祈雨渡旱，谕众以道——金蝉再显（唐僧·车迟·谕道）' }, },
  29: { id: 29, name: '三妖赌胜', act: 7, type: 'fight', icon: '⚔',
    fate: '战', echo: '原著地理重排·新增（第29难·地区7）',
    dark: '虎力赌头、鹿力剖腹、羊力下油锅。赌注不是命，是"谁才是这国的神"。',
    intro: '车迟国三妖以命相赌，逼你入局。',
    options: [
      { key: '战', label: '应赌破法，逐妖于求雨台前', fate: '战', fight: true, align: 'good', effect: {'alignGood':3} },
      { key: '渡', label: '罢赌劝善，点三妖归正', fate: '渡', align: 'good', effect: {'alignGood':8} },
      { key: '隐', label: '避赌潜踪，暗查三清观底细', fate: '隐', align: 'evil', effect: {'alignEvil':12} },
    ],
    hidden: { hero: 'xiaobailong', cond: '战 + 战≥2 + 夺宝≥1', job: '夺宝龙子', hint: '曾战且夺过至宝——龙子也能夺天', desc: '龙的宝，迟早游回龙手里（白龙·夺宝龙子前置）' } },
  30: { id: 30, name: '车迟监·灭僧', act: 7, type: 'event', icon: '✦',
    fate: '逆', echo: '原著地理重排·新增（第30难·地区7）',
    branchKey: 'n30_chechi',   // 网状叙事（P3）：三选一落印，难31「车迟三妖·魁首」据此改写
    dark: '车迟城监里关着千百和尚——不是犯戒，是"信错了神"。铁栏后有人喊你：取经人，救不救？',
    intro: '车迟国灭佛监僧，城中僧人尽数披枷。',
    options: [
      { key: '战', label: '劫牢破监，一战解僧厄', fate: '战', fight: true, align: 'good', effect: { alignGood: 3, rel: { 妖王: 3 } }, setFlag: 'n30_chechi:jielao' },
      { key: '渡', label: '入宫说法，谏王罢灭佛', fate: '渡', align: 'good', effect: { alignGood: 8, rel: { 玉帝: 5 } }, setFlag: 'n30_chechi:shuofa' },
      { key: '隐', label: '避战暗访，密联城中僧众', fate: '隐', align: 'evil', effect: { alignEvil: 12, ti: { eva: 7 } }, setFlag: 'n30_chechi:anfang' },
    ] },
  31: { id: 31, name: '车迟三妖·魁首', act: 7, type: 'fight', icon: '⚔',
    fate: '战', echo: '原著地理重排·新增（第31难·地区7）',
    branchKey: 'n30_chechi',   // 网状叙事（P3）：读难30车迟监三分支，改写 intro/选项
    branches: {
      jielao: { dark: '你劫牢放出千百僧众，满城缁衣拥你为救星。三妖的香火根基被这一闹抽了底——寺里再无人肯上一炷香。虎力提剑来战时，身后竟无一人随他。',
        intro: '车迟国关隘——僧众执棒相随，替你围住三妖。虎力回头，座下僧兵尽数倒戈。',
        options: [
          { key: '战', label: '僧众助阵，一棒破三妖', fate: '战', fight: true, effect: { alignEvil: 10, alignGood: 4, ti: { atk: 12, hp: 65 } }, battleFlags: { openingMomentum: 1 } },
          { key: '渡', label: '点破三妖，令其归正', fate: '渡', effect: { alignGood: 10, ti: { hp: 82, dr: 0.04 } } },
          { key: '逆', label: '反借僧众怨气，反噬三妖', fate: '逆', ni: true, effect: { alignEvil: 6, rel: { 妖王: +4 } } },
        ] },
      shuofa: { dark: '你入宫一席说法，国王幡然——原来这三妖求的雨，是拿满城香火喂出来的。王当庭下了一道撤坛旨，三妖面色灰败，香火骤断。',
        intro: '车迟国关隘——国王动摇，当庭质疑三妖来历。三妖狗急跳墙，欲擒王以挟众。',
        options: [
          { key: '战', label: '一棒破三妖，斩断香火神位', fate: '战', fight: true, effect: { alignEvil: 10, gold: 50 }, battleFlags: { openingMomentum: 1 } },
          { key: '缘', label: '请天庭下旨收三妖', fate: '缘', effect: { alignGood: 8, rel: { 玉帝: 2 } }, requireRel: { 玉帝: 5 }, consequence: '借天庭之势收妖，玉帝缘更厚' },
          { key: '渡', label: '点破三妖，令其归正', fate: '渡', effect: { alignGood: 10, rel: { 观音: +5 } } },
          { key: '逆', label: '反借香火，反噬三妖', fate: '逆', ni: true, effect: { alignEvil: 6, yuan: { matk: 16, mdef: 0.03 } } },
        ] },
      anfang: { dark: '你避战暗访，从三清观香炉底翻出一本旧册——三妖根本不是道仙，是虎鹿羊三株成精的兽修，混进车迟国骗了二十年香火。这底牌，比棒锋还利。',
        intro: '车迟国关隘——你手握那本兽修底册，三妖原形将揭，满朝文武鸦雀无声，只等你一句话。',
        options: [
          { key: '战', label: '一棒破三妖，斩断香火神位', fate: '战', fight: true, effect: { alignEvil: 10, ti: { atk: 11, dr: 0.05 } }, battleFlags: { openingMomentum: 1 } },
          { key: '逆', label: '当众揭破三妖兽修原形', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: 3 } }, consequence: '揭破兽修身份，妖界震动——妖王缘更深' },
          { key: '渡', label: '点破三妖，令其归正', fate: '渡', effect: { alignGood: 10, ti: { dr: 0.04, eva: 6 } } },
        ] },
    },
    dark: '虎力大仙被斩首后，颈腔里钻出的不是血，是香火灰。鹿力羊力骇然："大哥，你求的雨……"他笑："那雨，本来就是我们。"',
    intro: '车迟国关隘——虎力/鹿力/羊力，一役定神位。',
    options: [
      { key: '战', label: '一棒破三妖，斩断香火神位', fate: '战', fight: true, effect: { alignEvil: 10, ti: { hp: 59 } } },
      { key: '渡', label: '点破三妖，令其归正', fate: '渡', effect: { alignGood: 10, yuan: { mdef: 0.05 } } },
      { key: '逆', label: '反借香火，反噬三妖', fate: '逆', ni: true, effect: { alignEvil: 6, ti: { atk: 17 } } },
    ],
    hidden: { hero: 'bajie', cond: '战 + 战≥2', job: '车迟·力士', hint: '车迟国三场斗法一贯以「战」收场——力士之躯，越战越雄', desc: '车迟斗法扛桩力胜虎力，以肩承山（八戒·车迟·力士）' }, },
  32: { id: 32, name: '通天河渔户', act: 8, type: 'event', icon: '✦',
    fate: '缘', echo: '原著地理重排·新增（第32难·地区8）',
    dark: '陈家庄年年要往通天河送一对童男童女，供灵感大王。村长递给你一碗热汤："师父，今夜轮到我家了。"汤里映着他的脸。',
    intro: '陈家庄祭童之祸——通天河灵感大王索童。',
    options: [
      { key: '渡', label: '设坛祈渡，解陈家庄厄', fate: '渡', effect: { alignGood: 10, ti: { hp: 47, dr: 0.04 } } },
      { key: '逆', label: '掀了祭桌——谁定的这规矩', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +3 } } },
      { key: '缘', label: '应诺代童入河，换那孩子一命', fate: '缘', effect: { alignGood: 6, ti: { hp: 77 } } },
      { key: '战', label: '夜伏河畔，替这村守一夜', fate: '战', fight: true, effect: { alignGood: 4, ti: { eva: 6 } } },
    ],
    hidden: { hero: 'shaseng', cond: '渡 + 善≥20', job: '沙·问渡', hint: '通天河择「渡」、善行满二十——问龟亦问己，渡人先渡心', desc: '通天河畔问老龟寿数、以渡渡之——卷帘再问渡（沙僧·沙·问渡）' }, },
  33: { id: 33, name: '灵感大王', act: 8, type: 'event', icon: '✦',
    fate: '渡', echo: '原著地理重排·新增（第33难·地区8）',
    dark: '灵感大王庙里香火鼎盛，供的是条金鱼。你问庙祝：它吃什么？庙祝低头：童男童女。你抬头看那金鱼，它正盯着你笑。',
    intro: '金鱼精灵感大王盘踞通天河，以童男童女为食。',
    options: [
      { key: '逆', label: '砸庙揭供，断它千年香火', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_jinyu' } },
      { key: '渡', label: '入庙说法，渡那池中金鱼', fate: '渡', effect: { alignGood: 10, ti: { hp: 52, dr: 0.03 } } },
      { key: '夺', label: '夺灵感庙金身，熔作路上盘缠', fate: '夺', effect: { alignEvil: 6, ti: { atk: 13, hp: 53 } } , fight: true, bossDiff: 1.4, duo: 'T1', treasure: 'tre_jinshen' , chain: 'tt_jinshen' },
      { key: '战', label: '引它出水，一战定这条河', fate: '战', fight: true, effect: { alignGood: 3, ti: { atk: 10, hp: 43 } } },
    ] },
  34: { id: 34, name: '冰河渡难', act: 8, type: 'event', icon: '✦',
    fate: '隐', echo: '原著地理重排·新增（第34难·地区8）',
    dark: '河水一夜封冻，通天河结了冰。你踏上冰面，听见冰下"咚咚"——那是金鱼精在凿冰，等你踏空。',
    intro: '通天河结冰，踏冰过河险象环生。',
    options: [
      { key: '隐', label: '贴冰潜行，听它凿到天亮', fate: '隐', effect: { alignEvil: 2, ti: { eva: 8 } } },
      { key: '渡', label: '诵经化冰，稳步过河', fate: '渡', effect: { alignGood: 10, yuan: { matk: 9, mdef: 0.04 } } },
      { key: '战', label: '踏冰呐喊，引它破冰一战', fate: '战', fight: true, effect: { alignGood: 3, ti: { atk: 10, hp: 45 } }, battleFlags: { openingMomentum: 1 }},
    ],
    hidden: { hero: 'wukong', cond: '隐 + 隐≥3 + 隐x3', job: '白衣渡客', hint: '一贯以「隐」三难——白衣渡人，不留姓名', desc: '白衣渡尽，不着一物（悟空·白衣渡客前置）' } },
  35: { id: 35, name: '金兜金刚', act: 8, type: 'fight', icon: '⚔',
    fate: '夺', echo: '战副→金兜碎琢回扣(第74难)',
    dark: '青牛精的金刚琢，能套一切兵器——包括"天命"。老君下界，只为证明"连你手里的棍，也是我的"。',
    intro: '金兜洞外，青牛精持金刚琢套尽神兵；你战，或趁乱夺琢。',
    options: [
      { key: '战', label: '力战青牛，套尽神兵', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignGood: 3, ti: { atk: 11, hp: 49 } } },
      { key: '夺', label: '趁乱夺琢，金兜归你', fate: '夺', effect: { alignEvil: 6, ti: { atk: 13, hp: 45 } } , fight: true, bossDiff: 1.65, duo: 'T0', treasure: 'tre_jingangzhuo' },
      { key: '渡', label: '还琢论道，与老君共度青牛', fate: '渡', effect: { alignGood: 8, ti: { hp: 75, dr: 0.04 } } },
      { key: '逆', label: '反掌夺牛，悖其本源', fate: '逆', ni: true, effect: { alignEvil: 8, ti: { atk: 17, hp: 78 } } },
    ],
    // 第25难必掉装备（修复"劫难打怪不掉装备"）
    treasure: { id: 'jingangzhuo', type: 'treasure', note: '金刚琢·金兜洞机缘（原著：青牛精金刚琢）' } },
  36: { id: 36, name: '金鱼精·通天河决战', act: 8, type: 'fight', icon: '⚔',
    fate: '战', echo: '原著地理重排·新增（第36难·地区8）',
    dark: '灵感大王现出金鱼本相，翻江倒海。你想起陈家庄那碗汤——今日该让这河，换个吃法。',
    intro: '通天河关隘——金鱼精灵感大王决战。',
    options: [
      { key: '战', label: '翻江一战，擒那金鱼', fate: '战', fight: true, effect: { alignEvil: 3, ti: { atk: 10, hp: 76 } }, battleFlags: { openingMomentum: 1 }, chainMul: ['tt_jinshen', 0.88] },
      { key: '渡', label: '以佛法渡之，收其归正', fate: '渡', effect: { alignGood: 10, ti: { hp: 61, dr: 0.05 } } },
      { key: '逆', label: '借其反噬，反掌降妖', fate: '逆', ni: true, effect: { alignEvil: 6, treasure: 'ni_jinyu' } },
    ] },
  37: { id: 37, name: '女儿国水', act: 9, type: 'event', icon: '✦',
    fate: '缘', echo: '逆副→吞天净坛链(八戒)',
    dark: '子母河的水，喝一口便怀"取经人之种"——女儿国女王要的，不是夫，是"能走出这片国的种"。',
    intro: '子母河畔，落胎泉眼被如意真仙把持；你争泉，或强夺。',
    options: [
      { key: '战', label: '硬闯泉眼，强行夺水', fate: '战', effect: { alignEvil: 3, ti: { atk: 8, hp: 66 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '与其论法，劝真仙放行', fate: '渡', effect: { alignGood: 10, ti: { hp: 52, dr: 0.05 } } },
      { key: '缘', label: '取一葫芦子母河水——留着，说不定有用', fate: '缘', effect: { alignGood: 3, ti: { hp: 55 } } },
      { key: '逆', label: '倒转泉眼，破其守泉根本', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +4 } } },
    ],
    hidden: { hero: 'xiaobailong', cond: '隐 + 隐≥2', job: '白龙·渡河', hint: '女儿国一带一贯以「隐」护渡——藏身水脉，龙归其渊', desc: '女儿国水隐身护僧渡河，龙归水脉（小白龙·白龙·渡河）' },
  },
  38: { id: 38, name: '落胎泉·解阳山', act: 9, type: 'fight', icon: '⚔',
    fate: '战', echo: '原著地理重排·新增（第38难·地区9）',
    dark: '子母河水怀胎，解阳山落胎泉是唯一的解药。如意真仙守着泉，见你便拔剑："取经人，也配喝我的泉？"',
    intro: '解阳山落胎泉——如意真仙阻路，为取泉水须先破他。',
    options: [
      { key: '战', label: '夺泉一战，败如意真仙', fate: '战', effect: { alignEvil: 3, ti: { atk: 8, hp: 86 } }, fight: true},
      { key: '渡', label: '以礼相求，请其解厄', fate: '渡', effect: { alignGood: 10, ti: { hp: 55, dr: 0.04 } } },
      { key: '夺', label: '夺他如意钩', fate: '夺', effect: { alignEvil: 6, ti: { atk: 8, hp: 86 } } , fight: true, bossDiff: 1.42, duo: 'T1', treasure: 'tre_ruyigou' },
      { key: '逆', label: '夜取泉水，不告而取', fate: '逆', ni: true, effect: { alignEvil: 6, rel: { 妖王: +5 } } },
    ],
  },
  39: { id: 39, name: '女王招亲', act: 9, type: 'event', icon: '✦',
    fate: '逆', echo: '渡副→弃经链；女儿国种回扣(第75难)',
    dark: '女王许你王位，条件是留下——她看穿了：经书到手，你也只是灵山一尊新像。',
    intro: '女儿国驿馆，女王许你王位只为留"种"；你拒婚，或揭穿她也是囚徒。',
    options: [
      { key: '渡', label: '温柔辞别，留一纸通关', fate: '渡', effect: { alignGood: 15, ti: { hp: 56, dr: 0.05 } } },
      { key: '逆', label: '揭穿她也是这国的囚徒', fate: '逆', ni: true, effect: { alignEvil: 10, rel: { 妖王: +4 } } },
      { key: '隐', label: '夺通关文牒，连夜出城', fate: '隐', effect: { alignEvil: 6, ti: { atk: 16, hp: 50 } } },
    ],
    hidden: { hero: 'tangseng', cond: '逆 + 紫金钵 + 善≥20', job: '弃经者', hint: '碎金钵走逆、善行满二十——弃经者亦能行善', desc: '可拒通关，改写结局' } },
  40: { id: 40, name: '蝎精摄僧', act: 9, type: 'fight', icon: '⚔',
    fate: '渡', echo: '战副→蝎歌彻听回扣(第76难)',
    branchKey: 'n40_xiejing',   // 网状叙事（P3）：四选一落印，难41「六耳初现」据此改写
    dark: '琵琶精的倒马毒，专克佛门——她是第一个"用佛的办法破佛"的人。',
    intro: '琵琶洞中，蝎子精倒马毒克佛；你战，或听她歌破佛。',
    options: [
      { key: '渡', label: '请昴日星官降之，以音破毒', fate: '渡', effect: { alignGood: 10, rel: { 玉帝: 3 } }, fight: true, bossDiff: 0.92, setFlag: 'n40_xiejing:xingguan' },
      { key: '战', label: '以力破法，强战琵琶精', fate: '战', effect: { alignEvil: 8, ti: { atk: 9, hp: 87 } }, fight: true, battleFlags: { openingMomentum: 1 }, setFlag: 'n40_xiejing:lizhan' },
      { key: '夺', label: '夺她尾上那根倒马毒桩', fate: '夺', effect: { alignEvil: 8, ti: { atk: 18, hp: 60 } } , fight: true, bossDiff: 1.62, duo: 'T0', treasure: 'tre_daomadu', setFlag: 'n40_xiejing:duoduzhuang' },
      { key: '逆', label: '劝她弃邪西行——雷音寺推你那一把，我替你记着', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_xiejing', rel: { 妖王: 5 } }, fight: true, battleFlags: { openingMomentum: 2, drainPct: 0.02 }, bossDiff: 1.18, setFlag: 'n40_xiejing:quanxie', consequence: '此选择将影响：难41六耳现身时的援手' },
    ],
    hidden: { hero: 'bajie', cond: '战 + 战≥2', job: '八戒·护禅', hint: '蝎精摄僧一贯以「战」护禅——钯下护法，越战越稳', desc: '蝎精摄僧抡钯护禅，净坛护法（八戒·八戒·护禅）' },
  },
  41: { id: 41, name: '六耳初现', act: 10, type: 'event', icon: '✦',
    fate: '缘', echo: '原著地理重排·新增（第41难·地区10）',
    branchKey: 'n40_xiejing',   // 网状叙事（P3）：读难40蝎精四分支改写 intro/选项；本难自身另落 n41_liuer 供难70读取
    // 本难四选项各落 n41_liuer:xxx（缘观/渡观/棒喝/同修）；「逆·同修」开 liuerUnlocked → 难70六耳了断
    branches: {
      xingguan: { dark: '昴日星官一啼破了蝎毒，天庭的助力还没散。云头落下一道金光——观音不待你来请，已至。她合掌："真假，我自会辨。"',
        intro: '真假美猴王——天庭余威在侧，观音闻声自来，主动要替你辨真假。',
        options: [
          { key: '缘', label: '暂不责罚，细观其行', fate: '缘', effect: { alignGood: 6, ti: { hp: 90 } }, setFlag: 'n41_liuer:guancha' },
          { key: 'duanguan', label: '观音已至，求她当面辨真假', fate: '渡', effect: { alignGood: 12, rel: { 观音: 3 } }, setFlag: 'n41_liuer:guanyin' },
          { key: '战', label: '棒喝二猴，试其真身', fate: '战', effect: { alignEvil: 2, ti: { atk: 30, hp: 80 } }, fight: true, setFlag: 'n41_liuer:banghe' },
          { key: '逆', label: '不与它辨真假——伸手与它相认', fate: '逆', ni: true, effect: { alignEvil: 6, rel: { 妖王: 5 }, liuerUnlocked: true }, setFlag: 'n41_liuer:tongxiu', consequence: '此选择将影响：难70六耳了断分支' },
        ] },
      lizhan: { dark: '你力战蝎精一场，损耗不轻。那六耳觑准你气血未复，趁虚混入——它学你学了十成十，专挑你旧伤处攻。',
        intro: '真假美猴王——你新战方毕、气血未复，六耳趁虚而入，这一架格外难打。',
        options: [
          { key: '缘', label: '暂不责罚，细观其行', fate: '缘', effect: { alignGood: 6, rel: { 玉帝: +3 } }, setFlag: 'n41_liuer:guancha' },
          { key: '渡', label: '往南海请观音分辨真假', fate: '渡', effect: { alignGood: 10, rel: { 观音: 3 } }, setFlag: 'n41_liuer:guanyin' },
          { key: '战', label: '棒喝二猴，试其真身', fate: '战', effect: { alignEvil: 2, gold: 39 }, fight: true, bossDiff: 1.35, setFlag: 'n41_liuer:banghe' },
          { key: '逆', label: '不与它辨真假——伸手与它相认', fate: '逆', ni: true, effect: { alignEvil: 6, rel: { 妖王: 5 }, liuerUnlocked: true }, setFlag: 'n41_liuer:tongxiu', consequence: '此选择将影响：难70六耳了断分支' },
        ] },
      duoduzhuang: { dark: '你袖中藏着那根倒马毒桩——六耳猕猴善聆音、能察理，却最怕这专克佛门的阴毒。它望着你袖管，第一次露了怯。',
        intro: '真假美猴王——你掌中毒桩未收，六耳忌惮，原形将露，它第一次没敢先动手。',
        options: [
          { key: '缘', label: '暂不责罚，细观其行', fate: '缘', effect: { alignGood: 6, ti: { dr: 0.05 } }, setFlag: 'n41_liuer:guancha' },
          { key: 'pozhu', label: '以毒桩相逼，令六耳现形', fate: '夺', effect: { alignEvil: 6, ti: { atk: 24 } }, setFlag: 'n41_liuer:guancha', consequence: '以倒马毒桩逼六耳现原形' },
          { key: '渡', label: '往南海请观音分辨真假', fate: '渡', effect: { alignGood: 10, rel: { 观音: 3 } }, setFlag: 'n41_liuer:guanyin' },
          { key: '逆', label: '不与它辨真假——伸手与它相认', fate: '逆', ni: true, effect: { alignEvil: 6, rel: { 妖王: 5 }, liuerUnlocked: true }, setFlag: 'n41_liuer:tongxiu', consequence: '此选择将影响：难70六耳了断分支' },
        ] },
      quanxie: { dark: '你劝蝎精弃邪西行，妖界传你一句"懂妖"。六耳猕猴与满山妖王本是旧识——它如今敢来搅局，背后有妖王一族默许。',
        intro: '真假美猴王——妖王一族与六耳本是旧识，或可借旧情劝它退去，不必棒下见真章。',
        options: [
          { key: '缘', label: '暂不责罚，细观其行', fate: '缘', effect: { alignGood: 6, gold: 57 }, setFlag: 'n41_liuer:guancha' },
          { key: 'quanyao', label: '请妖王故交出面劝六耳', fate: '缘', effect: { alignGood: 8, rel: { 妖王: 2 } }, requireRel: { 妖王: 8 }, setFlag: 'n41_liuer:guancha', consequence: '借妖王旧情劝退六耳——妖王缘须足' },
          { key: '渡', label: '往南海请观音分辨真假', fate: '渡', effect: { alignGood: 10, rel: { 观音: 3 } }, setFlag: 'n41_liuer:guanyin' },
          { key: '逆', label: '不与它辨真假——伸手与它相认', fate: '逆', ni: true, effect: { alignEvil: 6, rel: { 妖王: 5 }, liuerUnlocked: true }, setFlag: 'n41_liuer:tongxiu', consequence: '此选择将影响：难70六耳了断分支' },
        ] },
    },
    dark: '你打伤一个"悟空"——他死前喊冤：我才是真的。另一个悟空从云里落下，冷笑：他装的。你看着两个一模一样的人，头一回分不清真假。',
    intro: '真假美猴王——六耳猕猴初现，真假难辨。',
    options: [
      { key: '缘', label: '暂不责罚，细观其行', fate: '缘', effect: { alignGood: 6, ti: { hp: 73 } }, setFlag: 'n41_liuer:guancha' },
      { key: '渡', label: '往南海请观音分辨真假', fate: '渡', effect: { alignGood: 10, rel: { 观音: 3 } }, setFlag: 'n41_liuer:guanyin' },
      { key: '战', label: '棒喝二猴，试其真身', fate: '战', effect: { alignEvil: 2, ti: { atk: 29, dr: 0.04 } }, fight: true, setFlag: 'n41_liuer:banghe' },
      { key: '逆', label: '不与它辨真假——伸手与它相认', fate: '逆', ni: true, effect: { alignEvil: 6, rel: { 妖王: 5 }, liuerUnlocked: true }, setFlag: 'n41_liuer:tongxiu', consequence: '此选择将影响：难70六耳了断分支' },
    ],
  },
  42: { id: 42, name: '沙僧辨假', act: 10, type: 'event', icon: '✦',
    fate: '缘', echo: '原著地理重排·新增（第42难·地区10）',
    dark: '沙僧去花果山请悟空，却见"悟空"在花果山称王。他跪求真经，两个悟空都说：我是真的。沙僧回来问你：师父，连我都辨不出。',
    intro: '真假猴王——沙僧往返对质，真假莫辨。',
    options: [
      { key: '缘', label: '慰沙僧，共商辨假之策', fate: '缘', effect: { alignGood: 6, ti: { hp: 85 } } },
      { key: '渡', label: '念经问心，以心辨假', fate: '渡', effect: { alignGood: 10, yuan: { matk: 27, mdef: 0.06 } } },
      { key: '逆', label: '怒而遣散二猴，独自西行', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +5 } } },
      { key: '隐', label: '隐于云端，袖手观真假之争', fate: '隐', effect: { alignEvil: 4, ti: { eva: 10 } } },
    ],
    hidden: { hero: 'shaseng', cond: '渡 + 善≥20', job: '沙·辨假', hint: '真假猴王择「渡」、善行满二十——渡假存真，沙僧慧眼', desc: '真假猴王以渡辨假，卷帘慧眼（沙僧·沙·辨假）' }, },
  43: { id: 43, name: '幽冥谛听', act: 10, type: 'event', icon: '✦',
    fate: '隐', echo: '原著地理重排·新增（第43难·地区10）',
    dark: '地府谛听伏地听了半晌，抬头只说了句："不可说破。"你问为何？它瞥你一眼："说破的，都是死过的。"',
    intro: '真假猴王——地府谛听辨六耳，不敢道破。',
    options: [
      { key: '隐', label: '不再追问，听其言外', fate: '隐', effect: { alignGood: 2, yuan: { mdef: 0.04 } } },
      { key: '渡', label: '请地藏开示，寻辨真法', fate: '渡', effect: { alignGood: 10, ti: { eva: 15 } } },
      { key: '逆', label: '逼谛听说破，不惜逆天', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +5 } } },
    ] },
  44: { id: 44, name: '如来说破', act: 10, type: 'event', icon: '✦',
    fate: '渡', echo: '原著地理重排·新增（第44难·地区10）',
    dark: '灵山之上，如来合掌："六耳猕猴，善聆音，能察理。"他话音未落，那假悟空已现出本相——浑身是毛，眼放金光。你忽然懂了：辨真假的法子，从来不在眼睛。',
    intro: '真假猴王——灵山如来道破六耳本相。',
    options: [
      { key: '渡', label: '合掌谢如来，了却真假', fate: '渡', effect: { alignGood: 10, ti: { hp: 103, dr: 0.07 } } },
      { key: '逆', label: '讥如来偏私，拂袖而去', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +3 } } },
      { key: '战', label: '一棒压那六耳，亲自收束', fate: '战', fight: true, effect: { alignEvil: 8, ti: { atk: 21, hp: 63 } } },
      { key: '隐', label: '隐于莲座旁，听如来道破', fate: '隐', effect: { alignGood: 2, ti: { eva: 8 } } },
    ] },
  45: { id: 45, name: '真假美猴王', act: 10, type: 'fight', icon: '⚔',
    fate: '逆', echo: '战/渡副→悟空线·六耳；真假归一回扣(第77难)',
    dark: '六耳猕猴不是妖，是"另一个可能"——若当年压在五行山下的，是听话的那只。',
    intro: '真假美猴王难辨，天庭地府皆无奈；你收六耳，或认下"你即我"。',
    options: [
      { key: '战', label: '如来收六耳', fate: '战', effect: { alignGood: 2, ti: { atk: 20, hp: 120 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '与六耳和解', fate: '渡', effect: { alignGood: 15, ti: { hp: 115, dr: 0.06 } } },
      { key: '夺', label: '夺他随心铁杆兵', fate: '夺', effect: { alignEvil: 6, ti: { atk: 12, hp: 66 } } , fight: true, bossDiff: 1.48, duo: 'T1', treasure: 'tre_suixinbing' },
      { key: '逆', label: '认下「你即我」', fate: '逆', ni: true, effect: { alignEvil: 15, d29Ni: true } },
    ],
    hidden: { hero: 'wukong', cond: '逆 + 紧箍 + 夺宝≥1', job: '齐天·大圣', hint: '逆上灵山、夺过至宝——大圣之名，自己写', desc: '双身同战，体物伤+30%' },
    // 8.11 难29 专属：六耳化身印（齐天·大圣 / 六耳·残 转职持有门槛件）
    treasure: { id: 'liuer', type: 'treasure', note: '六耳化身印·真假美猴王机缘（8.11 难29 专属）' } },
  46: { id: 46, name: '火焰借扇', act: 11, type: 'fight', icon: '⚔',
    fate: '夺', echo: '战副→火焰重燃回扣(第78难)',
    dark: '铁扇公主的扇，扇一下是火，扇一下是风——她守的不是山，是"不让你过去，就不必面对牛魔王背叛的真相"。',
    intro: '火焰山前，铁扇公主假扇戏你三调芭蕉；你力夺真扇，或变虫入腹逼扇。',
    options: [
      { key: '战', label: '力夺真扇', fate: '战', effect: { alignEvil: 6, ti: { atk: 25, hp: 101 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '夺', label: '变虫入腹，逼她交扇', fate: '夺', effect: { alignEvil: 8, ti: { atk: 17 } } , fight: true, bossDiff: 1.5, duo: 'T1', treasure: 'tre_bajiaoshan_ying' , chain: 'hy_jiashan' },
      { key: '缘', label: '以礼借扇，结一段善缘', fate: '缘', effect: { alignGood: 6, ti: { hp: 92 } } },
      { key: '逆', label: '与她同病——你守扇是替红孩儿守的，我夺扇又是替谁', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_luocha' } },
    ],
    hidden: { hero: 'bajie', cond: '战 + 战≥3', job: '净坛·踏焰', hint: '火焰山一贯以「战」踏焰——三战成锋，净坛越战越烈', desc: '火焰山踏焰扛山，净坛踏焰（八戒·净坛·踏焰）' },
    treasure: { id: 'liuer', note: '已在 TREASURES' } },

  47: { id: 47, name: '假扇风波', act: 11, type: 'event', icon: '✦',
    fate: '隐', echo: '原著地理重排·新增（第47难·地区11）',
    dark: '铁扇公主给了你一把扇，你借它灭火——火越扇越旺。你烧了满脸，才知扇是假的。你笑：真扇她留着，假扇烧了八百里。',
    intro: '火焰山——铁扇公主以假扇相欺，火势更旺。',
    options: [
      { key: '隐', label: '忍下火燎，再谋真扇', fate: '隐', effect: {'alignGood':4} },
      { key: '渡', label: '托人斡旋，求和借扇', fate: '渡', effect: {'alignGood':10} },
      { key: '战', label: '持假扇怒闯芭蕉洞', fate: '战', fight: true, effect: {'alignEvil':8} , chainMul: ['hy_jiashan', 1.15] },
      { key: '缘', label: '寻铁扇结缘，辨假扇真伪', fate: '缘', effect: {"alignGood":6} },
    ] },
  48: { id: 48, name: '积雷山·牛魔王', act: 11, type: 'fight', icon: '⚔',
    fate: '战', echo: '原著地理重排·新增（第48难·地区11）',
    dark: '积雷山摩云洞，牛魔王端坐饮酒，见你便笑："我妻的扇，你也敢惦记？"他吹一口气，山都矮了三分。',
    intro: '火焰山——积雷山牛魔王挡道。',
    options: [
      { key: '战', label: '棒斗牛魔王，夺路入洞', fate: '战', effect: { alignEvil: 8, ti: { atk: 27, hp: 61 } }, fight: true},
      { key: '渡', label: '攀交讲和，请他让扇', fate: '渡', effect: { alignGood: 10, ti: { hp: 85, dr: 0.04 } } },
      { key: '隐', label: '夜袭摩云洞，盗那扇柄', fate: '隐', effect: { alignEvil: 6, yuan: { mdef: 0.05 } } , chain: 'hy_bing' },
      { key: '逆', label: '不请天王父子——兄弟，你本就反过一次', fate: '逆', ni: true, effect: { alignEvil: 10, treasure: 'ni_niumo' } },
    ],
    hidden: { hero: 'xiaobailong', cond: '渡 + 善≥25', job: '白龙·吐水', hint: '积雷山牛魔王一战择「渡」、善行满二十五——吐水化雨，龙克真火', desc: '积雷山牛魔王真身前吐水克火，白龙化雨（小白龙·白龙·吐水）' } },
  49: { id: 49, name: '翠云山·真扇决战', act: 11, type: 'fight', icon: '⚔',
    fate: '战', echo: '原著地理重排·新增（第49难·地区11）',
    dark: '翠云山芭蕉洞前，牛魔王现出白牛本相，踏碎云头。你攥紧金箍棒——这扇不拿到手，八百里火焰山烧的就不止是路了。',
    intro: '火焰山关隘——牛魔王/铁扇公主，真扇之战。',
    options: [
      { key: '战', label: '降伏牛魔，得真扇灭焰', fate: '战', effect: { alignGood: 3, ti: { eva: 10 } }, fight: true, chainMul: ['hy_bing', 0.85] },
      { key: '渡', label: '以情动铁扇，化干戈为玉帛', fate: '渡', effect: { alignGood: 10, ti: { hp: 104, dr: 0.06 } } },
      { key: '夺', label: '巧夺芭蕉扇，拂焰而去', fate: '夺', effect: { alignEvil: 6, ti: { atk: 23, hp: 108 } } , fight: true, bossDiff: 1.65, duo: 'T0', treasure: 'tre_bajiaoshan' , chainMul: ['hy_jiashan', 0.90] },
      { key: '逆', label: '当面撕了那道招安的旨——平天大圣不是谁家的一条犬', fate: '逆', ni: true, effect: { alignEvil: 12, rel: { 妖王: +3 } } },
    ],
    // —— V8.57 补火焰山隐藏职（原 act11 0隐藏职）——
    hidden: { hero: 'all', cond: '渡 + 渡≥3', job: '罗刹·铁扇', hint: '火焰山以「渡」化铁扇，芭蕉真法自渡——走「渡」三难', desc: '铁扇公主见你以情动人，将芭蕉扇真法传你——解锁隐藏转职「罗刹·铁扇」（须于本难择「以情动铁扇」，且累计走「渡」三难）' } },
  50: { id: 50, name: '祭赛金光', act: 12, type: 'fight', icon: '⚔',
    fate: '渡', echo: '战副→祭赛还光回扣(第79难)',
    branchKey: 'n50_jisai',   // 网状叙事（P3）：三选一落印，难51「金光寺冤僧」据此改写
    dark: '金光寺舍利被窃，实是碧波潭龙女偷去献天——"献祭"是妖界向上爬的唯一路。',
    intro: '金光寺塔顶三年无光，满城香客怨僧不诚。你夜探碧波潭，见龙宫宴上九头虫把舍利系在龙女发间当夜明珠——"取经人？"九头虫九首齐转，"我缺一盏照夜灯，你来得正好。"',
    options: [
      { key: '战', label: '二郎助擒', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignGood: 6, rel: { 玉帝: 3 } }, setFlag: 'n50_jisai:erlang' },
      { key: '渡', label: '夺回舍利超度', fate: '渡', effect: {alignGood: 12, rel: { 观音: 5 } } , chain: 'js_du', setFlag: 'n50_jisai:duohui' }
,
      { key: '夺', label: '夺佛宝舍利，自取其一', fate: '夺', effect: {"alignEvil":6} , fight: true, bossDiff: 1.6, duo: 'T0', treasure: 'tre_sheli' , chain: 'js_sheli', setFlag: 'n50_jisai:duofo' },
    ],
    hidden: { hero: 'wukong', cond: '夺 + 日记装备≥3', job: '九头·掠宝', desc: '逆夺九虫佛宝，日记载其名（悟空·九头掠宝）', hint: '选「夺」取碧波潭佛宝，并持有≥3件冒险日记奇物——夺来的与记下的，都是你的凭证' },
    treasure: { id: 'zhaoyao', phase: 'out', effect: '照妖，下战-1' } },
  51: { id: 51, name: '金光寺冤僧', act: 12, type: 'event', icon: '✦',
    fate: '逆', echo: '渡副→金光寺舍利失窃（呼应第31难祭赛金光）',
    branchKey: 'n50_jisai',   // 网状叙事（P3）：读难50祭赛三分支改写冤僧走向
    branches: {
      erlang: { dark: '二郎显圣真君随你入城，天庭威名赫赫。国王哪敢再拦——地牢铁门当场打开，满寺冤僧鱼贯而出，对你纳头便拜。',
        intro: '祭赛国金光寺——天兵助阵，冤僧即刻开释，满城僧众伏地谢恩，塔顶三年无光重现一线。',
        options: [
          { key: '缘', label: '受僧众谢礼，取寺中香火钱济贫', fate: '缘', effect: { alignGood: 6, gold: 60 }, consequence: '天庭威名下，僧众献金谢恩' },
          { key: '逆', label: '趁乱夺塔中旧物', fate: '逆', effect: { alignEvil: 10, ti: { atk: 17, hp: 104 } } },
          { key: '夺', label: '夺回镇寺之宝，占为功果', fate: '夺', effect: { alignEvil: 6, ti: { atk: 28, hp: 110 } } , fight: true, bossDiff: 1.4, duo: 'T1', treasure: 'tre_foguang' },
        ] },
      duohui: { dark: '舍利归位，塔顶三年无光重放光明。冤僧们仰见金光，满眶是泪——佛没有偷他们的光，是有人替他们把光请回来了。',
        intro: '祭赛国金光寺——舍利归塔重光，冤僧感泣；你可为这场冤案超度一场。',
        options: [
          { key: '渡', label: '为僧申冤', fate: '渡', effect: { alignGood: 10, ti: { hp: 65, dr: 0.06 } } },
          { key: 'chao', label: '为满寺冤僧做一场水陆道场', fate: '渡', effect: { alignGood: 15, rel: { 观音: 3 } }, consequence: '超度冤魂，观音缘更厚' },
          { key: '逆', label: '趁乱夺塔中旧物', fate: '逆', effect: { alignEvil: 10, ti: { atk: 16, hp: 111 } } },
          { key: '夺', label: '夺回镇寺之宝，占为功果', fate: '夺', effect: { alignEvil: 6, ti: { atk: 15, hp: 85 } } , fight: true, bossDiff: 1.4, duo: 'T1', treasure: 'tre_foguang' },
        ] },
      duofo: { dark: '你夺了佛宝舍利，国王却把气全撒在僧众头上——"定是你们守宝不力！"刑枷加得更重。你要再替他们申冤，便是与王、与己都过不去。',
        intro: '祭赛国金光寺——佛宝已入你囊，国王迁怒僧众，刑枷愈重，满寺冤声一夜比一夜高。',
        options: [
          { key: '渡', label: '为僧申冤', fate: '渡', effect: { alignGood: 10, rel: { 观音: +5 } }, requireLock: ['n50_jisai:duofo'], consequence: '已夺佛宝舍利，再申冤便是自打自脸——此路已锁' },
          { key: '逆', label: '趁乱夺塔中旧物', fate: '逆', effect: { alignEvil: 10, gold: 53 } },
          { key: '夺', label: '夺回镇寺之宝，占为功果', fate: '夺', effect: { alignEvil: 6, gold: 35 } , fight: true, bossDiff: 1.4, duo: 'T1', treasure: 'tre_foguang' },
        ] },
    },
    dark: '金光寺宝塔失光，舍利被窃，满寺僧众被冤下狱——住持不认，被拷断十指；小沙弥不认，被锁进地牢。\n城里的孩童唱："和尚偷了佛的光，佛便收了城的香。"你路过地牢，听见老僧在念经——念的不是求饶，是超度。\n他们跪着求的佛，先偷了他们的光。',
    intro: '祭赛国金光寺宝塔蒙尘，舍利失窃，满寺僧众被冤下狱；你查案申冤，或趁乱取利，问一问那失窃的光。',
    options: [
      { key: '渡', label: '为僧申冤', fate: '渡', effect: { alignGood: 10, ti: { dr: 0.05, eva: 15 } } },
      { key: '逆', label: '趁乱夺塔中旧物', fate: '逆', effect: { alignEvil: 10, ti: { atk: 13, hp: 86 } } }
,
      { key: '夺', label: '夺回镇寺之宝，占为功果', fate: '夺', effect: {"alignEvil":6} , fight: true, bossDiff: 1.4, duo: 'T1', treasure: 'tre_foguang' },
    ] },

  52: { id: 52, name: '碧波潭探', act: 12, type: 'event', icon: '✦',
    fate: '隐', echo: '渡副→碧波潭龙宫暗线',
    dark: '碧波潭底，万圣龙宫灯火通明——九头虫把舍利当夜明珠，挂在龙女床头。',
    intro: '追查舍利至碧波潭，龙宫夜宴；你潜潭暗查，或逼问龙兵。',
    options: [
      { key: '渡', label: '劝龙兵回头', fate: '渡', effect: { alignGood: 15, ti: { hp: 103, dr: 0.04 } } },
      { key: '战', label: '杀进这场龙宫夜宴', fate: '战', effect: { alignEvil: 6, ti: { atk: 24, hp: 73 } } },
      { key: '夺', label: '夺九叶灵芝草', fate: '夺', effect: { alignEvil: 6, ti: { atk: 19, hp: 71 } } , fight: true, bossDiff: 1.42, duo: 'T1', treasure: 'tre_lingzhi' },
      { key: '逆', label: '逼问龙兵', fate: '逆', ni: true, effect: { alignEvil: 10, rel: { 妖王: +3 } } },
    ],
    hidden: { hero: 'shaseng', cond: '缘 + 缘≥4', job: '卷帘·守舍利', hint: '碧波潭一贯以「缘」守舍利——缘结四方，卷帘护宝', desc: '碧波潭守舍利结缘，卷帘守宝（沙僧·卷帘·守舍利）' },
  },
  53: { id: 53, name: '万圣盗草·乱石山伏', act: 12, type: 'event', icon: '✦',
    fate: '隐', echo: '缘副→九叶灵芝草暗线',
    dark: '万圣公主偷了王母的九叶灵芝草，只为给九头虫续命——她以为偷来的爱，能养出真心。',
    intro: '万圣公主盗九叶灵芝草救九头虫；你点破她，或助她偷到底。',
    options: [
      { key: '缘', label: '助她偷到底', fate: '缘', effect: { alignGood: 6, ti: { hp: 111 } } },
      { key: '渡', label: '点破她，止这一桩盗案', fate: '渡', effect: { alignGood: 10, ti: { hp: 62, dr: 0.05 } } },
      { key: '战', label: '黑吃黑，夺下盗草赃物', fate: '战', effect: { alignEvil: 8, ti: { atk: 14, hp: 87 } } },
      { key: '逆', label: '替她把草盗成——她盗草，只为给丈夫续一条命', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: +4 } } },
    ],
    hidden: { hero: 'tangseng', cond: '缘 + 缘≥3', job: '金蝉·谕经', hint: '乱石山伏一贯以「缘」谕经——缘续经传，金蝉了义', desc: '乱石山伏谕经化草，金蝉再谕（唐僧·金蝉·谕经）' },
  },
  54: { id: 54, name: '九头虫·碧波潭', act: 12, type: 'fight', icon: '⚔',
    fate: '战', echo: '战副→祭赛还光回扣(第79难)；九头虫伏诛',
    dark: '九头虫九头齐出，舍利在他腹中发光——他吞的不是佛宝，是"被供奉"的执念。\n他大笑："你替秃驴们讨光？他们供了三百年的佛光，佛可曾分他们一寸？不如留给我——我做这碧波潭的佛，起码还照得见龙女的眉。"',
    intro: '碧波潭底水宫尽塌，九头虫现出本相，九首各衔一件兵刃，舍利悬在正中那颗头颅的眉心——"取经人，你抢回去的只是一颗珠子。可这国的人，早忘了光是什么。"',
    options: [
      { key: '战', label: '战九头虫', fate: '战', effect: { alignGood: 3, ti: { atk: 15, hp: 94 } }, fight: true, battleFlags: { openingMomentum: 1 }, chainMul: ['js_sheli', 0.85] },
      { key: '渡', label: '请二郎显圣真君与梅山六兄弟来助', fate: '渡', effect: { alignGood: 10, ti: { hp: 92, dr: 0.06 } } },
      { key: '夺', label: '夺月牙铲，取回塔顶佛宝舍利', fate: '夺', effect: { alignEvil: 6, ti: { atk: 24, hp: 88 } } , fight: true, bossDiff: 1.48, duo: 'T1', treasure: 'tre_yueyachan' , chainMul: ['js_sheli', 0.85] },
      { key: '逆', label: '放它走——这群妖里只有它知道回去是什么下场', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_jiutou' } },
    ],
  },
  55: { id: 55, name: '木仙谈诗', act: 13, type: 'event', icon: '✦',
    fate: '缘', echo: '渡/隐副→诗酒机缘',
    dark: '荆棘岭树精邀你谈诗——它们活了千年，只因"不做取经人"。杏仙要你留下，做一棵树。',
    intro: '荆棘岭木仙庵，树精邀你谈诗欲留你做树；你斩树脱身，或愿做树一刻。',
    options: [
      { key: '渡', label: '点破它们执着于形的苦，送其往生', fate: '渡', effect: { alignGood: 10, ti: { hp: 95, dr: 0.05 } } },
      { key: '隐', label: '愿做树一刻', fate: '隐', effect: { alignGood: 4, yuan: { mdef: 0.05 } } },
      { key: '夺', label: '夺其千年木心', fate: '夺', effect: { alignEvil: 6, ti: { atk: 27, hp: 69 } } , fight: true, bossDiff: 1.42, duo: 'T1', treasure: 'tre_muxin' },
      { key: '逆', label: '不斩不留——它们只谈了一夜诗，凭什么被筑倒', fate: '逆', ni: true, effect: { alignEvil: 6, treasure: 'ni_shujing' } },
    ],
  },
  56: { id: 56, name: '小雷音假佛', act: 13, type: 'fight', icon: '⚔',
    fate: '逆', echo: '渡副→弃经链；小雷音破回扣(第80难)',
    dark: '黄眉童儿坐莲台，那人种袋能装一切——包括"你相信的那尊佛"。山门护法来收，却笑说：你分得清真假吗？',
    intro: '小雷音寺，黄眉童儿假佛坐莲台；你战，或夺人种袋破假佛。',
    options: [
      { key: '渡', label: '请弥勒来收，归他一个座下', fate: '渡', effect: { alignGood: 12, ti: { hp: 117, dr: 0.04 } }, fight: true, battleFlags: { dmgMul: 0.9, incomingDmgMul: 0.85 }},
      { key: '战', label: '一棒砸了这座假雷音', fate: '战', effect: { alignGood: 3, ti: { atk: 13, hp: 63 } } },
      { key: '夺', label: '夺金铙法器，破其假阵', fate: '夺', effect: { alignEvil: 6, ti: { atk: 25, hp: 107 } } , fight: true, bossDiff: 1.6, duo: 'T0', treasure: 'tre_jinnao' },
      { key: '逆', label: '夺人种袋——他想坐的，不过是那张位子', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_huangmei' } },
    ],
    treasure: { id: 'bf_renzhongdai', phase: 'in', effect: '装敌一回合，1/1' } },
  57: { id: 57, name: '朱紫医王', act: 13, type: 'event', icon: '✦',
    fate: '缘', echo: '逆副→吞天净坛链(八戒)',
    dark: '朱紫国王因"射伤神兽"被罚，金圣宫被赛太岁夺——天庭的罚，比妖狠。',
    intro: '朱紫国王被罚，金圣宫被赛太岁夺；你悬丝诊脉医王，或问其罪。',
    options: [
      { key: '缘', label: '悬丝诊脉，先医国王', fate: '缘', effect: { alignGood: 8, ti: { hp: 72, dr: 0.07 } } },
      { key: '渡', label: '往南海请观音收犼，还金圣宫娘娘', fate: '渡', effect: { alignGood: 10, ti: { hp: 60, dr: 0.05 } } },
      { key: '夺', label: '夺它三个金铃', fate: '夺', effect: { alignEvil: 6, ti: { atk: 20, hp: 83 } } , fight: true, bossDiff: 1.58, duo: 'T0', treasure: 'tre_jinling' },
      { key: '逆', label: '问国王三年不朝之罪——得病的到底是谁', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_jinmaohou' } },
    ],
  },
  58: { id: 58, name: '狮驼尸山·如来收鹏', act: 13, type: 'fight', icon: '⚔',
    fate: '逆', echo: '战/渡副→卷帘/弃经链；取尸骨为甲',
    dark: '四百里尸山，是历代取经人堆的——大鹏说：你不是第一个，也不会是最后一个。',
    intro: '狮驼岭四百里尸山，历代取经人堆成；你破尸山，或取尸骨为甲。',
    options: [
      { key: '战', label: '破尸山', fate: '战', effect: { alignGood: 3, ti: { atk: 29, hp: 99 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '超度亡魂', fate: '渡', effect: { alignGood: 20, ti: { hp: 105, dr: 0.06 } } },
      { key: '夺', label: '夺阴阳二气瓶', fate: '夺', effect: { alignEvil: 6, ti: { atk: 30, hp: 98 } } , fight: true, bossDiff: 1.62, duo: 'T0', treasure: 'tre_yinyangping' },
      { key: '逆', label: '取尸骨为甲', fate: '逆', ni: true, effect: { alignEvil: 10, rel: { 妖王: +4 } } },
    ],
    treasure: { id: 'bf_yinerping', phase: 'passive', effect: '敌现身处-8%血，1/1' },
    hidden: { hero: 'all', cond: '逆 + 第29难曾选逆', job: '六耳·残', hint: '第29难曾选「逆」、且已觉醒齐天·大圣——残躯承大圣之逆', desc: '解锁隐藏第四人·六耳可参战（须于难45真假美猴王认六耳）' } },
  59: { id: 59, name: '比丘白鹿', act: 14, type: 'event', icon: '✦',
    fate: '逆', echo: '原著地理重排·新增（第59难·地区14）',
    dark: '比丘国国王要用一千一百一十一个小孩的心肝做药引——他只道这是国丈献的长生方。国丈拄杖立在丹房，鹿眼藏在官帽下，看那些被锁的孩童如看草料。\n你问他：鹿心做药引，够不够？\n他笑了，声音像从很深的山洞里传来："够？国王要的是长生，我给的是药引。药引是真是假，谁在意呢——反正吃过的人，都死了。"\n后来你才知，这国丈是终南山的白鹿精，假扮寿星的模样，只为一国童血养它一具鹿身。',
    intro: '比丘国白鹿精假国丈，以孩童心肝炼药；国王久病不愈，国丈执掌朝纲。你入宫探案，或直捣清华洞，问鹿心够不够。',
    options: [
      { key: '逆', label: '揭穿国丈，救孩童于丹炉', fate: '逆', effect: {'alignEvil':8, treasure: 'ni_bailu' } },
      { key: '渡', label: '入宫说法，劝国王罢手', fate: '渡', effect: {'alignGood':10} },
      { key: '战', label: '追白鹿至清华洞，一战除妖', fate: '战', fight: true, effect: {'alignEvil':8}, battleFlags: { openingMomentum: 1 }, alignGood: 3 },
      { key: '隐', label: '隐于丹房，探白鹿底细', fate: '隐', effect: { alignGood: 2, ti: { eva: 13 } } },
    ] },
  60: { id: 60, name: '灭法剃王', act: 14, type: 'event', icon: '✦',
    fate: '逆', echo: '渡副→弃经链',
    branchKey: 'n60_miefa',   // 网状叙事（P3）：三选一落印；其中「逆·剃尽僧发反制」为中途结局触发点
    dark: '灭法国要杀万僧，因国王梦见"僧压龙"——梦是灵山授的，杀是王替天行。',
    intro: '灭法国王梦"僧压龙"要杀万僧；你智剃众僧发，或反制剃王。',
    options: [
      { key: '缘', label: '化解', fate: '缘', effect: { gold: 30, alignGood: 8, rel: { 玉帝: 5 } }, setFlag: 'n60_miefa:huajie' },
      { key: '逆', label: '剃尽僧发反制——你索性反了，自封战佛', fate: '逆', ni: true, effect: { alignEvil: 8, rel: { 妖王: 5 } }, setFlag: 'n60_miefa:tifa', midEnding: 'zhanfo', consequence: '此选择将触发中途结局：战佛临世' }
,
      { key: '夺', label: '夺其剃度刀，绝其王法', fate: '夺', effect: {"alignEvil":6} , fight: true, bossDiff: 1.4, duo: 'T1', treasure: 'tre_tidao', setFlag: 'n60_miefa:duodao' },
    ] },
  61: { id: 61, name: '隐雾梅花', act: 14, type: 'fight', icon: '⚔',
    fate: '隐', echo: '战副→卷帘复权链(沙僧)',
    dark: '南山大王分瓣梅花计，是把"你"拆成几瓣骗自己——你以为选了路，其实路选了你。',
    intro: '隐雾山分瓣梅花计，把"你"拆成几瓣骗自己；你破计，或识破不走。',
    options: [
      { key: '战', label: '破它的分瓣梅花计', fate: '战', effect: { alignGood: 3, ti: { atk: 17, hp: 94 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '隐', label: '识破不走', fate: '隐', effect: { alignGood: 4, yuan: { mdef: 0.06 } } },
      { key: '缘', label: '与梅花鹿精结缘，渡其归道', fate: '缘', effect: { alignGood: 6, ti: { hp: 140 } } },
      { key: '逆', label: '反用它的分瓣计——你拆我几瓣，我便拆了这座山', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_baozi' } },
    ],
    hidden: { hero: 'tangseng', cond: '隐 + 隐≥3 + 索命簿残卷', job: '判官金蝉', hint: '一贯以「隐」三难、持索命簿残卷——阴司账薄，你来做主', desc: '断人生死，替天行道' } },
  62: { id: 62, name: '凤仙求雨', act: 14, type: 'event', icon: '✦',
    fate: '缘', echo: '渡副→求雨机缘',
    dark: '凤仙郡侯因推倒供桌被旱三年——天庭的雨，要"诚心"买，诚心是粮。',
    intro: '凤仙郡旱三年，因推倒供桌触怒天庭；你建祠求雨，或咒天不下。',
    options: [
      { key: '渡', label: '建祠求雨', fate: '渡', effect: { alignGood: 15, ti: { hp: 148, dr: 0.05 } }, disciple: 'fengxian' },
      { key: '逆', label: '咒天不下', fate: '逆', effect: { alignEvil: 10, rel: { 妖王: +5 } } }
,
      { key: '夺', label: '夺雨符，自布云雨', fate: '夺', effect: {"alignEvil":6} , fight: true, bossDiff: 1.42, duo: 'T1', treasure: 'tre_yufu' },
    ] },
  63: { id: 63, name: '玉华盗兵', act: 14, type: 'fight', icon: '⚔',
    fate: '夺', echo: '战副→夺兵暗线',
    dark: '玉华州三王子学艺，黄狮精盗兵器开"钉耙会"——妖也办宴，庆自己"像个人"。',
    intro: '玉华州黄狮精盗兵开钉耙会，庆自己"像个人"；你夺兵，或赴宴。',
    options: [
      { key: '战', label: '夺回三般兵器', fate: '战', effect: { alignGood: 3, ti: { atk: 38, hp: 109 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '缘', label: '赴钉耙宴，与它同席吃一盏', fate: '缘', effect: { alignGood: 8, equipPick: 3 } },
      { key: '渡', label: '上天请太乙救苦天尊来收，给它一个正果', fate: '渡', effect: { alignGood: 10, ti: { hp: 99, dr: 0.06 } } },
      { key: '逆', label: '不请天尊——它办这场宴，只是想有个人来', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_huangshi' } },
    ],
  },
  64: { id: 64, name: '竹节九狮', act: 15, type: 'fight', icon: '⚔',
    fate: '渡', echo: '战副→九狮收；驯兽师伏笔',
    dark: '九灵元圣一口衔住你——它不恨你，只是"天尊的坐骑，习惯了衔东西"。被你一路收下的百兽，在你身后列队嘶吼，全世界都在等你，把这头九头狮子也收进你的兽园。',
    intro: '竹节山九灵元圣一口衔住你，只因习惯衔物；你收九狮为御兽，或顺毛脱身。',
    options: [
      { key: '战', label: '硬接它这一衔，战到它松口', fate: '战', effect: { alignGood: 3, ti: { atk: 29, hp: 108 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '请太乙救苦天尊来收，让它回座下', fate: '渡', effect: { alignGood: 10, ti: { hp: 128, dr: 0.05 } } },
      { key: '隐', label: '顺毛而脱', fate: '隐', effect: { alignGood: 4, yuan: { mdef: 0.06 } } },
      { key: '缘', label: '与九灵元圣结缘，化敌为友', fate: '缘', effect: { alignGood: 6, ti: { hp: 147 } } },
      { key: '逆', label: '收九灵为御兽——它反出天尊座下，不再替谁衔物', fate: '逆', ni: true,
        subText: '你有足够的兽缘与身阵——若能出阵三只以上的御兽，便以兽领群，说动这头九灵元圣，自封驭兽之主。',
        effect: { alignEvil: 8, treasure: 'ni_jiuling' } },
    ],
    hidden: { hero: 'all', cond: '逆 + 出阵灵兽≥3', job: '驯兽师·百兽归心', hint: '收九灵为御兽、出阵灵兽≥3、着御兽套——百兽归心',
      desc: '收九灵为御兽：每上阵一只灵兽，全属性放大约 6%' } },
  65: { id: 65, name: '金平犀灯', act: 15, type: 'fight', icon: '⚔',
    fate: '夺', echo: '战副→犀灯',
    dark: '三犀牛假佛收灯油，因香火供奉"收得太贵"——假佛的灯，照的也是真信徒。',
    intro: '玄英洞三犀假佛收灯油，因香火供奉收得太贵；你战四木禽星，或夺犀角灯。',
    options: [
      { key: '战', label: '战到四木禽星下界', fate: '战', effect: { alignGood: 3, ti: { atk: 29, hp: 126 } }, fight: true, battleFlags: { openingMomentum: 1 }},
      { key: '渡', label: '上奏天庭，请四木禽星收这三犀', fate: '渡', effect: { alignGood: 10, ti: { hp: 126, dr: 0.07 } } },
      { key: '夺', label: '夺犀角灯', fate: '夺', effect: { alignEvil: 6, ti: { atk: 28, hp: 82 } } , fight: true, bossDiff: 1.4, duo: 'T1', treasure: 'tre_xijiaodeng' },
      { key: '逆', label: '不请星官——人跪的从来不是佛，是那三支角', fate: '逆', ni: true, effect: { alignEvil: 8, treasure: 'ni_xiniu' } },
    ],
    hidden: { hero: 'shaseng', cond: '夺 + 夺≥3 + 夺宝≥2', job: '卷帘夺宴', hint: '夺道连三且夺过两件至宝——宴席之上，夺者入座', desc: '夺他人之宴，喂自己之腹' },
    treasure: { id: 'liuer', phase: 'out', effect: '回血40%' } },
  66: { id: 66, name: '给孤布金', act: 15, type: 'event', icon: '✦',
    fate: '渡', echo: '渡副→舍缘链',
    // 【2026-09-13 PHASE 6 · 内容去重】原「给孤招婚」的 dark/options 讲的是天竺玉兔假公主招亲——
    //   与第 68 难「玉兔假公主」是同一事件的两遍叙述，标题（给孤园）与内容（招婚）亦不符。
    //   现 66 归位为真正的「给孤园·布金寺」（原著第 93 回：给孤独长者黄金铺地买祇陀太子园），
    //   玉兔招亲主场全部让给 68；bajie 隐藏职「净坛·拾遗」保留在此（cond 仍为『渡』，语境已改）。
    dark: '舍卫国的给孤独长者要请佛说法，却买不下祇陀太子的园子。太子开价："黄金铺满园地，我便卖你。"长者开了库——金砖一块块铺下去，铺到大半，金子尽了，园子还差一角。太子看着满地金光，忽然按住他的手："罢了，园子你拿去，树是我的——树算我供的。"这便是"给孤园"的来历，也是"布金寺"的名字。\n三百年后你到此处，寺已残，金砖早被人掘走，只剩一块埋在地基里，还咬着当年的光。你蹲下去看那块砖——它什么也不说。舍出去的东西，本来就不必说什么。',
    intro: '舍卫国给孤独长者以黄金铺地买祇陀太子园建寺（布金寺）；三百年后寺残金尽，你入寺问"舍"。',
    options: [
      { key: '渡', label: '重扫布金寺，替长者续这一炷断了三百年的香', fate: '渡', effect: { alignGood: 15, ti: { hp: 81, dr: 0.07 } } },
      { key: '缘', label: '与守寺老僧论"舍"，取地基砖一块为念', fate: '缘', effect: { alignGood: 8, gold: 20 } },
      { key: '逆', label: '不拜——舍了还要刻碑记名，这舍便不干净', fate: '逆', effect: { alignEvil: 8, rel: { 妖王: +5 } } },
      { key: '隐', label: '绕塔而过，不问旧事', fate: '隐', effect: { alignGood: 2, ti: { eva: 20 } } },
    ],
    hidden: { hero: 'bajie', cond: '渡 + 日记装备≥2', job: '净坛·拾遗', desc: '重扫布金寺，行囊里多了几件奇物（八戒·净坛拾遗）', hint: '选「渡」重扫布金寺，并持有≥2件冒险日记奇物——你渡人，也拾奇' },
  },
  67: { id: 67, name: '铜台辨冤', act: 15, type: 'event', icon: '✦',
    fate: '逆', echo: '渡副→弃经链',
    dark: "寇员外斋僧万僧，却在自家门前被人一棍打死。官府拿了取经人当替罪羊，说'和尚贪财害命'。悟空夜入地府，一棒砸开森罗殿，要阎王还寇员外的魂。阎王翻簿：'他斋僧二十七年，善簿厚得压手——可他死前一念，恨的是我斋了一辈子僧，末了被僧害死。这一念恨，把二十七年的善，全烧成了灰。'悟空把那灰捧在手里，吹了一口气：'善人，你恨错了人。害你的不是僧，是贪。'寇员外睁眼，第一句话是：'我那斋僧的粥锅，还热着吗？'——善人的命，要猴王去讨；可善人的执念，要他自己放下。",
    intro: '寇员外斋僧被害，悟空辨冤复活；你复活员外，或查真凶是官。',
    options: [
      { key: '渡', label: '复活员外', fate: '渡', effect: { alignGood: 20, ti: { hp: 126, dr: 0.06 } } },
      { key: '逆', label: '查真凶是官', fate: '逆', effect: { alignEvil: 8, rel: { 妖王: +3 } } }
,
      { key: '缘', label: '与铜台百姓结缘，辨明冤情', fate: '缘', effect: {"alignGood":6} },
    ] },
  68: { id: 68, name: '玉兔假公主', act: 15, type: 'event', icon: '✦',
    fate: '缘', echo: '原著地理重排·新增（第68难·地区15）',
    dark: '天竺国公主绣球抛向你，你却见那"公主"手指甲里嵌着月宫的土。\n三百年前广寒宫，素娥仙子嫌捣药的玉兔挡路，一掌把它打翻在地。如今素娥转世为天竺公主，玉兔下界寻仇——可它见那公主眉目温软，忽然不知该恨谁。\n它杀不了一个无辜的转世，就做了三天公主，替她活一遍。嫦娥在月宫叹气："它偷的从来不是公主的命，是那三百年没被人好好看过的自己。"\n她笑：娶了我，保你西行无忧。你笑：我西行，从不靠娶。',
    intro: '天竺国玉兔精假扮公主招亲，只为替转世的素娥活一遍；你识破其异，或接绣球，窥她三百年心事。',
    options: [
      { key: '缘', label: '不接绣球，暗察其异', fate: '缘', effect: {'alignGood':6} },
      { key: '渡', label: '明言拒亲，劝其归月', fate: '渡', effect: {'alignGood':10} },
      { key: '逆', label: '当众揭破公主是假', fate: '逆', effect: {'alignEvil':8} },
      { key: '隐', label: '隐于月影，识破玉兔', fate: '隐', effect: { alignGood: 4, ti: { eva: 18 } } },
    ] },
  69: { id: 69, name: '月宫桂影', act: 15, type: 'event', icon: '✦',
    fate: '渡', echo: '原著地理重排·新增（第69难·地区15）',
    dark: '月宫桂树下，嫦娥低头捣药。她说那玉兔走失人间三百年，假扮公主只为躲一个"还"字。你问：还什么？她不答，桂影摇了一地。',
    intro: '月宫玉兔往事——嫦娥捣药，桂影摇摇。',
    options: [
      { key: '渡', label: '劝嫦娥了却旧怨，迎兔归月', fate: '渡', effect: {'alignGood':10} },
      { key: '缘', label: '记下玉兔苦衷，暂不相逼', fate: '缘', effect: {'alignGood':6} },
      { key: '隐', label: '不涉月宫恩怨，抽身而退', fate: '隐', effect: {'alignGood':4} , alignGood: 1 },
    ] },
  70: { id: 70, name: '捣药杵', act: 15, type: 'fight', icon: '⚔',
    fate: '夺', echo: '原著地理重排·新增（第70难·地区15）',
    branchKey: 'n70_yutu',   // 网状叙事（P3）：三选一落印；另有「逆·六耳了断」隐藏选项（须难41选「伸手相认」）
    dark: '玉兔操起捣药杵，砸碎天竺金銮殿的门。那杵不是药杵——是月宫里镇过妖的兵。',
    intro: '天竺国玉兔持捣药杵为兵，战于金銮殿。',
    options: [
      { key: '夺', label: '夺那捣药杵，破其兵势', fate: '夺', effect: {'alignEvil':6} , fight: true, bossDiff: 1.42, duo: 'T1', treasure: 'tre_daoyaochu' , chain: 'tz_chu', setFlag: 'n70_yutu:duochu' },
      { key: '战', label: '迎战玉兔，直捣其巢', fate: '战', fight: true, effect: {'alignEvil':8}, battleFlags: { openingMomentum: 1 }, setFlag: 'n70_yutu:yingzhan' },
      { key: '渡', label: '以佛法镇之，止其兵戈', fate: '渡', effect: {'alignGood':10}, setFlag: 'n70_yutu:fofa' },
      { key: '逆', label: '不打了——你与六耳的事，我来做个了断', fate: '逆', ni: true, effect: { alignEvil: 10, rel: { 妖王: +4 } }, setFlag: 'n70_yutu:liuerliao', requireFlag: 'n41_liuer:tongxiu', midEnding: 'liuer', consequence: '此选择将触发分支结局：六耳同修' },
    ] },
  71: { id: 71, name: '玉兔遁月', act: 15, type: 'event', icon: '✦',
    fate: '隐', echo: '原著地理重排·新增（第71难·地区15）',
    dark: '玉兔见败，纵身向月遁去。你伸手拦——她回眸："我偷了三百年的月光，该还了。"话音未落，人已入月，只剩一地清辉。',
    intro: '天竺国玉兔战败遁月，三百年偷来的月光一朝归还；你任其归月，或追月问罪，了却一段因果。',
    options: [
      { key: '隐', label: '任其归月，不再追逼', fate: '隐', effect: {'alignGood':4} },
      { key: '渡', label: '向月合掌，送其一程', fate: '渡', effect: {'alignGood':10} },
      { key: '逆', label: '追月问罪，讨个说法', fate: '逆', effect: {'alignEvil':8} },
    ] },
  72: { id: 72, name: '玉兔精·天竺决战', act: 15, type: 'fight', icon: '⚔',
    fate: '战', echo: '原著地理重排·新增（第72难·地区15）',
    dark: '玉兔精临逃回首，金瞳一睁："你可知天竺国这三年，供的都是假公主？今日一了——"你攥紧法器：假的供了三百年，真的就这一棒。',
    intro: '金銮殿前，玉兔精褪了人皮，露出雪白的耳——捣药杵横在身前，月光在她身周凝成霜："三百年，我学做公主、学做新娘、学做人。可你们只认那一张脸。今日我不躲了——你打碎了它，正好。"',
    options: [
      { key: '战', label: '一棒降玉兔，了结天竺之乱', fate: '战', effect: { alignEvil: 10, ti: { atk: 37, hp: 141 } }, fight: true, chainMul: ['tz_chu', 0.85] },
      { key: '渡', label: '渡其归月，化干戈', fate: '渡', effect: { alignGood: 10, ti: { hp: 124, dr: 0.07 } } },
      { key: '夺', label: '收其捣药杵为宝', fate: '夺', effect: { alignEvil: 6, ti: { hp: 100, dr: 0.08 } } , fight: true, bossDiff: 1.45, duo: 'T1', treasure: 'tre_daoyaochu_yue' , chainMul: ['tz_chu', 0.80] },
      { key: '逆', label: '不送它回月宫——回去接着捣药，正是它逃出来的原因', fate: '逆', ni: true, effect: { alignEvil: 10, treasure: 'ni_yutu' } },
    ],
  },
  73: { id: 73, name: '化电归真', act: 16, type: 'story', icon: '☯',
    fate: '逆', echo: '渡副→弃经/逆道链',
    dark: '雷音门前，如来拈花一笑："金蝉子，你历九九八十一难，功德圆满。今封你为旃檀功德佛，永世受香火。"你低头看自己的手——这双手，在灵山捻过佛珠，在轮回殿喝过孟婆，在长安城外接过唐王的酒，在白虎岭被白骨夫人的指甲划破过。它们是"金蝉子"的手，还是"你"的手？如来又问："你愿做经，还是愿做自己？"做经，便是永世被人念诵，被人供奉，被人当成一句"阿弥陀佛"——可再也没有人叫你"御弟"，再也没有人记得你在女儿国喝过的那杯酒。做自己，便是放下佛位，再入轮回，生生世世做一个普通人——可你终于可以自己决定，下一顿饭吃什么，下一段路怎么走。雷音寺的钟响了。你抬头，看见如来身后的墙上，刻着一行小字："佛者，觉也。觉者，自知也。"——最后一考，不是考你能不能成佛，是考你敢不敢不成佛。',
    intro: '雷音门前最后一考："做经，还是做自己"；你受封，或拒封。',
    options: [
      { key: '渡', label: '受封', fate: '渡', effect: { alignGood: 10, ti: { hp: 139, dr: 0.06 } } },
      { key: '逆', label: '拒封', fate: '逆', effect: { alignEvil: 20, flag: '逆道前置', rel: { 妖王: +4 } } }
    ] },
  74: { id: 74, name: '传经索人事', act: 16, type: 'event', icon: '✦',
    fate: '逆', echo: '原著地理重排·新增（第74难·地区16）',
    dark: '灵山藏经阁前，执事僧捻指："传经岂能白传？拿人事来。"你摸遍行囊，只剩一个破碗。他收了碗，给你一摞白纸。',
    intro: '灵山执事僧索人事，传"无字经"。',
    options: [
      { key: '逆', label: '索回人事，讥其贪墨', fate: '逆', effect: {'alignEvil':8} },
      { key: '渡', label: '以钵盂相赠，权作人事', fate: '渡', effect: {'alignGood':10} },
      { key: '战', label: '夺经而走，不与之交易', fate: '战', fight: true, effect: {'alignEvil':8}, battleFlags: { openingMomentum: 1 }},
      { key: '缘', label: '以钵结缘，赠执事人事', fate: '缘', effect: {"alignGood":6} },
    ] },
  75: { id: 75, name: '无字真经·勘破', act: 16, type: 'event', icon: '✦',
    fate: '渡', echo: '原著地理重排·新增（第75难·地区16）',
    dark: '你翻开"真经"，满纸无一字。你先是怒，继而笑——灵山给有字经渡人，给无字经渡心。你把这摞白纸揣进怀里：这一路八十一难，早把字都写在你心里了。',
    intro: '灵山无字真经——勘破白纸。',
    options: [
      { key: '渡', label: '合掌收下，悟无字之经', fate: '渡', effect: {'alignGood':10} },
      { key: '逆', label: '掷经于地，斥其欺世', fate: '逆', effect: {'alignEvil':8} },
      { key: '缘', label: '留存白纸，以证此行', fate: '缘', effect: {'alignGood':6} },
    ] },
  76: { id: 76, name: '问佛根源', act: 16, type: 'fight', icon: '☯',
    fate: '渡', echo: '渡副→老君伪善链(第二章最终Boss)',
    dark: '如来道："纵牛下界者，老君也。"悟空愣住——那青牛，原是老君炉边坐骑，故意放它下界，只为试取经队伍几分真心。',
    intro: '兜率宫前，太上老君自丹炉雾中现身。青牛已伏，执念未消——这一战，关乎"天道是否值得赴"。',
    // 第二章最终 Boss：老君本体战（呼应天庭征伐主题）。正道闭环天道秩序，逆道揭伪善得专属传记。
    boss: '太上老君化身',
    options: [
      { key: '渡', label: '问如来·请老君收牛', fate: '渡', effect: { alignGood: 28, ti: { hp: 86, dr: 0.06 } },
        rewardTitle: '天道归序·金丹护体', rewardDesc: '老君亲手收牛，赐你一粒护身金丹：受愿伤减免 +5%。天道秩序，自此闭环。',
        fight: true, bossDiff: 0.95},
      { key: '隐', label: '隐于莲座下，窃听佛问', fate: '隐', effect: { alignGood: 2, ti: { eva: 20 } } },
      { key: '战', label: '与这座兜率宫打一场', fate: '战', effect: { alignEvil: 12, ti: { atk: 22, hp: 142 } } },
      { key: '逆', label: '闯兜率宫·质问老君', fate: '逆', ni: true, effect: { alignEvil: 22, rel: { 妖王: +4 } },
        rewardTitle: '业藏录·老君伪善', rewardDesc: '你揪住老君衣襟："你纵牛下界，试我等真心！"——伪善被揭，专属传记《业藏录·老君伪善》解锁。攻击 +10、愿伤 +10。',
        unlockCodex: '业藏录·老君伪善', fight: true, bossDiff: 1.22},
    ],
  },
  77: { id: 77, name: '灵山无字·大圣残躯', act: 16, type: 'boss', icon: '⚔',
    fate: '逆', echo: '战副→逆道真结局门槛；↔80难小雷音破（无字碑↔假佛，真假灵山之辨）',
    dark: '灵山不见佛影，只有一块无字碑——碑上说：来者皆被写进经，有人把经当牢。你面前，是历代取经人的"合体"——大圣残躯。',
    intro: '终战 Boss（diff 20，多阶段）。',
    options: [
      { key: '渡', label: '归入经书', fate: '渡', effect: { alignGood: 10, yuan: { matk: 25, mdef: 0.08 } }, ending: '真·结局（牺牲线）'},
      { key: '隐', label: '携碑遁走', fate: '隐', effect: { alignGood: 2, yuan: { mdef: 0.07 } }, ending: '隐世结局（需全程隐≥阈值）'},
      { key: '战', label: '与这具大圣残躯打完最后一战', fate: '战', effect: { alignEvil: 8, ti: { atk: 29, hp: 94 } } },
      { key: '逆', label: '碎无字碑', fate: '逆', ni: true, effect: { alignEvil: 15, rel: { 妖王: +4 } }, ending: '逆道结局（反抗线，需全程逆≥阈值）', jobConfirm: '齐天·大圣'},
    ],
    hidden: { hero: 'all', cond: '逆 + 日记装备≥4', job: '行旅录主', desc: '一路奇物皆入日记，逆上灵山以物证道（全英雄·行旅录主）', hint: '选「逆」碎无字碑，并持有≥4件冒险日记奇物——以一路所得之奇物，证你逆道' },
    unlock: '击败后主菜单解锁"命数"面板与全部隐藏转职触发条件' },

  78: { id: 78, name: '凌云渡·无底船', act: 17, type: 'event', icon: '✦',
    fate: '渡', echo: '原著地理重排·新增（第78难·地区17）',
    dark: '凌云渡口，一只无底船泊在江心。撑船的老者看你："上船吧，这船不渡活人，只渡死过的。"你抬脚踏上——船没沉，因为你的影子，早沉了。',
    intro: '凌云渡无底船——渡生死之界。',
    options: [
      { key: '渡', label: '踏上无底船，渡此生死', fate: '渡', effect: {'alignGood':10} },
      { key: '逆', label: '拒不上船，质问船夫', fate: '逆', effect: {'alignEvil':8} },
      { key: '隐', label: '沿岸寻桥，绕开此渡', fate: '隐', effect: {'alignGood':4} , alignEvil: 3 },
      { key: '缘', label: '与渡夫结缘，同登彼岸', fate: '缘', effect: {"alignGood":6} },
    ] },
  79: { id: 79, name: '晒经石', act: 17, type: 'event', icon: '✦',
    fate: '缘', echo: '原著地理重排·新增（第79难·地区17）',
    dark: '通天河老鼋翻身，真经湿透。你在晒经石上摊开晾晒，几页经文的字被水浸去。你忽然明白：八十一难的最后一难，不在取，在"还"。',
    intro: '通天河晒经石——湿经还字。',
    options: [
      { key: '缘', label: '细读湿经残字，记其本真', fate: '缘', effect: {'alignGood':6} },
      { key: '渡', label: '合掌向老鼋，应诺还它一问', fate: '渡', effect: {'alignGood':10} },
      { key: '逆', label: '怪老鼋覆舟，拂袖而去', fate: '逆', effect: {'alignEvil':8} },
    ] },
  80: { id: 80, name: '灵山索经·阿难迦叶', act: 17, type: 'boss', icon: '⚰️',
    bossName: '传经吏·索经',
    fate: '逆', echo: '原著地理重排·新增（第80难·第9章关隘）；阿难迦叶索人事、传无字真经',
    dark: '灵山藏经阁前，阿难、迦叶二尊者捻指而笑："传经岂能白传？人事拿来。"你摸遍行囊，只剩一个紫金钵——那是大唐天子亲赐之物。他二人收了钵，递来一摞白纸。你终于开口：这一路十万八千里，究竟换来了什么？',
    intro: '终章关隘 Boss：阿难迦叶·索人事——或以钵相赠求有字真经，或砸经索还。',
    options: [
      { key: '战', label: '砸了白纸经，索还人事', fate: '战', fight: true, battleFlags: { openingMomentum: 1 }, effect: { alignEvil: 6, gold: 64 } },
      { key: '渡', label: '以紫金钵相赠，求有字真经', fate: '渡', effect: { alignGood: 12, yuan: { matk: 24, mdef: 0.05 } } },
      { key: '逆', label: '夺回紫金钵，讥其二尊者贪墨', fate: '逆', ni: true, effect: { alignEvil: 10, ti: { atk: 38, hp: 98 } } },
    ],
    treasure: { id: 'ts_bowl', type: 'treasure', note: '阿难迦叶·紫金钵（原著：人事换经）' } },
  81: { id: 81, name: '通天河遇鼋湿经', act: 17, type: 'boss', icon: '⚰️',
    heart: true, bossName: '通天河老鼋·湿经',  // 终局隐藏 Heart（杀戮尖塔式）：九章 Boss 之后的最终隐藏关
    fate: '逆', echo: '终局收束：通天河晒经石前，为八十一难之末；金蝉脱壳，湿经东归',
    dark: '『第八十一难』渡通天河，那老鼋问你：这一去灵山，可问过如来，几时可再回原地？你答不得——它驮着真经，沉了九天九夜，这一个字，你都还不上它。\n' +
      '它翻覆身子，真经湿透，晾干时熬下百二十余字。你忽然明白：八十一难的最后一难，不在取，在"还"。',
    intro: '终局 Boss 战：通天河老鼋，水覆沉经。渡水渡己，答或不答，皆在取舍之间。',
    options: [
      { key: '逆', label: '焚尽难簿 · 逆命乾元', fate: '逆', ending: '真·逆道结局（解锁全英雄终极隐藏职）', effect: { alignEvil: 20, treasure: 'ni_laoyuan' }},
      { key: '渡', label: '如实相告 · 引渡老鼋', fate: '渡', ending: '善之结局', effect: { alignGood: 15, ti: { hp: 122, dr: 0.07 } }},
      { key: '隐', label: '携湿经隐世', fate: '隐', ending: '隐世结局（全员隐藏职激活）', effect: { alignEvil: 6, yuan: { matk: 28, mdef: 0.08 } }}
    ],
    // 8.11 难81：全英雄终极隐藏职「真·逆道」= 逆 + 真·逆道结局
    hidden: { hero: 'all', cond: '逆 + 真·逆道结局', job: '真·逆道', desc: '逆道之极：全英雄终极隐藏职觉醒', hint: '逆道走到底、夺过至宝、且逆道难簿解锁≥10卷——无底船前你已写下属于自己的经' } },
};

// ============================================================
// 返程 / 暂存素材（隐藏保留 · 后续开发）
// 原 57-80 倒序返程段 + 被并入段（24 宝象变虎 / 34 七绝 / 36 盘丝 / 37 黄花 / 40 普天 / 53 乱石山），
// 正传流程不再使用；原样保留供后续开发（如二周目返程）。键号=原难号。
