// AUTO-GENERATED by _refactor_split.js — domain: changan
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  changanHtml() {
      const rub = NDX.loadRubbing() || {};
      const rubDone = Object.keys(rub).length;
      const rubTotal = Object.keys(NDX.SUTRA_SIX_DAOS || {}).length;
      const ash = NDX.loadAsh() || {};
      const ashCredits = ash.credits || 0;
      const fv = NDX.loadFavor() || {};
      const monuments = NDX.loadMonuments() || [];
      const hy = NDX.loadHunyuan() || {};
      // V8.35 本局行迹统计（游戏进行中显示）
      const s = NDX.game && NDX.game.state;
      const runStats = (() => {
        if (!s) return '';
        const gp = NDX.globalProgress(s);
        const actName = NDX.ACT_NAMES[Math.min((s.act || 1), NDX.TOTAL_ACTS) - 1] || ('第' + (s.act || 1) + '地区');
        const fs = s.fateStats || { trials: 0, kills: 0, events: 0 };
        const eqCount = (s.equips || []).length;
        const sealCount = (s.hSeals || s.seals || []).length;
        const fate = s.fate || {};
        const fateStr = ['战','渡','逆','隐','夺','缘'].map((d) => `${d}${fate[d]||0}`).join(' ');
        // 游玩时长
        const startTs = s._startTime || (s.startTime ? s.startTime : null);
        let timeStr = '';
        if (startTs) {
          const elapsed = Math.floor((Date.now() - startTs) / 1000);
          const m = Math.floor(elapsed / 60), sec = elapsed % 60;
          timeStr = `${m}分${sec}秒`;
        }
        return `<div class="cc-run-stats">
          <div class="cc-run-title">📜 本局行迹</div>
          <div class="cc-run-grid">
            <span class="cc-run-item"><b>进度</b>${gp}/${NDX.TOTAL_TRIALS}难</span>
            <span class="cc-run-item"><b>地区</b>${actName}</span>
            <span class="cc-run-item"><b>降妖</b>${fs.kills||0}</span>
            <span class="cc-run-item"><b>渡难</b>${fs.trials||0}</span>
            <span class="cc-run-item"><b>缘遇</b>${fs.events||0}</span>
            <span class="cc-run-item"><b>装备</b>${eqCount}</span>
            <span class="cc-run-item"><b>劫印</b>${sealCount}</span>
            <span class="cc-run-item"><b>六道</b>${fateStr}</span>
            ${timeStr ? `<span class="cc-run-item"><b>时长</b>${timeStr}</span>` : ''}
          </div>
        </div>`;
      })();
  
      // V8.26→ V8.30 布局：以长安城为背景，八座设施按「上下三排」整齐布列
      //   上排：大雁塔(左) · 录难阁(中) · 小雁塔(右)
      //   中排：藏品库(左) · 轮回殿(中·大号主殿) · 降妖簿(右)
      //   下排：钟楼(左) · 劫灰坊(右)
      //   八座塔由 CSS `.cc-scene/.cc-row` 以 flex 三行均分排布（行内水平居中、底部对齐），
      //   随场景高度伸缩永不重叠；轮回殿居中、卡片最大，成视觉主轴。
      // 方案X2·当前主道（六道殿塔 meta 展示：道名+攻式名）
      const _daoInfo = (() => {
        if (!s) return { dao: '渡', atk: '' };
        const st = (NDX.daoAtkStyleOf && NDX.daoAtkStyleOf(s)) || null;
        return { dao: st && st.dao ? st.dao : '渡', atk: st && st.style && st.style.name ? st.style.name : '' };
      })();
      const tower = (img, icon, name, desc, action, meta, sizeCls) => {
        // 长安塔图(img/changan_*.png) 无对应 .webp 版本，强制直连 PNG 避免 404 等待时间
        const _noWebp = /\/changan_[^/]+\.png$/i.test(img || '');
        const realSrc = (img && !_noWebp && typeof window.__pickWebp === 'function') ? window.__pickWebp(img) : img;
        // onerror：长安直连 PNG 失败 → 立刻给父 <button> 加 .no-img（纯 CSS 填充建筑外观，避免空黑框）
        //           其他图经 __pickWebp 转 webp → 先 webp→png fallback，仍失败再 no-img
        const _oeNoWebp   = `if(this.parentNode){this.parentNode.classList.add('no-img');} this.style.display='none';`;
        const _oeWithFb   = `var __f=false;try{if(window.__pickWebpImgFallback){__f=__pickWebpImgFallback(this);}}catch(_e_){__f=false;};if(!__f){if(this.parentNode){this.parentNode.classList.add('no-img');}this.style.display='none';}`;
        // 去掉 loading="lazy"：ndx-lock transform:rotate(90deg) 后浏览器用旧视口坐标计算 lazy load，
        // 认为图片在可视区外永远不加载 → 用户手机长安只剩1张小雁塔显示。塔图一共8张 ~4MB，
        // 单次加载开销可接受（loading=eager 或省略默认 eager），优先保证展示。
        return `<button class="cc-tower ${sizeCls}" data-action="${action}" title="${desc}">
          ${img ? `<img src="${realSrc}" alt="${name}" decoding="async" onerror="${_noWebp ? _oeNoWebp : _oeWithFb}">` : `<span class="tt-icon">${icon}</span>`}
          <span class="tt-name">${name}</span>
          <span class="tt-meta">${meta}</span>
        </button>`;
      };
  
      // V9.9 长安新布局：2行5列整齐网格，适配手机横屏
      //   第一行：大雁塔 · 录难阁 · 小雁塔 · 藏品库 · 轮回殿（主殿）
      //   第二行：降妖簿 · 钟楼 · 六道殿 · 劫灰坊 · 朝代年表
      const towers =
        `<div class="cc-grid">` +
        tower('img/changan_pagoda_dayanta.png', '⛩️', '大雁塔 · 舍利塔', '七层楼阁唐塔 · 1-6层刻历代行迹，7层逆道碑（点击入塔）', 'open-monuments', `${monuments.length} 世行迹`, 'tower-card') +
        tower('img/changan_lunange.png', '📜', '录难阁 · 难簿', '单檐悬山记录阁 · 81 块青石栏板对应八十一难（点击铜环开门录难）', 'open-ach', `已录 ${this._achCountText()}`, 'tower-card') +
        tower('img/changan_pagoda_xiaoyanta.png', '📖', '小雁塔 · 藏经阁', '十五层密檐唐塔 · 风蚀处刻被篡改经文（点击入塔拓印）', 'open-rubbing', `拓印 ${rubDone}/${rubTotal}`, 'tower-card') +
        tower('img/changan_storehouse.png', '🗃️', '藏品库', '单檐庑殿仓储 · 劫印/神仙链/跨周目继承物（点击铜锁解锁藏品）', 'open-collection', this._collCountText(), 'tower-card') +
        tower('img/changan_hall_lunhui.png', '⛓️', '轮回殿', '重檐庑殿 · 唐最高规制 · 转世重修（点击入殿）', 'open-cycle', `序${fv.orderLv || 0}·混${fv.chaosLv || 0}·淬${Object.keys(hy).length}`, 'tower-card main') +
        tower('img/changan_stele_pavilion.png', '🪞', '降妖簿', '单檐歇山碑亭 · 3米青石碑录降妖名（善杀暗金/恶杀暗红）（点击碑身展开图鉴）', 'open-yezanglu', `图鉴 ${this._yezangluCountText()}`, 'tower-card') +
        tower('img/changan_belltower.png', '⚖️', '钟楼 · 功德榜', '重檐歇山 · 历代行迹跨周目排行（点击敲钟观榜）', 'open-ranking', '寿 / 善 / 荣', 'tower-card') +
        tower('img/changan_dao_hall.png', '☸', '六道殿 · 道心', '重檐攒尖 · 供奉六藏碑（点击观六道总览·可改道）', 'open-dao-retune', `当前道：${_daoInfo.dao}·${_daoInfo.atk}`, 'tower-card') +
        tower('img/changan_furnace.png', '☯', '劫灰坊', '轮回殿侧 · 跨周永久升级 · 金蝉余韵（点击入坊）', 'open-ash', `✚ ${ashCredits} 劫灰`, 'tower-card') +
        tower('img/changan_dynasty.png', '🏮', '朝代年表', '十七朝兴亡录 · 每次陨落，人间便换一日月（点击翻阅）', 'open-dynasty', '十七朝', 'tower-card') +
        `</div>`;


      return `<div class="scene-overlay" data-action="close-modal">
        <div class="scene-modal changan-modal changan-city" data-stop>
          <div class="cc-bg" aria-hidden="true"></div>
          <button class="cc-overview-chip" data-action="open-meta-overview" title="总览章：承继家当 / 六藏拓印 / 难簿 / 隐藏职 / 结局CG / 家当三档 / 毕业目标 一屏总览">🧭 总览章</button>
          <div class="cc-title">长 安 · 西 行 大 本 营</div>
          <div class="cc-scene">${towers}</div>
          <div class="cc-foot">
            ${runStats}
            <details class="cc-bonus-fold">
              <summary>☯ 跨周永久 · 属性加成总览</summary>
              <div class="cc-bonus">${this._changanBonusHtml()}</div>
            </details>
            <button class="opt-btn" data-action="close-modal">踏 上 西 行</button>
          </div>
        </div>
      </div>`;
    },
  _changanBonusHtml() {
      const rows = [];
      const nz = (v) => (v ? `+${v}` : '—');
      // 八十一难簿
      try {
        const ab = NDX.globalAchBonus() || {};
        const ti = ab.ti || {}, yu = ab.yuan || {};
        rows.push(['八十一难簿', '难簿逐难 + 卷功名 · 永久',
          `已录 ${ab.count || 0} 难（等效 ${Number(ab.effective || 0).toFixed(1)}） · 攻 ${nz(ti.atk)} · 气血 ${nz(ti.hp)} · 法强 ${nz(yu.matk)} · 减伤 ${Math.round((ti.dr || 0) * 100)}%`]);
      } catch (e) {}
      // 藏经阁
      try {
        const rub = NDX.loadRubbing() || {};
        const d = Object.keys(rub).length;
        rows.push(['藏经阁', '六藏经文拓印 · 佛经全本永久拓印',
          `已拓印 ${d} 藏（集齐六藏解锁《八十一难·三结局》CG）`]);
      } catch (e) {}
      // 降妖簿
      try {
        const yz = NDX.yezangluState();
        let done = 0, total = 0, comp = 0;
        for (const g of (NDX.collectionGroups || [])) {
          if (!g || !g.id) continue;
          const p = yz.groupProgress[g.id] || { owned: 0, total: NDX._collEntries(g).length, complete: false };
          done += p.owned; total += p.total; if (p.complete) comp++;
        }
        rows.push(['降妖簿', '山野妖魔 / 师徒纪事 / 天庭诸神图鉴',
          `图鉴 ${done}/${total} 项 · 完成 ${comp}/${(NDX.collectionGroups || []).length} 组 · 领 25/50/75% 里程碑奖励`]);
      } catch (e) {}
      // 劫灰坊
      try {
        const lv = (id) => NDX.ashLevel(id);
        rows.push(['劫灰坊', '金蝉余韵 / 逆心初萌 / 六道亲和 / 法宝共鸣 / 劫印拓印',
          `气血+${lv('hp') * 2}% · 伤害+${(lv('dmg') * 1.5).toFixed(1)}% · 劫运骰+${lv('roll') * 5}% · 法宝首充+${lv('chg')} · 永久劫印槽+${lv('seal')}`]);
      } catch (e) {}
      // 轮回殿
      try {
        const fvv = NDX.loadFavor() || {};
        const hy = NDX.loadHunyuan() || {};
        rows.push(['轮回殿', '佛祖庇佑（秩序 / 混沌双线）+ 混元淬炼',
          `秩序 ${fvv.orderLv || 0} 级 · 混沌 ${fvv.chaosLv || 0} 级 · 混元淬炼 ${Object.keys(hy).length} 项`]);
      } catch (e) {}
      // 舍利塔
      try {
        const m = NDX.loadMonuments() || [];
        rows.push(['舍利塔', '逆道碑 · 历代先世行迹刻沉',
          `已镌刻 ${m.length} 世 · 塔上果位 ${m.filter((x) => x.win).length} · 碑上偈语 ${m.filter((x) => !x.win).length}`]);
      } catch (e) {}
      return rows.map((r) => `<div class="changan-bonus-row">
        <span class="cb-name">${r[0]}</span>
        <span class="cb-sub">${r[1]}</span>
        <span class="cb-val">${r[2]}</span>
      </div>`).join('') || '<p class="ledger-empty">尚无跨周积累——第一世的一切收获，都将在此沉淀。</p>';
    },

  // V8.61 反馈接线批：朝代年表（Rev.4 报告 Part 8）——把"死亡推进朝代"从死数变成可翻阅的收集页。
  // 已历朝代：全文展示（朝代/当朝天子/兴亡一语）；未至朝代：遮以"？？？"防剧透，留翻页悬念。
  showDynasty: false,
  dynastyHtml() {
      const list = (NDX.DYNASTY && NDX.DYNASTY.LIST) || [];
      const cur = (NDX.getDynastyIdx ? NDX.getDynastyIdx() : 0) || 0;
      const rows = list.map((d, i) => {
        const reached = i <= cur;
        const isNow = i === cur;
        if (!reached) {
          return `<div class="ach-row off"><div class="ach-text">
            <div class="ach-name">？？？ · 第 ${i + 1} 朝</div>
            <div class="ach-desc">后世之事，尚未写下——陨落一次，人间便换一日月。</div>
          </div></div>`;
        }
        return `<div class="ach-row on${isNow ? ' dynasty-now' : ''}"><div class="ach-text">
          <div class="ach-name">${d.full || d.name}${isNow ? ' · 当朝' : ''}<span class="dynasty-monarch">在位 · ${d.monarchTitle || d.monarch || '—'}</span></div>
          <div class="ach-desc">${d.desc || ''}${i === 0 ? '（通关重置，自夏重开）' : ''}</div>
        </div></div>`;
      }).join('');
      const d0 = list[cur] || {};
      return `<div class="scene-overlay" data-action="close-modal">
        <div class="scene-modal ach-book-modal" data-stop>
          <div class="box-title">🏮 朝代年表 · 十七朝</div>
          <p class="dynasty-lead">你每陨落一次，人间便老去一朝天。今值<b>${d0.full || d0.name || '—'}</b>，${d0.monarchTitle || d0.monarch || '当朝者'}在位。</p>
          <div class="ach-list">${rows}</div>
          <button class="opt-btn" data-action="close-modal">合上年表</button>
        </div>
      </div>`;
    }
});
