// AUTO-GENERATED by _refactor_split.js — domain: icons
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  _equipIcon(e) {
      if (!e) return '';
      const id = e.id || e.treasureId || '';
      const iconMap = NDX.ICON_MAP || {};
      const equipMap = iconMap.equipment || {};
      const treasureMap = iconMap.treasures || {};
      let src = equipMap[id] || treasureMap[id] || '';
      if (!src && e.slot) {
        // S1-2：img/icons/equipment 下 generic_* 已全部转码为 .webp，此处曾残留 .png 导致兜底图标 404
        const genericMap = { weapon: 'generic_weapon.webp', armor: 'generic_armor.webp', head: 'generic_head.webp', boots: 'generic_boots.webp', treasure: 'generic_treasure.webp', pet: 'generic_pet.webp' };
        src = 'img/icons/equipment/' + (genericMap[e.slot] || 'generic_weapon.webp');
      }
      return src ? '<img src="' + src + '" class="equip-icon" alt="' + esc(e.name || '') + '" loading="lazy" decoding="async" onerror="this.style.display=\'none\'">' : '';
    },
  _sutraIcon(sutraId) {
      if (!sutraId) return '';
      const src = (NDX.sutraIconPath ? NDX.sutraIconPath(sutraId) : '') || '';
      return src ? '<img src="' + src + '" class="sutra-icon" alt="' + esc(sutraId) + '" loading="lazy" decoding="async" onerror="this.style.display=\'none\'">' : '';
    },
  _achIcon(ach) {
      if (!ach) return '';
      const iconMap = NDX.ICON_MAP || {};
      const achMap = iconMap.achievements || {};
      const src = achMap[ach.id] || '';
      return src ? '<img src="' + src + '" class="ach-icon-img" alt="' + esc(ach.name || '') + '" loading="lazy" decoding="async" onerror="this.style.display=\'none\'">' : '<span class="ach-icon">' + (ach.icon || '？') + '</span>';
    }
});
