// AUTO-GENERATED by _refactor_split.js — domain: map
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  _initMapPan(mapEl) {
      if (!mapEl || mapEl.dataset.panBound === '1') return;
      mapEl.dataset.panBound = '1';
      const getNodes = () => mapEl.querySelector('.nodes');
      const getX = (str) => {
        const m = (str || '').match(/translateX\(([-\d.]+)px\)/);
        return m ? parseFloat(m[1]) : parseFloat(mapEl.dataset.targetX || '0');
      };
      const setX = (x, dragging) => {
        const nodes = getNodes();
        if (!nodes) return;
        nodes.classList.toggle('dragging', !!dragging);
        nodes.style.transform = `translateX(${x}px)`;
      };
      const snapBack = () => {
        const nodes = getNodes();
        if (!nodes) return;
        nodes.classList.remove('dragging');
        const targetX = parseFloat(mapEl.dataset.targetX || '0');
        nodes.style.transform = `translateX(${targetX}px)`;
      };
      const clamp = (x) => {
        const nodes = getNodes();
        if (!nodes) return x;
        const mapW = nodes.offsetWidth;
        const viewW = mapEl.clientWidth;
        const minX = Math.min(0, viewW - mapW);
        return Math.max(minX, Math.min(0, x));
      };
      let startX = 0, startTransX = 0, dragging = false;
      const onStart = (e) => {
        const touch = e.touches ? e.touches[0] : e;
        startX = touch.clientX;
        startTransX = getX(getNodes().style.transform);
        dragging = true;
        setX(startTransX, true);
      };
      const onMove = (e) => {
        if (!dragging) return;
        const touch = e.touches ? e.touches[0] : e;
        const dx = touch.clientX - startX;
        setX(clamp(startTransX + dx), true);
        if (e.cancelable && e.type !== 'mousemove') e.preventDefault();
      };
      const onEnd = () => {
        if (!dragging) return;
        dragging = false;
        snapBack();
      };
      mapEl.addEventListener('touchstart', onStart, { passive: false });
      mapEl.addEventListener('touchmove', onMove, { passive: false });
      mapEl.addEventListener('touchend', onEnd);
      mapEl.addEventListener('touchcancel', onEnd);
      mapEl.addEventListener('mousedown', onStart);
      window.addEventListener('mousemove', onMove);
      window.addEventListener('mouseup', onEnd);
    },
  _mapGateBanner(s) {
      const p = (s && s.pending) || {};
      const k = p.kind;
      let msg = null;
      if (k === 'bless-seal') msg = '先在中部择一道白劫印刻入命格，方可选路';
      else if (k === 'bless-treasure') msg = '先择一件法宝傍身，再启程选路';
      else if (k === 'start') msg = '先在中部选择本难抉择（战/渡/逆…），开启取经之路';
      else if (k === 'rest' || k === 'bonfire') msg = '先在歇脚处休整/祭炼，再继续选路';
      else if (k === 'shop') msg = '先在坊市购置，再继续选路';
      else if (k === 'trial' || k === 'elite' || k === 'boss') {
        // 劫难/精英/Boss 节点：需先在中部面板完成本劫抉择（战/渡/逆…或临阵祭宝），才可继续选路
        msg = '先在中部完成本难抉择/对峙，方可续行';
      } else if (!k) msg = '选中地图节点进入下一难';
      if (!msg) return '';
      return `<div class="map-gate-banner">🔒 ${msg} —— 地图节点暂不可点，完成后自动解锁</div>`;
    },
  _mapGeom() {
      const BASE_STEP = 86, PAD_X = 28, PORTAL_W = 132, MAX_STEP = 220;
      const LAYER_COUNT = NDX.LAYER_COUNT || 9;
      let STEP_X = BASE_STEP;
      try {
        if (document.documentElement.classList.contains('ndx-short-landscape') && LAYER_COUNT > 1) {
          // v327 黑框根修：视口宽必须用 #mapArea 实宽。此前用 lock.clientWidth（含 .frame
          // 左右内边距 30px×2），mapW 被算宽 60px → place() 回弹 translateX(-60px) →
          // region-bg 整体左移，地图左侧露出深色底成黑带。
          let vw = 0;
          const mapEl = document.getElementById('mapArea');
          if (mapEl && mapEl.clientWidth > 0) vw = mapEl.clientWidth;
          if (!vw) {
            const lock = document.getElementById('ndx-lock');
            const lockW = (lock && lock.clientWidth > 0) ? lock.clientWidth
              : Math.max(window.innerWidth || 0, window.innerHeight || 0);
            vw = lockW - 60; // 首帧 mapArea 尚未挂载：按 .frame 左右内边距估算
          }
          const avail = vw - PAD_X * 2 - PORTAL_W;
          const stretch = Math.floor(avail / (LAYER_COUNT - 1));
          if (stretch > STEP_X) STEP_X = Math.min(MAX_STEP, stretch);
        }
      } catch (e) { /* 保持基础步距 */ }
      const xOf = (L) => PAD_X + PORTAL_W + (LAYER_COUNT - L) * STEP_X;
      const mapW = PAD_X * 2 + PORTAL_W + (LAYER_COUNT - 1) * STEP_X;
      return { STEP_X, PAD_X, PORTAL_W, LAYER_COUNT, mapW, xOf };
    },
  mapHtml(s, g) {
      const COLS = NDX.MAX_COL || 4; // 每层列数上限
      // —— 横向·右→左：起始(第1层)在右，关隘(末层·西天方向)在左 ——
      const STEP_Y = 64, PAD_Y = 54;
      const _geom = this._mapGeom();
      const xOf = _geom.xOf;
      const LAYER_COUNT = _geom.LAYER_COUNT;
      const yOf = (c) => PAD_Y + (c - 1) * STEP_Y;
      const bossX = xOf(LAYER_COUNT);
      const mapW = _geom.mapW;
      const mapH = PAD_Y * 2 + (COLS - 1) * STEP_Y;
      // 区域(act)主题色：渲染为横向地图背景带，体现"不同区域的不同背景"
      const act = s.act || 1;
      const nextAct = act + 1;
      const hasNext = NDX.TOTAL_ACTS && nextAct <= NDX.TOTAL_ACTS;
      const nextName = hasNext ? (NDX.ACT_NAMES[nextAct - 1] || ('第' + nextAct + '境')) : null;
      const regionPal = (a, dim) => {
        const hue = ((a - 1) * 23) % 360, h2 = (hue + 20) % 360;
        const l1 = dim ? 11 : 15, l2 = dim ? 6 : 9;
        return `linear-gradient(90deg, hsl(${hue} 30% ${l1}%), hsl(${h2} 24% ${l2}%))`;
      };
      // 区域背景与地区一一对应：直接复用 NDX.ACT_BG（已按 act 顺序映射 img/bg/act_*.png），
      // 保证地图所见背景与当前/下一地区强绑定，强化逐区西行的沉浸感。
      const curImg = (NDX.ACT_BG && NDX.ACT_BG[act - 1]) ? `url('${NDX.ACT_BG[act - 1]}')` : 'none';
      const nextImg = (hasNext && NDX.ACT_BG && NDX.ACT_BG[nextAct - 1]) ? `url('${NDX.ACT_BG[nextAct - 1]}')` : 'none';
      const bossLayerMet = s.mode === 'outbound' && NDX.fateGateCheck(s).met;
      // 节点间连线从圆外缘开始/结束，不再穿过中心（R 为节点圆半径）
      const NODE_R = 19;
      const edgeLine = (x1, y1, x2, y2) => {
        const dx = x2 - x1, dy = y2 - y1;
        const dist = Math.hypot(dx, dy) || 1;
        const ux = dx / dist, uy = dy / dist;
        const x1e = x1 + ux * NODE_R, y1e = y1 + uy * NODE_R;
        const x2e = x2 - ux * NODE_R, y2e = y2 - uy * NODE_R;
        return `M${x1e.toFixed(1)} ${y1e.toFixed(1)} L${x2e.toFixed(1)} ${y2e.toFixed(1)}`;
      };
      const reach = g.choices();
      const reachKey = new Set(reach.map((n) => n.layer + '-' + n.col));
      const visKey = new Set((s.visited || []).map((v) => v.layer + '-' + v.col));
      // 已走过的层集合：这些层里"未被选中"的其余分支节点也一并标灰（同层已放弃路线）
      const passedLayers = new Set((s.visited || []).map((v) => v.layer));
  
      // —— SVG 连线：杀戮尖塔规则 —— 玩家一旦走过某条路，
      //    后续只有"活跃路径"那条蛇形线画出来；其它边不画（避免 X 交叉视觉）。
      //    可达分支边（从当前节点向下）用翠色；已走过的边用金色；其余全不画。
      //    这样"选了某分支就放弃隔壁回血"在视觉上一目了然。
      let links = '';
      const visitedEdges = new Set();
      // 1) 已走过的边：把 visited 链两两配对
      for (let i = 0; i < (s.visited || []).length; i++) {
        const cur = s.visited[i];
        const next = s.visited[i + 1];
        if (next && next.layer === cur.layer + 1) {
          visitedEdges.add(cur.layer + '-' + cur.col + '->' + next.layer + '-' + next.col);
        }
      }
      // 2) 当前节点向下的可达边（翠色高亮，玩家当前可选路线）
      const reachEdges = new Set();
      for (let c2 = 1; c2 <= COLS; c2++) {
        if (reachKey.has((s.layer + 1) + '-' + c2)) {
          const key = s.layer + '-' + s.col + '->' + (s.layer + 1) + '-' + c2;
          reachEdges.add(key);
        }
      }
      // 2.5) 杀戮尖塔式：先画出整张地图的全部连通边（淡色底），
      //      让玩家从开局即可纵观全局、规划路线，再于其上叠加已走/可达高亮。
      for (let L = 0; L < NDX.LAYER_COUNT; L++) {
        // 跳过第0层（逻辑起点层），避免绘制错误的路径
        if (L === 0) continue;
        for (let c = 1; c <= COLS; c++) {
          if (!NDX.LAYERS[L][c]) continue;
          const nxt = NDX.nextNodes(L, c);
          nxt.forEach((n) => {
            links += `<path class="ln ln-base" d="${edgeLine(xOf(L), yOf(c), xOf(n.layer), yOf(n.col))}" />`;
          });
        }
      }
      // 3) 画"已走过"的边（金色）
      for (const key of visitedEdges) {
        const [from, to] = key.split('->');
        const [Lf, cf] = from.split('-').map(Number);
        const [Lt, ct] = to.split('-').map(Number);
        links += `<path class="ln ln-visited" d="${edgeLine(xOf(Lf), yOf(cf), xOf(Lt), yOf(ct))}" />`;
      }
      // 4) 画"当前可达分支"的边（翠色）
      for (const key of reachEdges) {
        const [from, to] = key.split('->');
        const [Lf, cf] = from.split('-').map(Number);
        const [Lt, ct] = to.split('-').map(Number);
        links += `<path class="ln ln-reach" d="${edgeLine(xOf(Lf), yOf(cf), xOf(Lt), yOf(ct))}" />`;
      }
  
      // —— 节点 ——
      let cells = '';
      for (let L = 0; L <= NDX.LAYER_COUNT; L++) {
        for (let c = 1; c <= COLS; c++) {
          const node = NDX.LAYERS[L][c];
          if (!node) continue;
          const isCur = L === s.layer && c === s.col;
          const isStart = s.layer === 0 && L === 1; // 开局起点（长安 · 第一层）：高亮起点标识
          const ok = reachKey.has(L + '-' + c);
          const cls = ['cell', 'type-' + node.type];
          if (isCur) cls.push('current');
          else if (ok) cls.push('reachable');
          else if (visKey.has(L + '-' + c)) cls.push('passed');
          else if (passedLayers.has(L) && L < s.layer) cls.push('abandoned'); // 同层已被放弃的旧分支：标灰
          else cls.push('future'); // 未到、未访问、暂不可达：整图清晰可见，供规划选路
          if (isStart) cls.push('start-node'); // 起点：醒目标识，避免开局找不到初始节点
          if (node.startPoint) cls.push('start-node'); // 第一难·金蝉遭贬：地图起点标识（类杀戮尖塔铁人像）
          // V8.31 新手指引阶段：前三难的可达节点更醒目（金色呼吸光+放大）
          if (ok && L <= 3 && !s._tutorialFought) cls.push('teach-node');
          // V8.31 长安送行节点：特殊高亮（红色灯笼+金色呼吸光+标签）
          if (node.songEvent) cls.push('song-event-node');
          const clickable = ok;
          const x = xOf(L), y = yOf(c);
          const attr = clickable ? `data-action="node" data-layer="${L}" data-col="${c}"` : '';
          const idAttr = isCur ? 'id="map-cur"' : '';
          if (node.type === 'boss' && (s.act || 1) >= NDX.TOTAL_ACTS) cls.push('final-boss'); // 仅末地区关隘（终局）高亮
          // 缘分门槛（V8.17）：关隘 Boss 未达标 → 锁门样式
          if (node.type === 'boss' && s.mode === 'outbound' && !NDX.fateGateCheck(s).met) cls.push('gate-locked');
          if (node.type === 'boss' && s.mode === 'outbound' && NDX.fateGateCheck(s).met) cls.push('gate-open'); // 缘已至：关隘刷新（金光脉动）
          // 关隘门禁视觉现仅由 fateGateCheck 驱动（#63 移除 V8.34 配额制 gate-locked 死分支）
          // 天道劫：专属图标与 tooltip（不推翻现有系统，仅覆盖渲染）
          const _isTJ = !!node.tianJie;
          if (_isTJ) {
            const tjMeta = (NDX.TJ_NODE_ICON && NDX.TJ_NODE_ICON[node.type]) || null;
            if (tjMeta) cls.push('tj-node');
            if (node.mirrorBoss) cls.push('final-boss');
          }
          // 劫/缘/宝只显示类型（不标具体名）；进入时再随机，故地图节点数量不受名称限制
          // 环境叙事：用极简 tooltip（≤15字）替代弹窗式教学，让图标自身传达含义
          let _tip;
          if (_isTJ) {
            const m = (NDX.TJ_NODE_ICON && NDX.TJ_NODE_ICON[node.type]) || null;
            _tip = (node.tip || (m ? `${m.label}·${m.sys}` : node.name)) + (node.tjId ? `（${node.tjId}）` : '');
          }
          if (node.type === 'trial') _tip = '必有恶战';
          else if (node.type === 'event') _tip = '此处或有奇遇，亦藏凶险';
          else if (node.type === 'treasure') _tip = '宝物在前，取之需谋';
          else if (node.type === 'treasure_lux') _tip = '秘藏宝窟 · 镇窟至宝（必得金阶名器）';
          else if (node.type === 'cave') _tip = (node.name || '洞天') + '（三周目·逆道秘境）';
          else if (node.type === 'compound') {
            // 模块六·复合/融合节点诚实化：V8.27 已取消路线抉择入口页，故不再写「内含路线抉择」；
            // 改为如实标注「进入即连续历难 N 难」及子难名，让玩家开打前知道这是多难合一的连战节点。
            const _cDiffs = (node.fusionDiffs && node.fusionDiffs.length) ? node.fusionDiffs : ((NDX.compoundFor && NDX.compoundFor(s.act) && NDX.compoundFor(s.act).diffs) || []);
            const _cnt = (_cDiffs && _cDiffs.length) || 0;
            const _cNames = (_cDiffs || []).map((d) => { const _t = NDX.TRIAL_LIB && NDX.TRIAL_LIB[d]; return _t && _t.name ? _t.name : ('第' + d + '难'); }).join('·');
            _tip = (node.name || '多难合一') + ( _cnt > 0 ? `（连续历难 ${_cnt} 难：${_cNames}）` : '（多难合一·连续历难）');
          }
          else if (node.type === 'boss') {
            const _gate = NDX.fateGateCheck(s);
            _tip = (node.name || '关隘') + '（第 ' + (NDX.ACT_NAMES[Math.min((s.act || 1), NDX.TOTAL_ACTS) - 1] || '') + '地区关隘·第 ' + NDX.globalProgress(s) + ' 难）';
            if (!_gate.met) _tip += ' · 缘分未到：' + _gate.missing.map((m) => `${m.label}${m.cur}/${m.need}`).join(' ');
            // 关隘门禁现仅由 fateGateCheck 决定（#63 移除 V8.34 配额制相关提示）
          }
          else if (isStart) _tip = '起点 · ' + (node.name || '长安');
          else if (node.startPoint) _tip = '第一难 · ' + (node.name || '金蝉遭贬');
          else {
            const _risk = node.type === 'elite' ? '（精英）' : (node.type === 'rest' ? '（歇脚）' : '');
            _tip = node.name + _risk;
          }
          // 资源严格隔离提示：劫难节点只产劫印、精英节点产蓝劫+经文碎片（常驻小标，全层展示，
          // 让玩家一眼看清「走这条线得到什么、得不到什么」，强化路线博弈取舍）。
          let _yieldTag = '';
          if (node.type === 'trial') _yieldTag = `<span class="yield-tag yield-seal">劫印</span>`;
          else if (node.type === 'elite') _yieldTag = `<span class="yield-tag yield-seal">劫印·机</span>`;
          else if (node.type === 'cave') _yieldTag = `<span class="yield-tag yield-cave">逆道经文+红材</span>`;
          else if (node.type === 'treasure') _yieldTag = `<span class="yield-tag yield-treasure">法宝</span>`;
          else if (node.type === 'treasure_lux') _yieldTag = `<span class="yield-tag yield-lux">至宝</span>`;
          else if (node.type === 'boss') {
            _yieldTag = `<span class="yield-tag yield-boss">金劫印</span>`;
            if (s.mode === 'outbound' && !NDX.fateGateCheck(s).met) _yieldTag += `<span class="yield-tag yield-lock">缘未至·锁</span>`;
          }
          // 前 3 层差异化路线展示：节点常驻路线标签（历练/劫印/精英），让玩家直观看到「路线改变整局玩法」
          const _routeTag = (L <= 3 && node.route)
            ? `<span class="route-tag route-${node.route}">${node.route === 'lian' ? '历练线·练级' : node.route === 'jie' ? '劫印线·堆印' : '精英线·机制'}</span>`
            : '';
          const _routeCls = (L <= 3 && node.route) ? ' has-route' : '';
          // 节点本体去名化（#10）：名称不再压在图标上，改放到节点上方的空白空隙，节点只留图标 + 收益标
          const _name = (node && node.name) || (this._typeDisplayName ? this._typeDisplayName(node.type) : '');
          const cells2 = cells +
            `<div class="${cls.join(' ')}${_routeCls}" ${idAttr} ${attr}
                      style="left:${x}px; top:${y}px; transform:translate(-50%,-50%)"
                      title="${_tip.replace(/"/g, '&quot;')}">
                      <span class="nlabel">${_name}</span>
                      <span class="ico">${_isTJ ? ((NDX.TJ_NODE_ICON[node.type] || {}).icon || this.TAGS[node.type]) : this.TAGS[node.type]}</span>
                      ${_routeTag}${_yieldTag}
                    </div>`;
          cells = cells2;
        }
      }
  
      // —— 观音指引·关隘必修任务卡（常驻地图空白区，#8）：
      //    当前区域、四类任务进度、取经人今岁、以及经过各节点的岁月消耗 ——
      let missionHud = '';
      try {
        // V8.4x 观音指导（接引使者教学战）完成前隐藏「观音指引/渡难」卡，避免抢占地图空位
        // V8.5x 第一章已取消关隘刷新强制要求（刘洪直接可战），第一章不再显示 渡难/杀伐/缘遇 任务卡
        if (!s._tutorialFought || (s.act || 1) === 1) throw null;
        const gg = NDX.fateGateCheck(s);
        const area = (NDX.ACT_NAMES && NDX.ACT_NAMES[Math.min((s.act || 1), NDX.TOTAL_ACTS) - 1]) || ('第 ' + ((s.act) || 1) + ' 地区');
        const items = (NDX.MISSION_KINDS || ['trials', 'battle', 'events'])
          .filter((k) => (gg.gate[k] || 0) > 0)
          .map((k) => `<span class="mi i-${k}${gg.progress[k] >= (gg.gate[k] || 0) ? ' done' : ''}">${NDX.MISSION_KIND_LABEL[k] || ''} ${gg.progress[k]}/${gg.gate[k]}</span>`)
          .join('');
        const met = gg.met ? '<span class="mi met">缘已至 · 可叩关</span>' : '';
        // V8.34 地区配额制 quotaHud 已移除：用户确认 Boss 门槛为「历经足够劫难」（fateGateCheck + 动态尾 _tailStep），
        // 不再以地区配额条展示；右上角「已历 X/Y 难」芯片与下方 missionHud（渡难/杀伐/缘遇）即门禁进度。
        // 默认折叠为一行标题条（不压下方「下一地区」传送门，界面更简）；点标题展开
        const _missionCollapsed = s._missionCollapsed === false ? false : true;
        missionHud = `<div class="map-mission${gg.met ? ' met' : ''}${_missionCollapsed ? ' collapsed' : ''}" id="missionHud">
          <div class="mm-title" data-action="toggle-mission">🍃 ${area} <span class="mm-toggle">${_missionCollapsed ? '▸' : '▾'}</span></div>
          <div class="mm-body">
            <div class="mm-items">${items}${met}</div>
          </div>
        </div>`;
      } catch (e) { missionHud = ''; }
  
      // —— V8.56 万世剑冢·成亡节点地块：横卷地图上按「地区段」顶部空白区叠加衣冠冢/舍利塔，点击可回访拾取 ——
      let vaultBlocks = '';
      try {
        const _vp = (NDX.activeVaults ? NDX.activeVaults() : []);
        if (_vp.length) {
          // V8.59 地图级预示：引导未完成前，给首批成亡节点地块加「金色光圈+新角标」，提示玩家可点回访；引导完成一次后预示自动停止
          let _unguided = false;
          try {
            const _gk = (NDX.storage && NDX.storage.KEYS && NDX.storage.KEYS.VAULT_GUIDE) || 'xynj_vault_guide_done';
            _unguided = !NDX.SaveSystem.loadBoolean(_gk, false);
          } catch (e) { _unguided = false; }
          vaultBlocks = _vp.map(function (n) {
            if (!n || !n.region) return '';
            const _act = Math.max(1, Math.min(NDX.TOTAL_ACTS, n.region || 1));
            const _off = NDX.regionLayerOffset ? NDX.regionLayerOffset(_act) : 0;
            const _lay = ((NDX.ACT_RANGES && NDX.ACT_RANGES[Math.min(_act, (NDX.ACT_RANGES.length || 1)) - 1]) || {}).layers || 4;
            const _Lc = _off + Math.ceil(_lay / 2);
            let _x = xOf(_Lc);
            _x = Math.max(0, Math.min(mapW - 40, _x)); // 钳制在横卷可视范围内
            const _isShrine = n.kind === 'shrine';
            const _t = _isShrine ? '舍利塔' : '衣冠冢';
            const _dec = NDX.vaultDecay ? NDX.vaultDecay(n.pickupCount) : 1;
            const _decPct = Math.round((_dec || 1) * 100);
            const _loc = (NDX.ACT_NAMES && NDX.ACT_NAMES[Math.min(_act, NDX.TOTAL_ACTS) - 1]) || ('第' + _act + '地区');
            const _tip = `万世剑冢 · ${_t} · ${_loc} · 拾取传承 ×${_decPct}%（只留属性）`;
            // V8.58 打磨：徽记改内联SVG象形（碑/塔）、舍利塔金色微光、衰减按档位(盛/微衰/衰)分色
            const _lvl = _dec >= 0.9 ? 'hi' : (_dec >= 0.5 ? 'mid' : 'lo');
            return `<div class="vault-tile ${_isShrine ? 'shr' : 'tmb'} ${_lvl}${_unguided ? ' bait' : ''}" data-action="open-vault" data-vault="${esc(n.id || '')}" style="left:${_x}px; top:4px" title="${_tip}">
              ${_unguided ? '<span class="vt-new">新</span>' : ''}
              <span class="vt-ico" aria-hidden="true"></span>
              <span class="vt-tag">${_isShrine ? '舍利塔' : '衣冠冢'}</span>
              <span class="vt-loc">${_loc}</span>
              <span class="vt-dec">传承 ×${_decPct}%</span>
            </div>`;
          }).join('');
        }
      } catch (e) { vaultBlocks = ''; }
  
      // 地区 1-17 地图皮肤：按地区主题化渲染（CSS 皮肤），全地区覆盖
      const _skinCls = (act >= 1 && act <= 17) ? ' skin-act-' + act : '';
      return `<div class="map${_skinCls}" id="mapArea">
        ${missionHud}
        <div class="nodes" style="width:${mapW}px; height:${mapH}px">
          <svg class="links" width="${mapW}" height="${mapH}" viewBox="0 0 ${mapW} ${mapH}">${links}</svg>
          <div class="region-bg cur" style="left:${bossX}px; top:0; width:${mapW - bossX}px; height:${mapH}px; background:${regionPal(act,false)}; background-image:${curImg};"></div>
          <div class="region-bg next ${s.gateOpen ? 'gate-open' : (hasNext ? (bossLayerMet ? 'open' : 'locked') : 'final')}" style="left:0; top:0; width:${bossX}px; height:${mapH}px; background:${regionPal(nextAct, !s.gateOpen)}; background-image:${nextImg};"></div>
          ${s.gateOpen ? `<div class="region-portal gate-open" data-action="region-gate" style="left:${_geom.PAD_X}px; top:${PAD_Y}px; width:${_geom.PORTAL_W - 16}px; height:${mapH - 2*PAD_Y}px;">
            <div class="portal-tag">⛩ 土地庙</div>
            <div class="portal-name">${NDX.ACT_NAMES[(s.act||1)-1] || '灵山'}</div>
            <div class="portal-hint">歇脚整备 · 再启西行</div>
          </div>` : ''}
          ${cells}
          ${vaultBlocks}
        </div>
      </div>`;
    },
  statusHtml(s, st, hero) {
      const t = st.ti, y = st.yuan;
      const hpPct = Math.max(0, Math.min(100, Math.round((s.hp / t.maxHp) * 100)));
      const lf = (s && typeof s.life === 'number') ? s.life : NDX.LIFE.START;
      const lfMax = (s && s.lifeMax) || NDX.LIFE.MAX;
      const lfPct = Math.max(0, Math.min(100, Math.round((lf / lfMax) * 100)));
      // V8.36 修正寿数警告阈值：余寿<=8为垂死，<=3为濒死（原lf<=45是bug，初始余寿仅27）
      const lfDying = lf <= 3 ? ' dying critical' : (lf <= 8 ? ' dying' : '');
      const portraitSrc = (NDX.game && NDX.game.getHeroPortrait) ? NDX.game.getHeroPortrait() : (hero && hero.portrait || '');
      const portraitHtml = portraitSrc
        ? `<img class="hero-portrait-sm" src="${portraitSrc}" alt="${hero ? hero.name : ''}" />`
        : `<div class="hero-portrait-sm no-img">${hero ? hero.name[0] : '?'}</div>`;
      const acc = NDX.accountSnapshot(s);
      const accGot = acc.gained.length ? this._acctListHtml(acc.gained) : '<p class="ledger-empty">此世尚无余物——西行未深，家当未得。</p>';
      const accLost = acc.lost.length ? this._acctListHtml(acc.lost) : '<p class="ledger-empty">此世尚无人失——若死于途，随行家当将随之失落。</p>';
      const accInh = acc.toInherit.length ? this._acctListHtml(acc.toInherit) : '<p class="ledger-empty">尚无将传承之物——遗物/佛经/逆经/劫印（胜利时），方能带进下世。</p>';
      return `<div class="panel-box status">
        <div class="status-mini" data-action="show-hero-detail">
          ${portraitHtml}
          <div class="status-core">
            <div class="status-name">${hero ? hero.name : '行者'}</div>
            <div class="hpbar"><div class="hpfill" style="width:${hpPct}%"></div><span class="hptxt">${s.hp}/${t.maxHp}</span></div>
              <div class="hpbar lpbar${lfDying}" title="寿数 · 行路耗天、节点再加，见底则大限坐化"><div class="hpfill lifefill" style="width:${lfPct}%"></div><span class="hptxt">余${NDX.fmtLife(lf)}<span class="dim">/大限${NDX.fmtLife(lfMax)}</span></span></div>
            <div class="status-nums">
              <span class="ti-atk">攻 ${t.atk}</span>
              <span class="matk">原 ${y.matk}</span>
              <span class="good">善 ${s.good}</span>
              <span class="evil">恶 ${s.evil}</span>
            </div>
            ${this._benMingHtml(s)}
          </div>
          <div class="status-hint">点头像看完整属性</div>
        </div>
        <details class="ledger-box">
          <summary>📗 一生账本<span class="ledger-badge">攒${acc.gained.length} · 失${acc.lost.length} · 传${acc.toInherit.length}</span><span class="ledger-chev">▾</span></summary>
          <div class="ledger-grid">
            <div class="ledger-col ledger-got"><h5>本世攒得</h5>${accGot}</div>
            <div class="ledger-col ledger-lost"><h5>已失落</h5>${accLost}</div>
            <div class="ledger-col ledger-inh"><h5>将传承</h5>${accInh}</div>
          </div>
          ${this._onboardHint()}
        </details>
        ${this._reengageBtn(s)}
      </div>`;
    },
  _benMingHtml(s) {
      try {
        const bm = NDX.benMingFabao(s);
        if (bm) {
          return `<div class="benming-line" title="本命法宝 · 今生随身不失落 · 死后随世而散不复传承（每世各英雄法宝独立重历重得） · 成长随地区推进">
            <span class="benming-badge">本命</span>
            <span class="benming-name">${bm.name}</span>
            <span class="benming-stage">${NDX.benMingStage(bm)}</span>
          </div>`;
        }
        return `<div class="benming-line empty" title="本命法宝 · 今生随身不失落 · 死后随世而散不复传承">
          <span class="benming-badge">本命</span>
          <span class="benming-name">未得</span>
        </div>`;
      } catch (e) { return ''; }
    },
  _mapHud(s, st, hero) {
      try {
        const g = NDX.game; // V8.35 修复：_mapHud 内部此前引用未定义的 g，被 catch 吞掉导致整块 HUD 不渲染
        const t = st.ti || {};
        const lf = (s && typeof s.life === 'number') ? s.life : NDX.LIFE.START;
        const lfMax = (s && s.lifeMax) || NDX.LIFE.MAX;
        const lfPct = Math.max(0, Math.min(100, Math.round((lf / lfMax) * 100)));
        const xv = (s && typeof s.xinmo === 'number') ? s.xinmo : 0;
        const xp = Math.max(0, Math.min(100, xv));
        const held = s.equips ? s.equips.length : 0;
        const portraitSrc = g && g.getHeroPortrait ? g.getHeroPortrait() : (hero && hero.portrait || '');
        const portraitHtml = portraitSrc
          ? `<img class="hud-portrait" src="${portraitSrc}" alt="${hero ? hero.name : ''}" onerror="this.style.visibility='hidden'" />`
          : `<div class="hud-portrait no-img">${hero ? hero.name[0] : '?'}</div>`;
        // 顶部居中常驻条：第 x/81 难 · 所在区域 · 第 x 地区
        const _actName = NDX.ACT_NAMES[Math.min((s.act || 1), NDX.TOTAL_ACTS) - 1] || ('第 ' + (s.act || 1) + ' 地区');
        const _n = NDX.globalProgress(s);
        const _trialsDone = (s.trialsPassed || []).filter((t) => t.act === (s.act || 1)).length;
        const _trialsTotal = (NDX.actTrials ? NDX.actTrials(s.act || 1) : 9);
        // 模块六·道心践行度反馈：地区配额只累积「所选之道的心力」（关隘解锁另按渡难/杀伐/缘遇，见 hud-trials）。
        // 仅当本地区启用配额且已「立下道心」时展示——补上「选了道却看不到进度」的体验缝（V8.34 quotaHud 曾移除）。
        let _quotaChip = '';
        try {
          if (NDX.quotaEnabled && NDX.quotaEnabled(s.act || 1) && s._quotaDaoChosen) {
            const _dao = NDX.mainDaoOf(s);
            const _dk = NDX.quotaCheck(s, _dao);
            const _dq = (NDX.regionQuotaOf(s.act || 1) || {})[_dao] || null;
            // 主路径 token：显示所选道主攻项实时进度。
            // 备路径：仅当「主路径未成、备路径已成」时展示备 token 摘要，避免出现「战斗0/2 却道成」的矛盾观感，
            // 让玩家看到是走了哪条备道攒满践行度（模块六·配额可视化补齐）。
            const _mainTokens = (_dq && _dq.main)
              ? Object.keys(_dq.main).map((k) => {
                  const _need = _dq.main[k]; const _cur = (s.quota || {})[k] || 0; const _ok = _cur >= _need;
                  return `<span class="qp${_ok ? ' ok' : ''}">${(NDX.QUOTA_LABEL && NDX.QUOTA_LABEL[k]) || k}${_cur}/${_need}</span>`;
                }).join(' ')
              : '';
            let _altTokens = '';
            if (_dq && _dq.alt && !_dk.mainMet && _dk.altMet) {
              _altTokens = Object.keys(_dq.alt).map((k) => {
                const _need = _dq.alt[k]; const _cur = (s.quota || {})[k] || 0; const _ok = _cur >= _need;
                return `<span class="qp qp-alt${_ok ? ' ok' : ''}">${(NDX.QUOTA_LABEL && NDX.QUOTA_LABEL[k]) || k}${_cur}/${_need}</span>`;
              }).join(' ');
            }
            const _state = _dk.mainMet ? '<span class="qd-done">道成</span>' : (_dk.altMet ? '<span class="qd-done">备道却成</span>' : '');
            if (_dq) {
              const _altTitle = (_altTokens ? ` · 已走备道：${_dao}道 ${_dk.missingAlt.length ? '未满' : '全满'}` : '');
              _quotaChip = `<button class="hud-chip hud-quota" title="道心·${_dao}道 践行度——本地区立下的主攻道愿力累积；关隘之门不由此道开启，仍须履足 渡难/杀伐/缘遇（见右上「已历难」）${_altTitle}">
                <span class="qd-ico">☯</span>
                <span class="qd-dao">${_dao}道</span>
                ${_mainTokens}${_altTokens}${_state}
              </button>`;
            }
          }
        } catch (e) { _quotaChip = ''; }
        const _topBar = `<div class="hud-topbar" title="当前进度">
            <span class="hud-prog">第 ${_n}/${NDX.TOTAL_TRIALS} 难</span>
            <span class="hud-sep">·</span>
            <span class="hud-region">${_actName}</span>
            <span class="hud-sep">·</span>
            <span class="hud-act">第 ${s.act} 地区</span>
          </div>`;
        // 【V9.8 返程兑现 2026-09-14】东归九年前置可见：余寿跌破返程费即告警，
        //   否则玩家会一路走到灵山才发现「赢了也回不去」——那不是转折，是偷袭。
        const _RC = (NDX.LIFE && NDX.LIFE.RETURN_COST) || 9;
        const _noReturn = lf <= _RC;
        return `<div class="map-hud">
          ${_topBar}
          <!-- 左上：寿命 -->
          <button class="hud-chip hud-life" data-action="open-lamp" title="寿数 · 点击看详情（行路耗 ${NDX.LIFE.RIDE_DAYS || 5} 天/段、节点再加；六道各有日程：战 ${(NDX.LIFE.DAO_DAYS || {}).战 || 1} 日、渡 ${(NDX.LIFE.DAO_DAYS || {}).渡 || 10} 日）&#10;⚠ 取经功成后，东归还要再扣 ${_RC} 年——这九年不是你能花的">
            <span class="hud-ico">🪔</span>
            <span class="hud-life-body">
              <span class="hud-lifefill" style="width:${lfPct}%"></span>
            </span>
            <span class="hud-txt"${_noReturn ? ' style="color:#D85A30"' : ''}>寿${NDX.fmtAge(s.life)}${_noReturn ? ' ⚠东归不保' : ''}</span>
          </button>
          <!-- 右侧：心魔 -->
          <button class="hud-chip hud-xinmo" data-action="open-xinmo" title="心魔 · 点击看详情（满值下个劫难强制镜像战）">
            <span class="hud-ico">🔥</span>
            <span class="hud-xinmo-track"><span class="hud-xinmo-fill" style="width:${xp}%"></span></span>
            <span class="hud-txt">心魔 ${Math.round(xv)}</span>
          </button>
          <!-- 右上（changan 正下方）：已历劫难进度 -->
          <button class="hud-chip hud-trials" data-action="open-trials" title="已历劫难进度 · 点击看 Boss 刷新条件">
            <span class="hud-ico">📿</span>
            <span class="hud-txt">已历${_trialsDone}/${_trialsTotal}难</span>
          </button>
          ${_quotaChip}
          <!-- 左下：人物 -->
          <button class="hud-chip hud-hero" data-action="open-hero" title="人物详情 · 点击看完整属性">
            ${portraitHtml}
            <span class="hud-hero-name">${hero ? hero.name : '行者'}</span>
            <span class="hud-hp" style="width:${Math.max(0, Math.min(100, Math.round((s.hp / (t.maxHp || 1)) * 100)))}%"></span>
          </button>
          <!-- 右下：装备 -->
          <button class="hud-chip hud-bag" data-action="open-bag" title="行囊 · 点击看装备与家当">
            <span class="hud-ico">🎒</span>
            <span class="hud-txt">装备 ${held}</span>
          </button>
          <!-- 底部居中：行装快捷栏（装备栏/法宝栏/宠物栏；劫印栏在第四章结束后或持印后出现） -->
          ${this._mapDockHtml(s)}
          <!-- 角落极小入口：长安大本营 / 音效（不占主状态区） -->
          <button class="hud-chip hud-changan" data-action="open-changan" title="长安 · 西行大本营">🏯</button>
          <button class="hud-chip hud-settings" data-action="open-meta-overview" style="right:92px; top:12px" title="轮回总鉴：局外修行一屏总览">🧭</button>
          <button class="hud-chip hud-settings" data-action="open-settings" style="right:128px; top:12px" title="设置：音效 / 战斗速度 / 操作说明">⚙</button>
          <button class="hud-chip hud-snd ${NDX.sound && NDX.sound.isOn() ? '' : 'off'}" data-action="toggle-sound" title="${NDX.sound && NDX.sound.isOn() ? '静音' : '开启音效'}">${NDX.sound && NDX.sound.isOn() ? '🔔' : '🔕'}</button>
        </div>`;
      } catch (e) { return ''; }
    },
  _mapDockHtml(s) {
      try {
        const actN = s.act || 1;
        const actE = NDX.activeEquipsFor ? NDX.activeEquipsFor(s) : (s.equips || []);
        const gearN = actE.filter((e) => e && e.slot !== 'pet' && e.slot !== 'treasure').length;
        const treN = actE.filter((e) => e && e.slot === 'treasure').length;
        const petN = actE.filter((e) => e && e.slot === 'pet').length;
        const gearCap = NDX.gearSlotCap || 4;
        const petCap = NDX.petSlotCap || 2;
        const treCap = NDX.treasureSlotCap ? NDX.treasureSlotCap(actN) : 2;
        const sealN = (s.seals || []).length;
        const sealLayers = (s.seals || []).reduce((a, x) => a + (NDX.sealLayerVal ? NDX.sealLayerVal(x.tier) : 1), 0);
        const sealOpen = actN >= 5 || (s.seals || []).length > 0;
        const _btn = (tab, ico, label, cnt, cap) =>
          `<button class="dock-chip" data-action="dock-open" data-tab="${tab}" title="${label} · 生效 ${cnt}/${cap}">
            <span class="hud-ico">${ico}</span><span class="hud-txt">${label}</span><span class="dock-cnt">${cnt}/${cap}</span>
          </button>`;
        return `<div class="map-dock">
          ${_btn('equip', '🗡', '装备栏', gearN, gearCap)}
          ${_btn('treasure', '📜', '法宝栏', treN, treCap)}
          ${_btn('pet', '🐾', '宠物栏', petN, petCap)}
          ${sealOpen ? `<button class="dock-chip" data-action="dock-open" data-tab="seal" title="劫印 · 全数自动生效（${sealN}枚 · ${sealLayers}层）"><span class="hud-ico">🔯</span><span class="hud-txt">劫印栏</span><span class="dock-cnt">${sealN}枚</span></button>` : ''}
        </div>`;
      } catch (e) { return ''; }
    },
  nanbuMapHtml() {
      const cleared = new Set(NDX.loadClearedDiffs());
      const got = new Set(NDX.loadAch());
      const achById = NDX.ACH_BY_ID || {};
      // 判断某难对应成就的道途（正/逆）：从已落簿成就反查其难号归属
      const diffSide = {};
      NDX.NANBU_ALL.forEach((a) => {
        // req 形如 { 渡: 40 } / { 逆: 52 }，取首个数值为难号（跳过 null / 字符串等非对象门槛）
        if (!a.req || typeof a.req !== 'object') return;
        const rk = Object.keys(a.req)[0];
        if (!rk) return;
        const d = a.req[rk];
        if (!diffSide[d]) diffSide[d] = a.side === '逆道' ? 'nidao' : 'zhengguo';
      });
      const lib = NDX.TRIAL_LIB || {};
      const COLS = 9, ROWS = 9;
      let cells = '';
      for (let i = 0; i < COLS * ROWS; i++) {
        const diff = i + 1; // 1..81
        if (diff > NDX.TOTAL_TRIALS) { cells += `<div class="nbm-cell empty"></div>`; continue; }
        const isBoss = NDX.isBossTrial(diff);
        const passed = cleared.has(diff);
        const info = lib[diff] || {};
        const side = diffSide[diff]; // 'zhengguo' 正道金 / 'nidao' 逆道血 / undefined 普通
        const tone = !passed ? 'locked' : (side === 'nidao' ? 'ni' : 'zheng');
        const icon = info.icon || (isBoss ? '☠' : '·');
        const act = info.act || NDX.chapterOf(diff);
        const cls = `nbm-node tone-${tone} ${isBoss ? 'boss' : ''} ${diff === 1 ? 'start' : ''} ${diff === NDX.TOTAL_TRIALS ? 'end' : ''}`;
        cells += `<div class="nbm-cell">
          <div class="${cls}" data-diff="${diff}" title="${diff}难 · ${info.name || '？'}">
            <span class="nbm-dot">${icon}</span>
            <span class="nbm-no">${diff}</span>
          </div>
        </div>`;
      }
      // 连线用纯 CSS 行/列为底色，金色/血色由节点状态表达（断裂用虚线由 node 边框表现）
      return `<div class="nbm-map" data-stop>
        <div class="nbm-map-head">西 行 难 簿 · 八 十 一 难 长 卷</div>
        <div class="nbm-legend">
          <span class="nbm-leg tone-zheng">◉ 正道已通</span>
          <span class="nbm-leg tone-ni">◉ 逆道已通</span>
          <span class="nbm-leg tone-locked">○ 未历</span>
        </div>
        <div class="nbm-grid" style="grid-template-columns:repeat(${COLS},1fr)">${cells}</div>
        ${this.geoSegmentsHtml()}
        <div class="nbm-tip" id="nbm-tip">悬停节点，查看此难详情；点击展开难情。</div>
      </div>`;
    }
});
