// AUTO-GENERATED by _refactor_split.js — domain: modals
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  _clearBodyOverlays() {
      const ids = [
        'ach-book-modal', 'cycle-palace-modal', 'collection-modal', 'rubbing-modal',
        'yezanglu-modal', 'ash-shop-modal', 'monuments-modal', 'ranking-modal',
        'changan-modal', 'settings-modal', 'meta-overview-modal', 'dynasty-modal',
        'hero-detail-modal', 'bag-detail-modal', 'pet-atlas-modal', 'follower-atlas-modal', 'xinmo-detail-modal', 'dock-modal',
        'first-evil-overlay', 'promote-overlay', 'pre-anim-overlay',
      ];
      for (const id of ids) {
        const el = document.getElementById(id);
        if (el && el.parentNode) el.parentNode.removeChild(el);
      }
      // 清除错误提示
      document.querySelectorAll('.modal-error-tip').forEach(function (el) {
        if (el.parentNode) el.parentNode.removeChild(el);
      });
    },
  _appendSceneOverlays(app) {
      const items = [
        [this.showAchBook, 'ach-book-modal', '难簿', () => this.achievementBookHtml()],
        [this.showCyclePalace, 'cycle-palace-modal', '轮回殿', () => this.cyclePalaceHtml()],
        [this.showCollection, 'collection-modal', '藏品库', () => this.collectionHtml()],
        [this.showRubbing, 'rubbing-modal', '藏经阁', () => this.rubbingHtml()],
        [this.showYezanglu, 'yezanglu-modal', '降妖簿', () => this.yezangluHtml()],
        [this.showAsh, 'ash-shop-modal', '劫灰坊', () => this.ashHtml()],
        [this.showMonuments, 'monuments-modal', '舍利塔·逆道碑', () => this.monumentsHtml()],
        [this.showRanking, 'ranking-modal', '功德榜', () => this.rankingHtml()],
        [this.showChangan, 'changan-modal', '长安大本营', () => this.changanHtml()],
        [this.showDynasty, 'dynasty-modal', '朝代年表', () => this.dynastyHtml()],
        [this.showSettings, 'settings-modal', '设置', () => this.settingsModal()],
        [this.showCompliance, 'compliance-modal', '合规', () => this.complianceHtml()],
        [this.showMetaOverview, 'meta-overview-modal', '轮回总鉴', () => this.metaOverviewHtml()],
      ];
      // 先清除 body 中所有旧弹窗（render() 只清 #app，不清 body；不清除会导致重复叠加或关闭后残留）
      for (const [, id] of items) {
        const old = document.getElementById(id);
        if (old && old.parentNode) old.parentNode.removeChild(old);
      }
      // 同时清除旧的错误提示
      document.querySelectorAll('.modal-error-tip').forEach(function (el) {
        if (el.parentNode) el.parentNode.removeChild(el);
      });
      for (const [flag, id, name, htmlFn] of items) {
        if (!flag) continue;
        try {
          const html = htmlFn();
          const modal = document.createElement('div');
          modal.id = id;
          modal.innerHTML = html;
          // 弹窗挂进 ndx-modal-host（ndx-lock 内部，随旋转层一起横屏）；body 仅兜底。
          // 横屏尺寸由 CSS（.ndx-short-landscape 体系）唯一负责，不再用 JS inline style 补丁。
          (window.__ndxOverlay || document.body.appendChild.bind(document.body))(modal);
        } catch (err) {
          console.error(`[UI] ${name}弹窗生成失败:`, err);
          const tip = document.createElement('div');
          tip.className = 'modal-error-tip';
          tip.innerHTML = `<div class="box-title">${name}暂时无法打开</div><p class="muted">${err && err.message ? esc(String(err.message)) : '未知异常'}</p>`;
          (window.__ndxOverlay || document.body.appendChild.bind(document.body))(tip);
        }
      }
    },
  dockModalHtml(s) {
      const _tab = this.dockTab || 'equip';
      const actN = s.act || 1;
      const sealOpen = actN >= 5 || (s.seals || []).length > 0;
      const _tabs = [['equip', '🗡 装备栏'], ['treasure', '📜 法宝栏'], ['pet', '🐾 宠物栏']];
      if (sealOpen) _tabs.push(['seal', '🔯 劫印栏']);
      const _tabBar = `<div class="dock-tabs">${_tabs.map(([k, lbl]) =>
        `<button class="dock-tab${_tab === k ? ' on' : ''}" data-action="dock-tab" data-tab="${k}">${lbl}</button>`).join('')}</div>`;
      // —— 数值摘要（与换装弹窗同源）——
      const stat = (e) => {
        const a = e.atk ? `体攻${e.atk}` : '';
        const h = e.hp ? `气血${e.hp}` : '';
        const d = e.dr ? `护体${Math.round(e.dr * 100)}%` : '';
        const ev = e.eva ? `身法${Math.round(e.eva * 100)}%` : '';
        const m = e.matk ? `愿伤${e.matk}` : '';
        const md = e.mdef ? `御念${Math.round(e.mdef * 100)}%` : '';
        const r = e.hpRegen ? `回血${e.hpRegen}` : '';
        const c = e.crit ? `暴击${Math.round(e.crit * 100)}%` : '';
        const cm = e.criMult ? `暴伤+${Math.round((e.criMult - 1) * 100)}%` : '';
        const fa = e.fixAtk ? `破甲${e.fixAtk}` : '';
        const ap = e.armorPen ? `无视甲${Math.round(e.armorPen * 100)}%` : '';
        const sh = e.shieldPct ? `护盾${Math.round(e.shieldPct * 100)}%` : '';
        const re = e.reflect ? `反伤${Math.round(e.reflect * 100)}%` : '';
        const sp = e.spd ? `速+${e.spd}` : '';
        const ls = e.lifesteal ? `吸血${Math.round(e.lifesteal * 100)}%` : '';
        const set = e.set ? `·${e.set}套` : '';
        const qNames = ['凡器', '灵器', '宝器'];
        const q = e.quality || 0;
        const qTag = q > 0 ? `·${qNames[q]}` : '';
        const passiveNames = { gold_per_turn: '每战+金', regen: '每战回血', poison: '每回合毒', dragon_aura: '龙息护盾' };
        const pTag = e.petPassive ? `·${passiveNames[e.petPassive] || e.petPassive}` : '';
        return [a, h, d, ev, m, md, r, c, cm, fa, ap, sh, re, sp, ls, set].filter(Boolean).join(' · ') + qTag + pTag;
      };
      const activeIds = (NDX.activeEquipsFor ? NDX.activeEquipsFor(s) : []).map((x) => x && x.id);
      const _row = (e) => {
        const inside = activeIds.indexOf(e.id) >= 0;
        const sysTag = e.sys === 'yuan' ? '<span class="sys-yuan-tag">愿</span>' : '<span class="sys-ti-tag">体</span>';
        const petMark = e.slot === 'pet' ? '<span class="pet-mark">🐾</span>' : '';
        const ch = (e.chargesLeft == null ? (e.charges || 0) : e.chargesLeft);
        const treTag = (e.slot === 'treasure' && e.treasure) ? (ch > 0 ? ` <span class="bag-charge">充能×${ch}</span>` : ' <span class="bag-charge depleted">灵光已尽</span>') : '';
        return `<li>${this._equipIcon(e)}${sysTag}<b>${e.name}</b>${petMark} <span class="bag-stat">${stat(e)}</span>${treTag}
          <button class="use-btn slot-toggle${inside ? ' on' : ''}" data-action="bag-equip-toggle" data-id="${e.id}" title="${inside ? '点击撤下（不再获得加成）' : '置为生效'}">${inside ? '✔ 生效' : '置为生效'}</button>
          ${inside ? '<span class="bag-active-now">当前生效</span>' : ''}</li>`;
      };
      const _slotList = (slots) => (s.equips || []).filter((e) => e && slots.indexOf(e.slot) >= 0);
      let title = '装备栏', body = '';
      if (_tab === 'equip') {
        const list = _slotList(NDX.GEAR_SLOTS || ['weapon', 'armor', 'head', 'boots']);
        const cap = NDX.gearSlotCap || 4;
        const actGear = list.filter((e) => activeIds.indexOf(e.id) >= 0).length;
        body = `<p class="bag-req">兵刃/甲胄/头冠/战靴各按槽位生效，共 <b>${cap}</b> 格（当前生效 ${actGear}）。仅生效装备提供加成。</p>
          <ul class="baglist">${list.map(_row).join('') || '<li class="muted">行囊空空——击败劫难必得装备。</li>'}</ul>
          <div class="bag-actions"><button class="opt-btn ghost" data-action="open-follower-atlas" title="查看随从名录 / 已收服与可收的妖王随从及其属性">👥 随从名册</button></div>`;
      } else if (_tab === 'treasure') {
        title = '法宝栏';
        const list = _slotList(['treasure']);
        const cap = NDX.treasureSlotCap ? NDX.treasureSlotCap(actN) : 2;
        const actTre = list.filter((e) => activeIds.indexOf(e.id) >= 0).length;
        body = `<p class="bag-req">法宝生效格上限 <b>${cap}</b> 格（当前生效 ${actTre} 件）。生效格内方可临阵祭出/提供加成。</p>
          <ul class="baglist">${list.map(_row).join('') || '<li class="muted">尚无法宝——宝窟与奇遇中可得。</li>'}</ul>`;
      } else if (_tab === 'pet') {
        title = '宠物栏';
        const list = _slotList(['pet']);
        const cap = NDX.petSlotCap || 2;
        const actPet = list.filter((e) => activeIds.indexOf(e.id) >= 0).length;
        body = `<p class="bag-req">灵宠生效格上限 <b>${cap}</b> 格（当前出战 ${actPet}）。出阵灵兽可触发御兽羁绊与连招协同。</p>
          <ul class="baglist">${list.map(_row).join('') || '<li class="muted">尚未收服灵宠。</li>'}</ul>
          <div class="bag-actions"><button class="opt-btn ghost" data-action="open-pet-atlas">🐾 灵兽图鉴</button></div>`;
      } else {
        title = '劫印栏';
        const _daoMap = (NDX.SEAL_DAOTU || {});
        const _daoOrder = ['渡', '战', '缘', '夺', '隐', '逆'];
        const _tlRows = _daoOrder
          .filter((d) => NDX.sealDaoLayerSum ? NDX.sealDaoLayerSum(s, d) > 0 : false)
          .map((d) => {
            const sum = NDX.sealDaoLayerSum(s, d);
            const nxt = NDX.sealBreakInfo ? NDX.sealBreakInfo(s, d).nxtTier : null;
            const _nm = (_daoMap[d] || { name: d }).name;
            return `<span class="seal-tl-cell${nxt == null ? ' on' : ''}">${_nm} ${sum}层` +
              (nxt != null ? `<span class="bag-stat"> → ${nxt}层</span>` : `<span class="bag-active-now"> ◆ 圆</span>`) + `</span>`;
          }).join('');
        const _listS = (s.seals || []).map((x) => {
          const _dao = (_daoMap[x.dao] || { name: x.dao });
          return `<li><span class="seal-dao">${_dao.name}</span><b>${x.name}</b>
            <span class="bag-stat">+${Math.round((x.val || 0) * 100)}% · ${NDX.SEAL_TIER_LABEL ? (NDX.SEAL_TIER_LABEL[x.tier] || x.tier) : x.tier}</span>
            <span class="seal-layer">层×${NDX.sealLayerVal ? NDX.sealLayerVal(x.tier) : 1}</span>
            <span class="bag-active-now">全数自动生效</span></li>`;
        }).join('');
        body = `<p class="bag-req">劫印全数自动生效，不占生效格——按道累计「道途层数」，达 3/6/9/12 层自动触发阶段加成。</p>
          <div class="seal-tierline">${_tlRows || '<span class="bag-stat">尚无道途层数。</span>'}</div>
          <ul class="baglist">${_listS || '<li class="muted">尚无劫印——击败关隘之主后由观音授予。</li>'}</ul>`;
      }
      return `<div class="scene-overlay bag-overlay dock-overlay" data-action="close-modal">
        <div class="scene-modal bag-modal dock-modal" data-stop>
          <button class="modal-close" data-action="close-modal" aria-label="关闭">✕</button>
          <div class="panel-title"><span class="panel-corner">囊</span>行装 · ${title}</div>
          <div class="panel-body bag-detail">
            ${_tabBar}
            ${body}
          </div>
        </div>
      </div>`;
    },
  lampDetailModal(s, hero) {
      const lf = (s && typeof s.life === 'number') ? s.life : NDX.LIFE.START;
      const lfMax = (s && s.lifeMax) || NDX.LIFE.MAX;
      const lfPct = Math.max(0, Math.min(100, Math.round((lf / lfMax) * 100)));
      const drum = (s.drumBonus || 0);
      return `<div class="modal-plate lamp-plate">
        <button class="modal-close" data-action="close-modal" aria-label="关闭">✕</button>
        <div class="box-title">🪔 寿数</div>
        <p class="muted">去程每进一步都在耗寿；恶道抉择（战/夺/逆）额外折寿 ${NDX.LIFE.EVIL_SURCHARGE} 岁，隐道额外折寿 ${NDX.LIFE.HIDDEN_SURCHARGE} 岁。寿数见底则大限坐化。</p>
        <div class="lamp-detail-row">
          <span class="lamp-detail-label">寿数</span>
          <span class="hpbar"><span class="hpfill lifefill" style="width:${lfPct}%"></span><span class="hptxt">${lf} 岁 / 大限 ${lfMax}</span></span>
        </div>
        ${drum ? `<p class="muted">本世已敲钟 ${drum} 次：每次 +${NDX.LIFE.DRUM || 1} 月寿数（见好就收，第 3 次起收益减半）。</p>` : ''}
        <p class="muted">讨封节点「讨得正果」可续命；长安轮回殿可重置命运。</p>
      </div>`;
    },
  momentumHelpModal() {
      return `<div class="modal-plate momentum-help-plate">
        <button class="modal-close" data-action="close-modal" aria-label="关闭">✕</button>
        <div class="box-title">⚡ 气势 · 识破</div>
        <p class="muted"><b>气势</b>：命中则涨，受击则落。气势聚满可发动<b>「气势爆发」</b>——倾泻全部气势换一记全力重击，爆发后气势清零，需重新积攒。</p>
        <p class="muted"><b>识破</b>：妖物蓄力重击的那一回合，即为识破窗口。此时出手可打断其蓄力并额外加成；若按兵不动，便只能硬吃这一记重击。</p>
        <p class="muted">此二者是战斗中仅有的两个主动决策点：气势靠<b>连续命中</b>积累，识破靠<b>盯住蓄力</b>。手机端直接点按钮即可，无需长按。</p>
      </div>`;
    },
  xinmoDetailModal(s) {
      const X = NDX.XINMO || {};
      const v = (s && typeof s.xinmo === 'number') ? s.xinmo : 0;
      const pct = Math.max(0, Math.min(100, v));
      let tier = '心明如镜';
      for (const k of [100, 85, 60, 30, 0]) if (pct >= k && X.TIER_TXT) { tier = X.TIER_TXT[k]; break; }
      const danger = pct >= 100;
      const capped = (s.xinmoBattles || 0) >= (X.BATTLE_CAP || 99);
      const penaltyNote = (s.xinmoBattles || 0) > 0 ? `（已破镜 ${s.xinmoBattles} 次，下次败惩罚 ×${Math.pow(X.BATTLE_PENALTY_SCALE || 1, s.xinmoBattles).toFixed(1)}）` : '';
      return `<div class="modal-plate xinmo-plate">
        <button class="modal-close" data-action="close-modal" aria-label="关闭">✕</button>
        <div class="box-title">🔥 心魔</div>
        <p class="muted">心魔值满后，下个劫难将被镜中的你劫持为强制镜像战。胜无战利品；败则气血上限受损且可能丢失劫印。每次破镜后下次惩罚加重。顺命（渡/缘）不积心魔；争/夺/逆/隐会累积；土地庙歇息、转章回长安可压心魔。${penaltyNote}</p>
        <div class="xinmo-detail-row">
          <span class="xinmo-track big"><span class="xinmo-fill" style="width:${pct}%"></span></span>
          <span class="xinmo-num">${Math.round(v)}</span>
        </div>
        <div class="xinmo-tier ${danger ? 'danger' : ''}">${tier}${(s.xinmoBattles || 0) > 0 ? '·已破镜' + s.xinmoBattles : ''}</div>
        <p class="muted">六道抉择印记：战 ${s.fate['战'] || 0} · 渡 ${s.fate['渡'] || 0} · 逆 ${s.fate['逆'] || 0} · 隐 ${s.fate['隐'] || 0} · 夺 ${s.fate['夺'] || 0} · 缘 ${s.fate['缘'] || 0}</p>
      </div>`;
    },
  settingsModal() {
      const st = NDX.settings || NDX.DEFAULT_SETTINGS;
      const sndOn = st.soundOn !== false;
      const speed = st.fightSpeed || 1;
      const tutOn = st.showTutorial !== false;
      const speedOpts = [1, 2, 3].map((v) => `<button class="setting-opt${speed === v ? ' active' : ''}" data-action="set-speed" data-val="${v}">${v}x</button>`).join('');
      return `<div class="modal-plate settings-plate">
        <button class="modal-close" data-action="close-modal" aria-label="关闭">✕</button>
        <div class="box-title">⚙ 设置</div>
        <div class="setting-row">
          <span class="setting-label">🔔 音效</span>
          <button class="setting-toggle${sndOn ? ' on' : ''}" data-action="toggle-sound-setting">${sndOn ? '开启' : '关闭'}</button>
        </div>
        <div class="setting-row">
          <span class="setting-label">🔊 主音量</span>
          <div class="setting-opts">
            <input type="range" min="0" max="100" value="${Math.round((st.soundVol != null ? st.soundVol : 0.5) * 100)}" data-action="set-volume" style="width:160px;vertical-align:middle;" />
            <span class="muted" style="margin-left:6px;">${Math.round((st.soundVol != null ? st.soundVol : 0.5) * 100)}%</span>
          </div>
        </div>
        <div class="setting-row">
          <span class="setting-label">🎵 BGM音量</span>
          <div class="setting-opts">
            <input type="range" min="0" max="100" value="${Math.round((NDX.sound ? NDX.sound.getBgmVolume() : 0.7) * 100)}" data-action="set-bgm-volume" style="width:160px;vertical-align:middle;" />
            <span class="muted" style="margin-left:6px;">${Math.round((NDX.sound ? NDX.sound.getBgmVolume() : 0.7) * 100)}%</span>
          </div>
        </div>
        <div class="setting-row">
          <span class="setting-label">🔔 音效音量</span>
          <div class="setting-opts">
            <input type="range" min="0" max="100" value="${Math.round((NDX.sound ? NDX.sound.getSfxVolume() : 0.8) * 100)}" data-action="set-sfx-volume" style="width:160px;vertical-align:middle;" />
            <span class="muted" style="margin-left:6px;">${Math.round((NDX.sound ? NDX.sound.getSfxVolume() : 0.8) * 100)}%</span>
          </div>
        </div>
        <div class="setting-row">
          <span class="setting-label">🌿 环境音音量</span>
          <div class="setting-opts">
            <input type="range" min="0" max="100" value="${Math.round((NDX.sound ? NDX.sound.getAmbientVolume() : 0.5) * 100)}" data-action="set-ambient-volume" style="width:160px;vertical-align:middle;" />
            <span class="muted" style="margin-left:6px;">${Math.round((NDX.sound ? NDX.sound.getAmbientVolume() : 0.5) * 100)}%</span>
          </div>
        </div>
        <div class="setting-row">
          <span class="setting-label">⚔ 战斗速度</span>
          <div class="setting-opts">${speedOpts}</div>
        </div>
        <div class="setting-row">
          <span class="setting-label">📖 新手指引</span>
          <button class="setting-toggle${tutOn ? ' on' : ''}" data-action="toggle-tutorial">${tutOn ? '开启' : '关闭'}</button>
        </div>
        <div class="setting-row">
          <span class="setting-label">⚡ 速战模式</span>
          <button class="setting-toggle${st.fastMode ? ' on' : ''}" data-action="toggle-fast-mode">${st.fastMode ? '开启' : '关闭'}</button>
        </div>
        <div class="setting-row">
          <span class="setting-label">🎯 下局难度</span>
          <div class="setting-opts">
            ${['easy','normal','hard','hell'].map((id) => {
              const d = NDX.DIFFICULTY[id];
              return `<button class="setting-opt${(st.nextDifficulty || 'normal') === id ? ' active' : ''}" data-action="set-difficulty" data-val="${id}" title="${d.desc}">${d.icon} ${d.name}</button>`;
            }).join('')}
          </div>
        </div>
        <div class="setting-divider"></div>
        <div class="setting-section">
          <div class="setting-section-title">♿ 无障碍</div>
          <div class="setting-row">
            <span class="setting-label">🔤 字号</span>
            <div class="setting-opts">
              ${[0.9, 1, 1.1, 1.2].map((v) => `<button class="setting-opt${(st.fontScale || 1) === v ? ' active' : ''}" data-action="set-font-scale" data-val="${v}">${v === 1 ? '标准' : (v > 1 ? '大' + Math.round((v-1)*10) + '%' : '小' + Math.round((1-v)*10) + '%')}</button>`).join('')}
            </div>
          </div>
          <div class="setting-row">
            <span class="setting-label">◐ 高对比度</span>
            <button class="setting-toggle${st.highContrast ? ' on' : ''}" data-action="toggle-high-contrast">${st.highContrast ? '开启' : '关闭'}</button>
          </div>
          <div class="setting-row">
            <span class="setting-label">👁 色盲模式</span>
            <div class="setting-opts">
              ${[['none','标准'],['protanopia','红色盲'],['deuteranopia','绿色盲'],['tritanopia','蓝色盲']].map(([v,l]) => `<button class="setting-opt${(st.colorBlindMode || 'none') === v ? ' active' : ''}" data-action="set-colorblind" data-val="${v}">${l}</button>`).join('')}
            </div>
          </div>
        </div>
        <div class="setting-divider"></div>
        <div class="setting-section">
          <div class="setting-section-title">操作说明</div>
          <div class="setting-help">
            <p><b>攻</b>：普攻，无冷却，基础伤害</p>
            <p><b>经</b>：诵经/戾骨，法术伤害+回血，有冷却</p>
            <p><b>绝</b>：金蝉禅唱，终结大招，蓄满可用</p>
            <p><b>气势</b>：命中则涨、受击则落，满势可发动「气势爆发」</p>
            <p><b>识破</b>：妖物蓄力重击那回合出手，可打断并额外加成</p>
            <p><b>法宝</b>：战斗中点击法宝栏祭出，主动技能有冷却</p>
            <p><b>地图</b>：点击高亮节点前进，路线选择=奖励选择</p>
            <p><b>寿数</b>：每进节点耗寿，见底则大限坐化</p>
            <p><b>心魔</b>：恶道抉择累积，满值触发镜像战</p>
          </div>
        </div>
        <div class="setting-divider"></div>
        <div class="setting-section">
          <div class="setting-section-title">关于</div>
          <div class="setting-about">
            <p><b>逆道西行</b> · 黑暗西游 · 单局 Roguelike 肉鸽构筑</p>
            <p class="muted">八十一难，六道轮回。你是金蝉子，被贬入轮回，重走西行路。</p>
            <p class="muted">版本 V8.6x · 纯前端 H5 · 零第三方依赖</p>
            <div class="setting-divider"></div>
            <div class="setting-section">
              <div class="setting-section-title">🎵 音乐来源（OGA-BY 4.0 许可证）</div>
              <div class="setting-credits" style="font-size:12px;line-height:1.6;">
                <p><b>Boss战斗音乐</b>："Boss Fight" by AiTechEye — OpenGameArt.org</p>
                <p><b>普通战斗音乐</b>："BURNING HANDS" by AndyGun11 — OpenGameArt.org</p>
                <p><b>休息音乐</b>："Ethereal Hypnotic Dreamy Track" by raftxo — OpenGameArt.org</p>
                <p class="muted" style="margin-top:6px;">以上音乐采用 OGA-BY 4.0 许可证，需署名作者。</p>
              </div>
            </div>
            <p class="setting-compliance" style="margin-top:8px;font-size:12.5px;">
              <span class="compliance-age">适龄 16+</span>
              <span class="compliance-link" data-action="open-privacy" data-stop="1">隐私政策</span>
              <span class="compliance-link" data-action="open-terms" data-stop="1">用户协议</span>
              <span class="compliance-link" data-action="open-icp" data-stop="1">版号备案</span>
              <span class="compliance-link" data-action="open-feedback" data-stop="1">客服反馈</span>
            </p>
          </div>
        </div>
        <div class="setting-divider"></div>
        <button class="setting-danger-btn" data-action="reset-save" title="清除所有存档（成就/舍利/本局进度）">⚠ 重置全部存档</button>
      </div>`;
    },
  heroDetailModal(s, st, hero) {
      const t = st.ti, y = st.yuan;
      const dr = Math.round(t.dr * 100);
      const eva = Math.round(t.eva * 100);
      const mdef = Math.round(y.mdef * 100);
      const hpPct = Math.max(0, Math.min(100, Math.round((s.hp / t.maxHp) * 100)));
      const portraitSrc = (NDX.game && NDX.game.getHeroPortrait) ? NDX.game.getHeroPortrait() : (hero && hero.portrait || '');
      const portraitHtml = portraitSrc
        ? `<img class="hero-portrait-md" src="${portraitSrc}" alt="${hero ? hero.name : ''}" />`
        : '';
      // 初始套装进度
      const focusMap = { ts: '取经人', wk: '悟空', bj: '八戒', lm: '龙马', ss: '沙僧' };
      const setName = focusMap[(hero && hero.focus)] || null;
      const setIds = {
        取经人: ['ts_robe_top', 'ts_staff_top', 'ts_bowl_top'],
        悟空: ['wk_crown_top', 'wk_armor_top', 'wk_staff_top'],
        八戒: ['bj_rake_top', 'bj_robe_top', 'bj_belly_top'],
        龙马: ['lm_saddle_top', 'lm_scale_top', 'lm_hoof_top'],
        沙僧: ['ss_staff_top', 'ss_skull_top', 'ss_robe_top'],
      }[setName] || [];
      const owned = (s.equips || []).map((e) => e.id);
      const setCnt = setIds.filter((id) => owned.includes(id)).length;
      const setLine = setName ? `<div class="detail-line"><span class="detail-label">初始套装</span><span>${setName} ${setCnt}/3 ${setCnt >= 3 ? '·共鸣' : ''}</span></div>` : '';
      // 套装共鸣系统（平衡 V47）：展示当前已触发的套装共鸣（基于 computeStats 返回的 setResonance）
      const resonated = (st && st.setResonance) || [];
      const resoLine = resonated.length ? resonated.map((r) => {
        const tag = r.tier >= 3 ? '三件·大成' : '二件·小成';
        const isXuanwu = r.set === '玄武';
        return `<span class="reso-chip ${isXuanwu ? 'reso-xuanwu' : ''}" title="${r.name}：${tag}共鸣已激活">${r.name}·${tag}</span>`;
      }).join('') : '';
      const resoBlock = resonated.length ? `<div class="detail-line reso-line"><span class="detail-label">套装共鸣</span><span class="reso-tags">${resoLine}</span></div>` : '';
      // 系统间协同共鸣（V3 §6）：劫印+经文 / 劫印+装备 / 经文+装备 / 三者大协同词条
      const crossResonated = (st && st.crossResonance) || [];
      const crossResoLine = crossResonated.length ? crossResonated.map((r) => {
        return `<span class="reso-chip reso-cross" title="${r.desc}">${r.name}</span>`;
      }).join('') : '';
      const crossResoBlock = crossResonated.length ? `<div class="detail-line reso-line"><span class="detail-label">道途共鸣</span><span class="reso-tags">${crossResoLine}</span></div>` : '';
      const xuanwuActive = resonated.some((r) => r.set === '玄武');
      const lh = s.flags && s.flags.lostHeart ? s.flags.lostHeart : 0;
      const hiddenLine = (lh ? `<div class="detail-line"><span class="detail-label">迷失本心</span><span>${lh}/3</span></div>` : '') +
        ((s.flags && s.flags.tsHidden) ? `<div class="detail-line"><span class="detail-label">暗线</span><span>取经人隐藏</span></div>` : '');
      const pets = s.equips.filter((e) => e.slot === 'pet');
      const qNames = ['凡器', '灵器', '宝器'];
      const qMults = [1, 1.3, 1.6];
      const passiveNames = { gold_per_turn: '每战+金', regen: '每战回血', poison: '每回合毒', dragon_aura: '龙息护盾' };
      const petLine = pets.length ? `<div class="detail-line"><span class="detail-label">灵宠</span><span>${pets.map((e) => {
        const q = e.quality || 0;
        const qTag = q > 0 ? `<span class="pet-quality q${q}">${qNames[q]}</span>` : '';
        const pTag = e.petPassive ? `<span class="pet-passive">${passiveNames[e.petPassive] || e.petPassive}</span>` : '';
        const evoTag = e.evolveFrom ? '<span class="pet-evolved">已进化</span>' : '';
        return `${e.name}${qTag}${evoTag}${pTag}`;
      }).join('、')}</span></div>` : '';
      return `<div class="scene-overlay hero-overlay" data-action="close-modal">
        <div class="scene-modal hero-modal" data-stop>
          <div class="panel-title"><span class="panel-corner">行囊</span>${hero ? hero.name : '行者'} · 完整属性</div>
          <div class="panel-body hero-detail">
            <div class="hero-detail-head">${portraitHtml}<div class="hero-detail-txt">
              <div class="hero-form">${hero ? hero.form : ''} · 持${hero ? hero.symbol : ''}</div>
              <div class="hero-trait">${hero ? (hero.trait || '') : ''}</div>
            </div></div>
            <div class="hpbar detail-hp"><div class="hpfill" style="width:${hpPct}%"></div><span class="hptxt">${s.hp} / ${t.maxHp}</span></div>
            ${(() => {
              const power = t.power || 0;
              const rec = NDX.recommendPower((s && s.diff) || NDX.globalProgress(s));
              const ratio = rec > 0 ? power / rec : 1;
              // 战力强弱配色：红<黄<绿
              const tone = ratio >= 1.2 ? 'strong' : (ratio >= 0.8 ? 'ok' : 'weak');
              const pct = Math.max(4, Math.min(100, Math.round(ratio * 50))); // 对比条：战力占「推荐×2」的半幅，便于落点定位
              return `<div class="power-score power-${tone}">
                <div class="power-main">
                  <span class="power-label">战力总评</span>
                  <span class="power-num">${power}</span>
                </div>
                <div class="power-rec">推荐战力 <b>${rec}</b>（第 ${(s && s.diff) || NDX.globalProgress(s)} 难）</div>
                <div class="power-bar"><div class="power-fill" style="width:${pct}%"></div><div class="power-rec-mark" style="left:50%"></div></div>
                <div class="power-hint">${
                  tone === 'strong' ? '碾压 · 此难可轻松通过' :
                  tone === 'ok' ? '势均力敌 · 胜负在毫厘之间' :
                  '危 · 此难恐难通过，先去变强'
                }</div>
              </div>`;
            })()}
            <div class="detail-section sys-ti">体 · 肉身</div>
            <div class="detail-grid">
              <div title="英雄基础 + 兵刃/头冠/战靴体攻 + 战系劫印 + 隐藏职/经文/命痕"><span class="detail-label">体攻</span><span class="detail-val">${t.atk}</span></div>
              <div title="英雄基础 + 装备气血 + 夺系劫印 + 本命法宝/套装 + 劫灰永久加成"><span class="detail-label">气血上限</span><span class="detail-val">${t.maxHp}</span></div>
              <div title="装备护体 + 渡/缘系劫印御念 + 套装/经文减伤叠加"><span class="detail-label">护体</span><span class="detail-val${xuanwuActive ? ' val-xuanwu' : ''}">${dr}%${xuanwuActive ? ' ·玄武镇海' : ''}</span></div>
              <div title="装备身法 + 隐系劫印闪避，影响先手与闪避率"><span class="detail-label">身法</span><span class="detail-val">${eva}%</span></div>
              <div title="每场战斗自动恢复的气血量"><span class="detail-label">每场回血</span><span class="detail-val">${t.hpRegen || 0}</span></div>
            </div>
            <div class="detail-section sys-yuan">愿 · 心念</div>
            <div class="detail-grid">
              <div title="英雄基础 + 装备/法宝愿伤 + 愿系劫印法伤 + 经文全本加成"><span class="detail-label">愿伤</span><span class="detail-val">${y.matk}</span></div>
              <div title="装备御念 + 渡/缘系劫印法防"><span class="detail-label">御念</span><span class="detail-val">${mdef}%</span></div>
            </div>
            <div class="detail-section">命数</div>
            <div class="detail-grid">
              <div><span class="detail-label">道</span><span class="detail-val">${this.fateLabel(s.fate)}</span></div>
              <div><span class="detail-label">善</span><span class="detail-val good">${s.good}</span></div>
              <div><span class="detail-label">恶</span><span class="detail-val evil">${s.evil}</span></div>
              <div><span class="detail-label">金</span><span class="detail-val">${s.gold}</span></div>
              <div><span class="detail-label">装备数</span><span class="detail-val">${s.equips.length}</span></div>
            </div>
            <details class="detail-src">
              <summary>属性来源构成 <span class="src-chev">▾</span></summary>
              <div class="detail-src-body">
                <p><b>体攻</b> 英雄基础 + 兵刃/头冠/战靴的体攻 + 战系劫印 + 隐藏职/经文/命痕增益</p>
                <p><b>气血上限</b> 英雄基础 + 装备气血 + 夺系劫印 + 本命法宝/套装 + 劫灰「金蝉余韵」永久加成</p>
                <p><b>护体</b> 装备护体 + 渡/缘系劫印御念 + 套装/经文减伤叠加</p>
                <p><b>身法</b> 装备身法 + 隐系劫印闪避，影响先手与闪避率</p>
                <p><b>愿伤</b> 英雄基础 + 装备/法宝愿伤 + 愿系劫印法伤 + 经文全本加成</p>
                <p><b>御念</b> 装备御念 + 渡/缘系劫印法防</p>
                <p class="src-hint">本面板为聚合后总览；单项来源可点击对应装备、劫印查看其具体加成。</p>
              </div>
            </details>
            ${this.sixDaoRadar(s.fate)}
            ${this.niSutraHtml(s)}
            ${setLine}${resoBlock}${crossResoBlock}${hiddenLine}${petLine}
            <div class="detail-section seal-section">劫印 · 本局封印（破难即落一枚，离局清空）</div>
            <div class="seal-list">
              ${(s.seals && s.seals.length) ? s.seals.map((x) => {
                const dao = NDX.SEAL_DAOTU[x.dao] || { name: x.dao };
                const _tierName = { white: '白', blue: '蓝', gold: '金' }[x.tier] || '';
                // 旧存档/测试注入可能缺 desc：回退到词条真源定义，避免 title="undefined"
                const _sealDesc = x.desc || (NDX.SEAL_WORDS[x.name] && NDX.SEAL_WORDS[x.name].desc) || '';
                return `<span class="seal-chip tier-${x.tier}" title="${_sealDesc}">${_tierName}·${dao.name}·${x.name} +${Math.round(x.val * 100)}%</span>`;
              }).join('') : '<span class="seal-empty">尚未刻下任何劫印</span>'}
            </div>
            <div class="detail-section fate-section">劫印机制 · 本局战斗规则改写（蓝劫起附带，离局清空）</div>
            <div class="seal-list fate-list">
              ${(s.seals && s.seals.some((x) => x && x.mechanism)) ? s.seals.filter((x) => x && x.mechanism).map((x) => {
                const dao = NDX.SEAL_DAOTU[x.dao] || { name: x.dao };
                const _mechDesc = x.mechDesc || x.desc || (NDX.SEAL_WORDS[x.name] && NDX.SEAL_WORDS[x.name].desc) || '';
                return `<span class="fate-chip tier-${x.tier}" title="${_mechDesc}">${dao.name}·${x.name} · 机制</span>`;
              }).join('') : '<span class="seal-empty">尚未获得任何劫印机制</span>'}
            </div>
            <button class="opt-btn ghost" data-action="close-modal">关闭</button>
          </div>
        </div>
      </div>`;
    },
  bagDetailModal(s) {
      const _slotLabel = { weapon: '兵刃', armor: '甲胄', head: '头冠', boots: '战靴', treasure: '法宝', pet: '灵宠', component: '灵性' };
      const stat = (e) => {
        const a = e.atk ? `体攻${e.atk}` : '';
        const h = e.hp ? `气血${e.hp}` : '';
        const d = e.dr ? `护体${Math.round(e.dr * 100)}%` : '';
        const ev = e.eva ? `身法${Math.round(e.eva * 100)}%` : '';
        const m = e.matk ? `愿伤${e.matk}` : '';
        const md = e.mdef ? `御念${Math.round(e.mdef * 100)}%` : '';
        const r = e.hpRegen ? `回血${e.hpRegen}` : '';
        const c = e.crit ? `暴击${Math.round(e.crit * 100)}%` : '';
        const cm = e.criMult ? `暴伤+${Math.round((e.criMult - 1) * 100)}%` : '';
        const fa = e.fixAtk ? `破甲${e.fixAtk}` : '';
        const ap = e.armorPen ? `无视甲${Math.round(e.armorPen * 100)}%` : '';
        const sh = e.shieldPct ? `护盾${Math.round(e.shieldPct * 100)}%` : '';
        const re = e.reflect ? `反伤${Math.round(e.reflect * 100)}%` : '';
        const sp = e.spd ? `速+${e.spd}` : '';
        const ls = e.lifesteal ? `吸血${Math.round(e.lifesteal * 100)}%` : '';
        // 灵宠品质与被动标签
        const qNames = ['凡器', '灵器', '宝器'];
        const q = e.quality || 0;
        const qTag = q > 0 ? `·${qNames[q]}` : '';
        const passiveNames = { gold_per_turn: '每战+金', regen: '每战回血', poison: '每回合毒', dragon_aura: '龙息护盾' };
        const pTag = e.petPassive ? `·${passiveNames[e.petPassive] || e.petPassive}` : '';
        return [a, h, d, ev, m, md, r, c, cm, fa, ap, sh, re, sp, ls].filter(Boolean).join(' · ') + qTag + pTag;
      };
      const items = s.equips.map((e) => {
        const mark = e.slot === 'pet' ? '<span class="pet-mark">🐾</span>' : '';
        const sysTag = e.sys === 'yuan' ? '<span class="sys-yuan-tag">愿</span>' : '<span class="sys-ti-tag">体</span>';
        // V8.35 装备对比：同槽位当前生效装备（非宠物）与本件对比，列出增减项
        let cmpLine = '';
        if (e.slot && e.slot !== 'pet') {
          const active = NDX.activeEquipsFor ? NDX.activeEquipsFor(s) : [];
          const cur = active.find((x) => x.id !== e.id && x.slot === e.slot);
          if (cur) {
            const diff = [];
            const f = (a, b, label, pct) => {
              const av = a || 0, bv = b || 0;
              if (av === bv) return;
              const d = av - bv;
              const sign = d > 0 ? '+' : '';
              const unit = pct ? '%' : '';
              diff.push(`<span class="cmp-${d > 0 ? 'up' : 'down'}">${label} ${sign}${pct ? Math.round(d * 100) : d}${unit}</span>`);
            };
            f(e.atk, cur.atk, '体攻', false);
            f(e.hp, cur.hp, '气血', false);
            f(e.matk, cur.matk, '愿伤', false);
            f(e.dr, cur.dr, '护体', true);
            f(e.mdef, cur.mdef, '御念', true);
            f(e.eva, cur.eva, '身法', true);
            f(e.hpRegen, cur.hpRegen, '回血', false);
            if (diff.length) {
              cmpLine = `<div class="bag-cmp"><span class="cmp-title">对·${cur.name}</span>${diff.join(' ')}</div>`;
            } else {
              cmpLine = `<div class="bag-cmp"><span class="cmp-title">对·${cur.name}</span><span class="cmp-eq">持平</span></div>`;
            }
          }
        }
  
        let useBtn = '';
        if (e.treasure) {
          const ch = (e.chargesLeft == null ? (e.charges || 0) : e.chargesLeft);
          const T = NDX.TREASURES && NDX.TREASURES[e.treasureId];
          const phase = T ? T.phase : 'out';
          const inFight = s.pending && s.pending.kind === 'fight';
          const idle = !s.pending || s.pending.kind === 'choices';
          // V8.28：非生效格法宝不可祭出（UI层禁用，逻辑层亦有校验）
          const isActive = NDX.isEquipActive ? NDX.isEquipActive(s, e.id) : true;
          // 战斗中可用法宝（in / both）在战斗内可直接从背包祭出；
          // 取消强制战前选择后，玩家既可在战斗画面法宝栏点击，也可在背包中手动使用。
          const combatOnly = phase === 'in' || phase === 'both';
          const usableNow = (phase === 'out' && idle) || (phase === 'both' && idle) || (combatOnly && inFight);
          const chargeTxt = `<span class="bag-charge">充能×${ch}</span>`;
          if (!isActive) {
            useBtn = `<span class="use-btn disabled">未生效</span>${chargeTxt}`;
          } else if (phase === 'dead') {
            useBtn = `<span class="use-btn disabled">护身·自动</span>${chargeTxt}`;
          } else if (T && T.auto) {
            useBtn = `<span class="use-btn disabled">被动·自动</span>${chargeTxt}`;
          } else if (ch <= 0) {
            useBtn = `<span class="use-btn disabled">灵光已尽</span>${chargeTxt}`;
          } else if (combatOnly && inFight) {
            useBtn = `<button class="use-btn" data-action="use-item" data-id="${e.id}">祭出</button>${chargeTxt}`;
          } else if (combatOnly) {
            useBtn = `<span class="use-btn disabled" title="${T.desc || ''}">战斗用</span>${chargeTxt}`;
          } else if (!usableNow) {
            useBtn = `<span class="use-btn disabled">空闲用</span>${chargeTxt}`;
          } else {
            useBtn = `<button class="use-btn" data-action="use-item" data-id="${e.id}">祭出</button>${chargeTxt}`;
          }
        }
        const tTag = e.treasure ? ' <span class="bag-treasure">法宝</span>' : '';
        // V8.35 法宝道途徽标：完整包裹内显示 dao + 共鸣状态
        let daoTag = '';
        if (e.treasure && e.treasureId) {
          const _T = NDX.TREASURES && NDX.TREASURES[e.treasureId];
          if (_T && _T.dao) {
            const _pDao = NDX.playerDao ? NDX.playerDao(s) : null;
            const _res = _pDao && _pDao === _T.dao;
            daoTag = `<span class="bag-dao${_res ? ' resonate' : ''}" title="${_res ? '与你的主攻道共鸣——克制伤害 ×1.15' : '法宝道途'}">${_T.dao}道</span>${_res ? '<span class="bag-resonate">共鸣</span>' : ''}`;
          }
        }
        // 法宝额外显示效果说明（取自 desc 或 TREASURES 定义），让玩家不用点进详情也知道作用。
        let effectLine = '';
        if (e.treasure && e.treasureId) {
          const T2 = NDX.TREASURES && NDX.TREASURES[e.treasureId];
          const effectText = e.desc || (T2 && T2.desc) || '';
          if (effectText) effectLine = `<div class="bag-effect">${effectText}</div>`;
        }
        let slotBtn = '';
        if (e.slot === 'component') {
          // 升级石：唤醒对应套装隐藏职的资格凭证
          const _stone = NDX.JOB_STONES && NDX.JOB_STONES[e.id];
          if (_stone) {
            slotBtn = `<span class="use-btn comp-active" title="${_stone.set}套装之枢·持有即可唤醒隐藏职">⚡ ${_stone.name}</span>`;
          } else {
            // 套装组件：只有已持有对应升级石时才会激活隐藏职
            const _sj = (NDX.setJobByComp && NDX.setJobByComp(e.id)) || null;
            const _jobName = _sj ? _sj.job : (e.desc || '套装灵性');
            const _unlocked = _sj && s.equips.some((x) => NDX.JOB_STONES && NDX.JOB_STONES[x.id] && NDX.JOB_STONES[x.id].set === _sj.set);
            slotBtn = `<span class="use-btn comp-active" title="${_unlocked ? '套装组件·已唤醒隐藏职，不占装备格' : '套装组件·需对应升级石方可唤醒隐藏职'}" style="${_unlocked ? '' : 'opacity:.7'}">${_unlocked ? '⚡' : '○'} ${_unlocked ? '灵性生效' : '未唤醒'}</span>`;
          }
        } else {
          const inside = NDX.activeEquipsFor ? NDX.activeEquipsFor(s).some((x) => x.id === e.id) : false;
          const kind = NDX._equipKind ? NDX._equipKind(e) : 'gear';
          const cap = NDX.slotCapForKind ? NDX.slotCapForKind(s, kind) : 4;
          slotBtn = `<button class="use-btn slot-toggle${inside ? ' on' : ''}" data-action="bag-equip-toggle" data-id="${e.id}" title="生效格：${inside ? '已生效（点击撤下）' : '置为生效（该类别上限 ' + cap + ' 格）'}">${inside ? '✔ 生效' : '置为生效'}</button>`;
        }
        const iconHtml = NDX.getEquipIconHtml ? NDX.getEquipIconHtml(e, 'bag-equip-icon') : '';
        return `<li>${iconHtml}${mark}${sysTag}<b>${e.name}</b>${tTag}${daoTag} <span class="slot-${e.slot}">[${_slotLabel[e.slot] || e.slot}]</span> ${e.uses ? `<span class="inherit-tag" data-tier="${e.uses}" title="万世剑冢式·家当随世而旧：已历${e.uses}世，此世承${NDX.inheritTierOf ? NDX.inheritTierOf(e.uses).label : ''}（${NDX.inheritTierOf ? Math.round(NDX.inheritTierOf(e.uses).mult * 100) : 100}%），尚可再承 ${NDX.inheritTierOf ? NDX.inheritTierOf(e.uses).left : 0} 世">承 ${Math.round((NDX.inheritTierOf ? NDX.inheritTierOf(e.uses).mult : 1) * 100)}%</span>` : ''} <span class="bag-stat">${stat(e)}</span>${slotBtn}${useBtn}${effectLine}${cmpLine}</li>`;
      }).join('') || '<li class="muted">空空如也</li>';
      const matEntries = s.materials ? Object.entries(s.materials).filter(([, n]) => n > 0) : [];
      const matItems = matEntries.map(([name, n]) => `<li><span class="sys-ti-tag">材</span><b>${name}</b> <span class="bag-stat">×${n}</span></li>`).join('') || '<li class="muted">无材料</li>';
      // —— 劫印（V3 §1.1）——全数自动生效，不占生效格；只展示「道途层数」进度——
      const actN = s.act || 1;
      const _sealDao = (d) => (NDX.SEAL_DAOTU && NDX.SEAL_DAOTU[d]) ? NDX.SEAL_DAOTU[d].name : (d || '印');
      const _tclass = (x) => {
        const m = { white: 'tier-white', blue: 'tier-blue', gold: 'tier-gold', red: 'tier-red' };
        return m[x.tier] || '';
      };
      const sealItems = (s.seals || []).map((x, i) =>
        `<li class="seal-li"><span class="seal-dao">${_sealDao(x.dao)}</span><b class="seal-name">${x.name}</b><span class="seal-val ${_tclass(x)}">+${Math.round((x.val || 0) * 100)}%</span>
          <span class="seal-layer" title="V3 道途层数：白/蓝=1 层、金=2 层、红=3 层；同道累计达 3/6/9/12 自动触发阶段加成">层×${NDX.sealLayerVal ? NDX.sealLayerVal(x.tier) : 1}</span></li>`
      ).join('') || '<li class="muted">尚无劫印——唯破劫难方得其印。</li>';
      // V3 §1.1 砍生效格：劫印全数自动累计，不再有「生效/捺存」手动管理；
      // 展示六道「道途层数」进度（3/6/9/12 阶段碑自动累计于全部持有印）。
      const _AM = { atkPct: '攻', matkPct: '法', hpPct: '血', drPct: '护', eva: '闪', cri: '暴', dr: '减', atk: '攻', matk: '法' };
      const sealDaoRows = ['战', '渡', '缘', '夺', '隐', '逆'].map((d) => {
        const info = NDX.sealBreakInfo ? NDX.sealBreakInfo(s, d) : { dao: d, layer: 0, cur: null, nxtTier: 3 };
        const curTxt = info.cur && Object.keys(info.cur).length ? Object.keys(info.cur).map((k) => `${_AM[k] || k}+${Math.round((info.cur[k] || 0) * 100)}%`).join('、') : '未激活';
        const next = info.nxtTier ? `/${info.nxtTier}` : '/MAX';
        return `<span class="seal-tl-cell ${info.cur && info.layer >= 3 ? 'on' : ''}" title="道途层数 ${info.layer} · 当前：${curTxt}">${d}${info.layer}${next}</span>`;
      }).join('');
      const chapCaps = `装${NDX.gearSlotCap || 4} · 宠${NDX.petSlotCap || 2} · 宝${NDX.treasureSlotCap ? NDX.treasureSlotCap(actN) : 2} · 印全效`;
      return `<div class="scene-overlay bag-overlay" data-action="close-modal">
        <div class="scene-modal bag-modal" data-stop>
          <div class="panel-title"><span class="panel-corner">择</span>完整包裹 · 装备${s.equips.length} / 材料${matEntries.length} · <span class="bag-titlecap">生效格 [${chapCaps}]</span></div>
          <div class="panel-body bag-detail">
            <p class="bag-req">装备/宠物/法宝需在<b>生效格</b>内才提供加成（本地区 ${chapCaps}）；劫印<b>全数自动生效</b>，按道累计「道途层数」（白/蓝=1、金=2、红=3），达 3/6/9/12 自动触发阶段加成，无需任何整理。</p>
            <div class="bag-detail-section">装备</div>
            <ul class="baglist">${items}</ul>
            <div class="bag-detail-section">劫印 · 已刻 ${(s.seals || []).length} 枚（全数自动生效）</div>
            <div class="seal-tierline">道途层数：${sealDaoRows}</div>
            <ul class="baglist">${sealItems}</ul>
            <div class="bag-detail-section">材料</div>
            <ul class="baglist">${matItems}</ul>
            <div class="bag-actions">
              <button class="opt-btn ghost" data-action="open-pet-atlas" title="查看全部 39 形态灵兽的进化路线 / 羁绊 / 获得动机">🐾 灵兽图鉴</button>
              <button class="opt-btn ghost" data-action="open-follower-atlas" title="查看随从名录 / 已收服与可收的妖王随从及其属性">👥 随从名册</button>
              <button class="opt-btn ghost" data-action="close-modal">关闭</button>
            </div>
          </div>
        </div>
      </div>${this.bagSlotPick ? this.bagSlotPickerHtml(s, this.bagSlotPick) : ''}`;
    },
  _splitScenes(text, noSplit) {
      if (!text) return [''];
      if (noSplit) return [String(text).trim()];
      // 优先按「\n」段落切页：一段一页（长卷叙事如金蝉遭贬三段=三页，选项不必等到极末页）。
      const paras = String(text).split(/\n+/).map((p) => p.trim()).filter(Boolean);
      if (paras.length > 1) return paras;
      const parts = text.match(/[^。！？；…]+[。！？；…]?/g) || [text];
      const pages = [];
      for (let i = 0; i < parts.length; i += 2) pages.push(parts.slice(i, i + 2).join('').trim());
      return pages.length ? pages : [text];
    }
});
