// AUTO-GENERATED by _refactor_split.js — domain: misc
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  _guanyinGuide(text, cls) {
      if (!text) return '';
      const figure = (NDX.npcPortraitOf ? NDX.npcPortraitOf('观音菩萨') : '');
      const figHtml = figure
        ? `<img class="gg-figure" src="${figure}" alt="观音菩萨" onerror="this.style.visibility='hidden'"/>`
        : '<span class="gg-figure gg-figure-emoji">🪷</span>';
      return `<div class="guanyin-guide ${cls || ''}">${figHtml}<div class="gg-body"><span class="gg-name">观音菩萨</span><p class="gg-text">${text}</p></div></div>`;
    },
  openSutraBox() {
      const s = (NDX.game && NDX.game.state) || {};
      const mainDao = NDX.playerDao ? NDX.playerDao(s) : null;
      const du = NDX.SUTRA_FULLS || [];
      const ni = NDX.NI_SUTRA_FULLS || [];
      const duFrags = s.sutraFrags || {};
      const niFrags = s.niSutraFrags || {};
      // 方案X1·持诵位：当前持诵全本（渡/逆皆可），诵经技能随其 chantSkill 变更
      const _csId = (s.chantSutra) || null;
      const _csFull = _csId ? (NDX.sutraFullById(_csId) || NDX.niSutraFullById(_csId)) : null;
      const _csSkill = (_csFull && _csFull.chantSkill) || null;
      const card = (f, side, frags, done, pending) => {
        const held = f.frags.filter((fid) => (frags[fid] || 0) >= 1).length;
        const complete = done.indexOf(f.id) >= 0;
        const pend = pending.indexOf(f.id) >= 0;
        const pct = Math.round((held / f.frags.length) * 100);
        // V3 §二 每经道途标签：显示所属道途；与当前主道途一致则高亮（自动路由 ×1.5）
        const _dao = NDX.sutraDaoOf ? NDX.sutraDaoOf(f.id) : null;
        const _daoMain = mainDao && _dao === mainDao;
        const daoTag = _dao ? `<span class="sx-dao${_daoMain ? ' on' : ''}" title="${NDX.sutraDaoName ? NDX.sutraDaoName(f.id) : _dao}道${_daoMain ? ' · 主道途×1.5' : ''}">${_dao}</span>` : '';
        // V3 §二 待投/已投状态：已合成全本 = 已投（自动投入主道生效）；待投 = 已合成未并入（仅防御性出现）
        const routeTag = pend
          ? `<span class="sx-pending-tag">待投 · 将并入主道</span>`
          : (complete ? `<span class="sx-invested-tag">已投 · ${NDX.sutraDaoName ? NDX.sutraDaoName(f.id) : (_dao || '无')}道${_daoMain ? ' ×1.5' : ''}</span>` : '');
        const cells = f.frags.map((fid) => {
          const has = (frags[fid] || 0) >= 1;
          const nm = (side === 'ferry' ? NDX.sutraFragById(fid) : NDX.niSutraFragById(fid));
          return `<span class="sx-cell${has ? ' on' : ''}${complete || pend ? ' done' : ''}" title="${nm ? nm.name : fid}">${has ? (nm ? nm.name : '·') : '？'}</span>`;
        }).join('');
        // 终极经金边：仅华严经（渡）与逆天录（逆）——大经（≥12 片）不通用金边，终极专属
        const isZenith = f.id === 'su_full_huayan' || f.id === 'ni_full_nitian';
        // 方案X1·持诵位：已合成全本可设为持诵；持诵中卡片显示技能名与取下钮
        const _chanting = complete && f.id === _csId;
        const _sk = (complete && f.chantSkill) || null;
        const chantRow = complete
          ? `<div class="sx-chant-row${_chanting ? ' on' : ''}">${
              _chanting
                ? `<span class="sx-chant-now">持诵中 · 诵经=${_sk ? _sk.name : '本命'}</span><button class="opt-btn ghost sx-chant-btn on" data-action="clear-chant-sutra" title="取下持诵，诵经归于本命">取下</button>`
                : `<button class="opt-btn ghost sx-chant-btn" data-action="set-chant-sutra" data-id="${f.id}" title="持诵此经，诵经技能变更为「${_sk ? _sk.name : '本命'}」">设为持诵</button>`
            }</div>`
          : '';
        return `<div class="sx-card${complete ? ' sx-done' : ''}${isZenith ? ' sx-zenith' : ''}">
          <div class="sx-header">${this._sutraIcon(f.id)}<div class="sx-name">${f.name}${isZenith ? ' <span class="sx-zenith-tag">终极</span>' : ''}${daoTag}${routeTag}<span class="sx-count">${held}/${f.frags.length}</span></div>
  </div>
          <div class="sx-cells">${cells}</div>
          <div class="sx-bar"><i style="width:${pct}%"></i></div>
          <div class="sx-desc">${f.desc || ''}</div>
          ${_sk ? `<div class="sx-chant-skill">诵经 · ${_sk.name}：${_sk.desc}</div>` : ''}
          ${chantRow}
        </div>`;
      };
      const duHtml = du.map((f) => card(f, 'ferry', duFrags, s.sutras || [], s.sutraBackpack || [])).join('');
      const niHtml = ni.map((f) => card(f, 'rebel', niFrags, s.niSutras || [], s.sutraBackpack || [])).join('');
      // V3 §二 待投横幅：有已合成未投入主道的经文时提示（自动路由兜底，改道即投入）
      const _route = (NDX.sutraRouteState && NDX.sutraRouteState(s)) || null;
      const _pendN = (_route && _route.pending && _route.pending.length) || 0;
      const _routeBanner = _pendN > 0
        ? `<div class="sx-pending-banner">📜 ${_pendN} 部经文待投——将在下一次改道/定道时自动投入主道途生效</div>`
        : '';
      // 模块八·经匣拼篇阶位：凡3/灵6/真9晋阶，强化诵经（渡）/戾骨献祭（逆）
      const _acc4 = s._sutraPieces || {};
      const _t4 = (side) => { const t = NDX.sutraSideTier ? NDX.sutraSideTier(s, side) : null; return t ? t.label : '未晋阶'; };
      // 方案X1·持诵位横幅：显示当前持诵经与诵经技能，未设则提示
      const chantSlot = `<div class="sx-chant-slot${_csFull ? ' on' : ''}">
          <span class="sx-chant-label">持诵位</span>
          ${_csFull
            ? `<span class="sx-chant-name">${_csFull.name}</span><span class="sx-chant-skill-txt">诵经 · ${_csSkill ? _csSkill.name + '（' + _csSkill.desc + '）' : '本命诵经'}</span><button class="opt-btn ghost sx-chant-clear" data-action="clear-chant-sutra" title="取下持诵，诵经归于本命">取下持诵</button>`
            : `<span class="sx-chant-empty">未设持诵 —— 诵经为本命；在下方已合成全本卡片上「设为持诵」，念什么经，使什么法</span>`}
        </div>`;
      const body = `
        <div class="sutra-box">
          ${_routeBanner}
          ${chantSlot}
          <div class="sx-tabs">
            <button class="sx-tab on" data-sx-tab="du">渡匣 · ${(s.sutras || []).length}/${du.length} 部</button>
            <button class="sx-tab" data-sx-tab="ni">逆匣 · ${(s.niSutras || []).length}/${ni.length} 部</button>
          </div>
          <div class="sx-pane" data-sx-pane="du">
            <p class="muted sx-hint">渡经普适——渡选项/篝火/善缘事件可得；集齐一部即合成全本（属性被动 + 诵经加成）。合成即自动投入主道途生效：本经道途与主道一致 → 效果 ×1.5。经匣拼篇：拣渡 ${_acc4.ferry || 0} 片 · 诵经强化${_t4('ferry')}（凡3/灵6/真9晋阶）。</p>
            <div class="sx-grid">${duHtml}</div>
          </div>
          <div class="sx-pane" data-sx-pane="ni" hidden>
            <p class="muted sx-hint">逆经专属——逆选项/逆道事件可得；单部加成高于渡经。真·《逆天录》锁二周目论道。合成同样自动投入主道途生效（逆经道途：夺/战/逆为主）。经匣拼篇：拣逆 ${_acc4.rebel || 0} 片 · 戾骨献祭强化${_t4('rebel')}（凡3/灵6/真9晋阶）。</p>
            <div class="sx-grid">${niHtml}</div>
          </div>
        </div>`;
      const host = document.getElementById('app');
      if (!host) return;
      const ov = document.createElement('div');
      ov.className = 'scene-overlay sutra-overlay';
      ov.innerHTML = `<div class="scene-modal sutra-modal"><div class="panel-title"><span class="panel-corner">经藏</span>经匣 · 渡/逆双藏</div><div class="panel-body">${body}<button class="opt-btn ghost sx-close" data-action="sutra-box-close">合上经匣</button></div></div>`;
      host.appendChild(ov);
    },
  _stageBar(g, p) {
      const stages = p.monster.stages;
      const totalHp = stages.reduce((a, b) => a + b, 0);
      const cur = p.res.roundsDetail[p.roundIdx] || {};
      const stageNow = cur.stage || 1;
      const segs = stages.map((hp, i) => {
        const pct = Math.max(2, Math.round((hp / totalHp) * 100));
        const cls = i + 1 < stageNow ? 'done' : (i + 1 === stageNow ? 'active' : 'todo');
        const rhythm = (p.monster._bossRhythm && p.monster._bossRhythm[i]) ? `（约 ${p.monster._bossRhythm[i]} 合）` : '';
        return `<div class="stage-seg ${cls}"><div class="stage-seg-fill"></div><span class="stage-seg-txt">第${i + 1}相 ${hp}${rhythm}</span></div>`;
      }).join('');
      const claims = p.stageClaims || [];
      const claimTags = claims.filter(Boolean).map((c, i) =>
        `<span class="stage-claim ${c.manual ? 'manual' : 'idle'}">第${i + 1}相·${c.manual ? '破韧厚赏' : '挂机兜底'}</span>`
      ).join('');
      return `
        <div class="stage-bar">
          <div class="stage-bar-title">两相劫 · 阶段进度（合计 ≤ ${stages.length * 10} 合）</div>
          <div class="stage-segs">${segs}</div>
          ${claimTags ? `<div class="stage-claims">${claimTags}</div>` : ''}
        </div>`;
    },
  _atbBar(p, cur, rd) {
      const ai = (cur && cur.ai) || (rd && rd.ai) || {};
      const pSpd = ai.pSpd || 10, mSpd = ai.mSpd || 10;
      const total = (pSpd + mSpd) || 1;
      const pPct = Math.max(8, Math.round((pSpd / total) * 100));
      const mPct = 100 - pPct;
      const first = ai.first || (pSpd >= mSpd ? 'player' : 'enemy');
      const attrCls = ai.blackMiasma ? 'atk-black' : (ai.atkAttr === '佛光' ? 'atk-buddha' : 'atk-gold');
      const attrTxt = ai.blackMiasma ? '黑瘴（逆道·反伤）' : (ai.atkAttr || '金光');
      // V8.38 战斗节奏优化：显示当前回合数，让玩家感知战斗进度
      const roundNum = (p.roundIdx >= 0 ? p.roundIdx : 0) + 1;
      const totalRounds = (rd && rd.roundsDetail && rd.roundsDetail.length) || '?';
      // V8.40 回合限制：显示狂暴/失败回合，接近狂暴时警告
      const rl = (rd && rd.roundLimit) || (p.res && p.res.roundLimit) || null;
      let roundLimitTxt = '';
      let roundWarnCls = '';
      if (rl) {
        const enrageR = rl.enrageRound || 20;
        const defeatR = rl.defeatRound || 30;
        roundLimitTxt = ` · 狂暴${enrageR}/失败${defeatR}`;
        if (rl.roundEnraged) roundWarnCls = ' round-enraged';
        else if (roundNum >= enrageR - 3) roundWarnCls = ' round-warning';
      }
      // V8.40 战斗UI优化：战斗界面快捷速度切换按钮（1x/2x/3x）
      const _curSpeed = (NDX.ui && NDX.ui.fightSpeed) || (NDX.settings && NDX.settings.fightSpeed) || 1;
      const _speedLocked = !!(NDX.ui && NDX.ui.fightSpeedLocked);
      // 倍速门禁显示：自动战斗/Boss锁速→1x；手动按章节解锁（2x 首地区即用，3x 需第6地区），未解锁置灰
      const _spAct = ((NDX.game && NDX.game.state && NDX.game.state.act) || 1);
      const _spUnlock = (NDX.fightUnlock && NDX.fightUnlock(_spAct)) || {};
      const _autoNow = !!(p && p.autoFight);
      const _spCap = _speedLocked || _autoNow ? 1 : (_spUnlock.speed3 ? 3 : (_spUnlock.speed2 ? 2 : 1));
      const _sp2Locked = _spCap < 2, _sp3Locked = _spCap < 3;
      const _spTip = (v) => _speedLocked ? 'Boss战锁定1倍速'
        : (_autoNow ? '自动战斗固定1倍速' : (v > _spCap ? '第6地区解锁3x' : v + '倍速'));
      const _speedBtns = [1, 2, 3].map((v) => {
        const _lkd = _speedLocked || (v > 1 && (_sp2Locked && v === 2 || _sp3Locked && v === 3));
        return `<button class="atb-speed-btn${_curSpeed === v ? ' active' : ''}${_lkd ? ' locked' : ''}" data-action="set-fight-speed" data-val="${v}" ${_lkd ? 'disabled' : ''} title="${_spTip(v)}">${v}x</button>`;
      }).join('');
      // V8.40 战斗统计：实时显示累计伤害
      const _stats = (p.res && p.res.stats) || null;
      let _statsTxt = '';
      if (_stats && _stats.totalDamage > 0) {
        _statsTxt = `<div class="atb-stats">⚔ ${_stats.totalDamage}${_stats.critCount > 0 ? ` · 暴击${_stats.critCount}` : ''}${_stats.comboCount > 0 ? ` · 连招${_stats.comboCount}` : ''}</div>`;
      }
      return `
        <div class="atb-bar">
          <div class="atb-title${roundWarnCls}">第 <b>${roundNum}</b> / ${totalRounds} 回合${roundLimitTxt} · 行动顺序（<b>${first === 'player' ? '我方先手' : '敌方先手'}</b>）${rl && rl.roundEnraged ? '<span class="round-enraged-tag">⚡狂暴中</span>' : ''}</div>
          ${_statsTxt}
          <div class="atb-speed-bar">${_speedBtns}</div>
          <div class="atb-track">
            <div class="atb-side atb-player ${first === 'player' ? 'first next-action' : ''}">
              <span class="atb-name">我方${first === 'player' ? '<span class="next-arrow">▶</span>' : ''}</span>
              <div class="atb-fill" style="width:${pPct}%"></div>
              <span class="atb-val">速 ${pSpd}</span>
            </div>
            <div class="atb-mid">⇄</div>
            <div class="atb-side atb-enemy ${first === 'enemy' ? 'first next-action' : ''}">
              <span class="atb-name">${first === 'enemy' ? '<span class="next-arrow">◀</span>' : ''}敌</span>
              <div class="atb-fill" style="width:${mPct}%"></div>
              <span class="atb-val">速 ${mSpd}</span>
            </div>
          </div>
          <div class="atb-rule">我方固定优先攻击【血量最低】之敌 · 普攻属性：<b class="${attrCls}">${attrTxt}</b></div>
        </div>`;
    },
  logHtml(s) {
      const lines = s.log.slice(0, 14).map((l) => `<li>${l}</li>`).join('');
      return `<div class="panel-box log"><div class="box-title">纪事</div>
        <ul class="loglist">${lines || '<li class="muted">—</li>'}</ul></div>`;
    },
  _restCampSinBtn(s, _l3, _sinOpen) {
      const C = NDX.CAMP || {};
      const G = NDX.game;
      const cinfo = (G && G.campInfo) ? G.campInfo() : { level: 0, max: 5, bless: null, cost: (C.COST_BASE || 70), gold: 0 };
      const bl = (C.BLESS || []).find((b) => b.key === cinfo.bless);
      const sinU = s.sinUsed || { evil: [], good: [] };
      let h = '';
      if (_l3) h += `<button class="opt-btn rite-opt" data-action="rest-camp">🛕 土地神龛<span class="rite-sub">${cinfo.level}/${cinfo.max} 级 · ${bl ? bl.name : '相未立'} · 添香费 ${cinfo.cost}金</span></button>`;
      if (_sinOpen) h += `<button class="opt-btn rite-opt" data-action="rest-sin">🌑 罪业贸易<span class="rite-sub">妖魔法相/度化功德 · 已获 ${(sinU.evil || []).length}·${(sinU.good || []).length}</span></button>`;
      return h ? `<div class="rite-grid">${h}</div>` : '';
    },
  _hasDropableSutra(s) {
      const f = s.sutraFrags || {}, ni = s.niSutraFrags || {};
      return Object.keys(f).some((k) => f[k] > 0) || Object.keys(ni).some((k) => ni[k] > 0);
    },
  _campBlessBody(s) {
      const C = NDX.CAMP || {};
      const list = (C.BLESS || []).map((b) =>
        `<button class="opt-btn" data-action="camp-bless" data-bless="${b.key}">${b.icon} ${b.name}<span class="rite-sub">${b.desc}</span></button>`).join('');
      return `<p class="trial-text">神龛初立，香火已聚。祈一相，定本局土地神龛所向——此后每级添香皆随此相成长，一局只立一次。</p>
        <div class="opt-cards">${list}</div>
        <button class="opt-btn ghost" data-action="camp-cancel-bless">暂不立相 · 先回土地庙</button>`;
    },
  _srcTips(text) {
      if (!text) return text;
      const map = {
        '高反伤': '命中后妖物反弹裂缝伤害（高反伤词缀）。叠护盾 / 减伤劫印可扛，或抢先击杀。',
        '咒蚀': '持续毒（咒骨词缀）：每回合掉血，无视部分防御。叠法防 / 闪避或速战速决。',
        '封印侵蚀': '亵渎词缀：每回合始流失气血，无视护盾。需速战或靠回血法宝续命。',
        '狂暴': '残血狂暴：攻击暴涨、破绽更少。祭宝打断或提输出抢杀可破。',
      };
      return text.replace(/(〔(高反伤|咒蚀|封印侵蚀|狂暴)〕)/g, (m, full, k) => {
        const tip = map[k] || '';
        return `<span class="dmg-src" title="${tip}">${full}</span>`;
      });
    },
  promoteHtml(pm, s, Z) {
      const C = (Z && Z.CLASSES && Z.CLASSES[pm.dao]) || {};
      const tierCn = ['', '一转', '二转', '三转'][pm.tier] || `Lv.${pm.tier}`;
      const A = C.attrs || {};
      // attrs 键 → 中文标签（含机制型词条）
      const LAB = {
        atkPct: '攻击加成', hpPct: '气血加成', drPlus: '减伤加成', shieldPct: '护盾',
        hpRegen: '气血回复', crit: '暴击', eva: '闪避', sunder: '破甲·削弱敌防',
        lifesteal: '吸血', multi: 'AOE 溅射', bossDmg: '对强敌增伤', oldWound: '旧伤增伤',
        vanish: '幽影闪避', chaos: '乱纲真伤', paradox: '悖逆增伤', evadeLoot: '规避战利增益',
      };
      const keys = Object.keys(A);
      const effects = keys.map((k) => {
        const v = A[k];
        const label = LAB[k] || k;
        // 百分比类显示放大值；机制型词条(≥1 的非百分比如 shieldPct 等)按百分比显示
        const pctKey = ['atkPct','hpPct','drPlus','shieldPct','eva','crit','sunder','lifesteal','multi','bossDmg','oldWound','vanish','chaos','paradox','evadeLoot'];
        const isPct = pctKey.indexOf(k) >= 0;
        const val = isPct ? Math.round((v * 100)) + '%' : ('+' + v);
        return `<li><span class="promote-effect-name">${label}</span><span class="promote-effect-val">${val}</span></li>`;
      }).join('');
      // 三转大额返岁月保留角标
      const t3Badge = pm.t3Year ? `<div class="promote-t3badge">三转之成，可返旅途岁月</div>` : '';
      return `<div class="scene-overlay promote-overlay" data-action="close-modal">
        <div class="scene-modal promote-modal" data-stop>
          <div class="promote-kicker">六 道 专 职 · ${tierCn}</div>
          <div class="promote-head">
            <div class="promote-cls">${pm.dao} · <span class="promote-cls-name">${pm.cls}</span></div>
            <div class="promote-name">${esc(pm.name)}</div>
          </div>
          <div class="promote-path">${pm.dao}道武道已够（道 ${pm.daoCur}/${pm.daoNeed} · 行为 ${pm.behActual}）——转职即成，${s && s.heroName ? s.heroName + '易途' : '易途'}，然徒儿仍在身侧。</div>
          <ul class="promote-effects">${effects || '<li>转职已成，数值随阶渐长</li>'}</ul>
          ${t3Badge}
          <button class="opt-btn promote-confirm" data-action="promote-confirm">跻 身 此 道 ▸</button>
        </div>
      </div>`;
    },
  _warmPortrait(url) {
      if (!url) return;
      if (!NDX._portCache) NDX._portCache = {};
      if (NDX._portCache[url]) return;
      try {
        const i = new Image();
        i.src = url;
        NDX._portCache[url] = i;
      } catch (e) { /* 无 DOM 或非法地址时静默 */ }
    },
  preFightAnim(pa, s) {
      const tier = pa.tier; // mob | elite | boss
      const ph = pa.phase;  // transition | mobEnter | eliteFlash | eliteDrop | eliteAffix | bossReveal | bossAura
      const sceneCls = 'pa-scene-' + (pa.scene || 'wild');
      const showTransition = (ph === 'transition');
  
      // 真实立绘注入（消除入场占位小人）：英雄立绘 + 本场怪物立绘，预加载热身以确保即时显示。
      const heroPort = (s && NDX.game && NDX.game.getHeroPortrait) ? NDX.game.getHeroPortrait() : '';
      const monPort = pa.monsterPortrait || '';
      this._warmPortrait(heroPort);
      this._warmPortrait(monPort);
      const heroStance = heroPort
        ? ` class="pa-hero-stance pa-port" style="background-image:url('${esc(heroPort)}')"`
        : ' class="pa-hero-stance"';
      const monArt = monPort
        ? `<div class="pa-mon-art"><img class="pa-mon-art-img" src="${esc(monPort)}" alt="" onerror="this.closest('.pa-mon-art').style.opacity='0'" /><div class="pa-mon-art-name">${esc(pa.monsterName || '')}</div></div>`
        : '';
  
      // —— 通用：水墨卷帘遮罩过渡（所有档共用，1.2s）——
      const diff = (pa && pa.diff) || 1;
      const curtain = showTransition
        ? `<div class="pa-curtain"><div class="pa-curtain-top"></div><div class="pa-curtain-bot"></div><div class="pa-curtain-fog"></div><div class="pa-curtain-tip">第 ${diff} 难 · ${esc((NDX.TRIAL_LIB && NDX.TRIAL_LIB[diff] && NDX.TRIAL_LIB[diff].name) || '此劫难')}</div></div>`
        : '';
  
      // —— 小怪入场：3 只小妖左右滑入 + 妖气 + 中央 VS + 真实立绘 ——
      const mobEnt = (tier === 'mob' && !showTransition)
        ? `<div class="pa-stage pa-stage-mob">
            ${monArt}
            <div class="pa-hero-side pa-hero-left"><div${heroStance}></div><div class="pa-hero-aura soft"></div></div>
            <div class="pa-mobs">
              <div class="pa-mob pa-mob-l1"></div>
              <div class="pa-mob pa-mob-l2"></div>
              <div class="pa-mob pa-mob-r1"></div>
            </div>
            <div class="pa-vs">V S</div>
            <div class="pa-treasure-preload">${this._preloadTreasures(s)}</div>
          </div>`
        : '';
  
      // —— 精英入场：黑屏红光 → 踏云砸入 → 词缀浮字 + 主角环绕 + 旁白 ——
      const eliteEnt = (tier === 'elite' && !showTransition)
        ? `<div class="pa-stage pa-stage-elite ${ph === 'eliteFlash' ? 'pa-flash' : ''} ${ph === 'eliteDrop' ? 'pa-drop' : ''} ${ph === 'eliteAffix' ? 'pa-afx' : ''}">
            ${ph === 'eliteFlash' ? '<div class="pa-redflash"></div>' : ''}
            ${monArt}
            <div class="pa-elite-wrap"><div class="pa-elite-cloud"></div><div class="pa-elite-body"></div><div class="pa-elite-shake"></div></div>
            <div class="pa-hero-side pa-hero-center"><div${heroStance}></div><div class="pa-hero-aura ${this._heroAuraCls(s)}"></div></div>
            <div class="pa-treasure-preload all">${this._preloadTreasures(s)}</div>
            ${ph === 'eliteAffix' ? `<div class="pa-elite-affix">${(pa.affixes || []).map((a) => `<span class="pa-affix-tag">${a.icon} ${a.name}</span>`).join('') || '<span class="pa-affix-tag">❖ 高韧</span>'}</div><div class="pa-line">此妖身负劫难，需借法宝破局</div>` : ''}
          </div>`
        : '';
  
      // —— Boss 入场：横版立绘从上方降下 → 锁链/烈火炸开 + 韧性双条 + 四角命痕劫印预览 + 锁速提示 ——
      // V8.27 接入横版立绘大图：优先用 m.portrait 渲染 img + 暗色画框；无 portrait 时回退 CSS 抽象半身。
      const _bossPortrait = pa.monsterPortrait || '';
      const _bossName = pa.monsterName || '关隘之主';
      const _bossArt = _bossPortrait
        ? `<div class="pa-boss-art-frame">
            <img class="pa-boss-art" src="${esc(_bossPortrait)}" alt="${esc(_bossName)}" onerror="this.style.visibility='hidden'" />
            <div class="pa-boss-art-mark">关隘之主</div>
            <div class="pa-boss-art-name">${esc(_bossName)}</div>
            <div class="pa-boss-art-watermark-mask"></div>
          </div>`
        : '<div class="pa-boss-half"></div>';
      const bossEnt = (tier === 'boss' && !showTransition)
        ? `<div class="pa-stage pa-stage-boss ${ph === 'bossReveal' ? 'pa-reveal' : ''} ${ph === 'bossAura' ? 'pa-aura' : ''}">
            <div class="pa-sky"></div>
            <div class="pa-boss-far">${_bossArt}</div>
            <div class="pa-boss-runes">${ph === 'bossAura' ? '<div class="pa-chain"></div><div class="pa-fire"></div><div class="pa-buddha"></div>' : ''}</div>
            <div class="pa-hero-side pa-hero-bottom"><div${heroStance}></div><div class="pa-hero-aura ${this._heroAuraCls(s)}"></div></div>
            ${ph === 'bossAura' ? `
              <div class="pa-boss-bars">
                <div class="pa-bar pa-bar-phys"><span>物理韧性</span><i></i></div>
                <div class="pa-bar pa-bar-magic"><span>法术韧性</span><i></i></div>
              </div>
              <div class="pa-mechs-corner">${(pa.mechs || []).map((f) => `<span class="pa-mech" title="${f.mech || ''}">${f.dao || '◈'} ${f.name}</span>`).join('')}</div>
              <div class="pa-seals-corner">${(pa.seals || []).map((sl) => `<span class="pa-sl" title="${sl.kind || ''}">${sl.dao || '✶'} ${sl.name}</span>`).join('')}</div>
              <div class="pa-speed-lock">⏯ 已锁 1× 速　关闭 2× / 3×</div>
            ` : ''}
          </div>`
        : '';
  
      return `<div class="pa-overlay pa-tier-${tier} ${sceneCls}">
          <div class="pa-scene"></div>
          ${curtain}
          ${mobEnt}${eliteEnt}${bossEnt}
        </div>`;
    },
  _preloadTreasures(s) {
      const activeIds = NDX.activeEquipsFor ? NDX.activeEquipsFor(s).map((x) => x && x.id) : [];
      const eqs = (s.equips || []).filter((e) => e.treasure && activeIds.includes(e.id));
      if (!eqs.length) return '<span class="pa-tre-no">无临阵法宝</span>';
      return eqs.map((e) => `<span class="pa-tre ${e.chargesLeft > 0 ? 'on' : 'off'}" title="${e.name}">${e.icon || '☯'}</span>`).join('');
    },
  _heroAuraCls(s) {
      const evil = (s.evil || 0) - (s.good || 0);
      return evil > 0 ? 'demon' : 'buddha';
    },
  playTreasureCast(treasureId) {
      const fx = document.querySelector('.fb-layer-fx');
      if (!fx) return;
      const T = (NDX.TREASURES && NDX.TREASURES[treasureId]) || {};
      const tier = NDX.treasureTier(treasureId);
      const node = document.createElement('div');
      node.className = 'fb-cast fx-cast-' + tier;
      node.innerHTML =
        `<div class="fb-cast-ring"></div>` +
        `<div class="fb-cast-core">${T.icon || '☯'}</div>` +
        `<span class="fb-cast-name">${T.name || '法宝'}</span>`;
      fx.appendChild(node);
      // 0.8s 内结束：720ms 起淡出，820ms 移除，绝不拖沓
      setTimeout(() => { node.classList.add('fb-cast-end'); }, 720);
      setTimeout(() => { if (node.parentNode) node.parentNode.removeChild(node); }, 820);
      // 红色法宝（一局仅一件）：额外全屏水墨法相动画，气势更盛（仍是动画，非长 CG）
      if (tier === 'red') {
        const fax = document.createElement('div');
        fax.className = 'fb-faxiang';
        fax.innerHTML = `<div class="fx-ink"></div><div class="fx-seal">逆</div><div class="fx-name">${T.name || '逆道真器'}</div>`;
        fx.appendChild(fax);
        setTimeout(() => { if (fax.parentNode) fax.parentNode.removeChild(fax); }, 1600);
      }
    },
  openTreasurePopup(treasureId) {
      const _close = () => { const ex = document.querySelector('.fb-tre-popup'); if (ex && ex.parentNode) ex.parentNode.removeChild(ex); };
      _close();
      const s = NDX.game && NDX.game.state; if (!s) return;
      const eq = (s.equips || []).find((e) => e.treasureId === treasureId);
      const T = (NDX.TREASURES && NDX.TREASURES[treasureId]) || {};
      const tier = NDX.treasureTier(treasureId);
      const tierLabel = { white: '白阶', blue: '蓝阶', gold: '金阶', red: '红阶·逆道' }[tier] || tier;
      const eff = T.effect || {};
      const effLines = [];
      if (eff.dmgPct) effLines.push(`重创妖敌约 ${Math.round(eff.dmgPct * 100)}% 气血`);
      if (eff.dmgFlat) effLines.push(`固定重创 +${eff.dmgFlat}`);
      if (eff.healPct) effLines.push(`回护自身约 ${Math.round(eff.healPct * 100)}% 气血`);
      if (eff.capHeal) effLines.push('回满气血（化缘）');
      if (eff.shieldPct) effLines.push(`护盾 +${Math.round(eff.shieldPct * 100)}%`);
      if (eff.weakNext) effLines.push(`削敌来势（下一战 -${eff.weakNext}）`);
      if (eff.save) effLines.push('可破死劫 / 护身保命');
      if (!effLines.length && (T.atk || T.hp || T.matk)) effLines.push(`属性增益：体攻+${T.atk || 0} 气血+${T.hp || 0} 愿伤+${T.matk || 0}`);
      const link = this._treasureLinkage(s, T, eff);
      const _sealMap = { zhan: '战·金光', du: '渡·青魄', yuan: '缘·白丝', duo: '夺·赤煞', yin: '隐·银痕', ni: '逆·黑道' };
      const sealNames = (s.hSeals || []).map((x) => _sealMap[x] || x);
      // V8.26 命痕砍除：本局联动改为「劫印 / 经文」
      const sutraN = (s.niSutras || []).length;
      const sutraFragN = Object.keys(s.niSutraFrags || {}).reduce((a, k) => a + (s.niSutraFrags[k] || 0), 0);
      const html =
        `<div class="fb-tre-popup">` +
          `<div class="ftp-card tier-${tier}">` +
            `<div class="ftp-head"><span class="ftp-icon">${eq ? (eq.icon || '☯') : '☯'}</span><b>${T.name || '法宝'}</b><span class="ftp-tier">${tierLabel}</span></div>` +
            `<div class="ftp-desc">${T.desc || '—'}</div>` +
            `<div class="ftp-sec">临阵效果</div>` +
            `<ul class="ftp-eff">${effLines.map((l) => `<li>${l}</li>`).join('') || '<li>无直接战斗效果</li>'}</ul>` +
            `<div class="ftp-sec">本局联动（劫印 / 经文）</div>` +
            `<div class="ftp-link">劫印：${sealNames.length ? sealNames.join('、') : '无'} ｜ 经文：${sutraN} 部${sutraFragN ? ' / 碎片 ' + sutraFragN : ''}</div>` +
            (link.length ? `<ul class="ftp-eff ftp-link-list">${link.map((l) => `<li>${l}</li>`).join('')}</ul>` : `<div class="ftp-link ftp-no">（与当前劫印 / 经文暂无共鸣）</div>`) +
            `<button class="opt-btn ghost ftp-close" data-tre-popup-close>关闭</button>` +
          `</div>` +
        `</div>`;
      const host = document.querySelector('.fb-layer-fx') || document.body;
      const wrap = document.createElement('div'); wrap.innerHTML = html;
      const node = wrap.firstElementChild;
      host.appendChild(node);
      node.addEventListener('click', (ev) => { if (ev.target.closest('[data-tre-popup-close]')) node.remove(); });
    },
  _treasureLinkage(s, T, eff) {
      const out = [];
      const seals = s.hSeals || [];
      const mechs = (s.seals || []).filter((x) => x && x.mechanism).map((x) => x.mechanism);
      if (seals.includes('zhan') && (eff.dmgPct || eff.dmgFlat || T.atk)) out.push('⚔ 战·金光：体攻类重创 +15%');
      if (seals.includes('ni')) out.push('🌑 逆·黑道：逆道法宝威力 +20%（逆道专属共鸣）');
      if (mechs.includes('killRefreshTreasure')) out.push('☄ 机制·斩将夺机：每击杀一个单位，下战首个操作点法宝免充能');
      if (mechs.includes('hpLossBoostTreasure')) out.push('⚗ 机制·以血养兵：每损失 10% 气血，祭出法宝伤害 +5%');
      if (mechs.includes('lowHpTreasureCdHalf')) out.push('🔥 机制·焚天死战：气血低于 30% 时，法宝冷却减半');
      if (mechs.includes('doubleEvaResetCd')) out.push('🌪 机制·逐风：连续两次闪避，重置一件法宝冷却');
      return out;
    },
  _outTreasureQuickbar(s) {
      const inFight = s.pending && s.pending.kind === 'fight';
      if (inFight) return '';
      const treasures = (s.equips || []).filter((e) => {
        if (!e.treasure) return false;
        const T = NDX.TREASURES && NDX.TREASURES[e.treasureId];
        if (!T || (T.phase !== 'out' && T.phase !== 'both')) return false;
        // V8.28：仅生效格内法宝可在快捷栏祭出
        if (NDX.isEquipActive && !NDX.isEquipActive(s, e.id)) return false;
        return true;
      });
      if (!treasures.length) return '';
      const btns = treasures.map((e) => {
        const ch = (e.chargesLeft == null ? (e.charges || 0) : e.chargesLeft);
        const T = NDX.TREASURES[e.treasureId];
        if (ch <= 0) return `<button class="tq-btn disabled" data-action="use-item" data-id="${e.id}" title="${T.desc || ''}">${e.name}<i>尽</i></button>`;
        return `<button class="tq-btn" data-action="use-item" data-id="${e.id}" title="${T.desc || ''}">${e.name}<i>+${ch}</i></button>`;
      }).join('');
      return `<div id="treasure-quickbar" class="treasure-quickbar"><span class="tq-label">法宝</span>${btns}</div>`;
    },
  _optionGate(o) {
      const g = window.NDX && NDX.game;
      if (g && g._optionGate) return g._optionGate(o);
      const s = g && g.state;
      if (!s) return { locked: false, need: 0, cur: 0, side: null, reasons: [] };
      const f = o && o.fate;
      const reasons = [];
      // V8.26 与 game._optionGate 一致：声道锁定已废除（命痕亦已砍除），不再以命痕/劫印判断 daotu
      if (o && o.ge && o.geVal && o.geVal > 0) {
        const cur = (s.ge && s.ge[o.ge]) || 0;
        if (cur < o.geVal) reasons.push(`「${o.ge}」道行不足（需≥${o.geVal}，当前${cur}）`);
      }
      const side = (f === '渡' || f === '隐') ? 'good' : (f === '战' || f === '夺' || f === '逆') ? 'evil' : null;
      return { locked: reasons.length > 0, reasons, side, need: 0, cur: Math.max(s.good || 0, s.evil || 0) };
    },
  _cleanOptText(t) {
      if (!t) return t;
      return t
        .replace(/[（(]\s*善\s*\+\s*\d+\s*[）)]/g, '')
        .replace(/[（(]\s*恶\s*\+\s*\d+\s*[）)]/g, '')
        .replace(/[（(]\s*善\s*\+\s*[·•]\s*[）)]/g, '')
        .replace(/善\s*\+\s*\d+\s*[·•]?/g, '')
        .replace(/恶\s*\+\s*\d+\s*[·•]?/g, '')
        .replace(/\s*[·•]\s*$/g, '')
        .replace(/\s{2,}/g, ' ')
        .trim();
    },
  mirrorHtml(p) {
      const title = p.title || '业镜';
      const sub = p.sub || '';
      const mid = p.mirrorMeta && p.mirrorMeta.mid;       // 第50层·中阴身
      const broken = p.mirrorMeta && p.mirrorMeta.broken; // 无尽破碎
      const five = p.mirrorMeta && p.mirrorMeta.five;     // 照见五蕴
      const sideTag = (side) => {
        if (side === 'order') return `<span class="mirror-side order">顺 · 秩序</span>`;
        if (side === 'chaos') return `<span class="mirror-side chaos">逆 · 混沌</span>`;
        if (side === 'demon') return `<span class="mirror-side demon">心魔</span>`;
        if (side === 'void') return `<span class="mirror-side void">破碎</span>`;
        return '';
      };
      const opts = (p.opts || []).map((o, i) => `
        <div class="mirror-opt">
          <button class="opt-btn mirror-btn" data-action="mirror-opt" data-idx="${i}">
            ${sideTag(o.side)}
            <span class="mirror-verse">${this._cleanOptText(o.verse || o.text)}</span>
          </button>
          <div class="mirror-reflect">镜中倒影：${o.reflect || '镜面如水，无物映出。'}</div>
        </div>`).join('');
      const note = broken
        ? `<div class="mirror-note">文字与效果皆已错位。天道已疯，你亦成魔——凭直觉去赌。</div>`
        : (five ? `<div class="mirror-note">你携其神装碎片，心魔自现。此非二选一，是照见本心。</div>` : '');
      return `<div class="mirror-overlay ${mid ? 'mirror-mid' : ''}">
        <div class="mirror-scrim"></div>
        <div class="mirror-stage">
          <div class="mirror-glass">
            <div class="mirror-sheen"></div>
            <div class="mirror-figure mirror-figure-back"></div>
            <div class="mirror-title">${title}</div>
            <div class="mirror-sub">${sub}</div>
          </div>
          <div class="mirror-opts">${opts}</div>
          ${note}
          <div class="mirror-foot">— 你看到的每一选项，都是你未来要偿还的债 —</div>
        </div>
      </div>`;
    },
  _cnNum(d) {
      if (d == null) return '';
      const dN = Number(d);
      if (!isFinite(dN) || dN <= 0) return String(d || '');
      const CN = ['零', '一', '二', '三', '四', '五', '六', '七', '八', '九'];
      if (dN < 10) return CN[dN];
      if (dN < 100) {
        const t = Math.floor(dN / 10), o = dN % 10;
        return (t > 1 ? CN[t] : '') + '十' + (o ? CN[o] : '');
      }
      return String(dN);
    },
  _ditingLine(s, p) {
      if (!p || !p.fate) return '';
      let has = false;
      try {
        const act = NDX.activeEquipsFor ? NDX.activeEquipsFor(s) : (s.equips || []);
        has = (act || []).some((e) => e && e.slot === 'pet' && (e.id === 'ditingyou' || e.id === 'diting'));
      } catch (e) {}
      if (!has) return '';
      const daoName = { 渡: '渡', 逆: '逆', 缘: '缘', 战: '战', 夺: '夺', 隐: '隐' };
      const seen = {}; const fates = [];
      (p.opts || []).forEach((o) => { if (o.fate && daoName[o.fate] && !seen[o.fate]) { seen[o.fate] = true; fates.push(daoName[o.fate]); } });
      const cset = {};
      (p.opts || []).forEach((o) => {
        const ee = o.effect || {};
        if (o.goldCost) cset['耗财'] = 1;
        if (ee.hp && ee.hp < 0) cset['耗命'] = 1;
        if (o.battleFlags) cset['争杀'] = 1;
        if (ee.material) cset['得失'] = 1;
      });
      const costs = Object.keys(cset);
      return `<div class="diting-peek">👂 谛听·伏地听真 —— 主命运 <b>${esc(p.fate)}</b> · 六道倾向 ${fates.join(' / ') || '未明'} · 主要代价 ${costs.join(' / ') || '难测'} <span class="diting-note">（仅听其势，不泄其果）</span></div>`;
    }
});
