// AUTO-GENERATED by _refactor_split.js — domain: modals
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  sceneModal(p, title, opts, action, hint) {
      // V8.58 六道直选：取消三分组，六道长横条+悬停观音提示+确认/重新选择
      if (p.sixdaoSelect) {
        return this._sixdaoSelectModal(p, title, opts, action);
      }
      let pages = this._splitScenes(p.text, p.noSplit);
      // V8.27 follow-up：twoStep 模式下把选项强制放到独立的第二页（叙事第一页、选项第二页）。
      if (p.twoStep && opts.length) pages = [pages[0] || '', ''];
      const page = p.page || 0;
      const last = page >= pages.length - 1;
      // 图鉴式「条件」列消费点：把玩家状态交派生函数，才知道某选项当前是否够格
      const _st = (window.NDX && NDX.game && NDX.game.state) || null;
      const pageBody = `<div class="scene-page">${pages[page]}</div>`;
      const navRaw = last
        ? opts.map((o, i) => {
            const al = o.align || (NDX.optAlign ? NDX.optAlign(o) : null);
            const tag = al === 'good' ? `<span class="align-tag good">善</span>`
                      : al === 'evil' ? `<span class="align-tag evil">恶</span>` : '';
            const daoTag = o.daotu ? `<span class="dao-tag">${o.daotu}道</span>` : '';
            const clean = this._cleanOptText(o.text);
            // V8.41 抉择优化：选项文本截断20字（原12字），减少对title悬停的依赖，移动端更友好
            const shortText = clean.length > 20 ? clean.slice(0, 20) + '…' : clean;
            const fullTip = (clean.length > 20 ? clean : '') + (o.tip ? (clean.length > 20 ? ' — ' : '') + o.tip : '');
            const hoverAttr = fullTip ? ` title="${esc(fullTip)}"` : '';
            const tip = o.tip ? `<div class="opt-tip">${esc(o.tip)}</div>` : '';
            const consequence = o.consequence ? `<div class="opt-consequence">\u2696 ${esc(o.consequence)}</div>` : '';
            // V9.67 朝代'eventHint'特色：商朝事件选择有额外提示（显示 fate/effect 摘要）
            let dynHint = '';
            if (!consequence && NDX.dynastyHas && NDX.dynastyHas('eventHint')) {
              const _hints = [];
              if (o.fate) _hints.push(o.fate + '道');
              if (o.effect && o.effect.good) _hints.push('善+' + o.effect.good);
              if (o.effect && o.effect.evil) _hints.push('恶+' + o.effect.evil);
              if (o.effect && o.effect.gold) _hints.push('金+' + o.effect.gold);
              if (o.reward && o.reward.type === 'gear') _hints.push('装备');
              if (o.reward && o.reward.sutra) _hints.push('经文');
              if (_hints.length) dynHint = `<div class="opt-consequence dyn-hint">🔮 巫风提示：${esc(_hints.join(' · '))}</div>`;
            }
            // V9.50：带上下文门控——本难选项全锁时破例放行（防 P0-6 死锁），并标出破例徽记
            const gg = window.NDX && NDX.game && NDX.game._optGateCtx ? NDX.game._optGateCtx(p, o) : this._optionGate(o);
            const g = (gg && gg.locked) ? gg : null;
            if (g) {
              const why = (g.reasons && g.reasons.length) ? g.reasons.join('；') : '未通';
              return `<button class="opt-btn locked" disabled data-idx="${i}"${hoverAttr}>${tag}${daoTag}${shortText}<span class="gate-lock">🔒 ${esc(why)}</span></button>`;
            }
            // V8.16 取消善恶固定路线：移除一周目逆道封锁，逆道选项一周目即可选
            // V8.27 follow-up：若选项带 tip（如第一难姿态说明），用 opt-btn-tip 样式展示获得内容。
            const _esc = (gg && gg.escaped)
              ? `<div class="opt-consequence gate-escape">⚠ 前置未通（${esc(gg.why || '旗标缺失')}）· 为不使前路断绝，此路暂开</div>`
              : '';
            // —— 图鉴「条件 / 后续」两列落地 ——
            // 门槛徽章：只要选项声明了门槛字段就显形；当前不满足时换红标（玩家得知道为什么点不动）
            let condBadge = '';
            if (NDX.optionCondMet) {
              const _c = NDX.optionCondMet(o, _st);
              if (_c && _c.text) {
                condBadge = `<span class="opt-cond${_c.ok ? '' : ' opt-cond-unmet'}">门槛 · ${esc(_c.text)}</span>`;
              }
            }
            // 重刷语义徽章：只有非常态（一次性 / 战斗结束）才标，避免满屏噪音
            let repBadge = '';
            if (NDX.optionRepeatAll) {
              repBadge = NDX.optionRepeatAll(o)
                .filter((_rk) => _rk !== 'repeat')
                .map((_rk) => `<span class="opt-repeat rep-${_rk}">${esc(NDX.OPTION_REPEAT_LABEL[_rk] || _rk)}</span>`)
                .join('');
            }
            return `<button class="opt-btn opt-btn-tip ${o.fight ? 'trial-opt' : ''}" data-action="${action}" data-idx="${i}"${hoverAttr}><div class="opt-main">${tag}${daoTag}${shortText}</div>${condBadge}${repBadge}${_esc}${consequence}${dynHint}${tip}</button>`;
          }).join('')
        : `<button class="opt-btn scene-flip" data-action="scene-next">翻页 ▸　点按继续（${page + 1}/${pages.length}）</button>`;
      const nav = `<div class="opt-cards">${navRaw}</div>`;
      const pager = pages.length > 1 ? `<div class="scene-pager">第 ${page + 1} / ${pages.length} 页</div>` : '';
      const sub = hint ? `<div class="scene-sub">${hint}</div>` : '';
      // 剧情劫难同步教学：第一劫抉择内嵌提示条（不弹窗轰炸，融入劫难叙事）
      let teachBanner = '';
      if (p.teach === 'tutorial') {
        teachBanner = `<div class="teach-banner teach-tutorial">⚔ 教学战 · 三键为凭：攻（普攻）· 经（诵经回血）· 绝（大招，蓄满方可用）</div>`;
      } else if (p.teach === 'trial') {
        teachBanner = `<div class="teach-banner teach-trial">🜂 选择决定劫印，塑造你的流派</div>`;
      } else if (p.teach === 'sixdao' || p.teach === 'sixdao-sub') {
        // V8.5x 六道选择界面：观音弹窗（头像+气泡）说明六道，不阻断原选项
        // V8.5x 观音指点改为点击弹出覆盖层（立绘滑入+气泡动画），原文本选项保持一屏；teachBanner 留空
        teachBanner = '';
      } else if (p.teach === 'combat') {
        teachBanner = `<div class="teach-banner teach-combat">${p.teachText || '⚔ 战斗教学'}</div>`;
      } else if (p.teach === 'jieyin') {
        teachBanner = `<div class="teach-banner teach-jieyin">${p.teachText || '🔯 劫印教学'}</div>`;
      }
      // 8.11 六道命运：劫难节点展示主命运与前后呼应
      const meta = p.fate
        ? `<div class="scene-meta">主命运 · <b class="fate-${p.fate}">${esc(p.fate)}</b>　｜　前后呼应 · <span class="echo">${p.echo ? esc(p.echo) : '—'}</span></div>`
        : '';
      return `<div class="scene-overlay">
        <div class="scene-modal">
          <div class="scene-head"><span class="panel-corner">择</span>${title}${(p.teach === 'sixdao' || p.teach === 'sixdao-sub') ? '<button class="gy-trigger" data-action="gy-popup-open">🪷 观音指点</button>' : ''}</div>
          ${pager}
          <div class="scene-body">${teachBanner}${meta}${this._ditingLine(NDX.game && NDX.game.state, p)}${pageBody}${sub}${nav}</div>
        </div>
        
      </div>`;
    },
  // V8.58 六道直选面板：六道长横条+悬停观音提示+确认/重新选择
  _sixdaoSelectModal(p, title, opts, action) {
    const daoColors = { '战': '#dc143c', '渡': '#4169e1', '逆': '#9932cc', '隐': '#2f4f4f', '夺': '#ff8c00', '缘': '#32cd32' };
    const daoOrder = ['渡', '缘', '战', '夺', '隐', '逆'];
    const sortedOpts = daoOrder.map(d => opts.find(o => o.key === d)).filter(Boolean);

    const optRows = sortedOpts.map((o) => {
      const color = daoColors[o.key] || '#888';
      const tip = o.tip ? esc(o.tip) : '';
      const guanyinTip = o.guanyinTip ? esc(o.guanyinTip) : '';
      const longDesc = o.longDesc ? esc(o.longDesc) : '';
      const label = esc(o.label || o.text || '');
      // 修复：使用原始opts数组中的索引，而不是sortedOpts的索引
      const originalIdx = opts.indexOf(o);
      return `
        <div class="sixdao-row" data-action="sixdao-pick" data-idx="${originalIdx}" style="--dao-color:${color}">
          <div class="sixdao-dao-badge" style="background:${color}">${o.key}</div>
          <div class="sixdao-row-content">
            <div class="sixdao-row-label">${label}</div>
            <div class="sixdao-row-desc">${longDesc}</div>
            <div class="sixdao-row-tip">${tip}</div>
          </div>
          <div class="sixdao-guanyin-tip">${guanyinTip}</div>
          <div class="sixdao-row-arrow">▸</div>
        </div>`;
    }).join('');

    return `
      <div class="scene-overlay">
        <div class="scene-modal sixdao-modal">
          <div class="scene-head"><span class="panel-corner">道</span>${esc(title)}</div>
          <div class="scene-body">
            <div class="sixdao-intro">
              <div class="sixdao-guanyin-avatar">观音</div>
              <div class="sixdao-guanyin-text">观音菩萨：西行万法，归于六道——渡·缘·战·夺·隐·逆。先立一种心念姿态，再于其中选定一道。六道印记决定你的命运、装备与这世界如何回应你；择定一道后，将得对应六道装备升级石，可唤醒套装隐藏职。</div>
            </div>
            <div class="sixdao-rows">${optRows}</div>
            <div class="sixdao-confirm-bar" style="display:none">
              <div class="sixdao-selected-info"></div>
              <div class="sixdao-confirm-btns">
                <button class="opt-btn sixdao-confirm" data-action="sixdao-confirm">✓ 确认选择此道</button>
                <button class="opt-btn ghost sixdao-repick" data-action="sixdao-repick">↺ 重新选择</button>
              </div>
            </div>
            <div class="scene-sub">——八十一难，必历一方证菩提。</div>
          </div>
        </div>
      </div>`;
  }
});