// AUTO-GENERATED by _refactor_split.js — domain: panel
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  panelHtml(s, g, hero) {
      const p = s.pending;
      if (!p) return '';
      let body = '';
      let title = '';
      const _slotLabel = { weapon: '兵刃', armor: '甲胄', treasure: '法宝', pet: '灵宠' };
      const _slotTag = (slot) => `<span class="slot-${slot}">[${_slotLabel[slot] || slot}]</span>`;
      // §留存优化·P1-1：装备稀有度判断（变率强化反馈）
      const _equipRarity = (e) => {
        if (!e) return 'normal';
        if (e.owner) return 'hero';           // 英雄专属
        if (e.set && (e.setTier || 0) >= 1) return 'set';  // 套装基座/成品
        if (e.slot === 'treasure') return 'treasure';       // 法宝
        if (e.chapter && e.chapter >= 3) return 'epic';     // 高阶章节装备
        return 'normal';
      };
      const _rarityTag = (e) => {
        const r = _equipRarity(e);
        const map = {
          hero: '<span class="eq-rarity eq-hero">英雄专属</span>',
          set: '<span class="eq-rarity eq-set">套装</span>',
          treasure: '<span class="eq-rarity eq-treasure">法宝</span>',
          epic: '<span class="eq-rarity eq-epic">稀有</span>',
          normal: ''
        };
        return map[r] || '';
      };
      const _rarityClass = (e) => {
        const r = _equipRarity(e);
        return r === 'normal' ? '' : ' eq-rare-' + r;
      };
      // —— 胜利结算大屏（V8.9）：全屏独立页面，不叠加战斗画面，干净水墨底 ——
      if (p.kind === 'winresult') {
        const nt = p.nodeType || 'mob';
        const ntName = { mob: '小怪', trial: '劫难', elite: '精英', boss: 'BOSS' }[nt] || '战斗';
        const r = p.rewards || {};
        const sealColorMap = { zhan: '金', duo: '赤', yuan: '素', du: '青', yin: '银', ni: '玄' };
        // ① 永久装备 / 合成材料
        const eqHtml = (r.equips && r.equips.length)
          ? r.equips.map((e) => {
              const tier = (NDX.treasureTier && NDX.treasureTier(e.id)) || 'white';
              // 装备/法宝统一走 lootById（覆盖装备池/锻造池/BOSS奖励/法宝库），
              // 避免只查 TREASURES 导致普通装备回退显示内部 id（如 set_weapon_base）
              const T = (NDX.lootById && NDX.lootById(e.id)) || {};
              return `<li class="wr-item wr-eq tier-${tier}"><b>${e.name || T.name || e.id}</b><span class="wr-tier">${tier === 'red' ? '红宝' : tier === 'gold' ? '金宝' : tier === 'blue' ? '蓝宝' : '白宝'}</span></li>`;
            }).join('')
          : '<li class="wr-empty">本场无新装备</li>';
        const matEntries = r.materials ? Object.entries(r.materials) : [];
        const matHtml = matEntries.length
          ? matEntries.map(([k, v]) => `<li class="wr-item wr-mat"><b>${k}</b><span class="wr-x">×${v}</span></li>`).join('')
          : '<li class="wr-empty">本场无材料</li>';
        const eqCol = `<div class="wr-col wr-col-eq"><div class="wr-col-h">永久装备 / 合成材料</div><ul class="wr-list">${eqHtml}${matHtml}</ul><div class="wr-col-note">跨周目保留</div></div>`;
        // ② 货币（V8.26 起取消「本局法宝碎片」列）
        const goldVal = r.gold || 0;
        const curGold = NDX.game.state.gold || 0;
        const goldCol = `<div class="wr-col wr-col-gold"><div class="wr-col-h">灵石</div><div class="wr-gold-big">+${goldVal}</div><div class="wr-col-note">现有 ${curGold}</div></div>`;
        // 节点专属抉择提示
        const choiceHint = {
          mob: '小怪战 · 直接继续爬塔',
          trial: '劫难节点 · 稍后三选一【劫印】',
          elite: '精英战 · 稍后三选一【蓝劫·机制】',
          boss: 'BOSS 战 · 稍后金色法宝 + 金劫印二选一'
        }[nt] || '继续冒险';
        // Boss 专属：本局 BD 复盘 + 转职进度
        let extraHtml = '';
        if (nt === 'boss' && p.bd) {
          const bd = p.bd;
          const sealsTxt = (bd.seals || []).map((x) => sealColorMap[x] || x).join('、') || '无';
          const mechTxt = (bd.seals || []).filter((x) => x && x.mechanism).map((x) => x.name || x).join('、') || '无';
          const redTxt = (bd.red || []).map((e) => (NDX.TREASURES[e.id] || {}).name || e.id).join('、') || '无';
          extraHtml += `<div class="wr-bd"><div class="wr-bd-h">本局 BD 复盘</div>
            <div class="wr-bd-row"><span>核心劫印</span><b>${sealsTxt}</b></div>
            <div class="wr-bd-row"><span>劫印机制</span><b>${mechTxt}</b></div>
            <div class="wr-bd-row"><span>红色法宝</span><b class="wr-red">${redTxt}</b></div></div>`;
        }
        if (p.job && p.job.length) {
          const okJobs = p.job.filter((j) => j.ok);
          if (okJobs.length) {
            extraHtml += `<div class="wr-job wr-job-ok">✦ 转职解锁达成：${okJobs.map((j) => j.name).join('、')}（前往篝火转职）</div>`;
          } else {
            // 显示最接近达成的一条进度
            const near = p.job.slice().sort((a, b) =>
              (b.missingSeals.length + b.missingTrials.length + b.missingHeld.length) -
              (a.missingSeals.length + a.missingTrials.length + a.missingHeld.length))[0];
            if (near) {
              const miss = [];
              if (near.missingSeals.length) miss.push('劫印' + near.missingSeals.map((x) => sealColorMap[x] || x).join('/'));
              if (near.missingTrials.length) miss.push('试炼' + near.missingTrials.join('/'));
              if (near.missingHeld.length) miss.push('已持' + near.missingHeld.join('/'));
              extraHtml += `<div class="wr-job">转职进度 · ${near.name}：尚缺 ${miss.join(' · ') || '无'}</div>`;
            }
          }
        }
        // V9.x 战斗小结：从 res.roundsDetail 聚合本场五维表现（回合/最高一击/识破/爆发/气势峰值），
        // 纯聚合展示，零新状态——小怪一行、精英/Boss 全五维（数据量小，统一全量展示）
        const _sum = (p.res && p.res.roundsDetail && p.res.roundsDetail.length) ? (() => {
          const _rd = p.res.roundsDetail;
          let _maxHit = 0, _shipo = 0, _burst = 0, _momPeak = 0;
          _rd.forEach((dd) => {
            if (dd.pTurn && dd.pTurn.deal > _maxHit) _maxHit = dd.pTurn.deal;
            if (dd.intervention && dd.intervention.shiPo) _shipo++;
            if (dd.intervention && dd.intervention.burstTier > 0) _burst++;
            if ((dd.momentum || 0) > _momPeak) _momPeak = dd.momentum;
          });
          return { rounds: _rd.length, maxHit: _maxHit, shipo: _shipo, burst: _burst, momPeak: _momPeak };
        })() : null;
        const sumHtml = _sum ? `<div class="wr-summary">
          <span class="wr-sum-i"><b>${_sum.rounds}</b>回合</span>
          <span class="wr-sum-i"><b>${Math.round(_sum.maxHit)}</b>最高一击</span>
          <span class="wr-sum-i"><b>${_sum.shipo}</b>识破</span>
          <span class="wr-sum-i"><b>${_sum.burst}</b>爆发</span>
          <span class="wr-sum-i"><b>${_sum.momPeak}</b>气势峰值</span>
        </div>` : '';
        body = `<div class="wr-screen win">
          <div class="wr-cloud wr-cloud-a"></div><div class="wr-cloud wr-cloud-b"></div>
          <div class="wr-title">降妖得胜</div>
          <div class="wr-subtitle">${ntName}战 · 第 ${NDX.game.state.layer} 层</div>
          ${sumHtml}
          <div class="wr-rewards">
            ${eqCol}${goldCol}
          </div>
          ${extraHtml}
          <div class="wr-choice-hint">${choiceHint}</div>
          <button class="btn btn-gold wr-continue" data-action="win-continue">继续</button>
        </div>`;
        // 战斗结算改为弹窗，浮于地图之上，节省手机屏幕空间
        return `<div class="scene-overlay reward-overlay"><div class="scene-modal reward-modal winresult-modal"><div class="panel-title"><span class="panel-corner">择</span>战斗结算</div><div class="panel-body">${body}</div></div></div>`;
      }
      if (p.kind === 'fight') {
        // 战前法宝选择面板已取消：玩家直接进入战斗演出，通过法宝栏/背包手动祭出。
        // 保留以下代码注释以兼容旧逻辑，但不会再被触发（game.js 中 preFight 已固定为 false）。
        // if (p.preFight) { ... }
        // 立绘预加载热身：战斗一旦出现即提前发起图片解码，避免刚进战时立绘空白/占位延迟。
        // 仅表现层优化（Image 缓存），不触碰核心逻辑。
        try {
          this._warmPortrait((NDX.game && NDX.game.getHeroPortrait) ? NDX.game.getHeroPortrait() : '');
          if (p.monster && p.monster.portrait) this._warmPortrait(p.monster.portrait);
        } catch (e) { /* 预加载失败不影响战斗 */ }
        const mMax = p.monster.hp;
        const mPct = Math.max(0, Math.round((p.mHp / mMax) * 100));
        const st2 = g.stats();
        const pMax = st2.ti.maxHp;
        const pPct = Math.max(0, Math.round((p.pHp / pMax) * 100));
        const rd = p.res.roundsDetail;
        const heroName = (NDX.game.state && NDX.game.state.heroId && NDX.HEROES[NDX.game.state.heroId]) ? NDX.HEROES[NDX.game.state.heroId].name : '你';
        const firstHand = rd.length ? rd[0].first : 'player';
        const cur = p.roundIdx >= 0 && p.roundIdx < rd.length ? rd[p.roundIdx] : null;
        // P0-1 击杀判定：上一合火力基准（pBaseDeal）+ 当前可斩红闪（怪物残血 ≤ 基准×0.85）
        const prevRdKill = (p.roundIdx - 1 >= 0 && p.roundIdx - 1 < rd.length) ? rd[p.roundIdx - 1] : null;
        const killBase = (prevRdKill && prevRdKill.pBaseDeal) || 0;
        const killFlash = killBase > 0 && p.mHp > 0 && p.mHp <= killBase * 0.85;
        // 阶段标签（状态机：INTRO → 交锋 → 狂暴 → VICTORY/DEFEAT）
        let stage, line, sub = '';
        let floatP = null, floatM = null; // 飘字：{ txt, type, sub }
        if (p.roundIdx < 0) {
          stage = 'INTRO · 入场对峙';
          line = p.res.intro || '迎敌——';
          sub = firstHand === 'enemy' ? '⚡ 妖物气势更盛 · 抢得先手' : '⚡ 你金睛怒睁 · 占得先机';
        } else if (cur) {
          stage = '第 ' + (p.roundIdx + 1) + ' 合 · 交锋' + (cur.first === 'enemy' ? '（妖先手）' : '');
          if (cur.justEnraged) stage = '第 ' + (p.roundIdx + 1) + ' 合 · 狂暴！';
          line = this._srcTips(cur.narr || '');
          const pt = cur.pTurn, mt = cur.mTurn;
          if (pt) {
            if (pt.dodged) floatP = { txt: '落空', type: 'miss' };
            else floatP = { txt: '-' + pt.deal + (pt.cri ? '！' : ''), type: pt.cri ? 'crit' : 'hit', sub: pt.counter ? ('裂缝反弹 ' + pt.counter) : (pt.dot ? ('裂伤 ' + pt.dot) : '') };
          }
          if (mt) {
            if (mt.dodged) floatM = { txt: '闪避', type: 'miss' };
            else floatM = { txt: '-' + mt.deal, type: 'hurt', sub: mt.absorbed ? ('护盾 ' + mt.absorbed) : (mt.reflect ? ('反震 ' + mt.reflect) : '') };
          }
          const dotStr = (cur.resolve && cur.resolve.dots.length)
            ? ' · ' + cur.resolve.dots.map((d) => (d.tgt === 'p' ? '你' : '妖') + d.kind + ' ' + d.dmg).join(' / ')
            : '';
          sub = `〔第${p.roundIdx + 1}合｜你 ${pt ? pt.deal : 0}｜妖 ${mt ? mt.deal : 0}${dotStr}〕`;
        } else {
          stage = p.win ? 'VICTORY · 胜' : 'DEFEAT · 败';
          line = p.res.conclusion || (p.win ? '妖氛散尽。' : '力竭倒地……');
        }
        const endCls = (p.roundIdx >= rd.length && p.win) ? ' fb-win' : ((p.roundIdx >= rd.length && !p.win) ? ' fb-lose' : '');
        title = p.name; // V8.53：角标 panel-corner 已显「交战」，此处仅留怪名，避免「交战交战」重字
        const fightTreasures = this._fightTreasureBar(s);
        // 剧情劫难同步教学：第一小怪/第一 Boss 内嵌提示（不作独立弹窗轰炸）
        // V8.30 教学战：三键教学（攻/经/绝）
        // V8.5x 新手前三难首战 / 第一章Boss：观音弹窗（头像+气泡），其余沿用旧教学横幅
        // V8.6x 模块一·三键手感：观音首战点破主角键，让玩家开战前知本命节奏（真源 mainKey）
        const _heroRhythmHint = (() => {
          const _hid = (s && s.hero) || 'tangseng';
          const _H = (NDX.HEROES && NDX.HEROES[_hid]) || null;
          if (!_H || !_H.mainKey) return '';
          const _k = { atk: '攻', chant: '经', ult: '绝' }[_H.mainKey] || '攻';
          const _feel = (_H.attackFeel || '').split('：')[0] || '';
          return `且记汝本命——尔主键【${_k}】${_feel ? '，' + _feel : ''}。今习三键，此键为根。`;
        })();
        const _newbieFightTxt = p.teach === 'newbie-fight'
          ? '「此乃西行第一战。底部三键为凭——攻，普攻降妖；经，诵经回血兼伤敌；绝，气势蓄满方放绝招。按气泡指引，先点攻击。」' + _heroRhythmHint
          : p.teach === 'newbie-boss'
            ? '「关隘之主刘洪非同小可。命中涨气势、受重击则落，满势可点『爆发』倾泻；他蓄力重击时会露识破窗口，此刻出手可成暴击。善用三键与法宝。」'
            : null;
        // V8.44 接引使者教学战：逐回合观音气泡（攻→经→绝），与三键气泡保持一致节奏
        let _tutGuide = '';
        if (p.teach === 'tutorial') {
          const _ri = p.roundIdx >= 0 ? p.roundIdx : -1;
          let _g = '';
          if (_ri <= 1) _g = '观音菩萨：「先点【攻】——普攻降妖，观其血线。此獠皮糙肉厚，寻常攻伐难伤其根本。」' + _heroRhythmHint;
          else if (_ri === 2) _g = '观音菩萨：「再点【经】——诵经回血兼伤敌，攻守相济。」';
          else if (_ri >= 4) _g = '观音菩萨：「气势已成——点【绝】放绝招，唯此一击可了断此獠！」';
          else _g = '观音菩萨：「三键为凭——攻守之间，且看气势渐蓄。」';
          _tutGuide = this._guanyinGuide(_g, 'gg-fight');
        }
        const _teachTxt = p.teach === 'tutorial'
          ? '⚔ 教学战 · 三键为凭：攻（普攻）· 经（诵经回血）· 绝（大招，蓄满方可用）'
          : p.teach === 'mob'
          ? '🜂 此妖身死，必落永久装备——多周目仍可携用（肉鸽积累）'
          : p.teach === 'elite'
            ? '👺 精英战 · 此妖身负词缀（高反伤/咒蚀/狂暴等），需速战或针对性应对；战后落蓝劫·机制'
          : p.teach === 'boss'
              ? '👑 关隘之主 · 有韧性双条，阶段切换时须【临阵祭宝】破韧领厚赏；点下方法宝栏按钮手动祭出'
            : null;
        const _teachBanner = _newbieFightTxt
          ? this._guanyinGuide(_newbieFightTxt, p.teach === 'newbie-boss' ? 'gg-fight gg-boss' : 'gg-fight')
          : ((p.teach === 'tutorial' && _tutGuide) ? _tutGuide
              : (_teachTxt ? `<div class="teach-banner teach-${p.teach}">${_teachTxt}</div>` : ''));
        // —— 战斗分层视觉：背景场景 / 劫印机制 / 劫印光带 / 红色法宝光晕 ——
        // V8.26 命痕砍除：原命痕行改为「劫印机制槽」（展示携带机制的劫印，即局内战斗技能）
        const _sealColorMap = { zhan: 'gold', du: 'cyan', yuan: 'white', duo: 'red', yin: 'silver', ni: 'black' };
        const _sealColor = (se) => _sealColorMap[se] || 'gold';
        const sceneCls = (() => {
          if (p.monster && p.monster.scene) return 'fb-bg-' + p.monster.scene;
          if (s.act >= 15) return 'fb-bg-di';
          if (s.act >= 8) return 'fb-bg-ling';
          return 'fb-bg-huang';
        })();
        // V8.5x 劫印系统推迟：第13难前隐藏劫印UI（劫印光带、机制槽、命痕）
        const _sealsUnlocked = (NDX.globalProgress ? NDX.globalProgress(s) : (s.diff || 0)) >= 13;
        const myMechs = _sealsUnlocked ? (s.seals || []).filter((sl) => sl && sl.mechanism).slice(-4)
          .map((sl) => `<span class="fate-icon mech-chip" title="${sl.name} · ${sl.mechDesc || ''}">${sl.name[0] || '印'}</span>`).join('') : '';
        const hSealCls = (s.hSeals || []).map((se) => `seal-${_sealColor(se)}`).join(' ');
        const curShield = cur ? (cur.shieldAfter || 0) : 0;
        const shieldPct = pMax ? Math.min(100, (curShield / pMax) * 100) : 0;
        // 红色法宝（逆道类 bf_ 或本局逆道劫印）→ 全屏淡红专属光晕
        const redActive = ((s.hSeals || []).some((x) => x === 'ni')) ? 'fb-red-on' : '';
        // 十七地区连续地图结构下无旧 s.node 计数；以真实难号（1~81）显示当前战场所处层/难
        const totalLayers = NDX.globalProgress ? NDX.globalProgress(s) : (s.diff || s.layer || 1);
        const hSealAura = _sealsUnlocked ? (s.hSeals || []).map((se) => `<div class="hero-seal-band seal-${_sealColor(se)}"></div>`).join('') : '';
        // 敌方详情（拖拽空白处查看）：全部词缀 + 韧性数值
        const _foeTier = (p.monster && p.monster.tier) || (p.monster && p.monster.boss ? 'boss' : (p.monster && p.monster.type === 'elite' ? 'elite' : 'mob'));
        const _tierLabel = { mob: '小妖', elite: '精英', boss: '关隘之主' }[_foeTier] || '妖';
        const _affixChips = (p.monster && p.monster.affix && p.monster.affix.length)
          ? p.monster.affix.map((a) => {
              const d = (g.NDX && g.NDX.MONSTER_AFFIXES && g.NDX.MONSTER_AFFIXES[a]) || { icon: '❖', name: a, desc: '' };
              return `<div class="fed-affix"><span class="fed-affix-ic">${d.icon || '❖'}</span><div class="fed-affix-tx"><b>${d.name || a}</b><i>${d.desc || ''}</i></div></div>`;
            }).join('')
          : '<div class="fed-none">此妖身无词缀</div>';
        const _toughTxt = (p.monster && p.monster.breakMax)
          ? `${Math.round(p.monster.breakCur || 0)} / ${p.monster.breakMax}`
          : '—（非关隘之主，无韧性条）';
        // V8.49 战斗精灵：预取玩家/敌人精灵层（未注册返回 null → 走原静态立绘）
        const _sprYou = this._spriteLayers('hero', s.hero || (NDX.game.state && NDX.game.state.heroId) || 'tangseng');
        const _sprFoe = (p.monster && this._spriteLayers('foe', p.monster.id || p.monster.name)) || null;
        body = `
          <div class="combat-layout fb-fourlayer ${redActive}${(cur && cur.pDesperate) ? ' fb-desperate-on' : ''}${(cur && cur.intervention && cur.intervention.burst) ? ' fx-slowmo' : ''}">
            ${_teachBanner}
            <!-- 底层：劫难场景静态水墨背景（荒山 / 灵山 / 地府轮换） -->
            <div class="fb-bg ${sceneCls}"></div>
            <!-- V8.59 战斗高潮层：气势爆发/识破/终结时触发慢镜+全屏闪光+大字台词 -->
            ${(cur && cur.intervention && cur.intervention.burst) ? `
              <div class="fx-fullscreen-flash" style="background: radial-gradient(circle, rgba(255,215,0,0.4), rgba(255,100,0,0.2));"></div>
              <div class="fx-climax-text">
                <span class="fx-climax-label">气势爆发</span>
                <span class="fx-climax-sub">${cur.intervention.burstTier >= 3 ? '毁天灭地！' : cur.intervention.burstTier >= 2 ? '气贯长虹！' : '势如破竹！'} -${cur.intervention.burstDmg || 0}</span>
              </div>
            ` : ''}
            ${(cur && cur.intervention && cur.intervention.countered) ? `
              <div class="fx-fullscreen-flash" style="background: radial-gradient(circle, rgba(100,255,100,0.3), rgba(0,200,100,0.15));"></div>
              <div class="fx-climax-text">
                <span class="fx-climax-label">识破成功</span>
                <span class="fx-climax-sub">破绽已露，反击！</span>
              </div>
            ` : ''}
            <!-- 战斗层：左侧我方英雄、右侧敌方怪物，血条/韧性条居中悬浮 -->
            <div class="fb-layer-combat">
              ${this._atbBar(p, cur, rd)}
              <div class="fightbox${endCls}">
                <div class="fb-stage">${stage}</div>
                <div class="fb-arena ${(cur && (cur.mTurn || cur.pTurn)) ? 'screen-shake' : ''}">
                  ${cur && cur.pTurn ? '<div class="attack-slash-line"></div>' : ''}
                  <div class="fb-side you ${cur && cur.first === 'enemy' ? 'fb-defend' : 'fb-strike'} ${hSealCls}">
                    <div class="hero-auras">${hSealAura}</div>
                    <div class="fb-fate-row">${myMechs || '<span class="fate-none">劫印机制·无</span>'}</div>
                    <div class="fb-avatar you ${_sprYou ? 'sprite' : ''} ${cur && cur.pTurn ? 'attack-lunge' : ''} ${cur && cur.mTurn ? 'hit-shake hit-flash hit-recoil' : ''}" style="${_sprYou ? '' : `background-image:url('${(NDX.game && NDX.game.getHeroPortrait) ? NDX.game.getHeroPortrait() : (hero.portrait || '')}')`}">
                      ${_sprYou || ((hero.portrait || (NDX.game && NDX.game.getHeroPortrait && NDX.game.getHeroPortrait())) ? '' : heroName.slice(0, 1))}
                      ${curShield > 0 ? '<div class="hero-shield-veil"></div>' : ''}
                    </div>
                    <span class="fb-name">${heroName}</span>${(p.comboStreak > 1) ? `<span class="fb-combo-streak" title="连续基础攻击计数（连段分层递增）">连${p.comboStreak}</span>` : ''}
                    <div class="hpbar sm"><div class="hpfill you" style="width:${pPct}%"></div>${shieldPct > 0 ? `<div class="hpshield" style="width:${shieldPct}%"></div>` : ''}<span class="hptxt">${Math.max(0, p.pHp)}/${pMax}</span></div>
                    ${(() => {
                      // V8.40 战意/经力系统：显示资源条
                      const zy = p.zhanYi || 0, zyMax = p.zhanYiMax || 10;
                      const jl = p.jingLi || 0, jlMax = p.jingLiMax || 5;
                      const zyPct = Math.max(0, Math.min(100, zy / zyMax * 100));
                      const jlPct = Math.max(0, Math.min(100, jl / jlMax * 100));
                      const jlReady = p.jingLiReady;
                      // P2-1 满而不溢：显示溢流层角标（昂扬×N / 化雨×N）
                      const zyOv = p.zhanYiOverflow || 0;
                      const jlOv = p.jingLiOverflow || 0;
                      return `<div class="fb-resource-bar">
                        <div class="fb-resource zhanyi ${zyOv > 0 ? 'overflow' : ''}" title="战意：攻击叠加，受击清零，每层+3%伤害；满后溢出攒【昂扬】（绝招时每层 +15% 伤害）">
                          <span class="fb-resource-icon">⚔</span>
                          <div class="fb-resource-track"><div class="fb-resource-fill zhanyi-fill" style="width:${zyPct}%"></div></div>
                          <span class="fb-resource-txt">${zyOv > 0 ? `满·昂扬×${zyOv}` : `${zy}/${zyMax}`}</span>
                        </div>
                        <div class="fb-resource jingli ${jlReady ? 'ready' : ''} ${jlOv > 0 ? 'overflow' : ''}" title="经力：诵经积累，满${jlMax}层触发金刚经；满后溢出攒【化雨】（诵经时每层回复 6% 最大气血）">
                          <span class="fb-resource-icon">📜</span>
                          <div class="fb-resource-track"><div class="fb-resource-fill jingli-fill" style="width:${jlReady ? 100 : jlPct}%"></div></div>
                          <span class="fb-resource-txt">${jlReady ? (jlOv > 0 ? `金刚经·化雨×${jlOv}` : '金刚经就绪') : (jlOv > 0 ? `化雨×${jlOv}` : jl + '/' + jlMax)}</span>
                        </div>
                      </div>`;
                    })()}
                    ${floatP ? `<div class="fb-float ${floatP.type}">${floatP.txt}${floatP.sub ? `<i>${floatP.sub}</i>` : ''}</div>` : ''}
                    ${(function(){ const pd = (typeof cur !== 'undefined' && cur && cur.pDebuffs) || (s.pending && s.pending.pDebuffs) || {}; const ks = Object.keys(pd).filter((k)=>pd[k]>0); if(!ks.length) return ''; const D = NDX.PDEBUFF_DEFS||{}; return '<div class="fb-player-status">' + ks.map((k)=>{ const d=D[k]||{}; return '<span class="status-chip pdb-'+k+'" title="'+(d.desc||k)+'">'+(d.icon||'')+(d.name||k)+'</span>'; }).join('') + '</div>'; })()}
                    ${(cur && cur.pDesperate) ? '<div class="fb-desperate" title="绝境·命悬一线（气血≤25%）：此刻击杀妖物，回复10%最大气血并 +2 气势">☠ 绝境 · 以杀止杀</div>' : ''}
                    ${(cur && cur.pKillHeal > 0) ? `<div class="fb-killheal">+${cur.pKillHeal} 击杀回血 · 气势+2</div>` : ''}
                  </div>
                  <div class="fb-clash ${cur ? 'active' : ''}">⚔</div>
                  <div class="fb-side foe ${cur && cur.first === 'player' ? 'fb-defend' : 'fb-strike'}">
                    ${(_foeTier === 'boss' && p.monster && p.monster.portrait)
                      ? `<div class="fb-foe-art">
                          <img class="fb-foe-art-img" src="${esc(p.monster.portrait)}" alt="${esc(p.monster.name || p.name)}" onerror="this.style.visibility='hidden'" />
                          <div class="fb-foe-art-mark">关隘之主</div>
                          <div class="fb-foe-art-watermark-mask"></div>
                        </div>`
                      : `<div class="fb-avatar foe ${_sprFoe ? 'sprite' : ''} ${_foeTier === 'boss' ? 'foe-boss' : _foeTier === 'elite' ? 'foe-elite' : 'foe-mob'} ${cur && cur.pTurn ? 'hit-knockback' : ''}" style="${_sprFoe ? '' : `background-image:url('${(p.monster && p.monster.portrait) || (_foeTier === 'boss' ? 'img/ui/Boss.webp' : _foeTier === 'elite' ? 'img/ui/精英.webp' : 'img/ui/小怪.webp')}')`}">${_sprFoe || ''}${cur && cur.pTurn ? '<div class="hit-burst-particle"></div>' : ''}</div>`}
                    <span class="fb-name">${p.monster && p.monster.name ? p.monster.name : p.name}</span>
                    ${(function(){ const sp = (NDX._bossDebuffSpec && p.monster && NDX._bossDebuffSpec(p.monster.name)) || null; if(!sp) return ''; const dl = (NDX.pdebuffCleanseTreasure && NDX.pdebuffCleanseTreasure(sp.type)) || '对应法宝'; const dn = (NDX.PDEBUFF_DEFS && NDX.PDEBUFF_DEFS[sp.type] && NDX.PDEBUFF_DEFS[sp.type].name)||sp.type; return '<div class="fb-boss-debuff-hint" title="此妖招牌 debuff：'+dn+'——持【'+dl+'】临阵祭出可解">招牌·'+dn+' ｜ 克制·'+dl+'</div>'; })()}
                    ${(() => {
                      // V8.47 敌人头顶的"下一步意图"显示
                      const rd = p.res && p.res.roundsDetail ? p.res.roundsDetail[p.roundIdx] : null;
                      if (!rd) return '';
                      let intentText = '⚔ 攻击';
                      let intentColor = '#ff6b6b';
                      // V9.x 怪物行为引擎意图：guard=铁壁蓄势 / buff=妖气暴涨 / multi=疾风连击 / heal=妖法回春
                      if (rd.mIntent === 'guard') {
                        intentText = '🛡 铁壁蓄势';
                        intentColor = '#5ab4ff';
                      } else if (rd.mIntent === 'buff') {
                        intentText = (rd.mBuffLayers || 0) > 0 ? `🌀 妖气暴涨×${rd.mBuffLayers}` : '🌀 妖气暴涨';
                        intentColor = '#b48cff';
                      } else if (rd.mIntent === 'multi') {
                        const _h = rd.mMultiHits || 3;
                        const _l = rd.mMultiLanded || 0;
                        intentText = `⚡ 疾风连击×${_h}${_l && _l !== _h ? `·中${_l}` : ''}`;
                        intentColor = '#ff9f43';
                      } else if (rd.mIntent === 'heal') {
                        intentText = rd.mHealAmt ? `💚 妖法回春+${rd.mHealAmt}` : '💚 妖法回春';
                        intentColor = '#4ad9a0';
                      } else if (rd.telegraph || rd.mIntent === 'heavy') {
                        intentText = '💥 蓄力重击';
                        intentColor = '#ffd700';
                      } else if (rd.telegraphSoon) {
                        // V9.x 次级预警：下一回合将进入识破窗口（提前一轮揭示蓄力重击，杀戮尖塔式意图预告）
                        intentText = '🌀 妖气凝聚';
                        intentColor = '#b48cff';
                      } else if (rd.justEnraged) {
                        intentText = '🔥 狂暴';
                        intentColor = '#ff4444';
                      } else if (rd.enraged) {
                        intentText = '🔥 狂暴中';
                        intentColor = '#ff6666';
                      }
                      // V9.x 下一回合意图预告（仅 pattern 脚本可预知）：+N 角标，给玩家规划感
                      let nxt = '';
                      if (rd.mNextIntent && rd.mNextIntent !== 'atk') {
                        const _nx = rd.mNextIntent === 'heavy' ? '💥 重击' : rd.mNextIntent === 'guard' ? '🛡 蓄势' : rd.mNextIntent === 'buff' ? '🌀 暴涨' : rd.mNextIntent === 'multi' ? '⚡ 连击' : rd.mNextIntent === 'heal' ? '💚 回春' : rd.mNextIntent;
                        nxt = `<span class="fb-intent-next" title="下一回合意图">→ ${_nx}</span>`;
                      }
                      return '<div class="fb-intent" title="敌人下一步意图"><span class="fb-intent-icon" style="color:' + intentColor + '">' + intentText + '</span>' + nxt + '</div>';
                    })()}
                    ${killBase > 0 ? `<div class="fb-dmgbase" title="按上一合火力基准，本回合约可造成 ${killBase} 伤害（暴击/混沌会使实际更高）">⚔ 基准 ${killBase}</div>` : ''}
                    ${(p.res && p.res.sanxiPhase) ? `<div class="fb-sanxi-phase" title="三戏轮转：白骨精每3回合切换战/渡/逆三相"><span class="sanxi-label">三戏</span><span class="sanxi-cur ${p.res.sanxiIdx === 0 ? 'zhan' : p.res.sanxiIdx === 1 ? 'du' : 'ni'}">${p.res.sanxiPhase}</span>${p.res.sanxiSwitched ? '<span class="sanxi-switch">⚡形态切换</span>' : ''}</div>` : ''}
                    ${(p.monster && p.monster.affix && p.monster.affix.length) ? `<div class="fb-affix">${p.monster.affix.map((a) => { const d = (g.NDX && g.NDX.MONSTER_AFFIXES && g.NDX.MONSTER_AFFIXES[a]) || { icon: '❖', name: a }; return `<span class="affix-chip" title="${d.desc || ''}">${d.icon || ''}${d.name || a}</span>`; }).join('')}</div>` : ''}
                    ${(() => {
                      const _fx = p.combatFx || {};
                      const _b = [];
                      if (_fx.vuln > 0) _b.push(['🩸', '易伤' + _fx.vuln, 'red']);
                      if (_fx.mark > 0) _b.push(['🎯', '标记' + _fx.mark, 'red']);
                      if (_fx.frozen > 0) _b.push(['❄', '冻结' + _fx.frozen, 'blue']);
                      if (_fx.silence > 0) _b.push(['🔇', '沉默' + _fx.silence, 'blue']);
                      if (_fx.armor > 0) _b.push(['🛡', '叠甲' + _fx.armor, 'grey']);
                      if (_fx.qiaoReady) _b.push(['⚡', '奥义就绪', 'gold']);
                      if (!_b.length) return '';
                      return '<div class="fb-foe-status">' + _b.map((x) => '<span class="status-chip ' + x[2] + '" title="' + x[1] + '">' + x[0] + x[1] + '</span>').join('') + '</div>';
                    })()}
                    <div class="hpbar sm enemy${killFlash ? ' killflash' : ''}"><div class="hpfill foe" style="width:${mPct}%"></div><span class="hptxt">${Math.max(0, p.mHp)}/${mMax}${killFlash ? '<b class="fb-killmark">☠可斩</b>' : ''}</span></div>
                    ${(() => {
                      // P1-1 随从（精英/Boss 前置肉盾）：显示独立随从血条 + 破胆标记
                      const mn = (cur && (cur.minionMax > 0)) ? cur : (((p.res && p.res.minion) && p.res.minion.max > 0) ? { minionHp: p.res.minion.cur, minionMax: p.res.minion.max, minionBroken: p.res.minion.broken } : null);
                      if (!mn) return '';
                      const mpct = Math.max(0, Math.min(100, (mn.minionHp || 0) / mn.minionMax * 100));
                      return `<div class="fb-minion${mn.minionBroken ? ' broken' : ''}" title="随从妖：先行挡刀，破胆（血尽）后攻势长驱直入打本体">
                        <span class="fb-minion-icon">🛡</span>
                        <div class="fb-minion-track"><div class="fb-minion-fill" style="width:${mpct}%"></div></div>
                        <span class="fb-minion-txt">${mn.minionBroken ? '💥 破胆' : Math.max(0, mn.minionHp) + '/' + mn.minionMax}</span>
                      </div>`;
                    })()}
                    ${(p.monster && p.monster.breakMax && p.monster.breakMax > 0) ? (() => {
                      const m = p.monster;
                      const cur = Math.max(0, m.breakCur || 0);
                      const pct = Math.max(0, Math.min(100, cur / m.breakMax * 100));
                      const need = m.breakWith || null;
                      const needT = need && NDX.TREASURES && NDX.TREASURES[need];
                      const haveRight = need ? (s.equips || []).some((eq) => eq.treasureId === need && eq.chargesLeft > 0) : true;
                      const stageInfo = (m.stages && m.stages.length > 1) ? (() => {
                        // m.stages 为各阶段血量阈值数组（递减），当前所处阶段 = 首个 p.mHp 仍高于下一阶段阈值的阶段
                        let idx = m.stages.length - 1;
                        for (let i = 0; i < m.stages.length - 1; i++) { if (p.mHp > m.stages[i + 1]) { idx = i; break; } }
                        return `<span class="fb-tough-stage">第 ${idx + 1}/${m.stages.length} 劫</span>`;
                      })() : '';
                      return `<div class="fb-toughness ${p.awaitStageBreak > 0 ? 'broken' : ''} ${haveRight ? 'have-right' : 'no-right'} ${((s.evil||0)-(s.good||0))>0 ? 'red' : 'gold'}">
                        <div class="fb-tough-label">业障槽 ${Math.round(cur)}/${m.breakMax}${stageInfo}</div>
                        <div class="fb-tough-track"><div class="fb-tough-fill" style="width:${pct}%"></div>${pct >= 90 ? '<span class="fb-tough-edge"></span>' : ''}</div>
                        ${need ? `<div class="fb-tough-need ${haveRight ? 'ok' : 'bad'}">需持【${needT ? needT.name : need}】破韧</div>` : ''}
                      </div>`;
                    })() : ''}
                    ${floatM ? `<div class="fb-float ${floatM.type}">${floatM.txt}${floatM.sub ? `<i>${floatM.sub}</i>` : ''}</div>` : ''}
                  </div>
                </div>
                ${cur && cur.justEnraged ? `<div class="fb-enrage">妖目赤红 · 狂暴！攻势 ×1.5</div>` : ''}
              </div>
            </div>
            <!-- UI 交互层：顶部状态栏 + 中间飘字 + 底部法宝栏 -->
            <div class="fb-layer-ui">
              <div class="fb-topbar">
                <div class="fb-top-left">
                  <div class="fb-avatar-sm" style="${hero.portrait ? `background-image:url('${hero.portrait}')` : ''}">${hero.portrait ? '' : heroName.slice(0, 1)}</div>
                  <div class="fb-hpwrap">
                    <div class="fb-hp-top">${Math.max(0, Math.round(p.pHp))}/${pMax}</div>
                    <div class="hpbar sm fb-top-hp"><div class="hpfill you" style="width:${pPct}%"></div>${shieldPct > 0 ? `<div class="hpshield" style="width:${shieldPct}%"></div>` : ''}</div>
                    ${curShield > 0 ? `<div class="fb-shield-tip">🛡 护盾 ${Math.round(curShield)}</div>` : ''}
                  </div>
                </div>
                <div class="fb-top-mid">
                  <div class="fb-mid-line">☷ 六道劫 · 第 <b>${totalLayers}</b> 层</div>
                  <div class="fb-mid-line">劫印 <b class="fb-mid-fates">${(s.seals || []).length}</b> · 机制 <b>${(s.seals || []).filter((x) => x && x.mechanism).length}</b></div>
                </div>
                <div class="fb-top-right">
                  <div class="fb-speed-mini">
                    <button class="speed-btn ${this._spActive(1)}" data-action="fight-speed" data-speed="1" title="${this._spTip(1)}">1x</button>
                    <button class="speed-btn ${this._spActive(2)}" data-action="fight-speed" data-speed="2" ${this._spLockedFor(2)} title="${this._spTip(2)}">2x</button>
                    <button class="speed-btn ${this._spActive(3)}" data-action="fight-speed" data-speed="3" ${this._spLockedFor(3)} title="${this._spTip(3)}">3x</button>
                  </div>
                  <button class="opt-btn ghost fb-pause-btn" data-action="fight-toggle-pause" title="暂停 / 继续">${NDX.ui.fightPaused ? '▶' : '⏸'}</button>
                  <button class="opt-btn ghost fb-flee-btn" data-action="op-flee" title="逃跑">🏃</button>
                  <div class="fb-round-mini">回合 <b>${p.roundIdx + 1}/${rd.length}</b></div>
                </div>
              </div>
              <div class="fb-fx-floats" data-fx-floats></div>
              ${this._activeSkillBar(s, p)}
              <div class="fb-bottombar">
                <p class="fb-narr">${line}</p>
                ${sub ? `<p class="fb-sub">${sub}</p>` : ''}
                ${this._fightTreasureBar(s)}
                <div class="fb-bottom-actions">
                  ${_foeTier === 'boss' ? `<button class="opt-btn ghost fb-slow-btn" data-action="op-slow">⏱ 慢放韧性破局</button>` : ''}
                  ${(p.roundIdx < rd.length && (!NDX.fightUnlock || NDX.fightUnlock(((s && s.act) || 1)).skip))
                    ? `<button class="opt-btn ghost fb-skip-btn" data-action="fight-skip">⏩ 跳过</button>` : ''}
                </div>
                ${p.awaitOp > 0 ? this._opPointPanel(g, p, rd[p.awaitOp - 1]) : ''}
                ${p.awaitStageBreak > 0 ? this._stageBreakPanel(g, p) : ''}
              </div>
              <!-- 敌方详情（拖拽空白处查看全部词缀 / 韧性数值） -->
              <div class="fb-enemy-detail" data-enemy-detail hidden>
                <div class="fed-head">${p.name} <span class="fed-tier">${_tierLabel}</span></div>
                <div class="fed-stats">
                  <div class="fed-row"><span class="fed-k">气血</span><span class="fed-v">${Math.max(0, Math.round(p.mHp))} / ${mMax}</span></div>
                  <div class="fed-row"><span class="fed-k">韧性</span><span class="fed-v">${_toughTxt}</span></div>
                </div>
                <div class="fed-k">词缀（${p.monster && p.monster.affix ? p.monster.affix.length : 0}）</div>
                <div class="fed-affixes">${_affixChips}</div>
                <div class="fed-hint">↔ 拖拽空白处关闭</div>
              </div>
            </div>
            <!-- 特效层：法宝释放 / 闪避 / 暴击 / 反伤全屏粒子（优先级最高） -->
            <div class="fb-layer-fx ${redActive}">
              <div class="fb-red-glow"></div>
            </div>
            <!-- 台词层：英雄 / Boss 台词气泡（轻量不阻塞） -->
            <div class="fb-line-layer"></div>
          </div>`;
        return `<div class="scene-overlay combat-overlay ${((s.evil || 0) - (s.good || 0)) <= 0 ? 'fb-normal' : ''}"><div class="scene-modal combat-modal"><div class="panel-title"><span class="panel-corner">交战</span>${title}</div><div class="panel-body">${body}</div></div></div>`;
      }
      if (p.kind === 'curse-pick') {
        // P0-3 西行劫难词条·开局自择咒缚：通关解锁——选 1~3 条负面条件，战后碎金按倍率放大
        title = '西行劫难 · 自择咒缚';
        const sel = p.sel || [];
        const _mul = NDX.curseRewardMul ? NDX.curseRewardMul(sel) : 1;
        const _cards = (NDX.CURSE_ORDER || []).map((cid, i) => {
          const d = NDX.CURSE_TABLE && NDX.CURSE_TABLE[cid];
          if (!d) return '';
          const on = sel.indexOf(cid) >= 0;
          const locked = !on && sel.length >= 3;
          return `<button class="opt-btn curse-card${on ? ' on' : ''}${locked ? ' locked' : ''}" data-action="curse-toggle" data-idx="${i}"${locked ? ' disabled' : ''}>
            <b>${d.icon} ${d.name}</b><span class="rite-sub">${d.desc}</span>
            <span class="curse-mul">碎金 ×${(1 + (d.mul || 0)).toFixed(2)}</span>
          </button>`;
        }).join('');
        const selTxt = sel.length
          ? sel.map((c) => { const d = NDX.CURSE_TABLE && NDX.CURSE_TABLE[c]; return d ? d.name : c; }).join('、')
          : '（未选）';
        body = `<div class="scene-body">
          <div class="curse-intro">已通关一世，西行可再添劫数以偿重酬：自择 1~3 条<b>咒缚</b>，此世处处险阻，但战后<b>碎金</b>按倍率放大。正途西行亦可——佛门本不求险中求利。</div>
          <div class="curse-grid">${_cards}</div>
          <p class="curse-status">已择咒缚（${sel.length}/3）：${selTxt} → 战后碎金 <b class="fb-killmark">×${_mul.toFixed(2)}</b></p>
          <div class="opt-cards">
            <button class="opt-btn curse-go" data-action="curse-pick-opt"${sel.length ? '' : ' disabled'}>启程受缚（${sel.length} 条 · 碎金 ×${_mul.toFixed(2)}）</button>
            <button class="opt-btn ghost" data-action="curse-pick-skip">正途西行 · 不取咒缚</button>
          </div>
        </div>`;
      } else if (p.kind === 'choices') {
        title = '岔路在前';
        const chint = p.craftHint ? `<p class="craft-hint">🜂 套装进度：${p.craftHint}</p>` : '';
        // 用户要求：取消「点地图上高亮节点继续西行」整块 UI，简化界面——空闲抉择态不再渲染任何占位面板；
        // 仅当有实质内容（套装进度提示）时保留。真实分支/路线选择由地图节点点击（data-action=node）承担。
        if (!p.craftHint) return '';
        body = chint;
      } else if (p.kind === 'rest') {
        title = '土地庙';
        // 篝火献祭取舍系统（《体系补全》·一阶）：以「气血」等资源做不可逆交换
        const rites = (g.NDX && g.NDX.riteList) ? g.NDX.riteList(s) : [];
        const riteBtns = rites.map((r) => {
          const act = 'rite-' + r.id;
          const cls = 'opt-btn rite-opt';
          if (r.disabled) {
            return `<button class="${cls} disabled" disabled title="${r.why}">${r.icon} ${r.name}（${r.costText}）<span class="rite-sub">${r.why}</span></button>`;
          }
          return `<button class="${cls}" data-action="${act}">${r.icon} ${r.name}<span class="rite-sub">${r.desc}</span></button>`;
        }).join('');
        // 土地庙精简（V8.41）：首章仅保留 歇息回血 / 装备组合；劫印自动生效只看「道途层数」
        // 淬炼、献祭、土地神龛 第3章解锁；罪业贸易 第3章 + 善恶达标才开放
        const _l3 = (s.act || 0) >= 3;
        const _sins = (g && g.sinInfo) ? g.sinInfo() : null;
        const _sinOpen = _l3 && !!(_sins && _sins.unlocked);
        const _restTeach = p.firstRest ? `<div class="teach-banner teach-rest">⛩ 土地庙：歇息（回血+上限）· 装备组合。更多便利将随西行章节逐级开启。</div>` : '';
        body = _restTeach + `<p class="trial-text">残碑半掩，香灰尚温。你于 ${p.node.name} 暂得喘息——歇息回元、淬器精进，皆在此择。家当不经磨损、无需打磨——器物之旧唯系于轮回多寡，此世随行的传承神器各携前世痕。</p>` +
          `<button class="opt-btn" data-action="rest-opt" data-opt="rest">歇息（气血回满，上限 +120，法宝充能补满）</button>` +
          `<div class="rite-grid">
            <button class="opt-btn rite-opt" data-action="rest-opt" data-opt="combine">⚒ 装备组合<span class="rite-sub">组合件/升级件 → 进阶装备</span></button>
            <button class="opt-btn rite-opt" data-action="rest-opt" data-opt="reflux"${p._refluxTried ? ' disabled' : ''}>🔮 遗珠回流<span class="rite-sub">极低概率拾得失落散宝</span></button>
          </div>` +
          (p._refluxTried ? `<p class="shrine-hint">此番已探过遗珠，离庙再入可再探。</p>` : '') +
          (s._autoCombineMade ? (s._autoCombineMade.length ? `<p class="shrine-hint">⚒ 自动合成已熔铸：${s._autoCombineMade.join('、')}</p>` : `<p class="shrine-hint">⚒ 自动合成：当前行囊无可合成之材料。</p>`) : '') +
          (_l3 ? `<button class="opt-btn" data-action="rest-opt" data-opt="forge">淬炼精进（选一件装备升至二阶）</button>` : '') +
          (_l3 ? `<div class="rite-grid">${riteBtns}</div>` : '') +
          this._restCampSinBtn(s, _l3, _sinOpen) +
          (this._hasDropableSutra(s) ? `<button class="opt-btn rite-opt" data-action="rest-opt" data-opt="sutra-drop">📜 释经<span class="rite-sub">放下残片换碎金 · 冗余触发经尘回向</span></button>` : '') +
          ((s.seals || []).length ? `<button class="opt-btn rite-opt" data-action="rest-opt" data-opt="seal-drop">🔴 弃印<span class="rite-sub">放下劫印换碎金 · 非主道触发道印回向</span></button>` : '') +
          `<p class="shrine-hint">🗡 装备、灵宠、法宝按<b>生效格</b>整理；劫印全部<b>自动生效</b>、不占格，按道累计「道途层数」。</p>` +
          `<button class="opt-btn ghost" data-action="rest-opt" data-opt="leave">→ 离庙续行</button>`;
      } else if (p.kind === 'tudi-choice') {
        // #64 刘洪后首个土地庙：三选一引导（套装自动组合/打坐回寿），选完即退出
        title = '土地庙 · 观音指引';
        const _mt = (NDX.LIFE && NDX.LIFE.MEDITATE_REGAIN) || 0;
        const body = `
          <div class="scene-body">
            <div class="guanyin-guide gg-msg"><div class="gg-body"><span class="gg-name">观音菩萨</span><p class="gg-text">金蝉，刘洪已伏，前路尚遥。此庙有两般便利，你只可取其一——取毕即行，莫要留恋：</p></div></div>
            <div class="opt-cards tudi-choice-grid">
              <button class="opt-btn tudi-opt" data-action="tudi-choice" data-opt="combine"><b>⚒ 套装自动组合</b><span class="rite-sub">熔铸行囊中可合之链，成进阶装备</span></button>
              <button class="opt-btn tudi-opt" data-action="tudi-choice" data-opt="meditate"><b>🧘 打坐回寿</b><span class="rite-sub">残香下打坐，寿元 +${_mt}</span></button>
            </div>
          </div>
          <div class="scene-nav"><span class="shrine-hint">择一即行 · 观音傍观</span></div>`;
        return `<div class="scene-overlay"><div class="scene-modal"><div class="scene-head"><span class="panel-corner">庙</span>${title}</div>${body}</div></div>`;
      } else if (p.kind === 'sin') {
        title = '罪业贸易 · 一角幽冥，一角莲台';
        body = this._sinPanelBody(s);
      } else if (p.kind === 'camp') {
        title = '土地神龛';
        body = this._campPanelBody(s);
      } else if (p.kind === 'camp-bless') {
        title = '土地神龛 · 立龛相';
        body = this._campBlessBody(s);
      } else if (p.kind === 'forge') {
        title = '土地庙 · 淬炼精进';
        body = `<p class="trial-text">择一件随身之物，于香火中淬炼——属性精进，二阶可期（每件仅可一次）。</p>` +
          `<div class="opt-cards">${p.items.map((e) =>
            `<button class="opt-btn equip" data-action="forge" data-id="${e.id}">
              <b>${e.name}</b> ${_slotTag(e.slot)} ${e.desc}</button>`
          ).join('')}</div>` +
          `<button class="opt-btn ghost" data-action="rest-opt" data-opt="leave">不淬了</button>`;
      } else if (p.kind === 'sutra-drop') {
        // P2-2 释经（StS 删卡式精简）：择一片残片放下，换碎金；冗余片触发经尘回向
        title = '土地庙 · 释经';
        const _fragRow = (side, frags, fragById, doneArr, goldBase, goldRed, label) => {
          const rows = Object.keys(frags).filter((fid) => frags[fid] > 0).map((fid) => {
            const frag = (fragById && fragById(fid)) || { sutra: fid, name: fid, note: '残经' };
            const fullId = side === 'ferry' ? 'su_full_' + frag.sutra : frag.sutra;
            const full = (side === 'ferry' ? NDX.sutraFullById(fullId) : NDX.niSutraFullById(fullId)) || { name: fullId };
            const done = (doneArr || []).indexOf(fullId) >= 0;
            const gold = done ? goldRed : goldBase;
            return `<button class="opt-btn sutra-drop-btn ${done ? 'redundant' : ''}" data-action="sutra-drop-pick" data-side="${side}" data-fid="${fid}">
              <span class="sutra-seg">${label} · ${frag.name || fid}${frags[fid] > 1 ? ` ×${frags[fid]}` : ''}</span>
              <b>《${full.name}》残片</b>
              <span class="rite-sub">${done ? '全本已得·冗余释经 → 香火化金 +' + gold + '（触发经尘回向）' : '放下换碎金 +' + gold + ''}</span></button>`;
          });
          return rows.length ? rows.join('') : '';
        };
        const _ferryRows = _fragRow('ferry', s.sutraFrags || {}, NDX.sutraFragById, s.sutras || [], 8, 16, '渡经残片');
        const _niRows = _fragRow('ni', s.niSutraFrags || {}, NDX.niSutraFragById, s.niSutras || [], 12, 24, '逆经残片');
        const _empty = (!_ferryRows && !_niRows) ? '<p class="shrine-hint">行囊中并无残片可放下——经文之缘，尚在途中。</p>' : '';
        body = `<p class="trial-text">残经既拾，便与你有缘；然身负过多，反碍前行。择一片残片放下，香火化金，轻装再行——若全本已合，冗余之经更将回向未竟之卷。</p>` +
          (_ferryRows ? `<div class="rite-grid sutra-drop-grid"><div class="seal-bar-title">渡经残片</div>${_ferryRows}</div>` : '') +
          (_niRows ? `<div class="rite-grid sutra-drop-grid"><div class="seal-bar-title">逆经残片</div>${_niRows}</div>` : '') +
          _empty +
          `<button class="opt-btn ghost" data-action="rest-opt" data-opt="leave">暂不释经</button>`;
      } else if (p.kind === 'seal-drop') {
        // P2-2 弃印（StS 删卡式精简）：择一枚劫印放下，换碎金；非主道触发道印回向
        title = '土地庙 · 弃印';
        const _mainDao = (NDX.DaoSystem && NDX.DaoSystem.getMainDao) ? NDX.DaoSystem.getMainDao(s) : null;
        const _sealRows = (s.seals || []).map((sl, i) => {
          const tierLbl = (NDX.SEAL_TIER_LABEL && NDX.SEAL_TIER_LABEL[sl.tier]) || sl.tier;
          const gold = (NDX.SEAL_TIER_GOLD && NDX.SEAL_TIER_GOLD[sl.tier]) || 8;
          const offDao = _mainDao && sl.dao !== _mainDao;
          return `<button class="opt-btn seal-drop-btn" data-action="seal-drop-pick" data-idx="${i}">
            <span class="seal-dao">${sl.dao}道</span>
            <b class="seal-name">${tierLbl}「${sl.name}」</b>
            <span class="rite-sub">放下换碎金 +${gold}${offDao ? ' · 非主道 → 触发道印回向' : ''}</span></button>`;
        }).join('');
        const _empty = !(s.seals || []).length ? '<p class="shrine-hint">行囊中并无劫印可放——印随道心，尚无冗余。</p>' : '';
        body = `<p class="trial-text">劫印刻的是你走过的道。若印多而道窄、心有所滞，不妨放下一枚——香火化金，道印回向：非主道之印放下时，道心反哺主道同阶之印。</p>` +
          (_sealRows ? `<div class="opt-cards">${_sealRows}</div>` : '') +
          _empty +
          `<button class="opt-btn ghost" data-action="rest-opt" data-opt="leave">暂不弃印</button>`;
      } else if (p.kind === 'trial-result') {
        // 劫难抉择即时反馈：短剧情文案 + 本局变化提示（剧情+玩法双向绑定）
        title = `劫落 · ${p.title}`;
        const body = `
          <div class="scene-body">
            <div class="teach-banner teach-trial">🜂 此念既落，难度与机缘已随之改写</div>
            <div class="scene-page">${p.body}</div>
          </div>
          <div class="scene-nav">
            <button class="opt-btn scene-flip" data-action="trial-result-ok">受此业 ▸</button>
          </div>`;
        return `<div class="scene-overlay"><div class="scene-modal"><div class="scene-head"><span class="panel-corner">择</span>${title}</div>${body}</div></div>`;
      } else if (p.kind === 'guanyin-msg') {
        // 观音偈语（寿命教学 / 刘洪战前引导 / 土地庙首入引导）：
        //  此前该 kind 无渲染分支——会静默吞掉面板，玩家只见中部空白、地图节点全部不可点＝"卡死"。
        //  补上独立场景层，按钮 data-action="guanyin-msg-ok" 由 main.js 按 p.then 推进（含 start-fight / enter-node 重定向）。
        const _gyFig = (NDX.npcPortraitOf ? NDX.npcPortraitOf('观音菩萨') : '') || '';
        const _gyFigHtml = _gyFig
          ? `<img class="gg-figure" src="${_gyFig}" alt="观音菩萨" onerror="this.style.visibility='hidden'"/>`
          : '';
        const _gyBody = `
          <div class="scene-body">
            <div class="guanyin-guide gg-msg">${_gyFigHtml}<div class="gg-body"><span class="gg-name">观音菩萨</span><p class="gg-text">${p.text || ''}</p></div></div>
          </div>
          <div class="scene-nav">
            <button class="opt-btn scene-flip" data-action="guanyin-msg-ok">领受 ▸</button>
          </div>`;
        return `<div class="scene-overlay"><div class="scene-modal"><div class="scene-head"><span class="panel-corner">偈</span>观音偈语</div>${_gyBody}</div></div>`;
      } else if (p.kind === 'tutorial-intro') {
        // V8.44 接引使者教学战·开场：第一段文字 + 迎战按钮（点击开启教学战）
        // 观音题词不在此界面弹出，移入教学战场内逐回合引导（teach='tutorial' 驱动）
        title = this._trialHead(1, '金蝉遭贬');
        const _introText = p.text ? `<p class="scene-page">${p.text}</p>` : '';
        const _introBtn = `<div class="scene-nav"><button class="opt-btn trial-opt" data-action="tutorial-fight">⚔ 迎战接引使者 ▸</button></div>`;
        return `<div class="scene-overlay">
          <div class="scene-modal">
            <div class="scene-head"><span class="panel-corner">难</span>${title}</div>
            <div class="scene-body">${_introText}</div>
            ${_introBtn}
          </div>
        </div>`;
      } else if (p.kind === 'trial') {
        // 每难进入前，先以「第N难 · 劫难名」标题弹出（如 第八十一难 · 通天河遇鼋湿经），再呈现正文
        const _diff = (p.diff != null) ? p.diff : (p.trialId != null ? p.trialId : null);
        const _name = p.title || (p.node && p.node.name) || '劫难';
        title = this._trialHead(_diff, this._cleanOptText(_name));
        const safeP = Object.assign({ text: '', page: 0, opts: [] }, p);
        safeP.opts = Array.isArray(safeP.opts) ? safeP.opts : [];
        return this.sceneModal(safeP, title, safeP.opts, 'trial-opt', '——八十一难，必历一方证菩提。');
      } else if (p.kind === 'tiyuan') {
        title = `劫难觉悟 · ${p.node.name}`;
        const _grow = 1 + (NDX.globalProgress(g.state) - 1) * 0.09;
        const _fmt = (v) => Math.round(v * _grow);
        body = `<div class="opt-cards">${NDX.TIYUAN_OPTS.map((o) => {
          const e = o.effect;
          const parts = [];
          if (e.ti && e.ti.atk) parts.push(`体攻 +${_fmt(e.ti.atk)}`);
          if (e.ti && e.ti.hp) parts.push(`气血 +${_fmt(e.ti.hp)}`);
          if (e.yuan && e.yuan.matk) parts.push(`愿伤 +${_fmt(e.yuan.matk)}`);
          if (e.yuan && e.yuan.mdef) parts.push(`御念 +${_fmt(e.yuan.mdef * 100)}%`);
          const label = this._cleanOptText(o.text).replace(/【[体愿]】.*/, `【${o.key === 'ti' ? '体' : '愿'}】${parts.join(' · ')}`);
          const al = NDX.optAlign ? NDX.optAlign(o) : null;
          const tag = al === 'good' ? `<span class="align-tag good">善</span>` : al === 'evil' ? `<span class="align-tag evil">恶</span>` : '';
          return `<button class="opt-btn" data-action="tiyuan" data-key="${o.key}">${tag}${label}</button>`;
        }).join('')}</div>`;
      } else if (p.kind === 'event') {
        title = `缘 · ${p.title}`;
        return this.sceneModal(p, title, p.opts, 'event-opt', '——机缘在此，慎重抉择。');
      } else if (p.kind === 'roll') {
        // 劫运骰（阶段四）：高风险抉择一掷定成败
        const opt = p.opt || {};
        const pct = NDX.rollPct(p.chance);
        const good = g.state.good || 0, evil = g.state.evil || 0;
        const tilt = good !== evil ? (good > evil ? '天眷在善侧，善念替你左右这枚骰子' : '心魔牵引，骰面朝恶念偏了一线') : '善恶互抵，天地不偏不倚';
        return `<div class="scene-overlay"><div class="scene-modal roll-board">
          <div class="scene-head"><span class="panel-corner">劫运</span>${p.title || '劫运抉择'}</div>
          <div class="roll-die"><span class="roll-num">?</span></div>
          <p class="roll-opttext">${opt.text || ''}</p>
          <div class="roll-chance">这一掷，${pct} 成把握</div>
          <p class="roll-tilt">${tilt}</p>
          <p class="roll-tip">掷中则取满全；失手则吃反噬亏。收了手，反得一份稳妥的零头。</p>
          <div class="scene-nav">
            <button class="opt-btn roll-cast" data-action="roll-cast">🎲 掷子一搏</button>
            <button class="opt-btn ghost" data-action="roll-fold">收手保底</button>
          </div>
        </div></div>`;
      } else if (p.kind === 'quota-dao') {
        // V8.34 地区配额制·主攻道选择：六选一决定本地区配额目标道
        const _title = p.title || '立下道心';
        const _btns = (p.opts || []).map((o, i) => {
          const _daoTag = `<span class="dao-tag">${esc(o.dao)}道</span>`;
          const _tip = o.tip ? `<span class="opt-tip">${esc(o.tip)}</span>` : '';
          return `<button class="opt-btn opt-btn-tip" data-action="quota-dao-opt" data-idx="${i}">
            <div class="opt-main">${_daoTag}${esc(o.label || o.text || '')}</div>
            ${_tip}
          </button>`;
        }).join('');
        return `<div class="scene-overlay">
          <div class="scene-modal">
            <div class="scene-head"><span class="panel-corner">道</span>${esc(_title)}</div>
            <div class="scene-body">
              ${p.text ? `<p class="scene-page">${esc(p.text)}</p>` : ''}
              <div class="opt-cards">${_btns}</div>
            </div>
          </div>
        </div>`;
      } else if (p.kind === 'dao-retune') {
        // 方案X2·六道改道面板：每道展示攻式/装备套/转职石/经文钩子，当前道带标记（土地庙·长安入口）
        const _title = p.title || '重立道心 · 六道改道';
        const _btns = (p.opts || []).map((o, i) => {
          const _curTag = o.current ? '<span class="dao-cur">当前</span>' : '';
          const _atk = o.atkName
            ? `<div class="dao-atk"><span class="dao-atk-name">攻式·${esc(o.atkName)}</span><span class="dao-atk-desc">${esc(o.atkDesc || '')}</span></div>`
            : '';
          const _hooks = [];
          if (o.set) _hooks.push(`套：${esc(o.set)}`);
          if (o.stoneName) _hooks.push(`转职石：${esc(o.stoneName)}`);
          if (o.sutras && o.sutras.length) _hooks.push(`经：${esc(o.sutras.slice(0, 3).join('、'))}${o.sutras.length > 3 ? '…' : ''}`);
          const _hookHtml = _hooks.length ? `<div class="dao-hooks">${_hooks.map((h) => `<span>${h}</span>`).join('')}</div>` : '';
          return `<button class="opt-btn opt-btn-tip dao-retune-btn${o.current ? ' dao-current' : ''}" data-action="dao-retune-opt" data-idx="${i}">
            <div class="opt-main"><span class="dao-tag">${esc(o.dao)}道</span>${esc(o.name || '')}${_curTag}</div>
            <div class="dao-align">${esc(o.align || '')}道</div>
            ${_atk}
            ${_hookHtml}
          </button>`;
        }).join('');
        return `<div class="scene-overlay"><div class="scene-modal dao-retune-modal">
          <div class="scene-head"><span class="panel-corner">道</span>${esc(_title)}</div>
          <div class="scene-body">
            ${p.text ? `<p class="scene-page">${esc(p.text)}</p>` : ''}
            <div class="opt-cards">${_btns}</div>
            <div class="scene-nav">
              <button class="opt-btn ghost" data-action="dao-retune-close">${esc(p.next || '暂不改道')}</button>
            </div>
          </div>
        </div></div>`;
      } else if (p.kind === 'dao-overview') {
        // 方案X2·难1六道总览：首难择道后重点介绍六道（攻式/装备套/转职石/经文钩子），当前道高亮
        const _title = p.title || '六道 · 道途既定';
        const _cards = (p.opts || []).map((o, i) => {
          const _curTag = o.current ? '<span class="dao-cur">你在此道</span>' : '';
          const _atk = o.atkName
            ? `<div class="dao-atk"><span class="dao-atk-name">攻式·${esc(o.atkName)}</span><span class="dao-atk-desc">${esc(o.atkDesc || '')}</span></div>`
            : '';
          const _hooks = [];
          if (o.set) _hooks.push(`套：${esc(o.set)}`);
          if (o.stoneName) _hooks.push(`转职石：${esc(o.stoneName)}`);
          if (o.sutras && o.sutras.length) _hooks.push(`经：${esc(o.sutras.slice(0, 3).join('、'))}${o.sutras.length > 3 ? '…' : ''}`);
          const _hookHtml = _hooks.length ? `<div class="dao-hooks">${_hooks.map((h) => `<span>${h}</span>`).join('')}</div>` : '';
          return `<div class="dao-card dao-overview-card${o.current ? ' dao-current' : ''}">
            <div class="opt-main"><span class="dao-tag">${esc(o.dao)}道</span>${esc(o.name || '')}${_curTag}</div>
            <div class="dao-align">${esc(o.align || '')}道</div>
            ${_atk}
            ${_hookHtml}
          </div>`;
        }).join('');
        return `<div class="scene-overlay"><div class="scene-modal dao-retune-modal dao-overview-modal">
          <div class="scene-head"><span class="panel-corner">道</span>${esc(_title)}</div>
          <div class="scene-body">
            ${p.text ? `<p class="scene-page">${esc(p.text)}</p>` : ''}
            <div class="dao-cards-grid">${_cards}</div>
            <div class="scene-nav">
              <button class="opt-btn novel-btn" data-action="dao-overview-next">${esc(p.next || '踏上西行')} ▸</button>
            </div>
          </div>
        </div></div>`;
      } else if (p.kind === 'negotiate') {
        // 逆道谈判 · 以经为质（《竞品借鉴》§3）：妖王精英/Boss 前，以佛经积累为谈判强度收服随从
        const _nTitle = p.title || '以经为质';
        const _nBtns = (p.opts || []).map((o, i) => {
          return '<button class="opt-btn opt-btn-tip" data-action="negotiate-opt" data-idx="' + i + '">' +
            '<div class="opt-main">' + esc(o.label || o.text || '') + '</div>' +
          '</button>';
        }).join('');
        return '<div class="scene-overlay"><div class="scene-modal">' +
          '<div class="scene-head"><span class="panel-corner">质</span>' + esc(_nTitle) + '</div>' +
          '<div class="scene-body">' +
            (p.text ? '<p class="scene-page">' + esc(p.text) + '</p>' : '') +
            '<div class="opt-cards">' + _nBtns + '</div>' +
          '</div></div></div>';
      } else if (p.kind === 'follower-replace') {
        // V8.6x 模块九·随从满钦点替换：已收 3 名随从时，新妖王臣服须玩家钦点谁让位 / 或拱手放弃。
        const _nf = p.follower || {};
        const _oldBtns = (p.oldFollowers || []).map((fid, i) => {
          const _d = NDX.FOLLOWERS[fid] || {};
          return '<button class="opt-btn opt-btn-tip" data-action="follower-replace-opt" data-idx="' + i + '">' +
            '<div class="opt-main">让位于「' + esc(_d.name || fid) + '」</div>' +
            '<span class="rite-sub">' + esc(_d.desc || '') + '｜攻' + (_d.atk || 0) + ' 血' + (_d.hp || 0) + ' 法' + (_d.matk || 0) + '</span>' +
          '</button>';
        }).join('');
        return '<div class="scene-overlay"><div class="scene-modal">' +
          '<div class="scene-head"><span class="panel-corner">从</span>随从满阵 · 钦点谁让位</div>' +
          '<div class="scene-body">' +
            '<p class="scene-page">新妖王「' + esc(_nf.name || '？') + '」愿臣服入列（' + esc(_nf.desc || '') + '），然随从已满——你须指名一名旧随从让位，或拱手辞谢此缘。</p>' +
            '<div class="opt-cards">' + _oldBtns +
              '<button class="opt-btn opt-btn-tip" data-action="follower-replace-opt" data-idx="-1"><div class="opt-main">拱手辞谢 · 不换</div><span class="rite-sub">' + esc(_nf.name || '』') + ' 化烟归山，此缘暂断</span></button>' +
            '</div>' +
          '</div></div></div>';
      } else if (p.kind === 'branch') {
        title = `岔 · ${p.title}`;
        return this.sceneModal(p, title, p.opts, 'branch-opt', '——岔路当前，何去何从。');
      } else if (p.kind === 'compound-route') {
        // 复合节点（多难合并）路线抉择：选「渡 / 恶 / 跳过」决定子难节奏与 Boss 强度。
        // 不走 sceneModal 的分页阅读（routePrompt 是长文案，第一页无选项导致点击无反应），
        // 改为一次成型：标题 + 简短描述 + 选项按钮。V8.27 follow-up：去掉 align-tag「善/恶」红字，
        // 每个选项附带 o.tip 新手指引文案（告诉玩家该选项将获得什么）。
        const _title = p.title || '复合节点·抉择';
        // V8.27 follow-up：复合节点入口不再展示 routePrompt 长文案与固定副标题，只保留标题与路线选项。
        const _short = (p.text || '').split(/\n/)[0].slice(0, 200);
        const _btns = (p.opts || []).map((o, i) => {
          const daoTag = o.daotu ? `<span class="dao-tag">${o.daotu}道</span>` : '';
          const tip = o.tip ? `<span class="opt-tip">${esc(o.tip)}</span>` : '';
          return `<button class="opt-btn opt-btn-tip" data-action="compound-route-opt" data-idx="${i}">
            <div class="opt-main">${daoTag}${esc(o.label || o.text || '')}</div>
            ${tip}
          </button>`;
        }).join('');
        return `<div class="scene-overlay">
          <div class="scene-modal">
            <div class="scene-head"><span class="panel-corner">路</span>${esc(_title)}</div>
            <div class="scene-body">
              ${_short ? `<p class="scene-page">${esc(_short)}</p>` : ''}
              <div class="opt-cards">${_btns}</div>
            </div>
          </div>
        </div>`;
      } else if (p.kind === 'sub-choices') {
        // 第1难二级面板：心念分化后的子选项。V8.27 follow-up：
        // 不再走 sceneModal（那里会给选项加「善/恶」红字标签，且分页阅读会卡住选项显示）；
        // 改为一次成型：标题 + 长描述 + 每个选项带「新手说明 tip」，去掉 align-tag 前缀。
        const _title = p.subTitle || p.title || '心念分化';
        const _btns = (p.opts || []).map((o, i) => {
          const _label = esc(o.label || o.text || '');
          const shortLabel = _label.length > 12 ? _label.slice(0, 12) + '…' : _label;
          const tip = o.tip ? `<div class="opt-tip">${esc(o.tip)}</div>` : '';
          // 悬停详情：超长文本或带tip时显示完整内容
          let hoverParts = [];
          if (_label.length > 12) hoverParts.push(_label);
          if (o.tip) hoverParts.push(esc(o.tip));
          const hoverAttr = hoverParts.length ? ` title="${hoverParts.join(' — ')}"` : '';
          return `<button class="opt-btn opt-btn-tip" data-action="sub-trial-opt" data-idx="${i}"${hoverAttr}>
            <div class="opt-main">${shortLabel}</div>
            ${tip}
          </button>`;
        }).join('');
        return `<div class="scene-overlay">
          <div class="scene-modal">
            <div class="scene-head"><span class="panel-corner">向</span>${esc(_title)}</div>
            <div class="scene-body">
              <p class="scene-page">${esc(p.subText || '')}</p>
              ${p.teach === 'sixdao-sub' ? this._guanyinGuide(p.teachText, 'gg-sixdao gg-sixdao-sub') : ''}
              <p class="scene-sub">——同一念起，此后再分。</p>
              <div class="opt-cards">${_btns}</div>
            </div>
          </div>
        </div>`;
      } else if (p.kind === 'mirror') {
        return this.mirrorHtml(p);
      } else if (p.kind === 'equip') {
        const _slots = [...new Set(p.items.map((e) => e.slot))];
        const _label = _slots.length === 1 && _slotLabel[_slots[0]] ? _slotLabel[_slots[0]] : '装备';
        const _hasRare = p.items.some((e) => _equipRarity(e) !== 'normal');
        title = `拾得${_label} · ${p.items.length}选一${_hasRare ? ' ✦' : ''}`;
        body = `<div class="opt-cards">${p.items.map((e) =>
          `<button class="opt-btn equip${_rarityClass(e)}" data-action="equip" data-id="${e.id}">
             ${_rarityTag(e)}<b>${e.name}</b> ${_slotTag(e.slot)} ${e.desc}</button>`
        ).join('')}</div>`;
      } else if (p.kind === 'gift') {
        const _slots = [...new Set(p.items.map((e) => e.slot))];
        const _label = _slots.length === 1 && _slotLabel[_slots[0]] ? _slotLabel[_slots[0]] : '宝物';
        title = p.title || `宝窟 · 取一${_label}`;
        // P3-1 首次进入宝窟：引导横幅
        const _giftTeach = p.firstTreasure
          ? '<div class="teach-banner teach-treasure">💎 宝窟 · 法宝秘境：此间只藏法宝不藏兵甲——任选一件法宝入囊，法宝可临阵祭出打断AI普攻</div>'
          : '';
        body = _giftTeach + (p.text ? `<p class="trial-text">${p.text}</p>` : '') + `<div class="opt-cards">${p.items.map((e) =>
          `<button class="opt-btn equip eq-rare-treasure" data-action="gift" data-id="${e.id}">
             ${_rarityTag(e)}<b>${e.name}</b> ${_slotTag(e.slot)} ${e.desc}</button>`
        ).join('')}</div>`;
      } else if (p.kind === 'elitereward') {
        const _slots = [...new Set(p.items.map((e) => e.slot))];
        const _label = _slots.length === 1 && _slotLabel[_slots[0]] ? _slotLabel[_slots[0]] : '装备';
        const _hasRare = p.items.some((e) => _equipRarity(e) !== 'normal');
        title = `精英战利 · ${_label}${p.items.length}选一${_hasRare ? ' ✦' : ''}`;
        body = `<p class="trial-text">你斩落此獠，于残甲断兵间拣出${p.items.length}件可用之物——择其一，余者化尘。</p>` +
          `<div class="opt-cards">${p.items.map((e) =>
            `<button class="opt-btn equip${_rarityClass(e)}" data-action="elite-equip" data-id="${e.id}">
               ${_rarityTag(e)}<b>${e.name}</b> ${_slotTag(e.slot)} ${e.desc}</button>`
          ).join('')}</div>`;
      } else if (p.kind === 'craft') {
        title = '炼化合成 · 以宝物融材料';
        const hintLine = p.hint ? `<p class="craft-hint">🜂 套装进度：${p.hint}</p>` : '';
        body = `<p class="trial-text">你怀中宝物与沿途所得材料隐隐相鸣——择一炉，将劫难所夺之宝，炼作进阶之物；或集齐套装基座，铸成成套神兵。</p>` +
          hintLine +
          `<div class="opt-cards">${p.recipes.map((r) => {
            const out = NDX.craftById(r.out);

            // 防御：产物/基座缺失时跳过该配方，绝不因访问 undefined.name 而中断整次渲染
            if (!out) return '';
            if (r.comps) {
              const owned = (s.equips || []).map((e) => e.id);
              const countOwned = (id) => owned.filter((x) => x === id).length;
              const need = {};
              r.comps.forEach((c) => { need[c] = (need[c] || 0) + 1; });
              let ok = Object.keys(need).every((c) => countOwned(c) >= need[c]);
              const names = Object.keys(need).map((c) => { const b = NDX.equipById(c); const n = need[c]; const have = countOwned(c); return `${b ? b.name : c}×${n}(有${have})`; }).join(' + ');
              // 六道专职 L5：需专属遗物材料（残片为材料，主线/坊市确定获取），计入可铸判定与展示
              let relicSeg = '';
              if (r.relicId) {
                const rl = NDX.ZHUANJIE ? NDX.ZHUANJIE.relicById(r.relicId) : null;
                const haveR = (s.materials && s.materials[r.relicId]) || 0;
                if (haveR < 1) ok = false;
                relicSeg = `${rl ? rl.name : r.relicId}×1(有${haveR})`;
              }
              const fullNames = relicSeg ? names + ' + ' + relicSeg : names;
              return `<button class="opt-btn equip set-recipe ${ok ? '' : 'disabled'}" data-action="${ok ? 'craft' : ''}" data-id="${r.out}" ${ok ? '' : 'disabled'}>
                🜂 套装三合一：${fullNames} → <b>${out.name}</b>
                ${_slotTag(out.slot)} ${out.desc}</button>`;
            }
            const base = r.base ? NDX.equipById(r.base) : null;
            const baseCount = (s.equips || []).filter((e) => e.id === r.base).length;
            const baseOk = !r.base || (base && baseCount > 0);
            const req = r.materials || (r.material ? { [r.material]: r.count || 1 } : {});
            const matOk = Object.keys(req).every((m) => (s.materials && s.materials[m] || 0) >= req[m]);
            const matStr = r.materials
              ? Object.keys(r.materials).map((m) => { const have = (s.materials && s.materials[m]) || 0; return `${m}×${r.materials[m]}(有${have})`; }).join(' + ')
              : `${r.material}×${r.count}(有${(s.materials && s.materials[r.material]) || 0})`;
            const setTag = r.materials && !r.material ? '🜂 套装熔炼：' : '';
            const ok = baseOk && matOk;
            const baseLabel = base ? base.name : (r.base || '基座');
            return `<button class="opt-btn equip ${r.materials && !r.material ? 'set-recipe' : ''} ${ok ? '' : 'disabled'}" data-action="${ok ? 'craft' : ''}" data-id="${r.out}" ${ok ? '' : 'disabled'}>
              ${setTag}<b>${baseLabel}</b>(有${baseCount}) + ${matStr} → <b>${out.name}</b>
              ${_slotTag(out.slot)} ${out.desc}</button>`;
          }).join('')}</div>` +
          `<button class="opt-btn ghost" data-action="craft-leave">暂不炼化</button>`;
      } else if (p.kind === 'sutra') {
        // 佛经系统（通关后激活 · 自己西游+恶专属）：散件合成全本
        // V3 §二 自动路由：合成入背包 → 立即自动投入当前主道途生效
        title = '佛经合本 · 散件归一经卷成';
        const frags = s.sutraFrags || {};
        const done = (s.sutras || []).concat(s.sutraBackpack || []);
        const can = NDX.availableSutras ? NDX.availableSutras(s) : [];
        const list = (NDX.SUTRA_FULLS || []).map((f) => {
          const isDone = done.indexOf(f.id) >= 0;
          const canNow = can.some((c) => c.id === f.id);
          const prog = f.frags.map((fid) => {
            const frag = NDX.sutraFragById ? NDX.sutraFragById(fid) : null;
            const have = frags[fid] || 0;
            return `${frag ? frag.name : fid}${have >= 1 ? '✓' : '✗'}`;
          }).join(' · ');
          const cls = isDone ? 'done' : (canNow ? 'equip' : 'disabled');
          const act = isDone ? '' : (canNow ? `data-action="sutra" data-id="${f.id}"` : 'disabled');
          const tag = isDone ? '【已合全本 · 已投主道】' : (canNow ? '【可合成】' : '【散件未齐】');
          return `<button class="opt-btn sutra-btn ${cls}" ${act} ${isDone || canNow ? '' : 'disabled'}>
            ${tag}<b>${f.name}</b><br><span class="sutra-seg">${prog}</span><br><span class="sutra-desc">${f.desc}</span></button>`;
        }).join('');
        const leaveAct = (s.over && s.over.win) ? 'sutra-finish' : 'sutra-leave';
        const leaveTxt = (s.over && s.over.win) ? '西行圆满 · 跳出簿子 ▸' : '暂不参研，继续西行';
        body = `<p class="trial-text">你自取西经、逆天改命，沿途所拾佛经散件，此刻在怀中隐隐生辉。将一部之散件合为全本，经义自动投入主道途生效——本经道途与主道一致者效果 ×1.5（气血·攻伐·法伤·御念·自愈）。</p>` +
          list +
          `<button class="opt-btn ghost" data-action="${leaveAct}">${leaveTxt}</button>`;
      } else if (p.kind === 'shop') {
        // 坊市采用浮层弹窗，浮于地图之上（与拾取/战利/宝窟一致），不挤压底层画面
        title = `坊市 · 第${p.tier}档`;
        // P1-1 首次进入坊市：引导横幅
        const _shopTeach = p.firstShop
          ? '<div class="teach-banner teach-shop">🏪 坊市 · 三用：花金购兵甲 · 刷新货架（限次，价上浮）· 材料合成装备（坊市自动检测可合成配方）</div>'
          : '';
        // V8.35 商店刷新：花金换货，每店限次，价格随刷新上浮
        const _rrUsed = p.rerollCount || 0;
        const _rrLeft = Math.max(0, NDX.SHOP_REROLL_LIMIT - _rrUsed);
        const _rrPrice = NDX.shopRerollPrice(p.tier, _rrUsed + 1);
        const _rrTip = _rrUsed >= NDX.SHOP_REROLL_LIMIT
          ? `<span class="shop-rr-info">货郎今日新货已尽（已刷 ${_rrUsed}/${NDX.SHOP_REROLL_LIMIT} 次）</span>`
          : `<span class="shop-rr-info">刷新需 ${NDX.SHOP_REROLL_COST}金${_rrUsed > 0 ? `（下次新货价 ${_rrPrice}金，已上浮）` : ''} · 余 ${_rrLeft} 次</span>`;
        body = _shopTeach + p.items.map((e) =>
          `<button class="opt-btn equip" data-action="shop-buy" data-id="${e.id}">
             <b>${e.name}</b> ${_slotTag(e.slot)} ${e.desc} ｜ ${e.price}金</button>`
        ).join('') + `<div class="shop-rr-row">${_rrTip}
            <button class="opt-btn ghost shop-reroll" data-action="shop-reroll" ${_rrUsed >= NDX.SHOP_REROLL_LIMIT ? 'disabled' : ''}>刷新货架 · ${NDX.SHOP_REROLL_COST}金</button>
          </div>` + `<button class="opt-btn ghost" data-action="shop-leave">离开坊市</button>`;
        return `<div class="scene-overlay shop-overlay"><div class="scene-modal shop-modal"><div class="panel-title"><span class="panel-corner">择</span>${title}</div><div class="panel-body">${body}</div></div></div>`;
      } else if (p.kind === 'bossreward') {
        title = p.title || '关隘通关 · 法宝三选一（唯一）';
        const _bossText = p.text ? `<p class="trial-text">${p.text}</p>` : '';
        body = _bossText + p.items.map((e) =>
          `<button class="opt-btn equip" data-action="bossreward" data-id="${e.id}">
             <b>${e.name}</b> ${_slotTag(e.slot)} ${e.desc}</button>`
        ).join('');
      } else if (p.kind === 'bless-seal') {
        // 开局赐福 · 佛祖式：自选 1 套白色劫印（复用白劫渲染样式）
        title = p.title || '佛祖庇佑 · 开局赐福';
        // P4-5 开局赐福引导横幅
        const _blessTeach = '<div class="teach-banner teach-bless">🙏 开局赐福：佛祖庇佑——先择一道白劫印(永久属性)，再择一件法宝傍身；二者皆可跳过，但赐福不等人</div>';
        const _intro = p.text ? `<p class="trial-text">${p.text}</p>` : '';
        const _list = (p.sealOffers || []).map((o, i) => {
          const dao = NDX.SEAL_DAOTU[o.dao] || { name: o.dao };
          const _pct = Math.round(o.val * 100);
          const _uniqueTag = o.unique ? ' <span class="seal-unique">唯一</span>' : '';
          const _extra = [];
          if (o.crit) _extra.push(`暴击+${Math.round(o.crit * 100)}%`);
          if (o.lifesteal) _extra.push(`吸血${Math.round(o.lifesteal * 100)}%`);
          if (o.maxhp) _extra.push(`气血+${Math.round(o.maxhp * 100)}%`);
          const _extraStr = _extra.length ? `<span class="seal-extra">【${_extra.join(' · ')}】</span>` : '';
          const _icon = NDX.getSealIcon ? NDX.getSealIcon(o.name, o.dao) : '';
          const _iconHtml = _icon ? `<img class="seal-opt-icon" src="${_icon}" alt="${o.name}" onerror="this.style.display='none'" />` : '';
          return `<button class="opt-btn seal-opt tier-white" data-action="bless-seal-pick" data-idx="${i}">
              ${_iconHtml}
              <div class="seal-opt-info">
                <span class="seal-dao">${dao.name}</span>
                <b class="seal-name">${o.name}</b>${_uniqueTag}
                <span class="seal-val">+${_pct}%</span>
                <span class="seal-desc">${o.desc}</span>
                ${_extraStr}
              </div>
            </button>`;
        }).join('');
        body = _blessTeach + _intro + _list +
          `<button class="opt-btn ghost" data-action="bless-seal-skip">暂不需劫印，先看法宝</button>`;
      } else if (p.kind === 'bless-treasure') {
        // 开局赐福 · 佛祖式：自选 1 件基础法宝
        title = p.title || '佛祖庇佑 · 择一件法宝';
        const _intro = p.text ? `<p class="trial-text">${p.text}</p>` : '';
        const _list = (p.treasures || []).map((e, i) =>
          `<button class="opt-btn equip" data-action="bless-treasure-pick" data-idx="${i}">
             <b>${e.name}</b> ${_slotTag(e.slot)} ${e.desc}</button>`
        ).join('');
        body = _intro + _list +
          `<button class="opt-btn ghost" data-action="bless-treasure-skip">暂不需法宝，启程</button>`;
      } else if (p.kind === 'seal') {
        // 劫印系统（V41）：战斗胜利掉落劫印 3 选 1（V8.16 取消品阶持有上限——81难所得劫印即自然上限）
        // V8.26：改为适配横版界面的「长方形卡片三选一」；卡片右侧同等大小面板——上半=获得装备，下半=获得财产。
        const _tierName = { white: '白劫', blue: '蓝劫', gold: '金劫', red: '红劫' }[p.tier] || '劫印';
        const _tierCls = { white: 'tier-white', blue: 'tier-blue', gold: 'tier-gold', red: 'tier-red' }[p.tier] || '';
        const _total = (s.seals || []).length;
        title = `${_tierName} · 道途三选一`;
        const _list = (p.offers || []).map((o, i) => {
          const dao = NDX.SEAL_DAOTU[o.dao] || { name: o.dao };
          const _pct = Math.round(o.val * 100);
          const _uniqueTag = o.unique ? ' <span class="seal-unique">唯一</span>' : '';
          const _extra = [];
          if (o.crit) _extra.push(`暴击+${Math.round(o.crit * 100)}%`);
          if (o.lifesteal) _extra.push(`吸血${Math.round(o.lifesteal * 100)}%`);
          if (o.maxhp) _extra.push(`气血+${Math.round(o.maxhp * 100)}%`);
          if (o.evaOnDodge) _extra.push('残影·闪避后必中');
          const _extraStr = _extra.length ? `<span class="seal-extra">【${_extra.join(' · ')}】</span>` : '';
          return `<button class="opt-btn seal-opt ${_tierCls}" data-action="seal-pick" data-idx="${i}">
              <span class="seal-dao">${dao.name}</span>
              <b class="seal-name">${o.name}</b>${_uniqueTag}
              <span class="seal-val">+${_pct}%</span>
              <span class="seal-desc">${o.desc}</span>
              ${_extraStr}
            </button>`;
        }).join('');
        // 右侧面板：上半=获得装备，下半=获得财产（来自本场战利品）
        const _rw = p.rewards || {};
        const _eqArr = _rw.equips || [];
        const _matArr = Object.keys(_rw.materials || {}).map((k) => `${(NDX.MAT_LABEL && NDX.MAT_LABEL[k]) || k}×${_rw.materials[k]}`);
        const _gold = _rw.gold || 0;
        const _eqHtml = _eqArr.length
          ? _eqArr.map((e) => `<div class="rw-eq"><b>${e.name}</b><span class="rw-eq-slot">${NDX.EQUIP_SLOT_LABEL ? (NDX.EQUIP_SLOT_LABEL[e.slot] || e.slot) : e.slot}</span><span class="rw-eq-stat">攻${e.atk || 0} 血${e.hp || 0} 法${e.matk || 0}</span></div>`).join('')
          : '<div class="rw-empty">本场无新装备</div>';
        const _propHtml = (_matArr.length || _gold > 0)
          ? _matArr.map((m) => `<div class="rw-prop">${m}</div>`).join('') + ( _gold > 0 ? `<div class="rw-prop rw-gold">灵石 +${_gold}</div>` : '' )
          : '<div class="rw-empty">本场无财产进账</div>';
        const _rewardPanel = `<div class="seal-reward-panel">
            <div class="seal-reward-half seal-reward-eq"><div class="seal-reward-h">🎁 获得装备</div>${_eqHtml}</div>
            <div class="seal-reward-half seal-reward-prop"><div class="seal-reward-h">💰 获得财产</div>${_propHtml}</div>
          </div>`;
        // V8.5x 首次劫印解锁：观音介绍劫印系统
        const _sealTeachBanner = p.firstSealTeach
          ? '<div class="teach-banner teach-sixdao">🪷 观音菩萨：「此乃劫印——每一抉择落下一道印记，战·渡·逆·隐·夺·缘，累积光带，塑成你的流派与命痕。择一道途，刻下第一枚劫印。」</div>'
          : '';
        body = `<div class="seal-landscape">${_sealTeachBanner}
            <div class="seal-cards">${_list}</div>
            ${_rewardPanel}
          </div>
          <button class="opt-btn ghost seal-skip" data-action="seal-skip">不纳此印，继续西行</button>
          <p class="trial-text">破此一难，天庭于你命格之上落下一${_tierName}——择一道途，刻入劫印。<br>
          <span class="seal-cap">已纳劫印 ${_total} 枚（品阶不再设限，可于土地庙自由合成升阶）</span></p>`;
      } else if (p.kind === 'equipbar') {
        // 装备栏：按槽位单件生效 + 背包备选切换（V8.19）
        title = '土地庙 · 装备栏';
        const _slotLbl = NDX.EQUIP_SLOT_LABEL || { weapon: '兵刃', armor: '甲胄', pet: '灵宠', treasure: '法宝' };
        let _slotHtml = '';
        (NDX.EQUIP_SLOTS || ['weapon', 'armor', 'pet']).forEach((sl) => {
          const same = (s.equips || []).filter((e) => e && e.slot === sl);
          if (!same.length) { _slotHtml += `<div class="seal-bar-slot"><span class="seal-dao">${_slotLbl[sl] || sl}</span><span class="seal-extra">（空）</span></div>`; return; }
          const activeE = NDX.pickActiveEquip ? NDX.pickActiveEquip(sl, s.equips) : same[0];
          const _optBtn = (e) => {
            const isAct = e === activeE;
            const dao = (NDX.SEAL_DAOTU && NDX.SEAL_DAOTU[e.dao]) ? NDX.SEAL_DAOTU[e.dao].name : '';
            const txt = `<span class="seal-dao">${dao}</span><b class="seal-name">${e.name}</b>
              <span class="seal-val">攻${e.atk || 0} 血${e.hp || 0} 法${e.matk || 0||0} 减${e.dr ? Math.round(e.dr * 100) + '%' : 0}</span>`;
            if (isAct) return `<div class="seal-opt seal-active ${NDX.SEAL_TIER_CLS && NDX.SEAL_TIER_CLS[e.tier] || ''}">${txt}<span class="seal-extra">◆ 已生效</span></div>`;
            if (e.slot === 'treasure') return null;
            return `<button class="opt-btn seal-opt" data-action="equip-swap" data-id="${e.id}">${txt}<span class="seal-extra">设为生效</span></button>`;
          };
          _slotHtml += `<div class="seal-bar-slot"><span class="seal-dao">${_slotLbl[sl] || sl}</span> ${_optBtn(activeE) || ''}</div>`;
          (same).filter((e) => e !== activeE).forEach((e) => { const b = _optBtn(e); if (b) _slotHtml += b; });
        });
        const _treas = (s.equips || []).filter((e) => e.slot === 'treasure');
        const _treasActive = _treas.filter((e) => NDX.isEquipActive && NDX.isEquipActive(s, e.id));
        const _treCap = NDX.treasureSlotCap ? NDX.treasureSlotCap(s.act || 1) : 2;
        body = `<p class="trial-text">各槽位联动一件装备生效（按品质/数值自动择优，可手动锁定）。法宝生效格内方可祭出/提供加成。</p>` +
          _slotHtml +
          (NDX.EQUIP_SLOTS && _treas.length ? `<p class="trial-text">法宝生效 ${_treasActive.length}/${_treas.length} 件（上限 ${_treCap} 格，超出者不提供加成）。</p>` : '') +
          `<button class="opt-btn ghost" data-action="sealbar-back">合上</button>`;
      } else if (p.kind === 'equip-combine') {
        // 土地庙·装备组合面板（V8.50）：消费组合件/升级件/散宝合成进阶装备
        title = '土地庙 · 装备组合';
        const _allRecs = (NDX.eventComboRecipes && NDX.eventComboRecipes()) || [];
        const _owned = (s.equips || []).map((e) => e.id);
        const _has = (id) => _owned.indexOf(id) >= 0;
        // 同产物多配方（如·mk 双路径）去重：每 out 仅一张卡；优先展示当前材料齐备或配方更长者，便于看清缺口
        const _recs = [];
        const _seen = {};
        _allRecs.forEach((r) => {
          if (_seen[r.out]) return;
          _seen[r.out] = true;
          const specific = _allRecs.find((x) => x.out === r.out && (x.comps || []).every((id) => _has(id)))
            || _allRecs.find((x) => x.out === r.out && (x.comps || []).length > (r.comps || []).length)
            || r;
          _recs.push(specific);
        });
        const _cards = _recs.map((r) => {
          const prod = (NDX.lootById && NDX.lootById(r.out)) || { name: r.out };
          const can = (NDX.canCombine && NDX.canCombine(s, r.out)) || false;
          const compNames = (r.comps || []).map((id) => {
            const e = (NDX.lootById && NDX.lootById(id)) || { name: id };
            return `${e.name}${_has(id) ? '✓' : '<b style="color:var(--vermilion)">✗</b>'}`;
          }).join(' ＋ ');
          if (can) {
            return `<button class="opt-btn seal-opt" data-action="equip-combine-do" data-out="${r.out}"><b class="seal-name">${prod.name}</b><span class="seal-val">${compNames}</span><span class="seal-desc">合成</span></button>`;
          }
          return `<div class="seal-opt seal-locked"><b class="seal-name">${prod.name}</b><span class="seal-val">${compNames}</span><span class="seal-desc">材料不足</span></div>`;
        }).join('');
        body = `<p class="trial-text">以<b>组合件</b>、<b>升级件</b>与<b>游历散宝</b>相淬，铸进阶装备——初等散宝＋组合件→中等锻造散宝，再＋升级件→顶级，更可收束为圆满。材料不足者灰显。</p>` +
          (_cards || '<p class="trial-text">尚无可组合之配方。</p>') +
          `<button class="opt-btn ghost" data-action="equip-combine-back">回土地庙</button>`;
      } else if (p.kind === 'sealbar') {
        // 劫印栏（V3 §1.1）：全数自动累计生效，无生效位管理；只展示六道「道途层数」阶段碑
        title = '土地庙 · 劫印 · 道途层数';
        const _daoOrder = ['渡', '战', '缘', '夺', '隐', '逆'];
        const _dao = (NDX.SEAL_DAOTU || {});
        const _tlRows = _daoOrder
          .filter((d) => NDX.sealDaoLayerSum(s, d) > 0)
          .map((d) => {
            const sum = NDX.sealDaoLayerSum(s, d);
            const nxt = NDX.sealBreakInfo ? NDX.sealBreakInfo(s, d).nxtTier : null;
            const _nm = (_dao[d] || { name: d }).name;
            return `<span class="seal-tl-cell${nxt == null ? ' on' : ''}">${_nm} ${sum}层` +
              (nxt != null ? `<span class="seal-extra"> → ${nxt}层</span>` : `<span class="seal-cap"> ◆ 圆</span>`) + `</span>`;
          }).join('');
        const _all = (s.seals || []).map((x, i) => ({ x, i }));
        const _listS = _all.map((o) => {
          const x = o.x, _nm = (_dao[x.dao] || { name: x.dao }).name;
          return `<div class="seal-opt ${NDX.SEAL_TIER_CLS && NDX.SEAL_TIER_CLS[x.tier] || ''}">
              <span class="seal-dao">${_nm}</span>
              <b class="seal-name">${x.name}</b>
              <span class="seal-val">+${Math.round(x.val * 100)}%</span>
              <span class="seal-layer">层×${NDX.sealLayerVal(x.tier)}</span>
              <span class="seal-desc">全数自动生效</span>
            </div>`;
        }).join('');
        body = `<p class="trial-text">劫印已刻，全数自动附于道途——按道累计「道途层数」，每达 3/6/9/12 层激活阶段加成，无需整理生效。</p>` +
          `<div class="seal-tierline">${_tlRows || '<span class="seal-extra">尚无道途层数。</span>'}</div>` +
          (_all.length ? `<ul class="baglist">${_listS}</ul>` : `<p class="trial-text">尚无劫印。</p>`) +
          `<button class="opt-btn ghost" data-action="sealbar-back">合上</button>`;
      } else if (p.kind === 'abandon') {
        // 中途撤退·本局所得结算（《体系补全》·一阶）
        title = '中途收手';
        const mt = p.summary || {};
        const row = (k, v) => `<div class="ab-row"><span class="ab-k">${k}</span><span class="ab-v">${v}</span></div>`;
        body = `<p class="trial-text">你于此抽身而退，西行未竟，但本局所得已铭记——劫难进度已入谱录，不计入败绩。</p>` +
          `<div class="abandon-summary">` +
          row('抵达层数', `第 ${mt.layer || 1} 层`) +
          row('身怀金币', `${mt.gold || 0} 金`) +
          row('劫印在身', `${mt.sealN || 0} 枚`) +
          row('劫印机制', `${mt.mechN || 0} 枚`) +
          row('装备傍身', `${mt.equipN || 0} 件`) +
          row('本局遇劫', `${mt.met || 0} 难 / 共 ${mt.total || '?'} 难`) +
          `</div>` +
          `<button class="opt-btn" data-action="abandon-confirm">收手回程</button>`;
      } else if (p.kind === 'start') {
        // 长安开场：李世民邀请取经并赐予初始装备（弹窗，浮于地图之上）
        // V8.27 follow-up：寿命系统教学已拆到第二页（kind='start-teach'），避免第一页被教学块压得过挤。
        const opts = (p.opts || []).map((o, i) => {
          const _clean = this._cleanOptText(o.text);
          const shortText = _clean.length > 12 ? _clean.slice(0, 12) + '…' : _clean;
          const hoverAttr = _clean.length > 12 ? ` title="${esc(_clean)}"` : '';
          return `<button class="opt-btn scene-opt" data-action="start-opt" data-idx="${i}"${hoverAttr}>${shortText}</button>`;
        }).join('');
        return `<div class="scene-overlay start-overlay"><div class="scene-modal start-modal">
          <div class="scene-head">— 第〇难 · 长安 —</div>
          <div class="scene-page">${p.text.replace(/\n/g, '<br>')}</div>
          <div class="scene-opts">${opts}</div>
        </div></div>`;
      } else if (p.kind === 'start-teach') {
        // V8.30 开局流程重构：第〇难·长安送行——教学战后，寿命系统教学融入送行叙事
        const _L = (NDX.LIFE || {});
        const lifeTeach = `<div class="start-teach">
          <div class="start-teach-title">🕯 寿数有穷 · 唯传承不灭</div>
          <p class="start-teach-lead">你自 <b>${_L.START || 27} 岁</b>西行，寿烛至 <b>${_L.MAX || 55} 岁</b>而灭。<span class="muted">大限一至，便坐化归尘——不是终局，而是传承的开端。</span></p>
          <div class="start-teach-row"><span class="st-tag">每走一难</span>进节点便耗寿：劫难 ${_L.COST && _L.COST.trial} 岁，精英 ${_L.COST && _L.COST.elite} 岁，关隘 ${_L.COST && _L.COST.boss} 岁</div>
          <div class="start-teach-row"><span class="st-tag">恶道有价</span>夺/逆/战抉择，每次额外耗寿 ${_L.EVIL_SURCHARGE} 岁</div>
          <div class="start-teach-row"><span class="st-tag">如何续命</span>寻<b>土地庙</b>打坐回寿 ${_L.MEDITATE_REGAIN} 岁</div>
          <div class="start-teach-row"><span class="st-tag">死后如何</span>家当/遗物/经文由<b>下一世的你承继</b>；法宝随世而散不复传承</div>
        </div>`;
        const opts = (p.opts || []).map((o, i) =>
          `<button class="opt-btn scene-opt" data-action="start-teach-opt" data-idx="${i}">${this._cleanOptText(o.text)}</button>`).join('');
        return `<div class="scene-overlay start-overlay"><div class="scene-modal start-modal">
          <div class="scene-head">— 第〇难 · 长安送行 —</div>
          ${lifeTeach}
          <div class="scene-opts">${opts}</div>
        </div></div>`;
      } else if (p.kind === 'song-gift') {
        // 长安送行·观音赠宝（单窗口）：此 kind 此前无渲染分支——中部空白、节点全锁＝"卡死"。
        // 补上独立场景层，按钮 data-action="song-gift-ok" 由 main.js 按 p.then 推进。
        const _gifItems = (p.items || []).map((e) =>
          `<li class="song-gift-item">${NDX.getEquipIconHtml ? NDX.getEquipIconHtml(e, 'song-gift-icon') : ''}<b>${e.name}</b><span class="song-gift-desc">${e.desc || ''}</span></li>`
        ).join('') || '<li class="muted">无</li>';
        const _gifPortrait = (NDX.npcPortraitOf ? NDX.npcPortraitOf('观音菩萨') : '') || '';
        const _gifFig = _gifPortrait
          ? `<img class="scene-portrait" src="${_gifPortrait}" alt="观音菩萨" onerror="this.style.display='none'" />`
          : '';
        return `<div class="scene-overlay song-overlay"><div class="scene-modal song-modal">
          <div class="scene-head">— ${p.title || '长安送行 · 观音赠宝'} —</div>
          <div class="song-dialogue">${_gifFig}<p class="song-speaker">观音菩萨</p><p class="song-text">${p.text || ''}</p></div>
          <ul class="song-gift-list">${_gifItems}</ul>
          <div class="scene-nav"><button class="opt-btn scene-flip" data-action="song-gift-ok">收下行装 ▸</button></div>
        </div></div>`;
      } else if (p.kind === 'song-event') {
        // V8.5x 长安送行六步互动教学：0=开场对话 1=包裹教学 2=装备教学 3=法宝教学 4=地图引导 5=收尾/选项
        const step = p.teachStep || 0;
        const portraitUrl = p.portrait ? NDX.npcPortraitOf(p.portrait) : '';
        const portraitHtml = portraitUrl
          ? `<img class="scene-portrait" src="${portraitUrl}" alt="${p.portrait}" onerror="this.style.display='none'" />`
          : '';
        const opts = (p.opts || []).map((o, i) => {
          const _clean = this._cleanOptText(o.text);
          const shortText = _clean.length > 20 ? _clean.slice(0, 20) + '…' : _clean;
          const hoverAttr = _clean.length > 20 ? ` title="${esc(_clean)}"` : '';
          return `<button class="opt-btn scene-opt" data-action="song-event-opt" data-idx="${i}"${hoverAttr}>${shortText}</button>`;
        }).join('');
        // 步骤指示器
        const stepIndicator = `<div class="song-step-indicator">${[0,1,2,3,4,5].map(i => `<span class="song-step-dot${i <= step ? ' active' : ''}"></span>`).join('')}</div>`;
        // 根据步骤显示不同内容
        let stepContent = '';
        let stepNav = '';
        if (step === 0) {
          // 第一步：开场对话
          stepContent = `<div class="song-step-content">
            <div class="song-dialogue">
              <p class="song-speaker">观音菩萨</p>
              <p class="song-text">「金蝉子，前三难已历，你心中已有方向。此去西行，十万八千里，贫僧赠你三件法器。」</p>
            </div>
            <div class="song-dialogue">
              <p class="song-speaker">唐太宗</p>
              <p class="song-text">「御弟，此去经年，望早归。这锦襕袈裟、九环锡杖，乃朕亲赐。」</p>
            </div>
          </div>`;
          stepNav = `<button class="opt-btn song-next-btn" data-action="song-event-next">继续 ▸</button>`;
        } else if (step === 1) {
          // 第二步：包裹教学（V8.5x 新增）
          stepContent = `<div class="song-step-content song-teach-step">
            <div class="song-teach-icon">🎒</div>
            <h3 class="song-teach-title">包裹教学</h3>
            <p class="song-teach-text">西行路上所得装备、法宝、材料皆入包裹。<br>点击底部「包裹」按钮可随时查看与整理。</p>
            <div class="song-teach-tiyuan"><b>包裹分栏</b>：装备栏（兵刃/甲胄/身法）、法宝栏（主动战技）、材料栏（消耗品与合成素材）。击败劫难必得装备，多周目可携。</div>
            <div class="song-teach-hint">包裹容量有限，适时在商店变卖或合成更强装备</div>
          </div>`;
          stepNav = `<button class="opt-btn song-next-btn song-teach-btn" data-action="song-event-next">继续 ▸</button>`;
        } else if (step === 2) {
          // 第三步：装备教学
          stepContent = `<div class="song-step-content song-teach-step">
            <div class="song-teach-icon">📿</div>
            <h3 class="song-teach-title">装备教学</h3>
            <p class="song-teach-text">锦襕袈裟（甲胄，护体+15%，气血+200）<br>九环锡杖（兵刃，体攻+30）</p>
            <div class="song-teach-tiyuan"><b>体/愿双系</b>：体系（兵刃/甲胄/身法）提升普攻与生存；愿系（法宝/御念）提升法术与法宝威力。两系独立成长，按需构筑。</div>
            <div class="song-teach-hint">点击「装备入身」，学习如何穿戴装备</div>
          </div>`;
          stepNav = `<button class="opt-btn song-next-btn song-teach-btn" data-action="song-event-next">装备入身 ▸</button>`;
        } else if (step === 3) {
          // 第四步：法宝教学
          stepContent = `<div class="song-step-content song-teach-step">
            <div class="song-teach-icon">🔮</div>
            <h3 class="song-teach-title">法宝教学</h3>
            <p class="song-teach-text">紫金钵盂（渡道法宝）<br>战斗中点击法宝图标祭出，对全体敌人造成法伤，冷却3回合</p>
            <div class="song-teach-active"><b>生效格</b>：仅生效格内的法宝才加属性、可临阵祭出。格数随成长提升，超出的法宝暂不生效。</div>
            <div class="song-teach-hint">法宝是主动技能，战斗中手动祭出，有冷却时间</div>
          </div>`;
          stepNav = `<button class="opt-btn song-next-btn song-teach-btn" data-action="song-event-next">明白了 ▸</button>`;
        } else if (step === 4) {
          // 第五步：地图引导
          stepContent = `<div class="song-step-content song-teach-step">
            <div class="song-teach-icon">🗺️</div>
            <h3 class="song-teach-title">地图操作</h3>
            <p class="song-teach-text">点击高亮节点继续西行<br>不同节点有不同奖励：<br>🗡战斗 👺精英 ❓事件 🏮商店 ⛩休息 👑Boss</p>
            <div class="song-teach-hint">路线选择 = 奖励选择，高亮节点是当前可前进的节点</div>
          </div>`;
          stepNav = `<button class="opt-btn song-next-btn song-teach-btn" data-action="song-event-next">继续 ▸</button>`;
        } else {
          // 第六步：收尾/选项
          stepContent = `<div class="song-step-content song-final-step">
            <div class="song-final-quote">「西行不止取经，亦取你心中那一关。」</div>
            <p class="song-final-hint">前方关隘之主刘洪挡路，那是你西行第一场Boss战。去吧。</p>
          </div>`;
          stepNav = `<div class="scene-opts">${opts}</div>`;
        }
        // V8.32 手机适配：步骤0-4点「继续/明白了」后，弹观音气泡盖字，点掉气泡才推进（复用 _guanyinGuide）
        const _teachTip = SongStepTip(step);
        const songBubble = (p.songBubble && _teachTip)
          ? `<div class="song-bubble-wrap" data-action="song-event-next">${this._guanyinGuide(_teachTip, 'gg-song')}</div>`
          : '';
        // 跳过教学按钮（仅步骤0-4显示，步骤5是最终选项不需要跳过）
        const skipBtn = (step < 5)
          ? `<button class="teach-skip-btn song-skip-btn" data-action="song-event-skip" title="跳过教学，直接进入最终选择">跳过教学 ⏭</button>`
          : '';
        return `<div class="scene-overlay start-overlay song-event-overlay">
          <div class="scene-modal start-modal song-event-modal">
            ${skipBtn}
            <div class="scene-head">— ${p.title || '送行'} —</div>
            ${stepIndicator}
            ${portraitHtml}
            ${stepContent}
            ${songBubble}
            ${stepNav}
          </div>
        </div>`;
      } else if (p.kind === 'narrative') {
        // 标题随英雄身份：取经人为「取经人·西行记事」，其余为「斗法回·悟空小说」（由 game.js 按英雄生成 p.title）
        title = p.title || '西行 · 择';
        // 战斗结束后的小说叙事改为弹框，浮于地图之上，不挤压底层画面
        return `<div class="scene-overlay narrative-overlay">
          <div class="scene-modal narrative-modal">
            <div class="novel-ink">
              <div class="novel-title">— ${title} —</div>
              <p class="novel-text" id="narr-text"></p>
              ${p.restAtGate ? `<button class="opt-btn novel-btn" data-action="gate-meditate">打坐回寿（此炷香仅一回）▸</button>` : ''}
              ${p.retuneDao ? `<button class="opt-btn novel-btn" data-action="open-dao-retune">☯ 重立道心（改道）▸</button>` : ''}
              <button class="opt-btn novel-btn" data-action="narrative-next">${p.next || '继续西行'} ▸</button>
            </div>
          </div>
        </div>`;
      } else if (p.kind === 'vault-pick') {
        // 万世剑冢·成亡节点 二选一（V8.56）：衣冠冢=装备或组件；舍利塔=装备或经文。按拾取次数衰减（100/70/40）。灵活返回，不挤压底层地图。
        const op = p.op || {};
        const _isShrine = op.kind === 'shrine';
        const _name = _isShrine ? '舍利塔' : '衣冠冢';
        const _loc = (NDX.ACT_NAMES && NDX.ACT_NAMES[Math.min((op.region || 1) - 1, (NDX.ACT_NAMES || []).length - 1)]) || ('第' + (op.region || 1) + '地区');
        const _multPct = Math.round((op.mult || 1) * 100);
        const _decayNote = (op.mult || 1) >= 1
          ? `此节点首度拾取，${_name}灵光全盛——奖励属性 ×100%`
          : `此节点已拾取 ${op.nextCount || 0} 次，${_name}微芒渐敛——奖励属性 ×${_multPct}%（只留属性，不触发后续链）`;
        const _optRow = (o, i) => {
          const _tag = o.kind === 'equip' ? '装备' : (o.kind === 'sutra' ? '经文' : '组件/红材');
          const _sub = o.count != null ? ` ×${o.count}` : '';
          return `<button class="vault-opt" data-action="vault-opt" data-idx="${i}">
            <span class="vault-cat">${_tag}</span><b>${o.name}</b>${_sub ? `<span class="vault-sub">${_sub}</span>` : ''}<span class="vault-go">取</span>
          </button>`;
        };
        if (!op.opts || !op.opts.length) {
          return `<div class="frame"><div class="monu-wrap"><h2 class="death-title">${_name}空空</h2><p class="death-hint">此行两手空空，无从拾取。</p><button class="big-btn" data-action="vault-close">关</button></div></div>`;
        }
        return `<div class="frame">
          <div class="monu-bg" aria-hidden="true"></div>
          <div class="monu-wrap">
            <h2 class="death-title">${_isShrine ? '舍利塔 · 返程坐化' : '衣冠冢 · 前人遗蜕'}</h2>
            <p class="death-reason">${_loc} ← ${_name}，几世的魂在此守候。</p>
            <p class="monu-lead">${_isShrine ? '抵西天后返程坐化，舍利长明当道' : '中途倒下的行脚在此立碑'}——${_isShrine ? '可拾装备 或 经文' : '可拾装备 或 组件/红材'}，只取其一。${_decayNote}</p>
            <div class="monu-grid">${op.opts.map(_optRow).join('')}</div>
            <p class="death-hint">${_name}记名 · 下世复得遗珍</p>
          </div>
        </div>`;
      } else if (p.kind === 'gameover') {
        // 失败屏：全屏卷轴风画面 + 返回主界面按钮（独立于面板的死亡画面）
        return this.deathScreen(s);
      } else if (p.kind === 'win') {
        const r = s.over.result;
        const e = r.ending || { title: '灵山不过', text: '' };
        const portraitHtml = hero && hero.portrait
          ? `<div class="win-stand"><img class="hero-portrait" src="${hero.portrait}" alt="${hero.name}" /></div>`
          : '';
        title = `脱局 · 结局 ${e.title}`;
        body = `${portraitHtml}<div class="result">
          <p class="ending-text">${e.text}</p>
          <hr class="end-hr">
          <p>评价 <b>${r.rank}</b> ｜ 剩余生命 ${r.hpLeft}/${r.maxHp}（${r.hpPct}%）</p>
          <p>体·攻 ${r.ti.atk} ｜ 护体 ${r.ti.dr}% ｜ 身法 ${r.ti.eva}% ｜ 装备 ${r.equips}</p>
          <p>愿·伤 ${r.yuan.matk} ｜ 御念 ${r.yuan.mdef}% ｜ 善 ${r.good} ｜ 恶 ${r.evil} ｜ 金 ${r.gold}</p>
          <button class="big-btn" data-action="restart">再走一遍</button></div>`;
      }
      // 战斗 / 结算类画面（战斗、战利三选一、精英战利、宝窟、关隘三选一、劫印三选一、战斗结算）采用浮层弹窗，
      // 浮于地图之上、不挤压底层画面（底层地图/属性栏仍透过半透明可见）。
      // 土地庙及其子面板（歇息/淬炼/磨锋/劫印·道途层数/释经/弃印/祭事）统一浮层弹窗，浮于地图之上，适配手机屏
      const _modalKinds = {
        gift: 1, elitereward: 1, equip: 1, bossreward: 1, seal: 1,
        'bless-seal': 1, 'bless-treasure': 1, winresult: 1,
        rest: 1, forge: 1,
        sealbar: 1, abandon: 1
      };
      if (_modalKinds[p.kind]) {
        return `<div class="scene-overlay reward-overlay"><div class="scene-modal reward-modal ${esc(String(p.kind))}-modal"><div class="panel-title"><span class="panel-corner">择</span>${title}</div><div class="panel-body">${body}</div></div></div>`;
      }
      return `<div id="panel"><div class="panel-title"><span class="panel-corner">择</span>选择画面 · ${title}</div><div class="panel-body">${body}</div></div>`;
    }
});
