// AUTO-GENERATED by _refactor_split.js — domain: panel
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  _fightTreasureBar(s) {
      const inFight = s.pending && s.pending.kind === 'fight';
      if (!inFight) return '';
      const activeIds = NDX.activeEquipsFor ? NDX.activeEquipsFor(s).map((x) => x && x.id) : [];
      const treasures = (s.equips || []).filter((e) =>
        e.treasure && activeIds.includes(e.id) && (function () { const T = NDX.TREASURES && NDX.TREASURES[e.treasureId]; return T && (T.phase === 'in' || T.phase === 'both'); })()
      );
      if (!treasures.length) return '';
      const p = s.pending;
      // P0-5 教学战临阵祭宝引导：第3回合起高亮第一个可用法宝
      const isTutorialTre = p && p.teach === 'tutorial' && (p.roundIdx || 0) >= 2;
      let _treTeachDone = false;
      const btns = treasures.slice(0, 6).map((e) => {
        const ch = (e.chargesLeft == null ? (e.charges || 0) : e.chargesLeft);
        const tid = e.treasureId;
        const T = NDX.TREASURES[tid] || {};
        const tier = NDX.treasureTier(tid);             // white / blue / gold / red
        const manual = NDX.treasureGrade(tid) === 'high'; // 金/红须手动
        const used = (p && p.opUsed && p.opUsed.includes(tid));
        const cdRemain = (p && p.treasureCd && p.treasureCd[tid]) || 0;
        const tip = (T.desc ? T.desc + ' ｜ ' : '') + '点击即可打断 AI 普攻，优先释放此宝';
        let cls = 'fb-tre ' + (manual ? 'tre-manual ' : 'tre-auto ') + 'tier-' + tier;
        // V8.50 法宝克制·可解高亮：此宝能解当前玩家侧 debuff 时，脉冲提示临阵祭出
        if (T.effect && T.effect.cleanse && p.pDebuffs && T.effect.cleanse.some((t) => p.pDebuffs[t])) {
          cls += ' can-cleanse';
        }
        if (tier === 'red') cls += ' tre-red-unique '; // 红色法宝一局仅一件：图标放大一圈
        // P0-5: 教学战中第一个可用法宝添加高亮
        const isReady = !(cdRemain > 0 || ch <= 0 || used);
        const isTreTeach = isTutorialTre && isReady && !_treTeachDone;
        if (isTreTeach) { _treTeachDone = true; cls += ' teach-highlight'; }
        let inner = `<span class="fb-tre-icon">${e.icon || '☯'}</span><span class="fb-tre-name">${e.name}</span>`;
        if (isTreTeach) inner += '<div class="teach-bubble">点击法宝，临阵祭宝</div>';
        if (cdRemain > 0) {
          cls += ' on-cd';
          inner += `<span class="fb-tre-cd">${cdRemain}</span><span class="fb-tre-mask"></span>`;
        } else if (ch <= 0) {
          cls += ' depleted';
          inner += `<span class="fb-tre-state">已尽</span><span class="fb-tre-mask"></span>`;
        } else if (used) {
          cls += ' used';
          inner += `<span class="fb-tre-state">已用</span><span class="fb-tre-mask"></span>`;
        } else {
          cls += ' ready';
        }
        if (manual) inner += `<span class="fb-tre-manual">手动</span>`;
        const disabled = (cdRemain > 0 || ch <= 0 || used) ? 'disabled' : '';
        // data-tre-popup 供长按弹出详情（不触发释放）；data-action=op-manual 供单指点击释放
        return `<button class="${cls}" data-action="op-manual" data-tid="${tid}" data-tre-popup="${tid}" title="${tip}" ${disabled}>${inner}</button>`;
      }).join('');
      const slots = Math.max(0, 6 - treasures.slice(0, 6).length);
      const empty = slots > 0 ? `<span class="fb-tre fb-tre-empty">空</span>`.repeat(slots) : '';
      return `<div class="fb-tre-grid"><span class="fb-tre-label">法宝栏 · 点此打断普攻</span><div class="fb-tre-cells">${btns}${empty}</div></div>`;
    }
});
