// AUTO-GENERATED by _refactor_split.js — domain: trial
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  _trialCurtain(s) {
      const p = (s && s.pending) || {};
      const kind = p.kind;
      if (kind !== 'trial' && kind !== 'elite' && kind !== 'boss') return '';
      const diff = p.diff || s.diff || NDX.globalProgress(s);
      const libName = (NDX.TRIAL_LIB && NDX.TRIAL_LIB[diff] && NDX.TRIAL_LIB[diff].name) || '';
      const t = (p.title && p.title.trim()) || libName || '此劫难';
      // 地区开场叙事：进入本地区首难时，幕布附上 regionIntro（地区专属文案厚度）
      let introLine = '';
      try {
        const _range = (NDX.ACT_RANGES || []).find((r) => diff >= r.start && diff <= r.end);
        if (_range) {
          const _theme = NDX.ACT_MAP_THEME && NDX.ACT_MAP_THEME[_range.act];
          if (_theme && _theme.regionIntro && _range.start === diff) {
            introLine = `<span class="tc-region">${esc(_theme.regionIntro)}</span>`;
          }
        }
      } catch (e) { /* 地区开场缺失不影响幕布 */ }
      return `<div class="trail-curtain" data-diff="${diff}">
          <span class="tc-badge">第 ${diff} 难</span>
          <span class="tc-name">${esc(t)}</span>
          <span class="tc-sub">八十一难 · 步步劫</span>
          ${introLine}
        </div>`;
    },
  _trialHead(diff, name) {
      return `第${this._cnNum(diff) || (diff != null ? diff : '')}难 · ${name || '劫难'}`;
    }
});
