// AUTO-GENERATED by _refactor_split.js — domain: toast
NDX.ui = NDX.ui || {};
Object.assign(NDX.ui, {
  showLootToast(name, desc, mode) {
      mode = mode || 'gain';
      this._toastQueue.push({ name: name, desc: desc || '', mode: mode });
      if (!this._toastBusy) this._drainToast();
    },
  toast(msg) {
      if (!msg) return;
      const t = document.createElement('div');
      // 检测是否为教学类提示
      const isTeaching = /教学|系统|劫印|寿数|心魔|西行|六道|战斗|装备|法宝|地图/.test(msg);
      t.className = isTeaching ? 'game-toast game-toast-teaching' : 'game-toast';
      t.textContent = msg;
      (window.__ndxOverlay || document.body.appendChild.bind(document.body))(t);
      requestAnimationFrame(() => t.classList.add('game-toast-show'));
      // 教学类提示显示更久（4秒），普通提示1.8秒
      const duration = isTeaching ? 4000 : 1800;
      setTimeout(() => {
        t.classList.remove('game-toast-show');
        setTimeout(() => { if (t.parentNode) t.parentNode.removeChild(t); }, 400);
      }, duration);
    },
  _drainToast() {
      const self = this;
      const next = this._toastQueue.shift();
      if (!next) { this._toastBusy = false; return; }
      this._toastBusy = true;
  
      const isCraft = next.mode === 'craft';
      const isInit = next.mode === 'init';
      const icon = isCraft ? '⚒' : (isInit ? '❖' : '✦');
      const title = isCraft ? '炼 成' : (isInit ? '行 囊' : '意外之喜');
      const msg = isCraft
        ? `恭喜玩家合成装备<br><span class="loot-toast-name">${next.name}</span>`
        : (isInit
          ? `初始装备入囊<br><span class="loot-toast-name">${next.name}</span>`
          : `恭喜玩家意外获得装备<br><span class="loot-toast-name">${next.name}</span>`);
  
      const old = document.getElementById('loot-toast');
      if (old) old.remove();
  
      const toast = document.createElement('div');
      toast.id = 'loot-toast';
      if (isCraft) toast.classList.add('loot-toast-craft');
      toast.innerHTML = `
        <div class="loot-toast-bg"></div>
        <div class="loot-toast-card">
          <div class="loot-toast-icon">${icon}</div>
          <div class="loot-toast-title">${title}</div>
          <div class="loot-toast-msg">${msg}</div>
          <div class="loot-toast-desc">${next.desc}</div>
        </div>`;
      (window.__ndxOverlay || document.body.appendChild.bind(document.body))(toast);
  
      const HOLD = isCraft ? 2400 : 1900;
      setTimeout(() => {
        toast.classList.add('loot-toast-out');
        setTimeout(() => {
          if (toast.parentNode) toast.remove();
          self._drainToast();
        }, 480);
      }, HOLD);
    }
});
