// AUTO-GENERATED by _refactor_split.js — domain: meta
NDX.Game.prototype.stats = function stats() {
    const s = this.state;
    // V8.56 万世剑冢·经文衰减：由舍利塔地图节点以 <100% 拾得的经文，按其 _sutraMult 缩放被动（只留部分属性）
    const _sutraScale = (eff, id) => {
      if (!eff) return null;
      const m = (s._sutraMult && s._sutraMult[id]) || 1;
      if (m >= 1) return eff;
      const sc = Object.assign({}, eff);
      if (eff.ti) { sc.ti = Object.assign({}, eff.ti); for (const k of Object.keys(sc.ti)) if (typeof sc.ti[k] === 'number') sc.ti[k] = sc.ti[k] * m; }
      if (typeof eff.matk === 'number') sc.matk = eff.matk * m;
      if (typeof eff.mdef === 'number') sc.mdef = eff.mdef * m;
      return sc;
    };
    const sutraEffs = (s.sutras || []).map((id) => _sutraScale((NDX.sutraFullById && NDX.sutraFullById(id) || {}).effect, id)
      ).filter(Boolean).concat(
      // 逆道经文全本（选逆攒齐自动合成）：与佛经全本同管线并入被动战力
      (s.niSutras || []).map((id) => _sutraScale((NDX.niSutraFullById && NDX.niSutraFullById(id) || {}).effect, id)).filter(Boolean)
    );
    // 经文宏愿·数量加成（V8.35）：按集齐经文总数分档给全属性加成 + 主攻道专属加成
    const _sutraCountEff = NDX.sutraCountBonus && NDX.sutraCountBonus(s);
    if (_sutraCountEff) sutraEffs.push(_sutraCountEff);
    // 隐藏职加成：从已确认转职抽取 effect.bonus，叠加进面板（不替换英雄原基础属性）
    let jobTi = Object.assign({}, s.bonusTi), jobYuan = Object.assign({}, s.bonusYuan);
    let goodAdd = 0;
    const jobKey = s.flags.jobConfirm;
    if (jobKey) {
      let jobHit = null;
      for (const k of Object.keys(NDX.HIDDEN_JOBS || {})) {
        const hit = (NDX.HIDDEN_JOBS[k] || []).find((x) => x.job === jobKey);
        if (hit) { jobHit = hit; break; }
      }
      if (jobHit && jobHit.effect && jobHit.effect.bonus) {
        const b = jobHit.effect.bonus;
        if (b.ti) for (const k of Object.keys(b.ti)) jobTi[k] = (jobTi[k] || 0) + b.ti[k];
        if (b.yuan) for (const k of Object.keys(b.yuan)) jobYuan[k] = (jobYuan[k] || 0) + b.yuan[k];
        if (b.good) goodAdd = b.good;
      }
    }
    const base = NDX.computeStats(s.hero, s.equips, s.materials, { ti: jobTi, yuan: jobYuan, sutras: sutraEffs, seals: s.seals, followers: s.followers, tier: (NDX.ZHUANJIE ? NDX.ZHUANJIE.tierBonus(s) : null), daoxinTier: NDX.daoxinTier(s) }, s.diff, s.act);
    // V8.40 属性后处理：通过统一模块NDX.AttrCalc.applyPostProcessing()处理全部10项后续逻辑
    if (NDX.AttrCalc && typeof NDX.AttrCalc.applyPostProcessing === 'function') {
      NDX.AttrCalc.applyPostProcessing(s, base, sutraEffs);
    } else {
    // 降级：旧逻辑（后续处理）
    // 上限百分比加成（来自 maxhpPct 类效果）作用于体·气血；心魔战失败削减本局气血上限
    base.ti.maxHp = Math.round(base.ti.maxHp * (1 + (s.maxhpPctBonus || 0)) * (1 - (s.xinmoMaxHpLoss || 0)));
    // 阶段六·劫灰「金蝉余韵」全局气血 +% 已由 P0-C 移除（横向解锁传承英雄），此处不再叠加
    // Boss 遗物（跨 Act 永久被动）并入面板
    (s.relics || []).forEach((rel) => {
      const ef = (NDX.BOSS_RELICS.find((r) => r.id === rel) || {}).effect || {};
      if (ef.atkPct) base.ti.atk = Math.round(base.ti.atk * (1 + ef.atkPct));
      if (ef.matkPct) base.yuan.matk = Math.round(base.yuan.matk * (1 + ef.matkPct));
      if (ef.hpPct) { base.ti.maxHp = Math.round(base.ti.maxHp * (1 + ef.hpPct)); base.hp = base.ti.maxHp; }
      if (ef.dr) base.ti.dr = Math.min(0.85, base.ti.dr + ef.dr);
      if (ef.mdef) base.yuan.mdef = Math.min(0.85, base.yuan.mdef + ef.mdef);
      if (ef.eva) base.ti.eva = Math.min(0.6, base.ti.eva + ef.eva);
      if (ef.shieldPct) s._relicShieldPct = Math.max(s._relicShieldPct || 0, ef.shieldPct);
      if (ef.regenPct) s._relicRegenPct = Math.max(s._relicRegenPct || 0, ef.regenPct);
    });
    // 师徒缘（V8.17）：徒弟被动增益并入面板（血上限/减伤/战后回血）
    const _db = NDX.discipleBonus(s);
    if (_db.hp) { base.ti.maxHp = Math.round(base.ti.maxHp + _db.hp); base.hp = base.ti.maxHp; }
    if (_db.dr) base.ti.dr = Math.min(0.85, base.ti.dr + _db.dr);
    if (_db.hpRegen) base.ti.hpRegen = (base.ti.hpRegen || 0) + _db.hpRegen;
    // 佛经全本被动（恶线·自己西游专属隐藏战力）：体攻/气血/法伤/法防已由 computeStats(bonus.sutras) 并入，
    // 此处仅补「百分比类」与「暴击/自愈」字段（佛经 effect 兼容 maxhpPct/healPct/crit）
    sutraEffs.forEach((ef) => {
      if (ef.maxhpPct) base.ti.maxHp = Math.round(base.ti.maxHp * (1 + ef.maxhpPct));
      if (ef.healPct) base.ti.hpRegen += Math.round(base.ti.maxHp * ef.healPct);
      if (ef.crit) base.ti.cri = Math.min(1, (base.ti.cri || 0) + ef.crit);
    });
    // 金箍：战力暴涨百分百（+100% 体攻）。悟空走暗线不戴金箍时，残留妖性爆发作为补偿，
    // 避免「不戴金箍=体攻腰斩、后期必崩」的设计失衡（暗线体攻 +35%、体气血 +20%）。
    if (s.flags && s.flags.jingu) {
      base.ti.atk = Math.round(base.ti.atk * 2);
    } else if (s.hero === 'wukong') {
      base.ti.atk = Math.round(base.ti.atk * 1.35);
      base.ti.maxHp = Math.round(base.ti.maxHp * 1.2);
    }
    // 隐藏职善值加成（如弃经金蝉 +10 善）
    if (goodAdd) base.yuan.good = (base.yuan.good || 0) + goodAdd;
    // 双线赐福（秩序/混沌）百分比乘区：对接轮回殿最终定稿 NDX.applyBlessing
    // 仅当玩家已升级过任一线时生效（computeStats 之后做百分比乘算，避免数值失真）
    NDX.applyBlessing(base, NDX.loadFavor());
    // 业镜持续状态乘区：本局业镜抉择写入 s.mirror 的“百分比/标记”在此并入面板
    // （护盾/掉血/免疫等开关类状态由战斗结算读取，不在此处）
    const mr = s.mirror || {};
    if (mr.atkPct) base.ti.atk = Math.round(base.ti.atk * (1 + mr.atkPct));
    if (mr.drPct) base.ti.drPct = (base.ti.drPct || 0) + mr.drPct;   // 百分比减伤（与减法 dr 叠加）
    if (mr.bossDmgMul) base.bossDmgMul = (base.bossDmgMul || 0) + mr.bossDmgMul; // 对BOSS伤害加成
    if (mr.trueDmgLayer) base.trueDmgLayer = true;                  // 本层攻击附真实伤害（照见五蕴·龙吟）
    if (mr.voidLayer) base.voidLayer = true;                        // 本层隐形（照见五蕴·潜渊）
    // 本层最大生命 -X%（不可逆，如业镜·天兵"踏尸前行"）：直接折损气血上限
    if (mr.maxHpLossPct) base.ti.maxHp = Math.round(base.ti.maxHp * (1 - mr.maxHpLossPct));
    // 狂战血怒：生命越低伤害越高（最高 +50%）
    if (mr.bloodFury) {
      const ratio = Math.max(0, Math.min(1, s.hp / Math.max(1, base.ti.maxHp)));
      const fury = 0.5 * (1 - ratio);
      base.ti.atk = Math.round(base.ti.atk * (1 + fury));
    }
    // 挑担：负面状态转攻击力（简化：+20% 体攻）
    if (mr.negativeToAtk) base.ti.atk = Math.round(base.ti.atk * 1.2);
    // 业镜·护盾（吸收本局最大生命值 X% 伤害）/ 免疫致死 / 持续掉血：透传给战斗模拟层
    if (mr.shieldPct) base.shieldPct = (base.shieldPct || 0) + mr.shieldPct;
    if (mr.immuneDeath) base.immuneDeath = true;
    if (mr.hpDrainPct) base.hpDrainPct = (base.hpDrainPct || 0) + mr.hpDrainPct;
    // 业藏录加成（无怒气版 · 全局永久加成，与赐福/成就同池）：从缓存读取，避免每帧重算
    const cb = NDX._collBonus || {};
    if (cb.dmgBoss_coll) base.bossDmgMul = (base.bossDmgMul || 0) + cb.dmgBoss_coll;       // 对BOSS伤害
    if (cb.dmgTaken_coll) base.dmgTakenColl = (base.dmgTakenColl || 0) + cb.dmgTaken_coll;  // 受击减伤（负值=减伤）
    if (cb.breakEff_coll) base.breakEffColl = (base.breakEffColl || 0) + cb.breakEff_coll;  // 破韧效率
    if (cb.tough_coll) base.toughColl = (base.toughColl || 0) + cb.tough_coll;             // 韧性(抗打断)
    if (cb.cdRed_coll) base.cdRedColl = (base.cdRed_coll || 0) + cb.cdRed_coll;             // 法宝冷却缩减
    if (cb.miGain_coll) base.miGainColl = (base.miGainColl || 0) + cb.miGain_coll;          // 混元点获取
    if (cb.orderMultAdd_coll) base.orderMultAddColl = (base.orderMultAddColl || 0) + cb.orderMultAdd_coll; // 秩序赐福额外
    if (cb.healBoost_coll) base.healBoostColl = (base.healBoostColl || 0) + cb.healBoost_coll;             // 受治疗提升
    if (cb.dmgTianting_coll) base.dmgTiantingColl = (base.dmgTiantingColl || 0) + cb.dmgTianting_coll;     // 对天庭特攻
    if (cb.karmaSpeed_coll) base.karmaSpeedColl = (base.karmaSpeedColl || 0) + cb.karmaSpeed_coll;         // 业障积累速度(逆道)
    } // end of else (降级旧逻辑)
    return base;
  };
NDX.Game.prototype.pushLog = function pushLog(s) {
    this.state.log.unshift(s);
    if (this.state.log.length > 60) this.state.log.pop();
  };
NDX.Game.prototype._loseLife = function _loseLife(amount) {
    const s = this.state;
    if (!s || s.over || !amount || amount <= 0) return s && s.life;
    // V8.58 新手教学触发：第一次耗寿时触发寿数教学（n3_life_hud）
    try {
      if (!s.flags._lifeTeachTriggered && NDX.NewbieTeach && NDX.triggerTeach) {
        s.flags._lifeTeachTriggered = true;
        NDX.triggerTeach('n3_life_hud', { life: s.life, amount: amount });
      }
    } catch (e) { /* noop */ }
    s.life = Math.max(0, s.life - amount);
    this._checkLife();
    return s.life;
  };
NDX.Game.prototype._checkLife = function _checkLife() {
    const s = this.state;
    if (!s || s.over) return;
    if (s.life <= 0.0001) { this._dieByLife(); return; }
    // 档位按「剩余寿岁」升序（[22]==体力尚可 → [3]==大限将至）。s.life 倒计递减，
    // 故从最险的一档往前查，只报本次新跌破且最接近极限的那一条，避免大步跨阈一次性轰炸。
    const ages = NDX.LIFE.WARN_AGE;
    for (let i = ages.length - 1; i >= 0; i--) {
      const a = ages[i];
      if (s.life <= a && !s.lifeWarned[a]) {
        s.lifeWarned[a] = true;
        this.pushLog(`【寿数】${NDX.LIFE.WARN_TXT[a]}（现 ${Math.floor(s.life)} 岁）`);
        // 阶段七·音效：寿烛将尽的低沉警示
        try { if (NDX.sound) NDX.sound.play('lifeWarn'); } catch (e) {}
        break;
      }
    }
  };
NDX.Game.prototype._dieByLife = function _dieByLife() {
    const s = this.state;
    if (!s || s.over) return;
    try { if (NDX.sound) NDX.sound.play('lifeWarn'); } catch (e) {}
    s.over = {
      win: false,
      reason: '大限将至 · 寿数已尽',
      deathNarr: `你拄杖停在 ${NDX.ACT_NAMES[(s.act || 1) - 1] || ''}的山道上，咳出一口血。这条西行路终究没走完——金蝉未脱壳，你没能把这一生的真经带回长安。`
    };
    try { if (typeof NDX.recordRunEnd === 'function') NDX.recordRunEnd(s, true); } catch (e) { console.error('recordRunEnd fail on life-end', e); }
    try { if (typeof this.bumpCycleOnce === 'function') this.bumpCycleOnce(); } catch (e) { /* noop */ }
    // 朝代系统（V8.36）：死亡时递进朝代（清之后保持清）
    try {
      if (NDX.bumpDynasty) {
        const d = NDX.bumpDynasty();
        this.pushLog(`【朝代更迭】此身陨于${NDX.ACT_NAMES[(s.act || 1) - 1] || '西行路'}，下一世转生至${d.full}。`);
      }
    } catch (e) { /* noop */ }
    this.pushLog('【寿尽】大限已至，强制坐化。');
    this._openFailSettlement();
  };
NDX.Game.prototype.settleReturn = function settleReturn() {
    const s = this.state;
    if (!s || s.over) return;
    // —— 返程演出数据（V8.55）：到西天固定耗9岁返程，以最终余寿定归乡档位；统一起源自 buildReturnScene ——
    const rt = NDX.buildReturnScene(s);
    // 舍利塔（V8.56 万世剑冢）：到西天余寿不足(SHRINE_R)返程坐化，于归途某区立「舍利塔」地图节点（供后续周目回访拾遗 装备/经文 二选一）
    if (rt && rt.grade === 'shrine') {
      let _sv = null;
      try { _sv = NDX.registerVault(s, 'shrine', rt.region); } catch (e) { /* noop */ }
      rt.stupaReward = _sv ? { region: _sv.region } : null;
      rt.acts = rt.acts || [];
      rt.acts.push({ key: '舍', text: `返程九岁，你只到归途第 ${_sv ? _sv.region : (rt.region || 17)} 区便油尽——于途坐化成舍利。诸天感念，舍利长明当道，${NDX.getDynasty ? (NDX.getDynasty().name || '唐') : '东土'}诸世行脚历此可回访拾遗（装备/经文 二选一，次数越丰衰减越盛）。` });
      this.pushLog(`【舍利塔·返程坐化】于第 ${_sv ? _sv.region : (rt.region || 17)} 区立舍利，录入万世剑冢——后世行脚可回访拾遗（装备/经文 二选一）。`);
    }
    const ending = this.computeEnding();
    // V8.55 归乡档位：回长安(grade='return')者按到西天余寿档位授朝代称号，与英雄路线结局并存展示。
    // 完美（余寿≥19，≈36岁到西天）授「朝代+僧」；不完美（9≤余寿<19，≈37-46岁到西天）授「朝代+和尚」。
    if (rt && rt.grade === 'return') {
      ending.perfect = !!rt.perfect;                       // 完美=true / 不完美=false
      ending.rankName = rt.rankName || (rt.perfect ? '取经人' : '僧人');
      ending.text = `${ending.text}\n${rt.closing || ''}`; // 补返程受封结语（含余寿与称号）
      // V8.6x 逆道开启门：达成完美通关（正果·春朝僧档）即永久解锁「逆」道六道抉择
      if (ending.perfect && NDX.savePerfectClear) NDX.savePerfectClear();
    }
    // 排行榜（V8.55）：完美/不完美双榜皆入。记录 朝代+僧(和尚) + 英雄结局(金蝉正果等) + 玩家留名 + 余寿。
    if (rt && rt.grade === 'return' && NDX.submitRank) {
      const _fate = s.fate || {};
      const _daotu = Object.keys(_fate).sort((a, b) => (_fate[b] || 0) - (_fate[a] || 0))[0] || '';
      const _dynasty = NDX.getDynasty ? NDX.getDynasty() : { name: '唐' };
      const _dynastyName = _dynasty.name || '唐';
      const _dynastyFull = (NDX.getDynasty ? NDX.getDynasty().full : '唐') || _dynastyName;
      const _rankIdx = NDX.submitRank({
        perfect: ending.perfect,
        name: ending.rankName || '无名行脚',
        heroTitle: ending.title || '',
        player: (s.playerName || ''),
        dynasty: _dynastyName,
        cycle: (NDX.getCycle ? NDX.getCycle() : 1),
        life: (rt && rt.years) || 0,
        daotu: _daotu,
        time: Date.now(),
        difficulty: s.difficulty || 'normal',
      });
      if (_rankIdx > 0) this.pushLog(`【排行榜】${ending.perfect ? '完美' : '迟归'}通关！${_dynastyFull}御封「${ending.rankName}」，余寿 ${(rt && rt.years) || 0} 年，列${ending.perfect ? '完美·朝代僧' : '迟归·朝代和尚'}榜第 ${_rankIdx} 名。`);
    }
    s.over = { win: true, reason: `灵山终 · 第 ${NDX.TOTAL_TRIALS} 难功成`, ending };
    s.over.return = rt;
    // V8.63 P1-6 二周目论道：开启（二周目+逆道感悟≥3）则先入论道三选（UI 拦截渲染，
    //   见 ui_lundao.js / game_lundao.js）。须在 bumpCycleOnce 前判定以免周目数失真；
    //   三选了断后 s.over.ending 被改写，随后照常走下方终局收束。
    if (NDX.ZHUANJIE && NDX.ZHUANJIE.lundaoOpen && NDX.ZHUANJIE.lundaoOpen(s) && !s.lundaoDone) s._lundaoStep = 0;
    // 阶段六·NG+：通关后把遗物/经文/劫印存入「引渡匣」，供下一世开局自夏承继（法宝每世独立，不复随行）
    try {
      const cnt = NDX.saveInherit ? NDX.saveInherit(s) : 0;
      if (cnt > 0) this.pushLog(`【承继】遗物、经文与劫印已存入引渡匣（本命法宝随世而散、不复传承）——转世重修，自夏重新上路。`);
    } catch (e) {}
    this.bumpCycleOnce();
    // 朝代系统（V8.36）：通关后重置朝代为夏，进入二周目
    try {
      if (NDX.resetDynasty) {
        const d = NDX.resetDynasty();
        this.pushLog(`【朝代归位】西行功成，下一世自${d.full}重新上路——八十一难，再走一遭。`);
      }
    } catch (e) { /* noop */ }
    const runRec = NDX.recordRunEnd(s, false); // 通关：清失败摘要（避免下一局误享失败补偿）
    // V8.48 埋点：单局结束（通关）
    if (NDX.telemetry) { try { NDX.telemetry.track('run_end', { win: true, layer: s.layer, col: s.col, act: s.act || 1 }); } catch (e) {} }
    // P0-3（2026-09-06）：通关终局记录经济存量快照（run_end 采样点）
    if (NDX.telemetry) { try { NDX.telemetry.track('econ_snapshot', NDX.telemetry.buildEconEvent(s, 'run_end')); } catch (e) {} }
    s.pending = { kind: 'gameover' };
    if (runRec && runRec.freshRub && runRec.freshRub.length) {
      runRec.freshRub.forEach((dao) => {
        const d = NDX.SUTRA_SIX_DAOS[dao];
        this.pushLog(`【拓印】集齐《${d.name}》全本，已永久拓印入藏书阁（${Object.keys(NDX.loadRubbing()).length}/${Object.keys(NDX.SUTRA_SIX_DAOS).length} 藏）`);
      });
      if (NDX.sixDaosComplete()) this.pushLog('【藏经】六藏经文皆已拓印——八十一难·三结局 CG 画廊已解锁！');
    }
    this.pushLog(`【终局】第 ${NDX.TOTAL_TRIALS} 难 · ${(rt && rt.grade === 'shrine') ? '返程途中坐化' : '凌云渡金蝉脱壳'}——${(rt && rt.grade === 'shrine') ? '此生留舍利' : '你跳出簿子，西行功成'}。`);
    // 记录通关：解锁二周目隐藏初始选项 + 累计通关次数
    NDX.saveClear(s.hero);
    if (NDX.bumpClearCount) NDX.bumpClearCount();
    this._syncAch(); // 结局类成就在通关时落簿
    if (NDX.bus) NDX.bus.emit('render');
  };
NDX.Game.prototype.autoSave = function autoSave() {
    try {
      const s = this.state;
      if (!s || s.over) return;
      const snap = JSON.parse(JSON.stringify(s));
      delete snap.pending; // 不保存进行中的浮层（战斗/事件），从最近安全节点继续
      snap.meta = {
        hero: s.hero,
        heroName: s.heroName,
        layer: s.layer,
        col: s.col,
        ts: Date.now(),
        version: NDX.storage.VERSION
      };
      NDX.storage.save(NDX.storage.KEYS.RUN, snap);
    } catch (e) { console.error('autoSave fail', e); }
  };
// V8.61 反馈接线批：可感性检查（Rev.4 报告 Part 8 修复）
// ① 道心档位切换：缓存 s._daoTier，档位变化即 toast+pushLog（跳过本局首次初始化）。
//    SEAl_MOD ±15% 深埋乘区不可自察——切档瞬间用世界态文案告知玩家「世界与你的印都变了」。
// ② 心魔 ≥70 预警（一次性 s.flags._xinmoWarn70）：镜像战前给"镜中影动"压迫预告。
NDX.Game.prototype._checkPerception = function _checkPerception() {
    const s = this.state;
    if (!s || !NDX.daoxinTier) return;
    // ① 道心档位
    const tier = NDX.daoxinTier(s);
    if (s._daoTier === undefined) {
      s._daoTier = tier; // 本局首查：只初始化，不播报
    } else if (s._daoTier !== tier) {
      s._daoTier = tier;
      const W = (NDX.DAOXIN && NDX.DAOXIN.WORLD && NDX.DAOXIN.WORLD[tier]) || null;
      const name = (W && W.name) || tier;
      const desc = (W && W.worldDesc) || '';
      const mod = (NDX.DAOXIN && NDX.DAOXIN.SEAL_MOD && NDX.DAOXIN.SEAL_MOD[tier]) || null;
      const modTxt = mod ? (mod.evil > 1 ? '恶印×' + mod.evil + ' / 善印×' + mod.good : '善印×' + mod.good + ' / 恶印×' + mod.evil) : '';
      try { this.toast('☯ 道心 · ' + name); } catch (e) {}
      this.pushLog('【道心】' + desc + ' 你的道心已入「' + name + '」——随身劫印之力随之偏转（' + modTxt + '）。');
    }
    // ② 心魔近满预警（≥70 一次性）
    if ((s.xinmo || 0) >= 70 && !(s.flags && s.flags._xinmoWarn70)) {
      s.flags = s.flags || {};
      s.flags._xinmoWarn70 = true;
      try { this.toast('🪞 心魔七成——镜中影动，大难将至'); } catch (e) {}
      this.pushLog('【心魔】镜中的影子越来越像你。心魔满值时，下一处劫难将被它夺走——去土地庙打坐渡化，或速战速决。');
    }
  };
NDX.Game.prototype.negotiate = function negotiate(opt) {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'negotiate') return;
    const node = p.node;
    const follower = p.follower;
    const N = NDX.NEGOTIATE || {};
    if (!s.negotiated) s.negotiated = [];
    s.negotiated.push({ node: node.name, name: node.name, act: s.act });
    if (opt.key === 'fight') {
      this.pushLog('【以经为质·罢】你收起经卷——' + node.name + ' 妖性难驯，唯刀兵相见。');
      this._startNegotiableFight(p, false);
      return;
    }
    const chance = NDX.negotiateChance(s, node);
    const ok = Math.random() < chance;
    if (ok) {
      // 成功：收服随从（免战无掉落），心魔 +0，观音好感暂停 +1
      if (!s.followers) s.followers = [];
      const cap = N.followerCap || 3;
      if (s.followers.length >= cap) {
        // V8.6x 模块九·随从满不强制挤丢：交由玩家二选——让出哪一位旧随从，或放弃新随从。
        s.pending = { kind: 'follower-replace', node, follower, oldFollowers: s.followers.slice() };
        this.pushLog('【随从】随从已满（' + cap + '/' + cap + '）——' + follower.name + ' 愿臣服入列，须你钦点一名旧随从让位。');
        this.render();
        return;
      }
      s.followers.push(follower.id);
      s.favorGatePause = (s.favorGatePause || 0) + 1;
      s.xinmo = Math.min(100, (s.xinmo || 0) + (N.xinmoSuccess || 0));
      this.pushLog('【以经为质】' + node.name + ' 折服于你——' + follower.name + ' 臣服为随从（' + follower.desc + '）！本场免战，无战斗掉落。');
      this.toast('收服随从：' + follower.name + '！');
      s.pending = { kind: 'choices' };
      this.render();
    } else {
      // 失败：妖王激怒，本场战斗 atk+10%，心魔 +8
      s.xinmo = Math.min(100, (s.xinmo || 0) + (N.xinmoFail || 8));
      this.pushLog('【谈判破裂】' + node.name + ' 怒而暴起——妖王激怒，本场战斗攻击 +' + Math.round((N.angerAtkBonus || 0.10) * 100) + '%，心魔 +' + (N.xinmoFail || 8) + '。');
      this.toast('谈判失败：' + node.name + ' 激怒！');
      this._startNegotiableFight(p, true);
    }
  };
// V8.6x 模块九·随从满钦点替换：idx = 当前随从数组下标（让位该旧随从），-1 = 放弃新随从。
NDX.Game.prototype.replaceFollower = function replaceFollower(idx) {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'follower-replace') return;
    const follower = p.follower;
    if (idx === -1) {
      this.pushLog('【随从】你拱手谢绝——' + follower.name + ' 自唤一声，化烟归山，此缘暂断。');
      this.toast('放弃收服：' + follower.name);
      s.pending = { kind: 'choices' };
      this.render();
      return;
    }
    const _oldId = (s.followers && s.followers[idx]) || null;
    if (idx < 0 || idx >= (s.followers || []).length || !_oldId) { s.pending = { kind: 'choices' }; this.render(); return; }
    const _oldDef = NDX.FOLLOWERS[_oldId];
    s.followers[idx] = follower.id;
    s.favorGatePause = (s.favorGatePause || 0) + 1;
    const N = NDX.NEGOTIATE || {};
    s.xinmo = Math.min(100, (s.xinmo || 0) + (N.xinmoSuccess || 0));
    this.pushLog('【随从】' + (_oldDef ? _oldDef.name : _oldId) + ' 闻你唤声，低头让位——' + follower.name + ' 取而代之，随列入阵（' + follower.desc + '）。');
    this.toast('收服随从：' + follower.name + '（替换 ' + (_oldDef ? _oldDef.name : _oldId) + '）');
    s.pending = { kind: 'choices' };
    this.render();
  };
NDX.Game.prototype.evaluate = function evaluate() {
    const s = this.state;
    const st = this.stats();
    const hpPct = s.hp / st.ti.maxHp;
    let rank = 'C';
    if (hpPct >= 0.8 && s.equips.length >= 12) rank = 'S';
    else if (hpPct >= 0.5) rank = 'A';
    else if (hpPct >= 0.25) rank = 'B';
    return {
      rank,
      hpLeft: s.hp,
      maxHp: st.ti.maxHp,
      hpPct: Math.round(hpPct * 100),
      ti: { atk: st.ti.atk, dr: Math.round(st.ti.dr * 100), eva: Math.round(st.ti.eva * 100) },
      yuan: { matk: st.yuan.matk, mdef: Math.round(st.yuan.mdef * 100) },
      equips: s.equips.length,
      gold: s.gold,
      good: s.good,
      evil: s.evil,
    };
  };
NDX.Game.prototype.computeEnding = function computeEnding() {
    const s = this.state;
    const hero = s.hero;
    const good = s.good || 0;
    const evil = s.evil || 0;
    const fate = s.fate || {};
    const evilPath = evil > good || (fate['逆'] || 0) + (fate['战'] || 0) + (fate['夺'] || 0) > (fate['渡'] || 0) + (fate['隐'] || 0);

    if (hero === 'tangseng' && !evilPath) {
      return {
        title: '金蝉正果',
        text: `八十一难历历在心，你仍以慈悲渡尽劫波。凌云渡上，金蝉脱去的不是凡壳，而是最后一丝执妄。佛光不惊不怖，你合掌低眉——这一局，${s.heroName || '取经人'}如愿成佛，真经东归。`,
      };
    }
    if (evilPath) {
      return {
        title: '一魄转世',
        text: '你走到灵山脚下，却不愿跪。经不必取，佛不必见，天命更不必认。横刀向颈，血溅凌云渡——肉身沉水，只留一魄不灭，投胎来世，再走一条更野的路。',
      };
    }
    if (hero === 'wukong') {
      return {
        title: '大圣脱局',
        text: '金箍不在，簿子无名。你棒指雷音，笑了一声，转身逆云而去。八十一难困得住取经人，困不住那只醒了的猴子。',
      };
    }
    if (hero === 'bajie') {
      return {
        title: '净坛圆觉',
        text: '钉耙在肩，本是要散伙回高老庄的。你却一步步走了下去，走到灵山时才发现——不是佛法渡了你，是你替这一路贪嗔痴，尽数作了抵。佛赐你净坛使者，你笑拒：回高老庄，替翠兰扶一亩春。',
      };
    }
    if (hero === 'shaseng') {
      return {
        title: '卷帘归真',
        text: '流沙河的九次回回落成一串念珠，戴在你腕上，一颗是罪，一颗是守。你跪到灵山前，不是为了成佛，是想让那盏打碎的琉璃盏，有个人替它跪到头。佛法无声，唯有卷帘声起——你成了第一个「不说话」的罗汉。',
      };
    }
    if (hero === 'xiaobailong') {
      return {
        title: '白龙渡海',
        text: '化龙那一刻，你才明白：不是灵山择你，是你终于不再由父命、由天规、由那根勒着四蹄的缰绳摆布。南海潮涨三千丈，你驮着那卷经，也驮着被剥落的旧鳞一起归海——从此你是自己的龙王，自由东归——那卷经替你驮到了，你便再不必被人骑。',
      };
    }
    return {
      title: '逆道西行',
      text: '你走过八十一难，虽未成佛，却也未输。西游簿上少了一笔，天地间多了一条不认命的路。',
    };
  };
