// AUTO-GENERATED by _refactor_split.js — domain: event
NDX.Game.prototype.start = function start(heroId, mode) {
    NDX.syncYezanglu(); // 初始化业藏录加成缓存（旧档已收集项生效）
    if (!heroId) heroId = NDX.HERO_ORDER[0] || 'tangseng';
    // V8.35 新开一局：清除上次自动断点存档（防止旧档残影干扰）
    NDX.Game.clearRunSave();
    const _isTJ = (mode === 'tianjie');
    NDX.setTianJieMode(_isTJ);
    // V8.35 种子分享：开局用种子生成地图（NDX.pendingSeed 为首页输入的种子码，否则随机）
    // 非天道劫模式才启用种子；天道劫沿用自身地图源
    const _seedNum = (!_isTJ && typeof NDX.pendingSeed === 'number') ? NDX.pendingSeed : Math.floor(Math.random() * 2147483647);
    // P1 Seed 播种扩展：把开局 seed 派生整局候选流（runRng），供劫印/装备三选一候选随机消费，
    // 使同种子下候选流可复现（可复盘可测平衡）。战斗过程随机不受约束。天道劫沿用自身随机。
    if (!_isTJ && NDX.initRunRng) NDX.initRunRng(_seedNum);
    if (!_isTJ) {
      // 用种子流生成整张地图：同一种子必然得到相同布局（战斗/掉落仍随机）
      NDX.withSeed(_seedNum, () => { NDX.generateMap(1); });
    } else {
      NDX.generateTianJieMap();
    }
    const hero = NDX.HEROES[heroId];
    const base = NDX.playerBaseAt(1, hero);
    // —— 阶段六 · NG+ 转世承继：读「引渡匣」，把上世本命家当/遗物/佛经带回这一世 ——
    const _inh = (NDX.loadInherit ? NDX.loadInherit() : null);
    const _carry = (!_isTJ && _inh && _inh.hero === heroId) ? _inh : null;
    const _cEq = (_carry && (_carry.equips || [])) || [];
    const _cRel = (_carry && (_carry.relics || [])) || [];
    const _cSut = (_carry && (_carry.sutras || [])) || [];
    const _cNiSut = (_carry && (_carry.niSutras || [])) || [];
    const _cSeal = (_carry && (_carry.seals || [])) || [];   // V8.56 完美/不完美结局自长安出发 100% 承继劫印
    // (V8.56 万世剑冢：衣冠冢/舍利塔改为地图节点回访拾取，不再开局即时承接旧装备；见 data_vault.js)
    // —— 万世剑冢式 · 传承衰减（V8.21）：跨周目承继每世 -20%，第5世破损销毁 ——
    // 取消局内「打磨/磨损」。本命承继物按世衰减（×1→0.8→0.6→0.4）；
    // 超过承继上限(INHERIT_MAX_USES)者至此破损，不再随行（专属必可重历重得，无需永不消除兜底）。
    const _inheritBroken = [];
    {
      const _keep = [];
      for (const e of _cEq) {
        if (!e) continue;
        const nu = (e.uses || 0) + 1;                       // 本世为第 nu 次承继
        if (nu > (NDX.INHERIT_MAX_USES || 4)) { _inheritBroken.push(e.name || '传承神器'); continue; }
        e.uses = nu;                                        // 记录本世所历次数，供 computeStats 按世衰减
        _keep.push(e);
      }
      _cEq.length = 0;
      _cEq.push(..._keep);
    }
    // 永久劫印槽（§11.2 劫印拓印）：劫灰商店解锁的额外席位，各品阶统一扩
    const _sealExt = NDX.sealBonusSlots ? NDX.sealBonusSlots() : 0;
    const _carrying = _cEq.length + _cRel.length + _cSut.length + _cNiSut.length + _cSeal.length;
    this.state = {
      hero: heroId,
      heroName: hero.name,
      heroSys: hero.sys,        // 本英雄主线体系 ti / yuan
      act: 1,                    // 当前章节（1~TOTAL_ACTS），转章时 +1；缺失会导致 Boss 难度取表越界
      layer: NDX.START_LAYER || 0,
      col: 0,                    // 开局处于逻辑起点层，尚无具体节点（第 1 层多节点由 choices 提供）
      diff: 1,
      difficulty: (NDX.settings && NDX.settings.nextDifficulty) || 'normal',      // V8.40 难度选择：easy/normal/hard/hell，影响怪物强度和奖励倍率
      bonusTi: { atk: 0, hp: 0, dr: 0, eva: 0, maxHp: 0, cri: 0, criMult: 0, lifesteal: 0, matk: 0 },     // 体（肉身·物理）
      bonusYuan: { matk: 0, mdef: 0 },               // 愿（心念·法术）
      campShieldPct: 0,        // 土地神龛「舍利·金刚」相：每级开局气血护盾比例（并入 result.shieldPct）
      maxhpPctBonus: 0,
      relics: _cRel.slice(),             // 已获得的 Boss 遗物（跨 Act 永久持有）；NG+ 承继上世遗物
      _relicShieldPct: 0,
      _relicRegenPct: 0,
      equips: _cEq.slice(),
      shownEquips: [],
      gold: 0,
      good: 0,
      evil: 0,
      xinmo: 0,                    // 心魔值 0~100：顺命(渡/缘)=0，争/夺/逆/隐累积；满 100 触发镜像战
      xinmoChGain: 0,              // 单章心魔累计增幅（受 CHAPTER_CAP 封顶，转章复位）
      xinmoBattles: 0,             // 每局心魔镜像战计数（≤ BATTLE_CAP，达上限后不再满值复现）
      xinmoMaxHpLoss: 0,           // 本局因心魔战失败累积的气血上限削减比例
      firstEvilWarned: false, // 是否已就"违背佛祖规则"弹出过首次警示
      taught: {},              // 剧情劫难同步教学：已触发过的引导标记 {mob,trial,boss}，避免弹窗轰炸
      materials: {},
      sutraFrags: {},          // 佛经散件 {碎片id: 数量}：恶线（自己西游+恶）劫难掉落，合成全本后清空对应碎片
      sutras: _cSut.slice(),              // 已合成佛经全本 id 列表：由 computeStats 读取提供被动战力（NG+ 承继经文）
      niSutraFrags: {},        // 逆道经文碎片 {碎片id: 数量}：选「逆」道即随机拾得，攒齐 3 段自动合成
      niSutras: _cNiSut.slice(),            // 已合成逆道经文全本 id 列表：由 computeStats 读取提供被动战力（NG+ 承继经文）
      chantSutra: null,               // 方案X1·持诵位：当前持诵全本 id（渡/逆皆可，经匣内设置；null=本命诵经）
      trialsPassed: [],        // 经过的劫难记录 [{diff, act, name}]，隐藏专职/组件合成前置校验依据
      fateStats: { trials: 0, kills: 0, events: 0 }, // 缘分门槛（V8.17）：本章渡难/降妖/缘遇计数
      mission: { trials: 0, mob: 0, elite: 0, events: 0 }, // 关隘必修任务（v2）：本章已历的 劫难/小怪/精英/事件 计数
      _tailOpen: false,      // 关隘动态尾：是否已进入「任务驱动」补齐路径
      disciples: [],           // 师徒缘（V8.17）：已收徒弟 id 列表（被动增益 + 劫灰结算）
      followers: [],           // 逆道谈判·随从（《竞品借鉴》§3）：已收服妖王随从 id 列表（上限 NDX.NEGOTIATE.followerCap，战斗助战）
      negotiated: [],          // 逆道谈判记录 [{node, name, ok, chance, act}]：本局已谈判节点，防重复
      baiguToken: false,       // 白骨令牌（第10难隐选项获得）：Boss 谈判成功率 +20%
      favorGatePause: 0,       // 观音好感暂停次数（方案A）：每收 1 随从 +1，favorGate 触发时消耗 1 次跳过加成，无死局
      fate: {},                // 劫难/抉择倾向累计：{战,隐,夺,渡,逆}
      mainDao: null,           // V8.34 地区配额制：当前地区主攻道（进入配额地区时六选一；第一章 null）
      quota: {},               // V8.34 地区配额计数：{battle,elite,ferry,war,yuan,yin,duo,rebel,chant,xinmo,rest,sutra}（进新地区复位）
      seals: _cSeal.slice(),          // 已获劫印列表（V8.56 自长安结局可承继读回）：单局肉鸽构筑层，单局结束清空
      sealTierCap: { white: 3 + _sealExt, blue: 2 + _sealExt, gold: 1 + _sealExt }, // 全局劫印层数上限（白≤3/蓝≤2/金≤1，合计≤12；劫印拓印各品阶+_sealExt）
      flags: { nextFull: false, nextWeak: 0, nextGoldDouble: false, lostHeart: 0, tsHidden: false, hiddenJobReady: {}, gotInitGift: {} },
      petQuality: 0,    // 灵宠品质档：0=凡器 1=灵器 2=宝器（影响属性倍率×1.0/1.3/1.6）
      petBranch: null,  // 灵宠进化分支：dragon/ape/fox/jinchan/crane/qilin/gu/renshen/water/fire/light
      history: [],
      visited: [],
      hp: base.hp,
      // 寿命系统（阶段一）——限时一生的第一资源
      life: NDX.LIFE.START,
      lifeMax: NDX.LIFE.MAX - (NDX.lifeTighten ? NDX.lifeTighten(1, (NDX.getCycle ? NDX.getCycle() : 1)).maxPenalty : 0),
      lifeWarned: {},          // 已触发过的余寿压迫档位（22/15/8/3），防重复弹
      mode: 'outbound',        // outbound 去程 / return 返程（阶段一以去程消耗为主，返程做结算档位）
      _sutraMult: {},           // V8.56 万世剑冢·经文衰减：{经文id: 0.7/0.4}，stats() 据此缩放被动（只留部分属性）
      seed: (!_isTJ) ? NDX.encodeSeed(_seedNum) : null,  // V8.35 地图种子码（种子分享·可复制挑战同布局）
      _startTime: Date.now(),  // V8.35 本局开始时间戳（长安大本营行迹统计·游玩时长）
      pending: null,
      advLowStreak: 0,          // V8.51 游历散宝·小怪掉率保底：连续未掉次数
      over: null,
      log: [],
      achievements: [],       // 当前周目已解锁成就 id（跨周目历史并集见 NDX.loadAch）
      // V8.5C《竞品借鉴》：罪业贸易 + 土地神龛（局内长期 meta）
      sinUsed: { evil: [], good: [] },   // 妖魔法相/度化功德 已购档位（每档一次）
      campLevel: 0,              // 土地神龛等级 0..MAX
      campBless: null,           // 神龛相性（舍利·威武/安忍/长命），首级时择
      curses: [],                // P0-3 西行劫难词条（通关解锁开局自选 1~3 条负面条件）：见 NDX.CURSE_TABLE
    };
    const s = this.state;
    // (V8.56 万世剑冢：衣冠冢改为地图节点回访拾取，不再开局随行装备；见 data_vault.js)
    // 阶段六·NG+：兑现引渡匣（一次性），把承继到家当记进开局日志
    if (_carrying > 0) {
      if (NDX.clearInherit) { try { NDX.clearInherit(); } catch (e) {} }
      s.inheritedCarry = { equips: _cEq.length, relics: _cRel.length, sutras: _cSut.length, niSutras: _cNiSut.length, seals: _cSeal.length };
      // 轴二·承继账随世带：读回上世写匣的 ledger，转成 {type:id → {times}} 供本世 saveInherit 递增；
      // 同时摊成 inheritPreview（逐件外显名+已承世数），供 UI 开局弹「引渡匣·承继明细」浮层。（§4 P0·③）
      s._inheritLedger = {};
      (_carry.ledger || []).forEach((L) => { if (L && L.id != null) s._inheritLedger[(L.type || 'x') + ':' + L.id] = { type: L.type, id: L.id, name: L.name, times: L.times || 0 }; });
      if (NDX.inheritCarryOf) s.inheritPreview = NDX.inheritCarryOf(s);
      const _pcs = [];
      if (_cEq.length) _pcs.push(`本命家当 ×${_cEq.length}`);
      if (_cRel.length) _pcs.push(`遗物 ×${_cRel.length}`);
      if (_cSut.length) _pcs.push(`佛经 ×${_cSut.length}`);
      if (_cNiSut.length) _pcs.push(`逆道经文 ×${_cNiSut.length}`);
      if (_cSeal.length) _pcs.push(`劫印 ×${_cSeal.length}`);
      this.pushLog(`【转世·承继】引渡匣已开：你把上世的${_pcs.join('、')}，自夏重新带上路——此世不再是白手。`);
      // 万世剑冢式 · 承继损耗：家当随世而旧（每世 -20%，最多传世4次），破损者止步于此世
      if (_inheritBroken.length) {
        this.pushLog(`【转世·承继】上世有 ${_inheritBroken.length} 件家当——${_inheritBroken.slice(0, 3).join('、')}${_inheritBroken.length > 3 ? ' 等' : ''}——已损耗至尽头，未随出行。此世白手，唯重历八十一难再得。`);
      }
    }
    // 起点装备不再开局赐予：改为英雄历经特定劫难(见 HEROES[id].initTrial)之后，
    // 进入问号(?)随机事件触发「送行」获得（唐王送行/观音赠蹄等，见 INIT_GIFT_EVENTS）。
    const heroDef = NDX.HEROES[s.hero];
    const granted = [];
    // V8.5x 修订：开局不再授予初始劫印（劫印系统后移至刘洪战后），也不再授予初始命痕。
    // 隐藏职资格改由第一难六道抉择后发放的「套装升级石」触发。
    // 记录初始人物形态（如小猴子/小沙弥）与「送行礼」已得标记位（初始化为未得）
    s.form0 = heroDef ? heroDef.form0 : null;
    if (!s.flags.gotInitGift) s.flags.gotInitGift = {};
    // 长安开场：李世民邀请前往西天取经（仅嘱托，不再赐装备；初始装备留待途中送行事件）
    const startExtra = '';
    const songHint = NDX.INIT_GIFT_EVENTS && heroDef && heroDef.initTrial
      ? `（行囊空空，须待历过第 ${heroDef.initTrial} 难，途中自有故人送行，方得随身兵甲与法宝。）`
      : '';
    const startOpts = [
      { text: '领旨谢恩，叩首受命——圣恩浩荡，愿往西天（善+6）', effect: { good: 6 }, fate: '渡' },
    ];
    if (NDX.hasClearedAny && NDX.hasClearedAny()) {
      startOpts.push({ text: '淡然一笑，自带行囊上路——取经是自己的事，不欠谁的人情（恶+4）', effect: { evil: 4 }, fate: '逆' });
    }

    // —— 开局福利 · 轮回赐福永久全局加成 + 功名加成（取消开局佛祖庇佑赠送，劫印与法宝改为后续获得）——
    const blessing = NDX.buildOpeningBlessing(s);
    s._blessing = blessing;
    // 1) 轮回赐福感受性保底（P0-C 去纵向：不再并入体/愿攻击加成；仅保留起始金 + 掉装保底提前）
    if (blessing.favor && blessing.favor.unlocked) {
      const fb = blessing.favor;
      if (fb.startGold) s.gold = (s.gold || 0) + fb.startGold;
      if ((fb.pityGrace || 0) > 0) s._favorPity = fb.pityGrace; // 掉装 soft-pity 提前（rollEquips 读）
      blessing.lines.forEach((ln) => { if (ln.indexOf('轮回赐福') >= 0) this.pushLog('【赐福】' + ln); });
    }
    // 2) 劫难成就图鉴永久微量全局属性（难簿功名跨周目累计）
    const ab = NDX.globalAchBonus();
    if (ab.count > 0) {
      s.bonusTi.atk += ab.ti.atk;
      s.bonusTi.hp += ab.ti.hp;
      s.bonusTi.dr += ab.ti.dr;
      s.bonusYuan.matk += ab.yuan.matk;
      s.bonusYuan.mdef += ab.yuan.mdef;
      s._achBonus = ab;
      this.pushLog(`【功名】难簿已录 ${ab.count}/${ab.cap} 难功名，化作永久加持：体攻+${ab.ti.atk} 气血+${ab.ti.hp} 法伤+${ab.yuan.matk}`);
    }
    // V8.30 取消开局佛祖庇佑赠送（白劫印+法宝自选）：首局体验更纯粹，劫印与法宝改为途中获得

    // V8.31 新手引导重构：去掉开局唐王送行弹窗（第〇难·长安），直接进入第一难金蝉遭贬
    // 唐王送行后移到前三难完成后（song-event事件），做装备+法宝+地图教学收口
    // 初始善恶/命运不再在开局设置，玩家在第一难抉择中自然获得
    // P0-3 西行劫难词条：通关（hasClearedAny）后开局插入「自择咒缚」面板（选 1~3 条负面条件换碎金倍酬），
    // 首局/未通关者直接正途西行（0 条），不打断新手体验。
    this.state.pending = (NDX.hasClearedAny && NDX.hasClearedAny() && !_isTJ)
      ? { kind: 'curse-pick', sel: [] }
      : { kind: 'choices' };
    this.pushLog(`【启程】自长安城门出，前方第 ${NDX.LAYER_COUNT} 难各有歧路，择一而入。`);
  };
// —— P0-3 西行劫难词条 · 开局落定（curse-pick 面板确认/跳过均走此）——
// 选 1~3 条负面词条 → 本局战斗压力上升，战后碎金按 NDX.curseRewardMul 倍率放大（高难换高回报）。
NDX.Game.prototype.setCurses = function setCurses(ids) {
    const s = this.state;
    if (!s) return;
    s.curses = Array.isArray(ids) ? ids.slice(0, 3) : [];
    if (s.curses.length) {
      const _mul = NDX.curseRewardMul ? NDX.curseRewardMul(s.curses) : 1;
      const _names = s.curses.map((c) => { const d = NDX.CURSE_TABLE && NDX.CURSE_TABLE[c]; return (d ? d.icon + ' ' + d.name : c); }).join('、');
      this.pushLog(`【西行劫难】自择咒缚 ${s.curses.length} 条：${_names}——此世险阻重重，战后碎金 ×${_mul.toFixed(2)}。`);
    } else {
      this.pushLog('【西行劫难】正途西行：不取咒缚，不求倍酬。');
    }
    s.pending = { kind: 'choices' };
    this.render();
  };
NDX.Game.prototype.startReturn = function startReturn() {
    const s = this.state;
    if (!s || s.over) return;
    s.mode = 'return';
    s.returnChest = s.returnChest || [];
    this.pushLog('【归】金蝉脱壳。你转身向东——返程固定耗九岁，按到西天时的余寿定归乡档位。');
    this.settleReturn(false);
  };
NDX.Game.prototype.applyTiyuan = function applyTiyuan(opt) {
    const s = this.state;
    const eff = opt.effect;
    this.applyEffectCore(eff);
    this._autoGE(opt);
    this.pushLog(`【体愿】${opt.text}`);
    if (eff.equip) {
      const items = NDX.rollEquips(eff.equip, s, eff.slot);
      if (!items.length) s.pending = { kind: 'choices' };
      else s.pending = { kind: 'equip', items };
    } else {
      s.pending = { kind: 'choices' };
    }
  };
NDX.Game.prototype._compoundTrial = function _compoundTrial(diff) {
    const s = this.state;
    s.diff = diff;
    if (!s.trialsPassed) s.trialsPassed = [];
    if (!s.trialsPassed.some((t) => t.diff === diff)) {
      s.trialsPassed.push({ diff, act: s.act, name: `第${diff}难` });
      if (!s.fateStats) s.fateStats = { trials: 0, kills: 0, events: 0 };
      s.fateStats.trials = (s.fateStats.trials || 0) + 1;
    }
    let tr = NDX.normalizeTrial(NDX.trialByLayer(diff, s.hero));
    if (!tr || !tr.opts || !tr.opts.length) tr = NDX.normalizeTrial(NDX.pickTrial());
    const node = s.compound.node;
    s.pending = {
      kind: 'trial',
      node,
      diff,
      title: tr.title || '劫难',
      text: tr.text || '',
      // V8.27 follow-up：第一难「金蝉遭贬」已将三段叙事合并为一段，
      // 用 twoStep + noSplit 做成「叙事第一页 / 选项第二页」的两页结构。
      noSplit: diff === 1,
      twoStep: diff === 1,
      opts: tr.opts || [],
      drop: (tr.treasure && tr.treasure.id && NDX.lootById(tr.treasure.id)) ? tr.treasure.id
            : (this._heroBaseDrop(s.hero) || tr.drop || null),
      trialId: tr.id || null,
      fate: tr.fate || null,
      echo: tr.echo || null,
      page: 0,
    };
    // V8.5x 新手指引重构：难1战后六道教学（复合节点内同样移除接引使者教学战）
    if (diff === 1 && !s.taught.sixdao) {
      s.taught.sixdao = true;
      s.pending.teach = 'sixdao';
      s.pending.teachText = '🪐 六道教学 · 金蝉遭贬：此战已胜，你心中已有抉择——每一抉择落于渡·缘·战·夺·隐·逆之一道，六道印记决定命运、装备与世界回应；恶道抉择额外折寿。择定一道后，将得对应六道装备升级石，可唤醒套装隐藏职。';
    }
    this.pushLog(`【${NDX.ACT_NAMES[Math.min((s.act || 1), NDX.TOTAL_ACTS) - 1] || ''}·${tr.title}】`);
    this.render();
  };
