// AUTO-GENERATED by _refactor_split.js — domain: camp
NDX.Game.prototype.campInfo = function campInfo() {
    const s = this.state;
    const C = NDX.CAMP || {};
    const lv = s.campLevel || 0;
    return {
      level: lv, max: C.MAX || 5, name: C.NAME || '土地神龛',
      cost: C.COST_BASE ? C.COST_BASE * (lv + 1) : 0,
      gold: s.gold || 0,
      canUpgrade: lv < (C.MAX || 5),
      bless: s.campBless,
      hadBless: !!s.campBless,
      restXinmo: (C.REST_XINMO || 0) * lv
    };
  };
NDX.Game.prototype.campUpgrade = function campUpgrade() {
    const s = this.state;
    const C = NDX.CAMP || {};
    if (!s || s.over) return { ok: false, why: '此世已了' };
    const info = this.campInfo();
    if (!info.canUpgrade) return { ok: false, why: '土地神龛已至满级' };
    if ((s.gold || 0) < info.cost) return { ok: false, why: `金不足（需 ${info.cost}，现 ${s.gold||0}）` };

    s.gold -= info.cost;
    s.campLevel = (s.campLevel || 0) + 1;
    const lv = s.campLevel;
    s.bonusTi.hp = (s.bonusTi.hp || 0) + (C.HP || 120);

    if (s.campBless) {
      this._applyCampBlessStep(s.campBless, C);
      this.pushLog(`【土地神龛】添香加固·升至 ${lv} 级——气血上限 +${C.HP||120}，${s.campBless} 相再涨一阶。`);
      this.toast(`土地神龛 ↑${lv}·${s.campBless}相成长`);
    } else {
      this.pushLog(`【土地神龛】添香加固·升至 ${lv} 级——气血上限 +${C.HP||120}。此龛既成，众相俱全——归返土地庙，以一方净土，供养菩萨。`);
      s.pending = { kind: 'camp-bless', node: (s.pending && s.pending.node) || { name: '土地庙' } };
      this.render();
      return { ok: true, pendingBless: true };
    }
    this._backToRest();
    return { ok: true };
  };
NDX.Game.prototype.chooseCampBless = function chooseCampBless(blessKey) {
    const s = this.state;
    const C = NDX.CAMP || {};
    const b = (C.BLESS || []).find((x) => x.key === blessKey);
    if (!b) return { ok: false, why: '无此相' };
    if (s.campBless) return { ok: false, why: '营地相已定' };
    s.campBless = blessKey;
    this._applyCampBlessStep(blessKey, C);
    s.pending = { kind: 'rest', node: (s.pending && s.pending.node) || { name: '土地庙' } };
    this.pushLog(`【土地神龛】祈立「${b.name}」——${b.desc}。此后每级加固，皆随此相成长。`);
    this.toast(`${b.icon} 营地相定：${b.name}`);
    this.render();
    return { ok: true };
  };
NDX.Game.prototype.openCamp = function openCamp() {
    const s = this.state;
    s.pending = { kind: 'camp', node: (s.pending && s.pending.node) || { name: '土地庙' } };
    this.render();
  };
NDX.Game.prototype.chooseRite = function chooseRite(rite) {
    const s = this.state;
    const node = (s.pending && s.pending.node) || { name: '土地庙' };
    if (rite === 'blood') {
      const r = NDX.doRiteBlood(s);
      if (!r.ok) { this.toast('气血过低，无从献祭'); this.render(); return; }
      this.pushLog(`【篝火·舍血淬体】献祭 ${r.cost} 气血，体攻 +${r.atk}、气血上限 +${r.hp}、暴击 +${Math.round(r.cri * 100)}%`);
      s.pending = { kind: 'rest', node };
      this.render();
      return;
    }
    // V8.26 命痕砍除：化痕为印 / 化印为痕 仪式已随命痕系统一并移除
    // V3 §1.1 劫印砍管理：铸印司/相易/易红/购印 全部下线，劫印全量自动生效（见 openSealBar）
  };
