// AUTO-GENERATED by _refactor_split.js — domain: combat
NDX.Game.prototype.resolveStageBreakManual = function resolveStageBreakManual() {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'fight' || p.awaitStageBreak < 0) return false;
    const idx = p.awaitStageBreak - 1; // roundsDetail 0-based
    const rd = p.res.roundsDetail[idx];
    if (!rd || !rd.stageBreakPoint) return false;
    const stageIndex = rd.breakStage - 1; // 0-based
    const m = p.monster;
    const needId = (m && m.breakWith) || null; // 克制该 Boss 韧性的特定法宝
    // 仅当怀有"特定克制法宝"且仍有充能且在法宝栏内时，手动破韧才成立；其他法宝无效（等同挂机兜底）。
    const _activeIds = NDX.activeEquipsFor ? NDX.activeEquipsFor(s).map((x) => x && x.id) : [];
    const canSac = needId && (s.equips || []).some((eq) => {
      const T = NDX.TREASURES && NDX.TREASURES[eq.treasureId];
      if (!T) return false;
      const ph = T.phase;
      return eq.treasureId === needId && _activeIds.includes(eq.id) && (ph === 'in' || ph === 'both') && eq.chargesLeft > 0 && !(p.opUsed || []).includes(eq.treasureId);
    });
    let ok = false;
    try {
      ok = this.resolveStageBreak(stageIndex, !!canSac);
    } catch (e) {
      // 破韧结算异常不应卡死战斗：记日志后按挂机兜底处理，并继续解除暂停
      this.pushLog(`【破韧】临阵破韧结算异常，已兜底（${e && e.message ? e.message : e}）`);
      ok = false;
    }
    if (ok && canSac) {
      // 消耗该特定破韧法宝的充能（临阵破韧的代价），并计入本场已用
      const eq = (s.equips || []).find((e) => {
        const T = NDX.TREASURES && NDX.TREASURES[e.treasureId];
        if (!T) return false;
        const ph = T.phase;
        return e.treasureId === needId && _activeIds.includes(e.id) && (ph === 'in' || ph === 'both') && e.chargesLeft > 0 && !(p.opUsed || []).includes(e.treasureId);
      });
      if (eq) {
        eq.chargesLeft = eq.chargesLeft - 1;
        p.opUsed = p.opUsed || [];
        p.opUsed.push(eq.treasureId);
        this.pushLog(`【破韧】你祭出 ${NDX.TREASURES[eq.treasureId].name} 击碎第${stageIndex + 1}阶段韧性条，厚赏到手！`);
      }
    } else if (needId) {
      const Tname = (NDX.TREASURES[needId] && NDX.TREASURES[needId].name) || needId;
      const hasButUsed = (s.equips || []).some((eq) => eq.treasureId === needId && (p.opUsed || []).includes(eq.treasureId));
      this.pushLog(hasButUsed
        ? `【破韧】克制法宝「${Tname}」本场已用尽，无力破韧——自动以挂机兜底了结第${stageIndex + 1}阶段`
        : `【破韧】未携克制法宝「${Tname}」，无力破韧——自动以挂机兜底了结第${stageIndex + 1}阶段`);
    }
    p.stageBreakHandled = p.stageBreakHandled || [];
    p.stageBreakHandled.push(p.awaitStageBreak);
    p.awaitStageBreak = -1;
    p.stageBreakInfo = null;
    return true;
  };
NDX.Game.prototype.resolveStageBreakIdle = function resolveStageBreakIdle() {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'fight' || p.awaitStageBreak < 0) return false;
    const idx = p.awaitStageBreak - 1;
    const rd = p.res.roundsDetail[idx];
    if (!rd || !rd.stageBreakPoint) return false;
    const stageIndex = rd.breakStage - 1;
    this.resolveStageBreak(stageIndex, false);
    p.stageBreakHandled = p.stageBreakHandled || [];
    p.stageBreakHandled.push(p.awaitStageBreak);
    p.awaitStageBreak = -1;
    p.stageBreakInfo = null;
    return true;
  };
NDX.Game.prototype._grantFightDrops = function _grantFightDrops(node) {
    if (!node) return;
    const s = this.state;
    const dropArr = node.drop ? (Array.isArray(node.drop) ? node.drop.slice() : [node.drop]) : [];
    const matArr = node.material ? (Array.isArray(node.material) ? node.material.slice() : [node.material]) : [];
    // 战利品识别：装备池 + 法宝字典（NDX.lootById 统一覆盖，修复法宝类掉落被当材料）
    const lootItems = dropArr.map((id) => NDX.lootById(id)).filter(Boolean);
    const lootIds = lootItems.map((e) => e.id);
    const extraMatIds = dropArr.filter((id) => !NDX.lootById(id));
    const allMats = extraMatIds.concat(matArr);
    const owned = new Set((s.equips || []).map((e) => e.id));
    // —— 套装精英齐发：node.drop 含套装基座（如 set_treasure_base / wk_crown_base 等）时，
    // 一次性发齐「全部基座 + 各套专属材料」，确保玩家当章即可合成全部套装成品
    // （通用三套原为随机只发1件 + 50%材料，导致永远凑不齐；英雄套如高老招亲含多基座，
    // 原逻辑只发第一个基座，致其余套装基座/材料丢失，悟空等拿不到核心装备）。
    const setBases = lootItems.filter((e) => e.setTier === 1 && e.set && NDX.setCraftMatsOf(e.id).length);
    if (setBases.length) {
      // 套装精英节点：一场战斗只发 1 件战利品，避免一次凑齐整套。
      // 优先随机掉落 1 个未拥有的套装基座；若全已拥有，则改赠其 1 个专属/节点材料。
      let base = setBases.find((e) => !owned.has(e.id));
      if (!base) base = setBases[NDX._rand(0, setBases.length - 1)];
      if (!owned.has(base.id)) {
        this.grantEquip(base);
        this.pushLog(`【战利】获得 ${base.name}（${base.desc}）`);
      } else {
        const baseMats = NDX.setCraftMatsOf(base.id);
        const matPool = new Set([...allMats, ...baseMats]);
        const arr = Array.from(matPool);
        if (arr.length) {
          const m = arr[NDX._rand(0, arr.length - 1)];
          NDX.addMaterial(s, m, 1);
          this.pushLog(`【战利】${base.name} 已在行囊，改赠材料 ${m}。`);
        }
      }
      return;
    }
    // 装备/法宝：优先未拥有的基座，其次未拥有的其它，最多 1 件
    // 装备五档：Boss 掉落 tier 下限——在节点自有掉落中优先授予达标的战利品（成就感台阶）
    const _rank = (k) => (NDX.EQUIP_TIERS || []).findIndex((t) => t.key === k) + 1;
    const _floorRank = node.dropTier ? _rank(node.dropTier) : 0;
    const _tierOk = (e) => !_floorRank || (_rank(NDX.equipTierOf ? NDX.equipTierOf(e) : 'white') >= _floorRank);
    let baseItems = lootItems.filter((e) => e.setTier === 1 && !owned.has(e.id));
    let otherItems = lootItems.filter((e) => !(e.setTier === 1) && !owned.has(e.id));
    if (_floorRank) {
      const _bT = baseItems.filter(_tierOk); if (_bT.length) baseItems = _bT;
      const _oT = otherItems.filter(_tierOk); if (_oT.length) otherItems = _oT;
    }
    const pickItem = baseItems.length ? baseItems[NDX._rand(0, baseItems.length - 1)]
                  : (otherItems.length ? otherItems[NDX._rand(0, otherItems.length - 1)] : null);
    if (pickItem) {
      this.grantEquip(pickItem);
      const _tk = NDX.equipTierOf ? NDX.equipTierOf(pickItem) : 'white';
      const _tn = ((NDX.EQUIP_TIERS || []).find((t) => t.key === _tk) || {}).name || '';
      this.pushLog(`【战利】获得 ${pickItem.name}（${_tn}·${pickItem.desc}）`);
    }
    // 材料：最多 1 件，50% 概率
    if (allMats.length && Math.random() < 0.5) {
      const m = allMats[NDX._rand(0, allMats.length - 1)];
      NDX.addMaterial(s, m, 1);
      this.pushLog(`【战利】获得材料 ${m}`);
      NDX.sfx('colect');
    }
  };
NDX.Game.prototype._afterFightChoices = function _afterFightChoices() {
    const s = this.state;
    // V8.27 修复：复合节点（黄风岭三连难）战斗子难胜利后，连续推进下一子难（含最终 Boss 收束），避免回地图卡死
    if (s.compound) { this._compoundNext(); return; }
    this._autoCraft(s); // 材料齐备即自动合成，无需等到篝火
    if (s._narrative) {
      const t = s._narrative;
      s._narrative = null;
      // 从当前英雄对应的小说库中取序号（仅用于稳定复现，不影响显示）
      const _novelLib = (h) => (h === 'tangseng' ? (NDX.TANGSENG_NOVEL || [])
        : h === 'bajie' ? (NDX.BAJIE_NOVEL || [])
        : h === 'shaseng' ? (NDX.SHASENG_NOVEL || [])
        : h === 'xiaobailong' ? (NDX.LONGMA_NOVEL || [])
        : (NDX.WUKONG_NOVEL || []));
      const _novelTitle = (h) => (h === 'tangseng' ? '取经人 · 西行记事'
        : h === 'bajie' ? '净坛 · 行者记事'
        : h === 'shaseng' ? '卷帘 · 行者记事'
        : h === 'xiaobailong' ? '白龙 · 西行记事'
        : '斗法回 · 悟空小说');
      const lib = _novelLib(s.hero) || [];
      const seed = lib.indexOf(t);
      // 标题随英雄身份切换：取经人/八戒/沙僧/小白龙各有记事，其余沿用悟空小说
      const title = _novelTitle(s.hero);
      s.pending = { kind: 'narrative', text: t, title: title, seed: seed >= 0 ? seed : null };
    } else {
      s.pending = { kind: 'choices' };
    }
  };
NDX.Game.prototype._preFightTreasures = function _preFightTreasures(s) {
    const activeIds = NDX.activeEquipsFor ? NDX.activeEquipsFor(s).map((x) => x && x.id) : [];
    return (s.equips || []).filter((e) => {
      if (!e.treasure) return false;
      if (!activeIds.includes(e.id)) return false; // V8.28：仅生效格内法宝
      const ch = e.chargesLeft == null ? (e.charges || 0) : e.chargesLeft;
      if (ch <= 0) return false;
      const T = NDX.TREASURES && NDX.TREASURES[e.treasureId];
      return T && (T.phase === 'in' || T.phase === 'both');
    });
  };
NDX.Game.prototype.togglePreFightTreasure = function togglePreFightTreasure(id) {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'fight' || !p.preFight) return;
    p.preFightUsed = p.preFightUsed || [];
    const idx = p.preFightUsed.indexOf(id);
    if (idx >= 0) p.preFightUsed.splice(idx, 1);
    else p.preFightUsed.push(id);
  };
NDX.Game.prototype.startPreFight = function startPreFight() {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'fight' || !p.preFight) return;
    const used = (p.preFightUsed || []).slice();
    p.preFightUsed = [];
    p.preFight = false;
    // 依次祭出已选中的战斗中法宝，作用在战斗初始状态上（p.pHp / p.mHp）
    used.forEach((id) => {
      this.useItem(id);
    });
    if (used.length) this.pushLog(`【战前】已祭出 ${used.length} 件法宝，即将交锋。`);
  };
NDX.Game.prototype.useItem = function useItem(id) {
    const s = this.state;
    if (s.over) return;
    const eq = s.equips.find((e) => e.id === id && e.treasure);
    if (!eq) return;
    const T = NDX.TREASURES && NDX.TREASURES[eq.treasureId];
    if (!T) return;
    // 被动法宝（如紧箍）：敌人现身即自动发动，不可主动祭出
    if (T.auto) {
      this.pushLog(`【法宝】${eq.name} 为被动法宝，敌人现身时自动发动，不可主动祭出`);
      return;
    }
    // 护身禁器（如三根救命毫毛）：仅于败亡瞬间自动飘落替劫，不可主动祭出
    if (T.phase === 'dead') {
      this.pushLog(`【法宝】${eq.name} 为护身禁器，须待性命垂危方自行飘落替劫，不可主动祭出`);
      return;
    }
    // 充能校验
    if (eq.chargesLeft == null) eq.chargesLeft = eq.charges || 0;
    if (eq.chargesLeft <= 0) {
      this.pushLog(`【法宝】${eq.name} 灵光已尽，暂不可再用`);
      return;
    }
    // V8.28：法宝栏校验——非法宝栏法宝不可祭出
    if (NDX.isEquipActive && !NDX.isEquipActive(s, eq.id)) {
      this.pushLog(`【法宝】${eq.name} 未在法宝栏内，无法祭出（请先将其穿戴至法宝栏）`);
      return;
    }
    const inFight = s.pending && s.pending.kind === 'fight';
    const idle = !s.pending || s.pending.kind === 'choices';
    // 阶段校验：法宝只能在其允许的时机祭出
    if (inFight && T.phase === 'out') {
      this.pushLog(`【法宝】${eq.name} 需于非战斗时祭出，战场之上无从化缘`);
      return;
    }
    if (idle && T.phase === 'in') {
      this.pushLog(`【法宝】${eq.name} 需临阵祭出，此刻风平浪静，祭之无益`);
      return;
    }
    const eff = T.effect || {};

    if (inFight) {
      this._useTreasureInFight(eq, T, eff);
    } else {
      this._useTreasureIdle(eq, T, eff);
    }
    eq.chargesLeft -= 1;
    if (eq.chargesLeft <= 0) this.pushLog(`【法宝】${eq.name} 灵光耗尽，再难祭出`);
  };
NDX.Game.prototype._useTreasureInFight = function _useTreasureInFight(eq, T, eff) {
    const s = this.state;
    const p = s.pending; // fight pending
    // 阶段七·音效：祭宝法铃清音
    try { if (NDX.sound) NDX.sound.play('treasure'); } catch (e) {}
    const st = this.stats();
    const maxHp = st.ti.maxHp;
    const mMax = p.monster.hp;
    const before = p.pHp;
    // 1) 回血（含回满）
    if (eff.healPct) p.pHp = Math.min(maxHp, p.pHp + Math.round(maxHp * eff.healPct));
    if (eff.healFlat) p.pHp = Math.min(maxHp, p.pHp + eff.healFlat);
    if (eff.capHeal) p.pHp = maxHp;
    // 2) 伤敌
    if (eff.dmgPct) p.mHp = Math.max(0, p.mHp - Math.round(mMax * eff.dmgPct));
    if (eff.dmgFlat) p.mHp = Math.max(0, p.mHp - eff.dmgFlat);
    // 2.5) 敌攻削弱（灰烬罩/琢碎片）：近似为回复 debuff%*maxHp 的气血
    if (eff.enemyAtkDebuff) {
      const shield = Math.round(maxHp * eff.enemyAtkDebuff);
      p.pHp = Math.min(maxHp, p.pHp + shield);
      p.enemyAtkDebuff = eff.enemyAtkDebuff;
    }
    if (eff.enemyAtkDebuffPerm) {
      const shield = Math.round(maxHp * eff.enemyAtkDebuffPerm);
      p.pHp = Math.min(maxHp, p.pHp + shield);
      p.enemyAtkDebuff = eff.enemyAtkDebuffPerm;
      s.flags = s.flags || {};
      s.flags.enemyAtkDebuffPerm = eff.enemyAtkDebuffPerm;
    }
    // 3) 日志
    const parts = [];
    if (eff.capHeal) parts.push('回满气血');
    else if (eff.healPct || eff.healFlat) parts.push(`气血 +${Math.max(0, p.pHp - before)}`);
    if (eff.dmgPct || eff.dmgFlat) parts.push(`伤敌 -${Math.max(0, mMax - p.mHp)}`);
    if (eff.enemyAtkDebuff || eff.enemyAtkDebuffPerm) {
      const pct = Math.round((eff.enemyAtkDebuff || eff.enemyAtkDebuffPerm) * 100);
      parts.push(`敌攻 -${pct}%`);
    }
    this.pushLog(`【法宝·临阵】${eq.name} 祭出：${parts.join('，') || '镇压'}（余 ${eq.chargesLeft - 1} 次）`);
    // V8.40 法宝协同：通过统一模块NDX.BattleResource.onTreasureUse处理战意/经力调整
    if (NDX.BattleResource && typeof NDX.BattleResource.onTreasureUse === 'function') {
      const result = NDX.BattleResource.onTreasureUse(p, eff);
      if (result.zhanYiGained > 0) {
        this.pushLog(`【战意】${eq.name} 激发战意 +${result.zhanYiGained}（当前 ${p.zhanYi}/${p.zhanYiMax}）`);
      }
      if (result.jingLiGained > 0) {
        if (result.jingLiReady) {
          this.pushLog('【经力圆满】下次诵经将触发金刚经！');
        } else {
          this.pushLog(`【经力】${eq.name} 积累经力 +${result.jingLiGained}（当前 ${p.jingLi}/${p.jingLiMax}）`);
        }
      }
      // P2-1 满而不溢：法宝溢出改攒昂扬/化雨层（绝招 +15%/层、诵经回 6% 气血/层）
      if (result.zhanYiOverflow > 0) {
        this.pushLog(`【战意昂扬】战意已满，溢出化为昂扬×${result.zhanYiOverflow}（绝招时每层 +15% 伤害）`);
      }
      if (result.jingLiOverflow > 0) {
        this.pushLog(`【经力化雨】经力已满，溢出化为化雨×${result.jingLiOverflow}（诵经时每层回复 6% 最大气血）`);
      }
      if (result.keepZhanYiBuff > 0) {
        this.pushLog(`【护体】${eq.name} 护体，3回合内受击保留战意`);
      }
    } else {
      // 降级：手动处理法宝协同
      if (eff.dmgPct || eff.dmgFlat) {
        p.zhanYi = Math.min(p.zhanYiMax, (p.zhanYi || 0) + 2);
        this.pushLog(`【战意】${eq.name} 激发战意 +2（当前 ${p.zhanYi}/${p.zhanYiMax}）`);
      }
      if (eff.healPct || eff.healFlat || eff.capHeal) {
        p.jingLi = Math.min(p.jingLiMax, (p.jingLi || 0) + 2);
        if (p.jingLi >= p.jingLiMax && !p.jingLiReady) {
          p.jingLiReady = true;
          this.pushLog('【经力圆满】下次诵经将触发金刚经！');
        } else {
          this.pushLog(`【经力】${eq.name} 积累经力 +2（当前 ${p.jingLi}/${p.jingLiMax}）`);
        }
      }
      if (eff.enemyAtkDebuff || eff.enemyAtkDebuffPerm || eff.shield) {
        p.keepZhanYiBuff = (p.keepZhanYiBuff || 0) + 3;
        this.pushLog(`【护体】${eq.name} 护体，3回合内受击保留战意`);
      }
    }
    // 4) 结果干预：法宝祭出后若实际改变了战局（怪物被击杀 / 玩家从濒死被救回），
    // 同步修正预计算的 res.win，避免「演出中妖怪已死，结算却判败」的错位。
    if (!p.win) {
      const killed = p.mHp <= 0;
      const wouldDie = p.res.win === false && (p.pHp <= 0 || p.res.playerHpLeft <= 0);
      if (killed || (p.pHp > 0 && wouldDie && eff.healPct)) {
        p.win = true;
        p.res.win = true;
        p.res.playerHpLeft = Math.max(1, p.pHp);
        p.mHp = killed ? 0 : p.mHp;
        p.pHp = Math.max(1, p.pHp);
        p.savedBy = eq.name;
        // 提前收束演出：直接跳到收尾
        const total = (p.res.roundsDetail || []).length;
        p.roundIdx = Math.max(p.roundIdx, total - 1);
        this.pushLog(`【法宝·逆转】${eq.name} 光华大作——本已陷死劫，竟被强行扭转！妖氛顿消，你稳住了身形`);
      }
    }
    // V8.50 法宝克制·解厄：清除玩家侧 debuff
    const _cleans = (T && T.cleanse) || ((NDX.TREASURES && eq.treasureId && NDX.TREASURES[eq.treasureId] && NDX.TREASURES[eq.treasureId].effect && NDX.TREASURES[eq.treasureId].effect.cleanse) || []);
    if (_cleans.length) {
      p.pDebuffs = p.pDebuffs || {};
      const removed = _cleans.filter((t) => p.pDebuffs[t]);
      if (removed.length) {
        removed.forEach((t) => delete p.pDebuffs[t]);
        if (NDX.applyBattleCleanse) NDX.applyBattleCleanse(p.res, (p.roundIdx >= 0 ? p.roundIdx : 0) + 1, _cleans);
        const _nm = (t) => (NDX.PDEBUFF_DEFS && NDX.PDEBUFF_DEFS[t] && NDX.PDEBUFF_DEFS[t].name) || t;
        this.pushLog(`【法宝·解厄】${eq.name} 化解 ${removed.map(_nm).join('、')}！`);
      }
    }
  };
NDX.Game.prototype._useTreasureIdle = function _useTreasureIdle(eq, T, eff) {
    const s = this.state;
    const st = this.stats();
    const maxHp = st.ti.maxHp;
    if (eff.capHeal) {
      s.hp = maxHp;
      this.pushLog(`【法宝·化缘】${eq.name} 引甘露，气血回满（${maxHp}/${maxHp}）`);
    }
    if (eff.healPct) {
      const before = s.hp;
      s.hp = Math.min(maxHp, s.hp + Math.round(maxHp * eff.healPct));
      this.pushLog(`【法宝·化缘】${eq.name} 捻动人影，气血 +${s.hp - before}（${s.hp}/${maxHp}）`);
    }
    if (eff.healFlat) {
      const before = s.hp;
      s.hp = Math.min(maxHp, s.hp + eff.healFlat);
      this.pushLog(`【法宝】${eq.name} 续命，气血 +${s.hp - before}（${s.hp}/${maxHp}）`);
    }
    if (eff.weakNext) {
      s.flags.nextWeak = Math.max(s.flags.nextWeak || 0, eff.weakNext);
      this.pushLog(`【法宝·照妖】${eq.name} 照出前路妖隐，下一战难度 -${eff.weakNext}`);
    }
    if (eff.evil) {
      this.gainMoral(0, eff.evil, '迷失本心·' + (eq.name || '法宝'));
      s.flags.lostHeart = (s.flags.lostHeart || 0) + 1;
      this.pushLog(`【迷失本心】${eq.name} 用之，本心又失一分（恶+${eff.evil}，已失 ${s.flags.lostHeart} 分）`);
      if (s.flags.lostHeart >= 3 && !s.flags.tsHidden) {
        s.flags.tsHidden = true;
        this.pushLog(`【隐藏路线·取经人】本心迷失至深，你已踏入取经人"舍身饲魔"之暗线——纵为悟空，亦可行取经人未敢行之路`);
      }
    }
  };
