// AUTO-GENERATED by _refactor_split.js — domain: event
NDX.Game.prototype.applyTrialOpt = function applyTrialOpt(opt) {
    const s = this.state;
    // —— 双线事件选项归一化（V8.27 经文系统）：平铺字段并入 effect，供 applyEffectCore 消费 ——
    if (opt && opt._sutraEvId) {
      opt.effect = Object.assign({}, opt.effect, {
        alignGood: opt.alignGood, alignEvil: opt.alignEvil,
        sutra: opt.sutra, gear: opt.gear, favor: opt.favor
      });
    }
    // —— 复合节点路线抉择：选择渡/恶，决定子难流程与 Boss 强度 ——
    if (s.pending && s.pending.kind === 'compound-route') {
      this._compoundRoute(opt);
      return;
    }
    // —— 二级面板节点：一级姿态含 subOptions → 不直接结算，切到二级子面板 ——
    if (opt && Array.isArray(opt.subOptions) && opt.subOptions.length) {
      // V8.5x 难1首次进入二级六道选项：观音气泡点出眼前两道（不阻断选择）
      const _sixNode = (s.pending && s.pending.node) || null;
      const _sixFirst = !!(_sixNode && _sixNode.diff === 1 && !s.flags._sixSubTaught);
      if (_sixFirst) s.flags._sixSubTaught = true;
      const _sixDao = (opt.subOptions || []).map((o) => o.fate).filter(Boolean).join('、');
      // V8.5x 保留上一层 choices pending，供二级面板「返回上一层重选」回退
      const _prevPending = s.pending;
      s.pending = {
        kind: 'sub-choices',
        node: _sixNode,
        subText: opt.subText || opt.text || '',
        subTitle: opt.subTitle || opt.label || '心念分化',
        opts: opt.subOptions,
        page: 0,
        teach: _sixFirst ? 'sixdao-sub' : null,
        teachText: _sixFirst ? ('观音菩萨：「' + _sixDao + ' 二道就在眼前，择其一——此念一起，六道印记便落定第一道。善道养命，恶道折寿，随心而行。」') : '',
        then: _prevPending,
      };
      this.pushLog(`【劫·${opt.label || opt.key || '姿态'}】心念分化，趋向将分。`);
      this.render();
      return;
    }
    // 命运抉择门槛：声道锁定 / 格需求（善恶不设门槛，V8.16 起善/恶选项一律可选）
    const gate = this._optionGate(opt);
    if (gate.locked) {
      this.toast(`此路未通——${gate.reasons.join('；')}`);
      this.render();
      return;
    }
    const eff = opt.effect || {};
    const hasAttrGain = !!(eff.ti || eff.yuan || eff.atk != null || eff.hp != null || eff.dr != null || eff.eva != null || eff.matk != null || eff.mdef != null || eff.healFull);
    // 真正的"战"选项：显式 fight 标志，或 fate='战' 且不带体/愿属性增益（如只加善恶）
    // 第一章首难（难1·金蝉遭贬）六道选项的「战」「夺」不触发战斗：仅以抉择落印，
    // 不走第二场战斗（接引使者教学战已覆盖战斗教学）；后续劫难战/夺照常进入战斗。
    const isFightOpt = (opt.fight || (opt.fate === '战' && !hasAttrGain)) && !opt.noFight;

    // 战斗奖励 reward（atk/hp 等即时属性）也即时结算，避免「战斗选项只开打不给属性」
    // 渡道(续航劫更多)对属性类奖励额外加成：每选一次渡 +12%，体现"续航收益更高"
    if (opt.reward) {
      const r = opt.reward;
      const _sus = 1 + (s.flags.sustain || 0) * 0.12;
      if (r.atk) s.bonusTi.atk += Math.round(r.atk * (1 + (s.layer - 1) * 0.09) * _sus);
      if (r.hp) s.bonusTi.hp += Math.round(r.hp * (1 + (s.layer - 1) * 0.09) * _sus);
      if (r.eva) s.bonusTi.eva += Math.round(r.eva * (1 + (s.layer - 1) * 0.09) * _sus);
      if (r.dr) s.bonusTi.dr += r.dr;
    }

    // 战斗选项：开打精英怪。胜利后必得 drop 宝物 + 高额装备三选一（战斗奖励优于选项夺宝）。
    if (isFightOpt) {
      const node = s.pending.node;
      const mData = NDX.monsterAt(node.diff);
      const weak = s.flags.nextWeak || 0;
      s.flags.nextWeak = 0;
      const m = {
        type: 'elite', // 力战破劫 = 精英级战斗：1x 锁速 + 6–10 回合节奏校准
        hp: mData.hp,
        atk: Math.round(mData.atk * (1 - weak)),
        dr: mData.dr,
        matk: Math.round(mData.matk * (1 - weak)),
        mdef: mData.mdef,
        boss: false,
      };
      const bossName = NDX.trialBossName(s.pending);
      this.pushLog(`【劫·力战破劫】${bossName} 现身！`);
      // 劫难战斗掉落：只发「与劫难参与者（当前英雄）相关联的专属套装」——由 finishFight 的
      // elitereward 分支经 NDX.rollSetEquips 提供二选一（英雄专属套 + 本章章节套），不再依赖
      // TRIALS 里散乱硬编码的 drop 数组。保证劫难掉落始终聚焦于本英雄成长线（需求：劫难→关联装备）。
      const fightNode = Object.assign({}, node);
      this.setBattleFlags((opt && opt.battleFlags) || null);
      const _hint = (opt && opt.battleFlags) ? this.battleFlagsHint(opt.battleFlags) : '';
      if (_hint) this.toast(_hint);
      // 战斗型抉择的精确善恶分档：开打前即入账（战斗分支不随 applyEffectCore 结算，单独补挂；
      // 仅对带 alignGood/alignEvil 的选项生效，其余战斗选项行为不变）
      if (opt && opt.effect) {
        const e = opt.effect;
        if (e.alignGood || e.alignEvil) this.gainMoral(e.alignGood || 0, e.alignEvil || 0, '因果·战斗抉择' + ((opt && opt.fate) ? '·' + opt.fate : ''));
      }
      // 观音好感钩子（战斗型抉择同样生效）：已获其好感 → 愿力/善入账，且可携助战斗势入场
      if (opt && opt.favorGate) {
        const gods = (s.favors && s.favors.gods) || [];
        if (gods.indexOf(opt.favorGate) >= 0 && !this._favorGatePaused(s)) {
          const fb = opt.favorEffect || {};
          const _y = fb.yuan != null ? fb.yuan : 0;
          const _g = fb.alignGood != null ? fb.alignGood : 0;
          if (_y) s.yuan = (s.yuan || 0) + _y;
          if (_g) this.gainMoral(_g, 0, '观音回响');
          if (fb.momentum) this.setBattleFlags(Object.assign({}, opt.battleFlags || {}, { openingMomentum: fb.momentum }));
          this.pushLog(`【观音回响】${opt.favorText || ('观音念及旧缘，愿 +' + _y + '、善 +' + _g + '。')}`);
          this.toast(`观音好感回响：愿 +${_y}、善 +${_g}`);
        } else {
          this.pushLog(`【观音疏离】神缘未足，此战独力。`);
        }
      }
      // V8.5x 取消前三难战斗新手观音弹窗教学，减少前期信息轰炸
      this.fight(m, bossName, 'elitereward', null, fightNode, false, null);
      return;
    }

    // 观音好感钩子：选项带 favorGate 且已获该神好感 → 追加好感增强；未结缘则凡俗如常
    if (opt.favorGate) {
      const gods = (s.favors && s.favors.gods) || [];
      if (gods.indexOf(opt.favorGate) >= 0 && !this._favorGatePaused(s)) {
        const fb = opt.favorEffect || {};
        const _y = fb.yuan != null ? fb.yuan : 3;
        const _g = fb.alignGood != null ? fb.alignGood : 2;
        s.yuan = (s.yuan || 0) + _y;
        if (_g) this.gainMoral(_g, 0, '观音回响');
        this.pushLog(`【观音回响】${opt.favorText || ('观音念及旧缘，愿 +' + _y + '、善 +' + _g + '。')}`);
        this.toast(`观音好感回响：愿 +${_y}、善 +${_g}`);
      } else {
        this.pushLog(`【观音疏离】此路神缘未足，凡俗如常。`);
      }
    }
    this.applyEffectCore(eff);
    this._autoGE(opt);
    if (opt.fate) this._gainFate(opt.fate);
    // 师徒缘（V8.17·轻量）：选项可收徒——徒弟给被动增益，计入一生账本与劫灰结算
    if (opt.disciple) {
      const _d = NDX.discipleById(opt.disciple);
      if (_d && !(s.disciples || []).includes(_d.id)) {
        if (!s.disciples) s.disciples = [];
        s.disciples.push(_d.id);
        this.pushLog(`【收徒】${_d.name} 拜入门下（${_d.desc}）`);
        this.toast(`收徒：${_d.name} 入门（${_d.desc}）`);
      }
    }
    // 本局即时难度/收益调节：逆道→怪物强度上升、劫印品质更高；渡道→怪物弱化、续航劫更多。
    // 使"选择立刻改变对局难度与收益"，剧情与玩法双向绑定（区别于普通数值爬塔）。
    if (opt.fate === '逆') {
      s.flags.monStr = +(s.flags.monStr || 0) + 0.08;
      s.flags.sealUp = (s.flags.sealUp || 0) + 1;
      // 逆经碎片（选逆即得 · V8.27 收集制）：必掉 1 片（三选一池未弹窗时自动给）
      if (NDX.grantSutraAuto) {
        const fr = NDX.grantSutraAuto(s, 'rebel', s.act);
        if (fr) {
          this.pushLog(`【逆经残片】拾得 ${fr.name}（${fr.note}）`);
          // P1-4 新手指引：首次获得经文碎片时提示
          if (!s.flags._sutraTaught) {
            s.flags._sutraTaught = true;
            this.toast('📜 经文系统：拾得经文残片，集齐一部全本即化作因果补益战力（气血·攻伐·法伤·御念·自愈）；可于西经阁合本');
          }
        }
      }
    } else if (opt.fate === '渡') {
      s.flags.monWeak = +(s.flags.monWeak || 0) + 0.08;
      s.flags.sustain = (s.flags.sustain || 0) + 1;
      // 渡经碎片（选渡即得 · V8.27 收集制 · 普适无门槛）
      if (NDX.grantSutraAuto) {
        const fr = NDX.grantSutraAuto(s, 'ferry', s.act);
        if (fr) {
          this.pushLog(`【渡经残片】拾得 ${fr.name}（${fr.note}）`);
          if (!s.flags._sutraTaught) {
            s.flags._sutraTaught = true;
            this.toast('📜 经文系统：拾得经文残片，集齐一部全本即化作因果补益战力；可于西经阁合本');
          }
        }
      }
    }
    // 第一难六道抉择：根据最终所选六道赠送对应套装升级石（隐藏职资格凭证），每局仅一次
    // V8.5x 修订：不再直接给组件1，而是给升级石；只有持有升级石，同套组件才会激活隐藏职。
    if (opt.fate && !s.flags._firstSixDaoComp) {
      const _firstDiff = (s.pending && s.pending.then && s.pending.then.diff) || (s.pending && s.pending.diff);
      if (_firstDiff === 1) {
        s.flags._firstSixDaoComp = true;
        // 方案X2·难1择道定调：第一道印记即主道锚点（s.mainDao）——动态主道判定之基，
        // 装备掉落/道途攻式/转职/经文钩子皆以此为纲；土地庙可自愿改道
        s.mainDao = opt.fate;
        s._quotaDaoChosen = true;
        s.flags._firstDaoOverview = true; // 本难结算后弹六道总览（重点介绍钩子与攻式）
        const firstStoneMap = { '渡': 'xw_stone', '缘': 'tl_stone', '战': 'pw_stone', '隐': 'yd_stone', '逆': 'nm_stone', '夺': 'tt_stone' };
        const stoneId = firstStoneMap[opt.fate];
        if (stoneId) {
          const stone = NDX.lootById(stoneId);
          if (stone) {
            this.grantEquip(stone);
            const js = NDX.JOB_STONES && NDX.JOB_STONES[stoneId];
            this.pushLog(`【六道觉醒·${opt.fate}】${stone.name} 落入掌心——${js ? js.set : ''}隐藏职已可唤醒，后续收集同套组件可升转。`);
          }
        }
      }
    }
    this.pushLog(`【劫难·${opt.text}】`);

    // 选项级即时机缘：treasure=直接得宝（字符串/数组，写在 opt 或 opt.effect 均可）；
    // refill=已拥有的同名法宝补满充能。用 lootById 以便同时覆盖装备池与法宝字典（TREASURES）。
    const treasure = opt.treasure || eff.treasure;
    const refill = opt.refill || eff.refill;
    if (treasure) {
      const ids = Array.isArray(treasure) ? treasure : [treasure];
      ids.forEach((tid) => {
        const eq = NDX.lootById(tid);
        if (eq) {
          this.grantEquip(eq);
          this.pushLog(`【劫难宝物】获得 ${eq.name}（${eq.desc}）`);
        } else if (refill) {
          // 充能补满：在已有法宝中找同名 id 补满
          const owned = s.equips.find((e) => e.id === tid && e.treasure);
          if (owned && typeof owned._maxCharges === 'number' && !owned.noRecharge) { owned.chargesLeft = owned._maxCharges; this.pushLog(`【法宝补满】${tid} 充能已补满`); }
          else if (owned) this.pushLog(`【法宝补满】${tid} 已在行囊`);
          else this.pushLog(`【劫难宝物】未持有 ${tid}，无法补满`);
        } else {
          // 非装备类宝物（如材料名）按材料收
          NDX.addMaterial(s, tid, 1);
          this.pushLog(`【劫难宝物】拾得 ${tid}`);
        }
      });
    }

    // 选项级转职/结局确认
    // 1) 直接写死的 jobConfirm（如 trial 77 二周目专属）
    // 2) TRIAL_LIB 节点的 hidden 字段（8.11 各难隐藏职种子）——此前从未被消费，本次接线
    let jobConfirm = opt.jobConfirm;
    const pendingNode = s.pending && s.pending.node;
    if (!jobConfirm && pendingNode && pendingNode.hidden) {
      const h = pendingNode.hidden;
      const heroOk = (h.hero === s.hero || h.hero === 'all');
      // 无 cond 的隐藏项视为条件天然满足，后续由 jobConfirm 路径的劫难前置/持宝门槛统一校验
      const res = heroOk ? (h.cond ? NDX.evalHiddenCond(h.cond, s, opt) : { ok: true }) : { ok: false, kind: 'hero' };
      if (heroOk && res.ok) {
        if (h.hero === 'all') {
          // 全英雄级隐藏职：以旗标解锁（非单一 jobConfirm）
          if (h.job === '六耳·残') {
            if (!NDX.isAwakened('六耳·残')) { s.flags.liuerUnlocked = true; NDX.recordAwakened('六耳·残'); this.pushLog(`【隐藏转职】六耳·残 已解锁——隐藏第四人可参战`); }
            else this.pushLog(`【隐藏转职】六耳·残 早已觉醒（多周目跳过）`);
          } else if (h.job === '真·逆道') {
            if (!NDX.isAwakened('真·逆道')) { s.flags.allHiddenUnlocked = true; NDX.recordAwakened('真·逆道'); this.pushLog(`【隐藏转职】真·逆道 已解锁——全英雄终极隐藏职觉醒`); }
            else this.pushLog(`【隐藏转职】真·逆道 早已觉醒（多周目跳过）`);
          } else if (h.job === '驯兽师·百兽归心') {
            // V8.22 宠物修订版：全英雄级·驯兽师隐藏职，凭「出阵灵兽 + 御兽套」觉醒（非单一 jobConfirm 路径）
            if (!NDX.isAwakened('驯兽师·百兽归心')) { NDX.recordAwakened('驯兽师·百兽归心'); this.pushLog(`【隐藏转职】驯兽师·百兽归心 已觉醒——收九灵为御兽，上阵灵兽越多全属性越强`); }
            else this.pushLog(`【隐藏转职】驯兽师·百兽归心 早已觉醒（多周目直承）`);
            s.flags.jobConfirm = '驯兽师·百兽归心';
          } else {
            s.flags.jobConfirm = h.job;
          }
          this._syncAch();
        } else {
          jobConfirm = h.job;
        }
      } else if (heroOk && !res.ok) {
        // 轻量化校验：六道数值 / 善 / 恶 / 闪避 / 特殊剧情 缺失 → 分级弹窗提示
        if (res.kind === 'fate') {
          const txt = (typeof res.need === 'number')
            ? `命运${res.dao}数值不足 ${res.need}（当前 ${res.cur}），难承此道`
            : `未以「${res.dao}」道抉择，无缘此隐藏职`;
          this.toast(`转职受阻 · ${h.job}：${txt}`);
          this.pushLog(`【转职·受阻】${h.job}：${txt}`);
        } else if (res.kind === 'good') {
          this.toast(`转职受阻 · ${h.job}：善行不足（需善≥${res.need}，当前 ${res.cur}）`);
          this.pushLog(`【转职·受阻】${h.job}：善行不足（需善≥${res.need}，当前 ${res.cur}）`);
        } else if (res.kind === 'evil') {
          this.toast(`转职受阻 · ${h.job}：恶业不足（需恶≥${res.need}，当前 ${res.cur}）`);
          this.pushLog(`【转职·受阻】${h.job}：恶业不足（需恶≥${res.need}，当前 ${res.cur}）`);
        } else if (res.kind === 'eva') {
          this.toast(`转职受阻 · ${h.job}：身法不足（需闪避≥${res.need}，当前 ${res.cur}）`);
          this.pushLog(`【转职·受阻】${h.job}：身法不足（需闪避≥${res.need}，当前 ${res.cur}）`);
        } else if (res.kind === 'plot') {
          this.toast(`转职受阻 · ${h.job}：前置因缘未至（${res.tag}）`);
          this.pushLog(`【转职·受阻】${h.job}：前置因缘未至（${res.tag}）`);
        }
      }
    }
    // —— 逆兽师·百逆归心（全英雄级·逆道驯兽隐藏职）——
    // 在竹节九狮(难64)收九灵为御兽之刻，若身负逆道（逆道劫印≥2 / 已合成逆经）且出阵灵兽≥3、着御兽套，
    // 则一并觉醒（与驯兽师同源异道：驯兽师承「夺」，逆兽师承「逆」）。
    // 注：不依赖 trials81.js 的 hidden 字段触发，避免触碰并行会话文件；此处独立判定，逻辑与驯兽师对称。
    if (pendingNode && pendingNode.id === 64 && NDX.isNiRoute && NDX.isNiRoute(s) && !NDX.isAwakened('逆兽师·百逆归心')) {
      let _petN = 0, _hasYushou = false;
      try {
        const _act = (NDX.activeEquipsFor) ? NDX.activeEquipsFor(s) : (s.equips || []);
        _petN = (_act || []).filter((e) => e && e.slot === 'pet').length;
        _hasYushou = (_act || []).some((e) => e && e.set === '御兽');
      } catch (e) {}
      if (_petN >= 3 && _hasYushou) {
        NDX.recordAwakened('逆兽师·百逆归心');
        this.pushLog(`【隐藏转职】逆兽师·百逆归心 已觉醒——逆道驯兽，逆修之兽更凶（额外出战位 + 御兽逆道增幅）`);
        this._syncAch();
      }
    }
    if (jobConfirm) {
      // 多周目已觉醒该隐藏职：再次触发本劫难直接跳过弹窗，减少 20 节点短流程的拖沓
      if (NDX.isAwakened(jobConfirm) || s.flags.jobConfirm === jobConfirm) {
        s.flags.jobConfirm = jobConfirm;
        this.pushLog(`【转职】${jobConfirm} 早已觉醒（多周目直承，跳过校验）`);
      } else {
        // 隐藏职双重硬门槛（8.11《每难装备法宝映射与转职持有要求总表》§二）：
        //   1) 劫难前置：必须先历经本英雄的特定关键劫难（如八戒需历九劫）；
        //   2) 持有门槛：须实际持有对应劫难掉落的专属装备/法宝（held 字段，如「弃经金蝉」须持紫金钵）。
        const hiddenEntry = (() => {
          for (const k of Object.keys(NDX.HIDDEN_JOBS)) {
            const hit = (NDX.HIDDEN_JOBS[k] || []).find((x) => x.job === jobConfirm);
            if (hit) return hit;
          }
          return null;
        })();
        if (hiddenEntry) {
          // 门槛 1：劫难前置（序章隐藏职【trial:1】除外——首难凭「逆择 + 持钵」即可直接觉醒，见市场/玩法报告"第一难早解锁转职"）
          // V8.42 位置感知（V41.1 落地）：不再依赖 hiddenJobReady 标志位，直接用 hiddenTrialsMet 按当前位置校验，
          //   只要求「必经劫难 ≤ 当前难号」已过且当前难视为已达成，避免「难43判官金蝉须先过难65/73/81」死锁。
          const isPrologueJob = hiddenEntry.trial === 1;
          let gateBlocked = false;
          if (!isPrologueJob) {
            const miss = NDX.hiddenTrialsMet(s.hero, s.trialsPassed, (s.diff != null ? s.diff : hiddenEntry.trial)).missing;
            if (miss.length) {
              gateBlocked = true;
              this.toast(`转职受阻 · ${jobConfirm}：需完成 ${miss.join('、')} 难解锁转职条件`);
              this.pushLog(`【转职·受阻】${jobConfirm} 需先历经本英雄的特定关键劫难（你尚缺难号 ${miss.join('/')}），逃课太多，无缘此隐藏职`);
            }
          }
          if (!gateBlocked) {
            // 门槛 2：持有对应装备/法宝（8.11 硬门槛）。本难自身 treasure 视为已持有。
            let held = hiddenEntry.held || [];
            if (jobConfirm === '齐天·大圣' && s.flags.d22Refuse) held = []; // 难22抗命不松箍→免去紧箍持有门槛
            const ownedIds = new Set((s.equips || []).map((e) => e.id || e.treasureId));
            if (pendingNode && pendingNode.treasure) ownedIds.add(pendingNode.treasure.id);
            const lack = held.filter((id) => !ownedIds.has(id));
            if (lack.length) {
              const names = lack.map((id) => (NDX.lootById(id) ? NDX.lootById(id).name : id));
              this.toast(`转职受阻 · ${jobConfirm}：持有 ${names.join('、')} 法宝后方可觉醒`);
              this.pushLog(`【转职·受阻】${jobConfirm} 须持有专属装备/法宝（尚缺：${names.join('、')}），空手难承此职`);
            } else {
              s.flags.jobConfirm = jobConfirm;
              NDX.recordAwakened(jobConfirm);
              // P1-2 新手指引：首次实际转职成功时提示
              if (!s.flags._jobTaught) {
                s.flags._jobTaught = true;
                this.toast(`⚔ 转职觉醒：${jobConfirm} —— 隐藏职提供专属被动与独特玩法，多周目已觉醒职可直接继承`);
              }
              // §3 边框协调：同一选项结算并发了六道转职浮层 → 顺延六道转职，只弹英雄隐藏职
              if (NDX.ZHUANJIE) {
                const _defer = NDX.ZHUANJIE.deferPromote(s);
                if (_defer) this.pushLog(`【转职·顺延】此难已觉隐藏职「${jobConfirm}」，六道专职「${_defer}」顺延至下一劫`);
              }
              this.pushLog(`【转职】${jobConfirm} 已确认（隐藏职激活）`);
            }
          }
        } else {
          s.flags.jobConfirm = jobConfirm;
          NDX.recordAwakened(jobConfirm);
          // §3 边框协调：同一选项结算并发了六道转职浮层 → 顺延六道转职，只弹英雄隐藏职
          if (NDX.ZHUANJIE) {
            const _defer = NDX.ZHUANJIE.deferPromote(s);
            if (_defer) this.pushLog(`【转职·顺延】此难已觉隐藏职「${jobConfirm}」，六道专职「${_defer}」顺延至下一劫`);
          }
          this.pushLog(`【转职】${jobConfirm} 已确认`);
        }
      }
    }
    if (opt.ending) { s.ending = opt.ending; this.pushLog(`【结局】${opt.ending}`); }

    // 属性/体愿增益选项：只取属性，不再获得任何装备或材料（避免"加体加攻还送宝"）
    const isAttrOpt = hasAttrGain && !eff.equip && opt.fate !== '夺';
    let gotEquip = false;

    if (!isAttrOpt) {
      // 非属性选项才发放劫难掉落/装备：夺宝得普通宝物，其他（善恶/材料）保留材料机缘
      const dropRaw = (s.pending && s.pending.drop) || (s.pending && s.pending.node && s.pending.node.drop) || null;
      if (dropRaw) {
        const drops = Array.isArray(dropRaw) ? dropRaw : [dropRaw];
        // 用 lootById（装备池 + 法宝字典统一覆盖）识别：法宝（如紫金红葫芦/照妖镜/紧箍）此前被 equipById 漏判成材料，导致剧情劫难「该得的原著法宝」发不出
        const equipIds = drops.filter((id) => NDX.lootById(id));
        const matIds = drops.filter((id) => !NDX.lootById(id));
        const isLootOpt = opt.fate === '夺' || eff.equip;
        if (equipIds.length) {
          // 劫难只发放 1 件核心宝物：优先从套装基座（setTier===1 的 * 基座）中随机，无基座（即纯法宝）则取第一件
          const baseIds = equipIds.filter((id) => { const e = NDX.lootById(id); return e && e.setTier === 1; });
          const coreId = baseIds.length ? baseIds[Math.floor(Math.random() * baseIds.length)] : equipIds[0];
          const eq = NDX.lootById(coreId);
          // 若抽到已拥有的套装基座，改为直接发放其专属合成材料，避免重复入包
          if (eq && eq.setTier === 1 && eq.set && s.equips.some((e) => e.id === eq.id)) {
            const mats = NDX.setCraftMatsOf(eq.id);
            if (mats.length) {
              mats.forEach((m) => NDX.addMaterial(s, m, 1));
              gotEquip = true;
              const tag = isLootOpt ? '夺宝' : '劫难宝物';
              this.pushLog(`【${tag}】${eq.name} 已在行囊，改赠合成材料 ${mats.join('、')}。`);
            } else {
              this.grantEquip(eq);
              gotEquip = true;
              const tag = isLootOpt ? '夺宝' : '劫难宝物';
              this.pushLog(`【${tag}】获得 ${eq.name}（${eq.desc}）` + (isLootOpt ? '' : '——可寻材料合成进阶'));
            }
          } else {
            this.grantEquip(eq);
            gotEquip = true;
            const tag = isLootOpt ? '夺宝' : '劫难宝物';
            this.pushLog(`【${tag}】获得 ${eq.name}（${eq.desc}）` + (isLootOpt ? '' : '——可寻材料合成进阶'));
          }
        }
        // 基座/材料：层数越高越易出，但非必得，保留肉鸽赌博性
        const matChance = Math.min(0.6, 0.22 + s.layer * 0.025);
        if (matIds.length) {
          if (Math.random() < matChance) {
            const pick = matIds[NDX._rand(0, matIds.length - 1)];
            NDX.addMaterial(s, pick, 1);
            this.pushLog(`【劫难残骸】拾得材料 ${pick}（合成机缘 ${Math.round(matChance * 100)}%）`);
          } else {
            this.pushLog(`【劫难残骸】残骸散尽，未得可用基座（合成机缘未至）`);
          }
        }
      }
    // 显式 equip 数量且未从 drop 拿宝物时，额外弹装备三选一（避免"一次拿两次"）
    if (eff.equip && !gotEquip) {
      const items = NDX.rollEquips(eff.equip, s, eff.slot);
      if (!items.length) s.pending = { kind: 'choices' };
      else s.pending = { kind: 'equip', items };
      // 英雄专属抉择：金箍 / 隐藏暗线（保留）
      this._applyJingu(opt);
      this._applyTsHidden(opt);
      return;
    }
  } else {
    this.pushLog(`【劫难·抉择】未取宝物，只承其运`);
  }

  // 非战斗劫难 → 掉「善」道劫印（V8.20：只有劫难才必掉劫印；非战斗只出善印）
  // 与战斗型劫难（finishFight 掉恶印）成对：兵不血刃则随缘得善，力战破劫则得战/夺/逆之印。
  if (s.pending && s.pending.kind === 'trial' && !s._trialGoodSealed) {
    const offers = NDX.offerSealsAligned ? NDX.offerSealsAligned(s.hero, 'white', s, 'good') : NDX.offerSeals(s.hero, 'white', s);
    if (offers.length) {
      const r = NDX.addSeal(s, offers[0]);
      if (r.ok) {
        s.hSeals = s.hSeals || []; s.hSeals.push(offers[0]);
        this.pushLog(`【劫印·善】此劫兵不血刃，随缘纳善道劫印：${offers[0].name}（渡/隐/缘）`);
      }
    }
    s._trialGoodSealed = true;
  }

  // 英雄专属抉择：金箍 / 隐藏暗线 / 紧箍裂纹 / 专属传记（保留 + 8.12 新增）
  this._applyJingu(opt);
  this._applyTsHidden(opt);
  this._applyCrackJingu(opt);
  this._applyUnlockCodex(opt);

  // V8.31 新手教学提示：第二难隐藏职/升级石教学、第三难心魔教学
  const _eff = opt.effect || {};
  if (s.diff === 2 && !s._sealTeachShown) {
    s._sealTeachShown = true;
    setTimeout(() => this.toast('🗡 套装隐藏职——第一难择定六道后得升级石，同套组件方可唤醒隐藏职'), 600);
  }
  if (s.diff === 3 && !s._demonTeachShown && (_eff.alignEvil || 0) > 0) {
    s._demonTeachShown = true;
    setTimeout(() => this.toast('👹 心魔系统——恶道增心魔，满100触发镜像惩罚战'), 600);
  }

  // 劫难抉择即时反馈：同步弹出短剧情文案 + 本局变化提示（剧情+玩法双向绑定），
  // 让玩家清晰感知「我的选择立刻改变了难度与收益」。战斗选项已在开打时反馈，不重复弹。
  // V8.27 修复：复合节点子难（顺命/避世/掠走物证等非战斗抉择）完成后，连续推进下一子难，避免回地图卡死
  if (s.compound) {
    this._compoundNext();
    return;
  }
  const card = this._trialResultCard(opt, s);
  // 方案X2·难1六道总览：首难择道后重点介绍六道（攻式/装备套/转职石/经文钩子 + 改道说明），看完再踏上西行
  if (s.flags._firstDaoOverview) {
    s.flags._firstDaoOverview = false;
    const _cards = (NDX.sixDaoCards && NDX.sixDaoCards()) || [];
    s.pending = {
      kind: 'dao-overview',
      title: '六道 · 道途既定',
      text: `你以「${opt.fate}道」落定第一道印记。六道各有其攻式，且与装备套装、转职石、经文互为钩子——装备掉落将优先予你当前之道；日后于土地庙歇脚时可随时改道，道心无定，随心而行。`,
      chosen: opt.fate,
      opts: _cards.map((c) => ({
        dao: c.dao, name: c.name, desc: c.desc, align: c.align,
        atkName: c.atk ? c.atk.name : '', atkDesc: c.atk ? c.atk.desc : '',
        set: c.set, stoneName: c.stoneName, sutras: c.sutras || [],
        current: c.dao === opt.fate,
      })),
      next: '踏上西行',
    };
    this.render();
    return;
  }
  if (card) {
    s.pending = { kind: 'trial-result', title: card.title, body: card.body, sub: card.sub };
    if (card.awakenFate) s.pending.awakenFate = card.awakenFate;
  } else {
    s.pending = { kind: 'choices' };
  }
};
NDX.Game.prototype._trialResultCard = function _trialResultCard(opt, s) {
  const f = s.flags || {};
  const _pct = (v) => (v > 0 ? '+' : '') + Math.round(v * 100) + '%';
  // 本局即时变化文案（已关闭显示：不再在反馈卡底部列出妖魔凶悍/劫印品质等数值提示）
  const sub = '';
  // 短剧情文案：优先用该抉择自带的叙事 echo（前后呼应），否则按道途给默认黑暗叙事
  let body = opt.echo || opt.story || null;
  if (!body) {
    const fate = opt.fate || s.pending.fate || null;
    body = ({
      逆: '你逆天而行。三界妖魔闻之色变，自此更加凶悍；然你掌中劫印，却愈淬愈利——以险换锋。',
      渡: '你顺劫而渡。怨气化作暗流退去，妖魔气焰渐消；你得以喘息，续得更多机缘。',
      战: '你以杀止劫。血溅当场，劫数未消，唯刀锋记得你未曾退避。',
      隐: '你藏形于暗。劫难看不见你，你却看清了劫难的纹路。',
      夺: '你夺其所有。劫难之物落入你手，旁人眼中的灾，成了你的资粮。',
      缘: '你随缘而转。命运在此分岔，你踏上的那条，连天庭也未曾写就。',
    })[fate] || '劫落于此，你做出了选择。这一念，已悄然改写此后每一步的轻重。';
  }
  // V8.5x 劫印系统后移：第一难不再触发劫印觉醒，改为第一章 Boss（刘洪）战后首次获得劫印
  const result = { title: opt.text || '劫难已渡', body, sub };
  return result;
};
NDX.Game.prototype.afterTrialResult = function afterTrialResult() {
  const s = this.state;
  if (!s.pending || s.pending.kind !== 'trial-result') return;
  if (s.compound) { this._compoundNext(); return; } // V8.27 修复：复合节点非战斗子难连续推进
  // V8.31 长安送行改为地图节点形式（第4层强制插入），不再在劫难反馈后直接弹窗
  s.pending = { kind: 'choices' };
  this.render();
};
NDX.Game.prototype._applyJingu = function _applyJingu(opt) {
  if (!opt.jingu) return;
  const s = this.state;
  s.flags.jingu = true;
  const jg = NDX.equipById('jingu_treasure');
  if (jg) { this.grantEquip(jg); this.pushLog(`【金箍】戴上金箍，${jg.name} 已入行囊；战力暴涨百分百！`); }
  else this.pushLog(`【金箍】戴上金箍，战力暴涨百分百！`);
};
NDX.Game.prototype._applyTsHidden = function _applyTsHidden(opt) {
  if (!opt.tsHidden) return;
  const s = this.state;
  s.flags.tsHidden = true;
  this.pushLog(`【隐藏】你摘下符，山中另一个自己醒了——隐藏暗线已成必经之路。`);
};
NDX.Game.prototype._applyCrackJingu = function _applyCrackJingu(opt) {
  if (!opt.crackJingu) return;
  const s = this.state;
  s.flags.jinguCracks = (s.flags.jinguCracks || 0) + (opt.crackJingu || 1);
  this.pushLog(`【紧箍裂纹】金箍应声裂开第 ${s.flags.jinguCracks} 道纹——束缚与反噬皆更深，道途愈险。`);
};
NDX.Game.prototype._applyUnlockCodex = function _applyUnlockCodex(opt) {
  if (!opt.unlockCodex) return;
  const s = this.state;
  s.flags.unlockedCodex = s.flags.unlockedCodex || {};
  const key = opt.unlockCodex;
  if (NDX.readBiography && NDX.YEZANG_BIOGRAPHY && NDX.YEZANG_BIOGRAPHY[key]) {
    const r = NDX.readBiography(key);
    if (r && r.ok) this.pushLog(`【业藏录·纪事】${key} 已解锁——前往业藏录可阅其业障纪事。`);
    else s.flags.unlockedCodex[key] = true;
  } else {
    s.flags.unlockedCodex[key] = true;
    this.pushLog(`【业藏录·纪事】${key} 已记入——揭露老君纵牛之伪，天道叙事添一笔暗线。`);
  }
};
NDX.Game.prototype.applyMirrorOpt = function applyMirrorOpt(opt) {
    const s = this.state;
    const ap = opt.apply || {};
    s.mirror = s.mirror || {};
    const mr = s.mirror;
    const log = (t) => this.pushLog('【业镜】' + t);
    // —— 立即结算类（进镜即生效，不依赖战斗）——
    if (ap.healPct) {                 // 回复 30% 生命
      const maxHp = NDX.computeStats(s.hero, s.equips, s.materials, { ti: s.bonusTi, yuan: s.bonusYuan, seals: s.seals, followers: s.followers, daoxinTier: NDX.daoxinTier(s) }, s.diff, s.act).ti.maxHp;
      s.hp = Math.min(maxHp, s.hp + Math.round(maxHp * ap.healPct));
      log(`镜前回神，气血回复 ${Math.round(ap.healPct * 100)}%`);
    }
    if (ap.maxHpLossPct) {            // 本层最大生命 -10%（不可恢复）：以标记注入，下次 stats 时折算
      mr.maxHpLossPct = (mr.maxHpLossPct || 0) + ap.maxHpLossPct;
      log(`镜中杀意蚀骨，本层气血上限 -${Math.round(ap.maxHpLossPct * 100)}%（不可逆）`);
    }
    if (ap.shieldPct) {               // 护盾：吸收本局最大生命值 X% 伤害
      mr.shieldPct = Math.max(mr.shieldPct || 0, ap.shieldPct);
      log(`受星宿一礼，得护盾（抵 ${Math.round(ap.shieldPct * 100)}% 本局气血伤害）`);
    }
    if (ap.grantRandomDivine) {       // 无尽破碎：得随机神装
      const shard = NDX.rollDivineShard(s.layer || 1, false);
      (s.tjShards = s.tjShards || []).push.apply(s.tjShards, shard);
      log(`业镜破碎，错位的恩赐落入怀中：${shard.join('、') || '神装碎片'}`);
    }
    if (ap.loseFirstSlot) {           // 无尽破碎：失去装备栏第一格
      if ((s.equips || []).length) { const lost = s.equips.shift(); log(`因果线断，你竟失了 ${lost.name}`); }
      else log('因果线断，然你两手空空，无物可失');
    }
    // —— 照见五蕴·五英雄心魔特殊机制 ——
    if (ap.wuCutArmor) {              // 悟空【斩业】：弃一件防御装换金箍棒碎片 x2
      const idx = (s.equips || []).findIndex((e) => e.slot === 'armor');
      if (idx >= 0) { const d = s.equips.splice(idx, 1)[0]; log(`【斩业】弃防具 ${d.name}，换如意金箍棒碎片×2`); }
      else log('【斩业】你本无甲可弃，金箍棒碎片仍落入手心');
      (s.tjShards = s.tjShards || []).push(
        { id: 'tj_shard_wukong_0', name: '如意金箍棒碎片', tier: 'gold', tianJie: true },
        { id: 'tj_shard_wukong_1', name: '如意金箍棒碎片', tier: 'gold', tianJie: true }
      );
    }
    if (ap.wuHeartShield) { mr.shieldPct = Math.max(mr.shieldPct || 0, 0.5); log('【斩心】全队护盾（抵 50% 本局伤害）'); }
    if (ap.tsSacrifice) {             // 取经人【舍身】：耗 50% 当前生命复活队友
      s.hp = Math.max(1, Math.round(s.hp * 0.5));
      s.flags.reviveAllies = true; log('【舍身】散去半身气血，唤回同行亡魂');
    }
    if (ap.tsSaveBoss) { mr.nextBossAlly = true; log('【普度】倾尽混元，下层 BOSS 暂化为友军（仅本层）'); }
    if (ap.bjGlutton) {              // 八戒【暴食】：吞噬一件装备，属性化入本身（近似叠加）
      if ((s.equips || []).length) {
        const eaten = s.equips.pop(); mr.atkPct = (mr.atkPct || 0) + 0.12;
        log(`【暴食】吞噬 ${eaten.name}，其精华化入本躯（体攻 +12% 本局）`);
      } else log('【暴食】你已身无长物，无物可吞');
    }
    if (ap.bjVomit) {                 // 八戒【呕吐】：弃所有装备换混元点
      const n = (s.equips || []).length; s.equips = []; mr.voidLayer = false;
      const mi = n * 50; NDX.addMiPoints(mi, s.layer); log(`【呕吐】尽吐装备 ${n} 件，换得混元点 ${mi}`);
    }
    if (ap.ssDrop) {                  // 沙僧【卸担】：清除负面、本局不再获劫印
      mr.negativeCleared = true; mr.noNewSeal = true;
      mr.hpDrainPct = 0; mr.bloodFury = false; mr.maxHpLossPct = 0; mr.starDmgTaken = 0;
      log('【卸担】卸下重担，负面尽消，但此去再难纳新劫印');
    }
    if (ap.ssCarry) {                 // 沙僧【挑担】：负面转攻击
      mr.negativeToAtk = true; log('【挑担】担上业力尽化为锋芒，攻击大涨');
    }
    if (ap.blRoar) { mr.trueDmgLayer = true; mr.fateNodeDisabled = true; log('【龙吟】本层攻击附真实伤害，然缘分节点再不应你'); }
    if (ap.blDive) { mr.voidLayer = true; mr.noLootLayer = true; log('【潜渊】本层隐于天道，敌不可见你，你亦不可取利'); }
    // —— 本局持续状态（百分比/标记）乘区，由 stats/fight/finishFight 读取 ——
    if (ap.atkPct) mr.atkPct = (mr.atkPct || 0) + ap.atkPct;
    if (ap.drPct) mr.drPct = (mr.drPct || 0) + ap.drPct;
    if (ap.bossDmgMul) mr.bossDmgMul = (mr.bossDmgMul || 0) + ap.bossDmgMul;
    if (ap.bloodFury) mr.bloodFury = true;                 // 生命越低伤害越高（最高+50%）
    if (ap.hpDrainPct) mr.hpDrainPct = (mr.hpDrainPct || 0) + ap.hpDrainPct; // 每秒流失
    if (ap.immuneDeath) mr.immuneDeath = true;             // 免疫一次致死
    if (ap.slowMove) mr.slowMove = true;                   // 过场变慢（表现层）
    if (ap.nextEnemyMinus) mr.nextEnemyMinus = (mr.nextEnemyMinus || 0) + ap.nextEnemyMinus; // 下场敌人-1
    if (ap.hpLossOnEnterPct) mr.hpLossOnEnterPct = (mr.hpLossOnEnterPct || 0) + ap.hpLossOnEnterPct; // 进层掉血
    if (ap.starDmgTaken) mr.starDmgTaken = (mr.starDmgTaken || 0) + ap.starDmgTaken; // 星宿类敌人伤害+
    if (ap.starPassive) mr.starPassive = true;             // 随机星宿被动（每杀回血等，简化标记）
    if (ap.bossDebuff) mr.bossDebuff = (mr.bossDebuff || 0) + ap.bossDebuff; // 后续BOSS属性削弱
    if (ap.fateNodeDisabled) mr.fateNodeDisabled = true;   // 缘分节点增益失效
    if (ap.enemyAtkMul) mr.enemyAtkMul = (mr.enemyAtkMul || 1) * (1 + ap.enemyAtkMul); // 后续敌攻
    if (ap.enemyHpMul) mr.enemyHpMul = (mr.enemyHpMul || 1) * (1 + ap.enemyHpMul);     // 后续敌血
    // —— 第50层中阴身：强制改写双线权重 + 解锁结局分支 ——
    if (ap.midOrder) { mr.midOrder = true; mr.fateBranch = ap.fateBranch; this._applyMidOrder(); }
    if (ap.midChaos) { mr.midChaos = true; mr.fateBranch = ap.fateBranch; this._applyMidChaos(); }
    // 记录本次选择到旗标（供演出层灰影残留 / 日志）
    s.flags.lastMirror = { side: opt.side, verse: opt.verse, reflect: opt.reflect };
    // 照见五蕴：标记本英雄心魔已照见（避免同局重复）
    if (s.flags._mirrorFivePending) {
      s.flags._mirrorFiveSeen = s.flags._mirrorFiveSeen || [];
      if (s.flags._mirrorFiveSeen.indexOf(s.flags._mirrorFivePending) < 0) s.flags._mirrorFiveSeen.push(s.flags._mirrorFivePending);
      delete s.flags._mirrorFivePending;
    }
    log(`镜中人：${opt.reflect}`);
    // 失效的"被放弃选项"由 UI 灰影处理；此处直接进入下一节点选择
    s.pending = { kind: 'choices' };
    this.render();
  };
NDX.Game.prototype._applyMidOrder = function _applyMidOrder() {
    const fv = NDX.loadFavor();
    if (fv && typeof fv.chaosLv === 'number') fv.chaosLv = Math.max(0, Math.round(fv.chaosLv / 2));
    if (fv && typeof fv.orderLv === 'number') fv.orderLv = Math.round(fv.orderLv * 2);
    NDX.saveFavor(fv);
    this.pushLog('【中阴身·认命】混沌淬炼减半，秩序赐福翻倍——归顺天道之路已开');
  };
NDX.Game.prototype._applyMidChaos = function _applyMidChaos() {
    const fv = NDX.loadFavor();
    if (fv && typeof fv.orderLv === 'number') fv.orderLv = Math.max(0, Math.round(fv.orderLv / 2));
    if (fv && typeof fv.chaosLv === 'number') fv.chaosLv = Math.round(fv.chaosLv * 2);
    NDX.saveFavor(fv);
    this.pushLog('【中阴身·逆命】秩序赐福减半，混沌淬炼翻倍——大闹天宫之路已开');
  };
