// AUTO-GENERATED by _refactor_split.js — domain: compound
NDX.Game.prototype._compoundRoute = function _compoundRoute(opt) {
    const s = this.state;
    const c = s.compound;
    if (!c) { s.pending = { kind: 'choices' }; this.render(); return; }
    const e = opt.effect || {};
    if (e.alignGood || e.alignEvil) this.gainMoral(e.alignGood || 0, e.alignEvil || 0, '复合节点·' + (opt.key || ''));
    c.route = opt.key;
    c.bossMul = opt.bossMul || 1;
    if (opt.skipDiffs) c.diffs = c.diffs.filter((d) => opt.skipDiffs.indexOf(d) < 0);
    const routeName = opt.key === '渡' ? '渡化前行' : '逆道直行';
    this.pushLog(`【黄风岭三连难】你选择「${routeName}」——${opt.label}`);
    this._compoundNext();
  };
NDX.Game.prototype._compoundNext = function _compoundNext() {
    const s = this.state;
    const c = s.compound;
    if (!c) { s.pending = { kind: 'choices' }; this.render(); return; }
    if (c.idx >= c.diffs.length) {
      // 新手指引复合节点（第一章·前三难）完成：补发原序章教学奖励「锦襕袈裟」（原独立教学节点已并入本节点）
      if (s.act === 1 && !s.flags.gotIntroGift) {
        s.flags.gotIntroGift = true;
        const eq = NDX.equipById('jinlan_jiasha');
        if (eq) { s.equips.push(eq); this.pushLog(`【新手指引】金蝉遭贬、出胎几杀、满月抛江——三难历尽，得 ${eq.name}（${eq.desc}）`); }
      }
      // V8.34 地区配额制·融合节点结算：
      //   ① 融合节点完成后，其子难按战斗计入 battle 配额（每个融合子难 +1 battle，保证战道/夺道可攒满）；
      //   ② 融合节点完成后直接发高品质劫印（融合含难越多品质越高：1难=白、2难=蓝、3难=金）——
      //      直接给不碎片，兑现「劫难融合提高品质」设计。
      //      V9.6：**三难全战**（子难 3）为红劫唯一产出源——金为底，按逆道抉择深度低概率升华红（见 rollSealTier）。
      if (NDX.quotaEnabled(s.act)) {
        const _fusCnt = (c.diffs || []).length;
        for (let i = 0; i < _fusCnt; i++) NDX.addQuota(s, 'battle', 1);
      }
      // 融合节点劫印发放：仅两界山（quotaTier）启用「完成即得高品质印」；第一章/黄风岭保持原逻辑
      if (c.node && c.node.fusionDiffs && c.node.fusionDiffs.length) {
        const _n = c.node.fusionDiffs.length;
        // V9.6 品质档位收敛到真源（融合子难数 1/2/3 → 白/蓝/金）
        const _tier = NDX.rollSealTier ? NDX.rollSealTier('fusion', s, { fusionN: _n })
          : (_n >= 3 ? 'gold' : (_n >= 2 ? 'blue' : 'white'));
        const _offers = NDX.offerSealsAligned ? NDX.offerSealsAligned(s.hero, _tier, s, null) : NDX.offerSeals(s.hero, _tier, s);
        if (_offers.length) {
          const r = NDX.addSeal(s, _offers[0]);
          if (r.ok) {
            s.hSeals = s.hSeals || []; s.hSeals.push(_offers[0]);
            this.pushLog(`【融合·劫印】${c.node.name} 历尽，得 ${_offers[0].name}（${_offers[0].dao}道·${_offers[0].tier}）`);
          }
        }
      }
      this.pushLog(`【${NDX.compoundFor(s.act) ? NDX.compoundFor(s.act).name : '复合节点'}】历尽子难，前路已通。`);
      // 车迟国复合节点收束：三场斗法全「战」→ 解锁第31难一打三合体战；含「渡」（无隐）则斗法折服、跳过合体战
      if (c.chechi) {
        s.chechiAllWar = !!(c.chechi.choices && c.chechi.choices.length >= 3 && c.chechi.choices.every((x) => x === '战'));
      }
      // 通天河（act8）终局矩阵：全渡 → 鱼篮收伏（跳过决战）；全逆 → 河神反噬（决战强化）
      if (c.tongtian) {
        const _ch = c.tongtian.choices || [];
        s.tongtianAllDu = _ch.length >= 3 && _ch.every((x) => x === '渡');
        s.tongtianAllNi = _ch.length >= 3 && _ch.every((x) => x === '逆');
      }
      s.compound = null;
      s.pending = { kind: 'choices' };
      this.render();
      return;
    }
    const diff = c.diffs[c.idx];
    c.idx++;
    if (NDX.isBossTrial(diff)) this._compoundBoss(diff);
    else this._compoundTrial(diff);
  };
