// AUTO-GENERATED by _refactor_split.js — domain: combat
NDX.Game.prototype._startNegotiableFight = function _startNegotiableFight(p, angered) {
    const s = this.state;
    const node = p.node;
    const m = p.m;
    if (angered && m) {
      m.atk = Math.round((m.atk || 0) * (1 + (NDX.NEGOTIATE.angerAtkBonus || 0.10)));
      m.matk = Math.round((m.matk || 0) * (1 + (NDX.NEGOTIATE.angerAtkBonus || 0.10)));
    }
    this.fight(m, node.name, p.afterKind, null, node, true, p.teach);
  };
NDX.Game.prototype.fight = function fight(monster, name, afterKind, onWin, node, alreadyScaled, teach) {
    const s = this.state;
    const st = this.stats();
    // 【M1 音频治理 · BGM 单一 owner 收口（补正）】
    // 原此处战斗开场直连 mp3_player 播 audio/{battle,boss}_bgm.mp3，绕过桥接层，
    // 与 ui_core.js 的 NDX.sound.music('fight'|'boss')（assets/sound/bgm_*_ai.ogg）叠加成双 BGM。
    // 现收口：战斗/Boss BGM 一律由 js/sound.js 的 music() 播放（唯一 owner），此处不再拉 BGM。
    // NDX_MP3.init() 一并移除的依据：mp3_player.playSfx() 每次自带 new Audio()（mp3_player.js:72-79），
    // 不依赖 init() 预载的 sfxPool；stopBgm() 在无 playBgm 时是 no-op →
    // game_combat_2.js:25 的 victory/defeat SFX（playSfx）不受影响。
    // V8.54 法宝战斗间冷却：每场战斗开始时所有法宝 cd-1（cd>0 的法宝本场不可用）
    if (s._treasureCd) { for (const _k in s._treasureCd) { if (s._treasureCd[_k] > 0) s._treasureCd[_k] -= 1; } }
    // —— 肉鸽难度缩放：怪物强度随「难度层」温和爬升（对标杀戮尖塔，越往后期越凶险，
    // 但避免过度膨胀导致后期血条爆炸、普通玩家不可玩）。原 (diffLv-6)^1.7*0.035 在
    // diff18/20 时贡献 1.74/2.64 倍，怪血破万致回合过长；现改为温和线性缩放：
    // 基础随层 0.04 + 后期线性 0.12，避免指数爆炸使脆皮愿流派(取经人)/闪避流(白龙)后期断崖。
    // alreadyScaled：复活原地重打本场时传入，复用上次缩放结果，避免二次膨胀。
    const diffLv = (node && node.diff) || s.diff || s.layer;
    let m;
    const _jdef = NDX.enemyDefOf && NDX.enemyDefOf(node);
    if (alreadyScaled && monster && monster.__scaled) {
      m = Object.assign({}, monster); // 复用上次已缩放的怪物数据
    } else {
      // V8.56 多阶段回归修复：从输入怪物整体复制（保留 game_core_2 装配的阶段字段
      // stages/phaseStats/phaseOverrides/phase2Override/stageRewards/breakWith/blessTreasure/phaseSkipOn/
      // sanxi/spd/enrage/counter/affix…），仅覆盖随难度缩放的战斗主属性。
      // 此前按字段重建会丢弃 stages → calcCombat 走单阶段 → 两相劫/破韧窗口/阶段厚赏在实机不触发
      //（已实证：calcCombat 收到 hasStages=false）。战斗数值真相以本处为准。
      // 🔴 B3/P0-1C（2026-09-26）难度缩放重定标：
      //   旧曲线 hp = 1+(d-1)×0.06 + max(0,d-6)×0.08（d81 时 ×11.8）、atk = 1+(d-1)×0.13（×11.4），
      //   叠加 Boss 基础值自身的成长后 ⇒ 全局 Boss 血 ×42.6／攻 ×23，而玩家 DPS 仅 ×2.1、血 ×1.4
      //   ⇒ ch3 起「承伤预算回合」被击杀回合反超（ch4~ch9 采样胜率全 0%）。
      //   新曲线：统一温和斜率 0.03/档、上限封顶 1.6（d≥21 后不再膨胀），
      //   Boss 强度改由**逐 Boss 设计基础值**承载（见 enemies_part1 BOSS_FORMS 归一化表）。
      const _cap = Math.min(diffLv - 1, 20);
      // 🔴 S18 §⑤-1（2026-09-28 平衡批次）：**章间非单调的根因修复**。
      //   上式在 **d21 即饱和（×1.6）** ⇒ ch2 之后**所有章节的怪物缩放完全相同**，
      //   章间难度差异只剩「逐 Boss 基础值」一项；实测「渡档裸号」胜率随章**非单调**
      //   （ch3 仅 17% 而 ch8 高达 67%）——同一缩放下的 Boss 基础值差异被放大成噪声。
      //   故补一段**章末级微增**：d≥22 起每档 +0.8%，封顶 **+0.36**（⇒ d81 处 ×1.96，
      //   相对旧 ×1.6 仅 **+22%**）。量级远低于 B3/P0-1C 曾修的「Boss 血 ×42.6」爆炸面，
      //   不回归该次修复；且与玩家侧 d21–d77 的续长（`data_heroes.js` late 起点前移）
      //   形成「双端同档续长」，正是 S18 D1 的设计要求。
      const _lateCap = Math.min(0.12, Math.max(0, diffLv - 21) * 0.008);
      // V9.67 朝代‘diff’特色：秦朝难度+10%（怪物缩放倍率增加）
      const _dynDiffMul = NDX.dynastyAdjust ? NDX.dynastyAdjust(1, 'diff') : 1;
      const scale = (1 + _cap * 0.03 + _lateCap) * _dynDiffMul;
      const atkScale = (1 + _cap * 0.03 + _lateCap) * _dynDiffMul;
      m = Object.assign({}, monster);
      m.name = monster.name;
      m.type = monster.type;   // 类型透传（mob/elite/boss）：供小怪/精英节奏校准判定
      m.hp = Math.round((monster.hp || 100) * scale);
      m.atk = Math.round((monster.atk || 18) * atkScale);
      m.dr = Math.min(0.45, (monster.dr != null ? monster.dr : 0.1));
      m.matk = Math.round((monster.matk || 20) * atkScale);
      m.mdef = Math.min(0.45, (monster.mdef != null ? monster.mdef : 0.05));
      m.boss = !!monster.boss;
      // 阵营标签（供法宝「克制 counter」命中）+ 蓄力重击周期（触发识破窗口）+ 蓄力倍率
      m.tags = monster.tags || (_jdef && _jdef.tags) || (monster.boss ? ['天庭'] : ['妖']);
      m.heavyEvery = monster.heavyEvery || (_jdef && _jdef.heavyEvery) || (monster.boss ? 4 : 0);
      m.heavyMult = monster.heavyMult || (_jdef && _jdef.heavyMult) || 1.6;
      // P1-1 随从（前置肉盾）：随从存活期间玩家伤害全吃随从，破胆后溢出直打本体。
      // 数据源优先怪实例，其次敌库定义（BOSS_TABLE/ELITE_TABLE 可配 minion.hpPct/name）。
      m.minion = monster.minion || (_jdef && _jdef.minion) || null;
      m.__scaled = true;
      // 怪物随机词缀（《体系补全》·一阶）：缩放后附加，高层更凶；Boss 亦可能带词缀（已剔除过苛的「亵渎」）
      m = NDX.attachAffix(m, diffLv);
      m.__scaled = true;
    }
    // V8.30 教学战特例：跳过词缀附加，保留原始属性
    if (monster.tutorial) {
      m = Object.assign({}, monster);
      m.__scaled = true;
    }
    // 立绘与展示档位：按怪物名/类型/tags 解析最新立绘路径（resolvePortraitPath→img/portraits/子目录），供战斗头像动态渲染
    // V8.35 传入 m.tags（阵营标签），portraitOf 命中阵营立绘时覆盖 4 张轮换的视觉重复
    m.portrait = NDX.portraitOf(name, monster.type, m.boss, m.tags);
    m.tier = m.boss ? 'boss' : (monster.type === 'elite' ? 'elite' : 'mob');
    // 【语音集成】战斗开始时播放出场语音
    try {
      if (NDX.playBossVoice && m.boss) {
        // 尝试匹配Boss ID
        const bossIdMap = {
          '白骨夫人': 'boss_baigujing', '白骨精': 'boss_baigujing',
          '黄风大圣': 'boss_huangfeng', '黄风怪': 'boss_huangfeng',
          '红孩儿': 'boss_honghaier', '圣婴大王': 'boss_honghaier',
          '刘洪': 'boss_liuhong',
          '金角大王': 'boss_jinjiao', '金角': 'boss_jinjiao',
          '银角大王': 'boss_yinjiao', '银角': 'boss_yinjiao',
          '大鹏金翅雕': 'boss_dapeng', '大鹏': 'boss_dapeng',
          '牛魔王': 'boss_niumowang', '平天大圣': 'boss_niumowang',
        };
        const bossId = bossIdMap[name] || bossIdMap[m.name];
        if (bossId) NDX.playBossVoice(bossId, 'enter');
      } else if (NDX.playHeroVoice && s.hero) {
        // 玩家英雄出场语音（仅Boss战播放，避免过于频繁）
        if (m.boss) NDX.playHeroVoice(s.hero, 'enter');
      }
    } catch (e) { /* 语音播放失败不影响游戏 */ }
    // —— V9.x 怪物行为引擎：未自定义 behavior 时按类型派生默认行为 ——
    // mob=技能池加权（暗黑地牢式）；elite/boss=意图脚本循环 + 低血 30% 切换阶段脚本（杀戮尖塔式）。
    // guard=铁壁蓄势（本回合不出手+减伤，白嫖爆发窗口）；buff=妖气暴涨（本回合不出手+攻击叠层）；
    // multi=疾风连击（多段独立闪避）；heal=妖法回春（本回合不出手+回复，制造集火压力）。
    // 优先级：怪物自带 behavior > 敌库定义 behavior（_jdef，BOSS_TABLE/ELITE_TABLE 可配专属脚本）
    //          > 类型默认。教学战（tutorial）跳过：保持纯普攻，不受行为引擎影响。
    if (!m.behavior && !monster.tutorial) {
      const defBeh = _jdef && _jdef.behavior;
      if (defBeh) {
        m.behavior = defBeh;
      } else if (m.type === 'mob') {
        m.behavior = { mode: 'pool', pool: [
          { type: 'atk', w: 8 }, { type: 'heavy', w: 1 }, { type: 'guard', w: 0.5 }, { type: 'buff', w: 0.5 },
        ], guardPct: 0.25, buffAtkPct: 0.2 };
      } else if (m.type === 'elite') {
        m.behavior = { mode: 'pattern', pattern: ['atk', 'atk', 'guard', 'heavy', 'multi', 'buff'], stagePatterns: { 0.30: ['heavy', 'multi', 'atk', 'atk'] }, guardPct: 0.35, buffAtkPct: 0.2 };
      } else if (m.boss) {
        m.behavior = { mode: 'pattern', pattern: ['atk', 'guard', 'atk', 'heavy', 'multi', 'buff'], stagePatterns: { 0.30: ['heavy', 'multi', 'heavy', 'atk'] }, guardPct: 0.40, buffAtkPct: 0.25 };
      }
    }
    // 🆕 V9.61 地区词缀（Boss 技能链复活·A 点）：按章注入 REGION_AFFIXES（吹沙/骨爪/火星…）。
    //    零回归：getRegionAffix 查无 / 教学战 ⇒ 原样返回；数值沿用旧表（平衡批次实测后再调）。
    if (!monster.tutorial && NDX.applyRegionAffixToMob && s && s.act) {
      try { NDX.applyRegionAffixToMob(m, s.act); } catch (e) { /* 词缀失败不影响战斗 */ }
    }
    // —— V9.x 小怪节奏校准（浮动区间版）：普通小怪（type==='mob'）单场 2–8 回合浮动，
    // 玩家构筑越强（暴击/反震/劫印/装备加成），实际回合越短（下限2回合）；
    // 玩家构筑越弱，实际回合越长（上限8回合）。保留10回合硬上限，绝不超时。
    // 做法：按玩家本场「每回合有效伤害（含暴击期望）」反推小怪目标血量，
    // 构筑强度系数 = 增强DPS / 基础DPS，目标回合 = 基础目标回合 / 构筑强度系数。
    // 与旧版固定3-5回合的区别：玩家能明显感受到"我变强了，打怪更快了"。
    // V8.30 教学战跳过节奏校准（已由 applyStartOpt 按玩家属性精确校准）
    // P0-3 劫难词条·妖气弥漫：怪物开场即叠 1 层妖气暴涨（combat.js 读 m.buffLayersStart 起手）
    if (NDX.hasCurse && NDX.hasCurse(s, 'qiyao') && !monster.tutorial) m.buffLayersStart = 1;
    // P0-3 劫难词条·六根不净：每场重置识破计数（第 3 次起失效，见 resolveOpTreasure 拦截）
    if (NDX.hasCurse && NDX.hasCurse(s, 'liugen')) s._shiPoCount = 0;
    if (m.type === 'mob' && !monster.tutorial) {
      // 基础DPS：体伤+愿伤（忽略暴击/裂伤/反震——旧版逻辑）
      const _baseDpr = Math.max(
        1,
        (st.ti.atk * (1 - Math.min(0.9, (m.dr || 0) + (st.ti.drPct || 0)))) + (st.yuan.matk * (1 - Math.min(0.9, (m.mdef || 0) + (st.ti.drPct || 0))))
      );
      // V9.x 增强DPS：含暴击期望伤害（暴击率 × (暴击倍率 - 1)）
      // 暴击期望乘数 = 1 + 暴击率 × (暴击倍率 - 1)，例如暴击率20%、暴击倍率1.5 → 1.1
      const _cri = Math.min(1, st.ti.cri || 0);
      const _criMult = st.ti.criMult || 1.5;
      const _criMul = 1 + _cri * (_criMult - 1);
      // 反震期望（简化：反震比例 × 0.3，因为反震需要先挨打）
      const _reflect = Math.min(0.5, (st.ti.reflect || 0) + (st.sealReflect || 0));
      const _reflectMul = 1 + _reflect * 0.3;
      // 生命偷取期望（简化：吸血比例 × 0.2，因为吸血需要先造成伤害）
      const _lifeSteal = Math.min(0.5, st.lifesteal || 0); // V9.44 修正大小写：吸血为 computeStats 顶层键 lifesteal（原 st.ti.lifeSteal 恒 undefined → 自适应难度漏算吸血）
      const _lifestealMul = 1 + _lifeSteal * 0.2;
      // 增强DPS = 基础DPS × 暴击乘数 × 反震乘数 × 吸血乘数
      const _enhancedDpr = _baseDpr * _criMul * _reflectMul * _lifestealMul;
      // 构筑强度系数 = 增强DPS / 基础DPS（范围1.0-2.5）
      const _buildPower = Math.min(2.5, Math.max(1.0, _enhancedDpr / _baseDpr));
      // 基础目标回合：3-5回合（随难度递增）
      const _baseTargetRounds = Math.min(5, Math.max(3, Math.round(3 + (diffLv - 1) * 0.15)));
      // 实际目标回合 = 基础目标回合 / 构筑强度系数，限制在2-8回合
      const _targetRounds = Math.min(8, Math.max(2, Math.round(_baseTargetRounds / _buildPower)));
      // V8.58 方案A：给atk成长留35%净收益——怪物血量不再完全按_baseDpr缩放，
      // 引入成长保留系数：atkGrowth^-0.35，即玩家atk翻倍时，怪物血量只增长约57%，玩家保留约43%净收益。
      const _atkBase = 100;
      const _atkGrowth = Math.max(1, (st.ti.atk + st.yuan.matk) / _atkBase);
      const _growthMul = Math.pow(_atkGrowth, -0.35); // <1，随成长递减
      const _adjustedDpr = _baseDpr * _growthMul;
      m.hp = Math.max(1, Math.round(_targetRounds * _adjustedDpr));
      m._mobRhythm = _targetRounds;
      m._buildPower = _buildPower;
      this.pushLog(`【小怪节奏】目标 ${_targetRounds} 回合速决（构筑×${_buildPower.toFixed(2)}，暴击×${_criMul.toFixed(2)}，atk成长×${_atkGrowth.toFixed(2)}→血量×${_growthMul.toFixed(2)}，基础伤 ${Math.round(_baseDpr)}，校准血量 ${m.hp}）`);
    }
    // —— V9.x 精英节奏校准（浮动区间版）：精英（type==='elite'，不含 Boss）单场 4–16 回合浮动，
    // 玩家构筑越强，实际回合越短（下限4回合）；构筑越弱，实际回合越长（上限16回合）。
    // 难度越高回合越接近上限；若带「护盾（铁壁）/反伤（高反击）」词缀，因攻坚更慢、基础回合+2。
    // 与普通小怪同理：按玩家单回合有效伤害（含暴击期望）反推目标血量，构筑强度系数影响目标回合。
    // 机制缺口（主动提速收益）：精英的「护盾」与「韧性条（残血狂暴阈值）」存在固定释放窗口
    // （operationPoint：enrage / routine）；玩家在窗口内手动祭出法宝（临阵祭宝）可大幅压缩回合——
    // 不祭宝按基准回合打完，主动祭宝则提前斩杀，操作有明确提速收益。
    else if (m.type === 'elite') {
      const _baseDpr = Math.max(
        1,
        (st.ti.atk * (1 - Math.min(0.9, (m.dr || 0) + (st.ti.drPct || 0)))) + (st.yuan.matk * (1 - Math.min(0.9, (m.mdef || 0) + (st.ti.drPct || 0))))
      );
      // V9.x 增强DPS：含暴击期望伤害
      const _cri = Math.min(1, st.ti.cri || 0);
      const _criMult = st.ti.criMult || 1.5;
      const _criMul = 1 + _cri * (_criMult - 1);
      const _reflect = Math.min(0.5, (st.ti.reflect || 0) + (st.sealReflect || 0));
      const _reflectMul = 1 + _reflect * 0.3;
      const _enhancedDpr = _baseDpr * _criMul * _reflectMul;
      const _buildPower = Math.min(2.5, Math.max(1.0, _enhancedDpr / _baseDpr));
      let _baseRounds = Math.min(10, Math.max(6, Math.round(6 + (diffLv - 1) * 0.25)));
      // 护盾（铁壁词缀，dr 抬升）或反伤（高 counter 反击）词缀：攻坚更慢，基础回合+2
      const _shieldOrReflect = (m.affix && m.affix.indexOf('ironwall') >= 0) || (m.counter >= 0.18);
      const _adjustedBase = _shieldOrReflect ? Math.min(12, Math.max(6, _baseRounds + 2)) : _baseRounds;
      // 实际目标回合 = 基础目标回合 / 构筑强度系数，限制在4-16回合
      const _targetRounds = Math.min(16, Math.max(4, Math.round(_adjustedBase / _buildPower)));
      // V8.58 方案A：给atk成长留35%净收益（同小怪逻辑）
      const _atkBase = 100;
      const _atkGrowth = Math.max(1, (st.ti.atk + st.yuan.matk) / _atkBase);
      const _growthMul = Math.pow(_atkGrowth, -0.35);
      const _adjustedDpr = _baseDpr * _growthMul;
      m.hp = Math.max(1, Math.round(_targetRounds * _adjustedDpr));
      m._eliteRhythm = _targetRounds;
      m._buildPower = _buildPower;
      this.pushLog(`【精英节奏】目标 ${_targetRounds} 回合${_shieldOrReflect ? '（护盾/反伤·放宽）' : ''}（构筑×${_buildPower.toFixed(2)}，暴击×${_criMul.toFixed(2)}，atk成长×${_atkGrowth.toFixed(2)}→血量×${_growthMul.toFixed(2)}，基础伤 ${Math.round(_baseDpr)}，校准血量 ${m.hp}）；窗口内临阵祭宝可压缩回合`);
    }
    // —— 关隘 Boss 两相劫节奏校准：阶段1 固定 8–10 回合、阶段2 固定 8–12 回合，总计 ≤20 回合。
    // 依玩家单回合有效伤害反推各阶段血量；护盾/反伤词缀的攻坚更慢，本阶段上限各放宽 2 回合。
    // 阶段衔接处（calcMultiStage 注入 stageBreakPoint）须手动临阵祭宝破韧方能领取阶段厚赏。
    if (m.stages && m.stages.length >= 2) {
      // V8.59 保存原始阶段血量，校准后不低于原始血量的50%，避免Boss被过度校准导致3回合打死
      const _origStages = (m._origStages || m.stages || []).slice();
      if (!m._origStages) m._origStages = _origStages.slice();
      const _dpr = Math.max(
        1,
        (st.ti.atk * (1 - Math.min(0.9, (m.dr || 0) + (st.ti.drPct || 0)))) * (1 + (st.bossDmgMul || 0)) + (st.yuan.matk * (1 - Math.min(0.9, (m.mdef || 0) + (st.ti.drPct || 0))))
      );
      const _shieldOrReflect = (m.affix && m.affix.indexOf('ironwall') >= 0) || (m.counter >= 0.18);
      const _p1 = _shieldOrReflect ? Math.min(12, Math.max(8, 9 + 1)) : Math.min(10, Math.max(8, 8 + Math.round((diffLv - 1) * 0.2)));
      const _p2 = _shieldOrReflect ? Math.min(14, Math.max(8, 11 + 1)) : Math.min(12, Math.max(8, 9 + Math.round((diffLv - 1) * 0.3)));
      // V8.58 方案A：给atk成长留35%净收益（同小怪/精英逻辑）
      const _atkBase = 100;
      const _atkGrowth = Math.max(1, (st.ti.atk + st.yuan.matk) / _atkBase);
      const _growthMul = Math.pow(_atkGrowth, -0.35);
      const _adjustedDpr = _dpr * _growthMul;
      // V8.59 Boss血量下限：校准后不低于原始血量的50%，避免前期Boss被过度校准
      const _minHp1 = _origStages[0] ? Math.round(_origStages[0] * 0.5) : 0;
      const _minHp2 = _origStages[1] ? Math.round(_origStages[1] * 0.5) : 0;
      m.stages = [
        Math.max(_minHp1, 1, Math.round(_p1 * _adjustedDpr)),
        Math.max(_minHp2, 1, Math.round(_p2 * _adjustedDpr)),
      ];
      m._bossRhythm = [_p1, _p2];
      this.pushLog(`【两相劫节奏】阶段1 目标 ${_p1} 回合、阶段2 目标 ${_p2} 回合（atk成长×${_atkGrowth.toFixed(2)}→血量×${_growthMul.toFixed(2)}，有效伤 ${Math.round(_dpr)}，校准 阶段1=${m.stages[0]} / 阶段2=${m.stages[1]}，原始 阶段1=${_origStages[0] || '?'} / 阶段2=${_origStages[1] || '?'}，下限50%）；阶段间须临阵祭宝破韧领厚赏`);
    }
    // —— 被动法宝·如意精箍棒（金箍）：敌人现身（战斗开始）时金箍骤紧，立削其 5%~10% 气血（自动发动，不耗充能）；
    //    另：每回合有概率附带一次额外物理攻击，概率随法宝增强（atk）提高 ——
    //    V8.28：被动法宝也须在法宝栏内方可发动
    const _passiveIds = NDX.activeEquipsFor ? NDX.activeEquipsFor(s).map((x) => x && x.id) : [];
    const hasJingu = (s.equips || []).some((e) => e.treasure && e.treasureId === 'jingu' && _passiveIds.includes(e.id));
    // 断山符·被动：开局破紧箍一次（金箍骤紧失效）
    const hasDuanshanfu = (s.equips || []).some((e) => e.treasure && e.treasureId === 'duanshanfu' && _passiveIds.includes(e.id));
    let jinguProcChance = 0;
    if (hasJingu && m.hp > 0) {
      if (hasDuanshanfu) {
        this.pushLog(`【法宝·断山符】符光一闪，金箍骤紧被强行破除——紧箍镇压本回合失效`);
      } else {
      const cut = 0.05 + Math.random() * 0.05; // 5%~10%
      const before = m.hp;
      m.hp = Math.max(1, Math.round(m.hp * (1 - cut)));
      m._jinguMark = true; // 表现层：标记紧箍触发，供 driveFight 发射 jingu 特效
      this.pushLog(`【法宝·如意精箍棒】金箍骤紧，${name} 现身即被镇压，气血 ${before} → ${m.hp}（削 ${Math.round(cut * 100)}%）`);
      // 附带攻击概率：基础 18%，每点攻击力超出基准 16 提升 0.8%，上限 50%（法宝增强即概率提高）
      const jEq = (s.equips || []).find((e) => e.treasure && e.treasureId === 'jingu' && _passiveIds.includes(e.id));
      const jAtk = (jEq && jEq.atk) || 16;
      jinguProcChance = Math.min(0.5, 0.18 + Math.max(0, jAtk - 16) * 0.008);
      this.pushLog(`【法宝·如意精箍棒】每回合有 ${Math.round(jinguProcChance * 100)}% 概率附带一记额外物理重击（法宝愈强，概率愈高）。`);
      }
    }
    // —— 被动法宝·dmgPctStart（金箍成长链/轮回盘等）：敌人现身时自动削敌气血 ——
    //    支持 数组格式 [min, max]（随机）和 固定数值格式（如轮回盘 0.08）
    //    跳过 jingu 主件（已由上方金箍骤紧块处理）
    const _dmgStartEquips = (s.equips || []).filter((e) => {
      if (!e.treasure) return false;
      if (e.treasureId === 'jingu') return false; // 已由上方金箍骤紧块处理
      if (!_passiveIds.includes(e.id)) return false; // V8.28：须在法宝栏内
      const T = NDX.TREASURES && NDX.TREASURES[e.treasureId];
      return T && T.effect && T.effect.dmgPctStart != null;
    });
    for (const eq of _dmgStartEquips) {
      if (m.hp <= 0) break;
      const T = NDX.TREASURES[eq.treasureId];
      const val = T.effect.dmgPctStart;
      const cut = Array.isArray(val) ? (val[0] + Math.random() * (val[1] - val[0])) : val;
      const before = m.hp;
      m.hp = Math.max(1, Math.round(m.hp * (1 - cut)));
      this.pushLog(`【法宝·${T.name}】${T.name}自动发动，${name || '妖敌'} 气血 ${before} → ${m.hp}（削 ${Math.round(cut * 100)}%）`);
    }
    // —— 天道劫：敌人血量指数缩放（防崩坏机制 floor）——
    // 公式：base * (1 + layer*0.1)^2；作为节奏校准血量的「地板」，确保后期必死且不破坏前期节奏控制。
    if (NDX.isTianJie() && node && node.tianJie) {
      const _floor = NDX.tianJieMonsterHpScale(node.diff || s.layer || 1, monster.hp || 100);
      if (_floor > m.hp) {
        m.hp = _floor;
        this.pushLog(`【天道劫·业重】第${node.diff || s.layer}阶妖敌气血随层数暴涨 → ${m.hp}（指数缩放地板生效）。`);
      }
    }
    // —— 金刚琢机制（青牛/老君专属）：套走兵器 = 破韧 + 缴械（清空法宝蓄势），二阶段无敌帧须以「非兵器手段」破业障槽 ——
    // 检测：Boss/精英定义里的 jinguo 标记（或 bossName 命中青牛/老君）
    const _jname = (_jdef && _jdef.jinguo) || (NDX.BOSS_TABLE && NDX.BOSS_TABLE[name] && NDX.BOSS_TABLE[name].jinguo) || (NDX.ELITE_TABLE && NDX.ELITE_TABLE[name] && NDX.ELITE_TABLE[name].jinguo);
    if (_jname) {
      m.jinguo = true;
      m.jinguoTurn = 3; // 第 3 回合祭出金刚琢
      this.pushLog(`【金刚琢】${name} 祭出金刚琢：第 3 回合将套走你的兵器（破韧 + 缴械），二阶段须以「非兵器手段」（毫毛分身 / 耙子投掷）破其业障槽！`);
    }
    // —— 业镜·本局持续状态注入战斗（中阴身/照见五蕴/选线标记）——
    const _mr = s.mirror || {};
    if (_mr.enemyHpMul && _mr.enemyHpMul !== 1) { m.hp = Math.max(1, Math.round(m.hp * _mr.enemyHpMul)); }
    if (_mr.enemyAtkMul && _mr.enemyAtkMul !== 1) {
      m.atk = Math.round(m.atk * _mr.enemyAtkMul); m.matk = Math.round(m.matk * _mr.enemyAtkMul);
    }
    if (_mr.starDmgTaken && m.kind === 'star') { m.atk = Math.round(m.atk * (1 + _mr.starDmgTaken)); m.matk = Math.round(m.matk * (1 + _mr.starDmgTaken)); }
    if (_mr.bossDebuff && m.boss) { m.atk = Math.round(m.atk * (1 - _mr.bossDebuff)); m.matk = Math.round(m.matk * (1 - _mr.bossDebuff)); }
    if (_mr.nextBossAlly && m.boss) { m.__ally = true; this.pushLog('【普度】此层 BOSS 受混元感化，化作友军，不战而过。'); }
    if (_mr.voidLayer) { m.__void = true; this.pushLog('【潜渊】你隐于天道，此层妖敌无视你，安然掠过。'); }
    if (_mr.trueDmgLayer) { m.__trueDmg = true; this.pushLog('【龙吟】本层攻击附真实伤害，无视其甲胄。'); }
    if (_mr.bossDmgMul && m.boss) { m.hp = Math.max(1, Math.round(m.hp / (1 + _mr.bossDmgMul))); } // 对BOSS伤害+ → 等效降其血
    if (_mr.nextEnemyMinus && m.count) { m.count = Math.max(1, m.count - _mr.nextEnemyMinus); this.pushLog('【业镜·绕道】此战妖敌 -' + _mr.nextEnemyMinus + ' 名。'); }
    let playerHp = s.hp;
    // 防御：怪物数据无效（NaN/0/负数）时跳过战斗演出，按胜利直接结算，避免"满血却判败"
    if (!monster || !Number.isFinite(Number(monster.hp)) || Number(monster.hp) <= 0) {
      this.pushLog(`【战斗】${name}：妖影虚无，未历险即过`);
      if (typeof onWin === 'function') onWin();
      const after = afterKind;
      if (after === 'bossreward') s.pending = { kind: 'bossreward', title: '关隘通关 · 法宝三选一（唯一）', text: '此关隘镇压之宝，乃本章专属强力法宝——可临阵祭出、具主动战技，与兵刃甲胄灵宠等装备截然不同。择其一，余者化尘。', items: NDX.bossRewardsFor(s.hero, s.act) };
      else if (after === 'tiyuan') s.pending = { kind: 'tiyuan', node: node || null };
      else s.pending = { kind: 'choices' };
      return;
    }
    // 业镜·潜渊（隐形掠过）/ 照见五蕴·普度（友军不战）：直接胜，不播对轰演出
    if (m.__void || m.__ally) {
      this.pushLog(`【战斗】${name}：${m.__void ? '潜渊隐形，妖敌无视你，安然掠过' : '普度感化，BOSS 化友军，不战而过'}`);
      if (typeof onWin === 'function') onWin();
      const after = afterKind;
      if (after === 'bossreward') s.pending = { kind: 'bossreward', title: '关隘通关 · 法宝三选一（唯一）', text: '此关隘镇压之宝，乃本章专属强力法宝——可临阵祭出、具主动战技，与兵刃甲胄灵宠等装备截然不同。择其一，余者化尘。', items: NDX.bossRewardsFor(s.hero, s.act) };
      else if (after === 'tiyuan') s.pending = { kind: 'tiyuan', node: node || null };
      else s.pending = { kind: 'choices' };
      return;
    }
    // —— P0-3 劫难词条：开场提示本场受缚（仅教学战/潜渊/普度不提示）——
    if (!monster.tutorial && !m.__void && !m.__ally && (s.curses || []).length) {
      const _cs = s.curses.map((c) => { const d = NDX.CURSE_TABLE && NDX.CURSE_TABLE[c]; return d ? d.icon + ' ' + d.name : c; }).join(' · ');
      this.pushLog(`【西行劫难】此战受缚：${_cs}——险中求利，碎金倍酬在望。`);
    }
    // —— P0-D 运气核心：Build 匹配采样 + 方差钳制（V3 §4.3/4.4）——
    // 将原「固定难度倍率（monsterHpMult/AtkMult）」替换为按「当前 Build 强度 + 难度档」动态采样：
    // 依玩家承伤预算（气血 + 每回合回复）× 威胁压力系数反推怪物体/愿攻击，使任何 Build 在该难度档下
    // 都「扛得住而不必死、但威胁足够」（pressure 恒钳于 [0.25,0.90]，0.90<<1 → 必死局占比≈0，方差钳制）。
    // 血量由既有「节奏校准」（玩家 _dpr 反推怪血）显式承接——本就是 Build 匹配，故本处专钳威胁侧。
    // 教学战/潜渊/普度（不战而过）跳过：前者已由 applyStartOpt 精确校准，后者不进入对轰。
    if (!monster.tutorial && !m.__void && !m.__ally) {
      const _mInfo = NDX.buildMatchFight(st, m, {
        difficulty: (s && s.difficulty) || 'normal',
        diffLv,
        heroId: s.hero,
      });
      if (_mInfo) this.pushLog(`【势均采样】压力系数 ${_mInfo.pressure}（目标回合 ${_mInfo.rounds}，承伤预算 ${_mInfo.tank}，威胁目标 ${_mInfo.targetThreat}/现 ${_mInfo.threatCur}）；怪攻钳至 体${_mInfo.atk}/愿${_mInfo.matk}（scale ${_mInfo.scale}）`);
    }
    const heroDef = NDX.HEROES[s.hero] || {};
    const _playerObj = {
        heroId: s.hero,                       // 英雄独立被动
        jobConfirm: NDX.currentJob ? NDX.currentJob(s) : (s.flags.jobConfirm || null), // 隐藏职当前形态（兼容旧单值字段）
        // 🔴 2026-09-26 链上叠加：战斗侧必须拿到**全部**已确认职，否则被动又退化为「只算最后一个」
        jobs: (NDX.activeJobs ? NDX.activeJobs(s) : (s.flags.jobConfirm ? [s.flags.jobConfirm] : [])),
        good: s.good || 0,                    // 取经人善念
        spd: st.spd || (heroDef.baseSpd || 8), // 速度（computeStats 含装备速度加成）决定先手
        ti: Object.assign({}, st.ti, { hp: playerHp, curHp: playerHp }), // 完整体属性 + 当前血量
        yuan: { matk: st.yuan.matk, mdef: st.yuan.mdef },
        // V8.5x 构筑分化：装备通用来源（反伤/护盾），收敛体攻暴击流唯一解
        reflect: st.reflect || 0,
        shieldPct: st.shieldPct || 0,
        // V8.44 事件装备·无视护甲（穿透怪物减伤）
        armorPen: st.armorPen || 0,
        // 劫印派生标记（反伤/吸血/残影必中）与劫印机制标记（fateFlags）：透传给战斗内核
        sealReflect: st.sealReflect || 0,
        lifesteal: st.lifesteal || 0,
        evaOnDodge: st.evaOnDodge || false,
        fateFlags: st.fateFlags || {},
        // 业藏录全局加成（与赐福/成就同池）：透传给战斗内核，供受击减伤/破韧/特攻判定使用
        // ⚠ V-fix（R1②）：coll 四键改读 st.*（computeStats 产出），fallback s.* / 0。
        //   注：attr_calc.js:520-530 已将业藏录 coll 写入 st，故本改会真正启用 coll 加成（此前读 s.* 恒 0 而失效）；
        //       属"修复装配断裂"，但会改变战斗数值，需 S18 重新定标（见 R10）。
        coll: {
          dmgTakenColl: st.dmgTakenColl ?? s.dmgTakenColl ?? 0,     // 受击减伤（负值=减伤）
          breakEffColl: st.breakEffColl ?? s.breakEffColl ?? 0,     // 破韧效率
          bossDmgMul: st.bossDmgMul ?? s.bossDmgMul ?? 0,         // 对 BOSS 伤害
          dmgTiantingColl: st.dmgTiantingColl ?? s.dmgTiantingColl ?? 0, // 对天庭特攻
        },
        battleFlags: this._ashBattleFlags(),
        // P0-3 劫难词条·心魔缠身：每 5 回合玩家流失 3% 当前气血（战斗内核按 round%5 结算）
        _curseXinmo: NDX.hasCurse ? NDX.hasCurse(s, 'xinmo') : false,
        // 方案X2·六道攻式：按当前主要道途单一生效（战斗内核 playerAttack / 手动三键 activeSkill 双轨消费）
        daoAtk: (NDX.daoAtkStyleOf ? NDX.daoAtkStyleOf(s) : null),
        // V9.31 自动回合内核：透传经位（atk 格 skill 经修饰 → 自动战斗与手动三键同口径消费）
        jingSlots: (function () { if (NDX.ensureJingSlots) NDX.ensureJingSlots(s); return s.jingSlots || null; })(),
        // V9.31 多怪编队：atk 格经是否带群伤 → 决定溅射比例（无群伤仅顺手扫击）
        squadAoe: (function () {
          if (!NDX.ensureJingSlots) return false;
          NDX.ensureJingSlots(s);
          const id = s.jingSlots && s.jingSlots.atk;
          const bk = (id && NDX.jingBookOf) ? NDX.jingBookOf(id) : null;
          return !!(bk && bk.mod && (bk.mod.aoe || bk.mod.splash));
        })(),
        // 🩸 X1 接线（2026-09-27 · Batch 0）：以下 7 个字段是 `simulateSingle`（js/combat_part1.js:443+）
        //   **真实读取**但本白名单漏掉的透传项 ⇒ 生产端 computeStats 算了、装进内核却读不到，机制整体静默失效：
        //     · followerSkills —— 随从 13/13 主动技 + 5/5 羁绊（combat_part1.js:1231）
        //     · engineTier    —— 转职机制词（破甲/多段/旧伤/悖论/混沌）：combat_part1.js:457
        //     · petPassive    —— 灵宠机制被动：combat_part1.js:461
        //     · petCombo      —— 兽印·裂连击率：combat_part1.js:916
        //     · finalDamage   —— 逆道·终伤乘区：combat_part1.js:888
        //     · hpDrainPct    —— 业镜·燃寿（每回合掉血比例）：combat_part1.js:1269
        //     · immuneDeath   —— 业镜·天命护符（免疫一次致死）：combat_part1.js:1362
        //   全部给「缺省值」而非 undefined ⇒ 无这些来源时逐位等价于改前（构造性零回归）。
        finalDamage: st.finalDamage || 0,
        engineTier: st.engineTier || {},
        petPassive: st.petPassive || {},
        petCombo: st.petCombo || 0,
        followerSkills: st.followerSkills || [],
        hpDrainPct: st.hpDrainPct || 0,
        immuneDeath: !!st.immuneDeath,
    };
    // —— V9.31 多怪编队：普通怪/精英怪按难度派生「前排主怪 + 从怪」——
    //   Boss 保持原多阶段/随从设计不变（不与编队叠加，避免机制互相淹没）。
    let _squad = [m];
    if (NDX.buildSquad && !m.boss && !m.tutorial) {
      _squad = NDX.buildSquad(m, { type: m.type, diff: diffLv, act: (s.act || 1) });
    }
    const res = (_squad.length > 1 && NDX.calcCombatSquad)
      ? NDX.calcCombatSquad(_playerObj, _squad, { stanceSeq: [s.stance || 'ATK'] })
      : NDX.calcCombat(_playerObj, m, { stanceSeq: [s.stance || 'ATK'] });
    // V9.33 · 自动回合内核：经位 atk 格经书 on-hit 状态（道途派生；复用 applyMonsterStatus）
    //   眩晕真跳过怪物行动、灼烧真扣血、破甲真增伤 —— 经文 debuff 不再只活在手动三键路径。
    if (NDX.applyJingOnHit) NDX.applyJingOnHit(res, _playerObj);
    // V9.30 · 六道装备成长：本场挨打计数（怪物命中玩家的回合数）→ 满 10 次自动成长（缘固防/战攻/夺血/渡法伤/隐闪/逆反伤）
    if (NDX.bumpEquipGrowthHits) {
      const _hitsTaken = (res.roundsDetail || []).filter((r) => r && r.mTurn && (r.mTurn.deal || 0) > 0).length;
      const _grown = NDX.bumpEquipGrowthHits(s, _hitsTaken);
      if (_grown > 0) this.pushLog(`【装备成长】历经 ${_hitsTaken} 次打击，${_grown} 件道装共鸣成长`);
    }
    this._battleFlags = null;
    // STANCE·战前姿态心魔落账：心魔净量经唯一入口 gainXinmo 写入（战斗内核不再直写全局心魔）。
    // 静默/不计数/不计配额，仅作用于本场预结算的攻守姿态增量；setStance re-resolve 会先撤销此量再重算。
    const _stanceAppliedXm = res.stanceXinmo
      ? this.gainXinmo(res.stanceXinmo, { countGain: false, quota: false, silent: true, source: 'stance' })
      : 0;
    // 法宝·如意精箍棒：每回合概率附带一次额外物理攻击（概率随法宝增强而提高）
    // 在 calcCombat 之后对 res 做确定性就地修正，使演出与结算一致（与 applyBattleIntervention 同思路）
    if (jinguProcChance > 0) {
      NDX.applyJinguProc(res, {
        procChance: jinguProcChance,
        physBase: (st && st.ti && st.ti.atk) || 0,
        mDr: (m && m.dr) || 0,
      });
    }
    // —— V9.6 被动法宝·on-hit（西游释厄传名器：紫金葫芦/金刚琢/芭蕉扇…）：普攻命中概率触发削弱/控制/灼烧 ——
    // 与 applyJinguProc 同思路：calcCombat 之后对 res 做确定性就地修正（演出与结算一致）。
    // 仅"法宝栏内被动法宝"（_passiveIds）且 effect.onHit 者触发；phase:'passive' 自动排除在祭宝列表外。
    const _onHitEquips = (s.equips || []).filter((e) => {
      if (!e.treasure || !_passiveIds.includes(e.id)) return false;
      const T = NDX.TREASURES && NDX.TREASURES[e.treasureId];
      return T && T.effect && T.effect.onHit;
    });
    let _onHitList = [];
    if (_onHitEquips.length) {
      _onHitList = _onHitEquips.map((e) => {
        const T = NDX.TREASURES[e.treasureId];
        return Object.assign({}, T.effect.onHit, { _tid: e.treasureId, _name: T.name });
      });
      // V9.6 法宝×经文耦合：玩家所持全本经文的道途集合（单一真源 NDX.sutraDaosOf）
      const _sutraDaos = NDX.sutraDaosOf ? NDX.sutraDaosOf(s) : [];
      NDX.applyTreasureOnHit(res, _onHitList, {
        boss: !!m.boss,
        playerDao: (s.daoAtk && s.daoAtk.dao) || (s.dao) || null,
        sealMechs: (s.seals || []).map((sl) => (sl && sl.mechanism) || '').filter(Boolean),
        sutraDaos: _sutraDaos,
      });
    }
    this.pushLog(`【战斗】${name}（难度${diffLv}·气血${m.hp}/体攻${m.atk}/愿攻${m.matk}）：${res.win ? '胜' : '败'}，共${res.roundsDetail.length}回合`);

    // 生成战斗叙事文字（西游 + 冒险日记风）：为对峙 / 每回合 / 收尾注入代入感描述
    const hero = NDX.HEROES[s.hero] || { name: '行者', form: '', symbol: '兵刃' };
    this._buildFightNarrative(res, hero, name, m.hp, { isBoss: !!m.boss || (node && node.type === 'boss'), isTrial: !!(node && (node.type === 'trial' || node.trial)) });

    // 进入演出状态：保存结果、双方初始血量、推进方式（无论胜负都演一遍）
    // 取消强制战前法宝选择：玩家直接进入战斗演出，在战斗中通过法宝栏手动祭出。
    // 保留 preFight 字段与相关方法以兼容旧逻辑，但不再强制进入战前面板。
    // —— 战斗节奏控制：多阶段 Boss 自动锁定 1 倍速（通过 bus 'fightSpeed' 事件通知 UI）——
    // V8.38 优化：精英战不再锁速，允许2x加快节奏；仅 Boss 战锁1x，确保关键演出不被跳过
    // V8.38 速战模式：非Boss战强制2x速度
    const _isBoss = !!m.boss;
    // 战斗节奏控制：多阶段 Boss 自动锁定 1 倍速；通过业务总线通知 UI 层，避免反向依赖 NDX.ui
    NDX.bus.emit('fightSpeed', {
      locked: _isBoss,
      speed: _isBoss ? 1 : ((NDX.settings && NDX.settings.fastMode) ? 2 : undefined)
    });
    // P0-D 难度：怪物血量/攻击已由「节奏校准（血量侧）+ buildMatchFight（威胁侧）」锁定，
    // 不再在此后二次乘固定难度倍率（否则与势均采样冲突、且演出与结算脱节）。
    // 难度档差异已收敛为 buildMatchFight 的 pressureFactor（见 data_config.js）。
    s.pending = {
      kind: 'fight',
      name,
      monster: m,
      afterKind,
      node: node || null,
      onWin: (typeof onWin === 'function') ? onWin : null,
      res,
      win: res.win,
      roundIdx: -1,           // 尚未开始播放
      mHp: m.hp,              // 演出中的敌方当前血量
      pHp: playerHp,          // 演出中的玩家当前血量
      lastDetail: null,
      preFight: false,        // 战前法宝选择阶段已取消
      preFightUsed: [],       // 玩家已选中的法宝 id（保留兼容）
      // —— 主动操作点：战斗中择机祭宝（打破纯被动回放）——
      opHandled: [],          // 已处理过的操作点回合序号（1-based）
      opUsed: [],             // 本场已祭出的法宝 id（每件每场仅一次）
      awaitOp: -1,            // 当前暂停等待玩家抉择的操作点回合（1-based），-1 表示无
      activeCdAt: { atk: -99, chant: -99, ult: -99 },  // 三键主动技能上次释放拍数（CD 按拍差校验，V8.27）
      ultUsed: false,         // 戾骨献祭本场已用（限 1 次，V8.27）
      phase: 'intro',         // V8.29 回合制阶段：intro/wait/play/break/finish
      noTimer: (typeof s.diff === 'number' && s.diff >= 1 && s.diff <= 9),  // 第一章（act 1，diff 1–9）：战斗全部"择机"窗口无时间限制，强制等待玩家输入，便于新手学习机制
      autoFight: false,        // V8.32 取消自动攻击：所有战斗默认手动，玩家须点击三键技能（攻/经/绝）
      combatFx: (NDX.cfxInit ? NDX.cfxInit(m) : {}), // V8.47 战斗状态（debuff/叠甲/搓招）随每场重置
      pDebuffs: Object.assign({}, (res && res.pDebuffs) || {}), // V8.50 玩家侧 debuff（Boss 招牌，临阵可解）
      teach: teach || null,   // 剧情劫难同步教学：随战斗面板内嵌显示（不作独立弹窗轰炸）
      _startTs: Date.now(),    // P0-3（2026-09-06）：战斗起始墙钟，供 finishFight 计算本场时长（ms）
      // V8.40 战意/经力系统：通过统一模块NDX.BattleResource初始化，综合英雄+劫印+经文+装备
    };
    // V8.58 新手教学触发：接引使者教学战触发战斗教学（n1_battle_attack）
    try {
      if (teach === 'tutorial' && NDX.NewbieTeach && NDX.triggerTeach) {
        NDX.triggerTeach('n1_battle_attack', { battle: true, teach: teach });
      }
    } catch (e) { /* noop */ }
    // V8.40 战意/经力初始化：通过统一模块计算，替代散落在多处的手动计算
    if (NDX.BattleResource && typeof NDX.BattleResource.createState === 'function') {
      const brState = NDX.BattleResource.createState(s);
      Object.assign(s.pending, brState);
    }
    // STANCE·战前姿态：缓存整场预结算上下文，供 setStance 在开场前（intro / 首回合 wait）re-resolve（单一真源、向后兼容）
    s.pending._stanceCtx = {
      playerObj: _playerObj,
      m: m,
      jinguProcChance: jinguProcChance,
      physBase: (st && st.ti && st.ti.atk) || 0,
      mDr: (m && m.dr) || 0,
      onHitList: _onHitList || [],
      boss: !!m.boss,
      playerDao: (s.daoAtk && s.daoAtk.dao) || (s.dao) || null,
      sealMechs: (s.seals || []).map((sl) => (sl && sl.mechanism) || '').filter(Boolean),
      sutraDaos: (NDX.sutraDaosOf ? NDX.sutraDaosOf(s) : []),
      hero: hero,
      name: name,
      isBoss: !!m.boss || (node && node.type === 'boss'),
      isTrial: !!(node && (node.type === 'trial' || node.trial)),
      appliedXm: _stanceAppliedXm,   // STANCE：本场已落账的心魔净量（setStance re-resolve 前先撤销）
    };
    // —— 战前入场动画（分小怪/精英/Boss 三档，强化层级感知）——
    // 在 driveFight 真正播放 INTRO 拍之前，由 main.runPreFightAnim 调度分层动画；
    // 动画期间主战斗演出暂停（roundIdx 保持 -1），避免与入场覆盖层抢画面。
    const _tier = m.boss ? 'boss' : (m.type === 'elite' ? 'elite' : 'mob');
    // 本局核心劫印机制预览（Boss 四角图标用，提醒玩家搭法宝应对机制；V8.26 命痕并入劫印）
    const _sealMechPrev = (s.seals || []).filter((sl) => sl && sl.mechanism).slice(-3).map((x) => ({ name: x.name || '劫印', dao: x.dao || '', mech: (x.mechanism || '') }));
    const _sealPrev = (s.seals || []).slice(-3).map((sl) => ({ name: sl.name || '劫印', dao: sl.dao || '', kind: sl.kind || '' }));
    // 精英 / Boss 的特质词缀浮字（反伤 / 封印 / 高韧 等），红色警示字体停留
    const _affixPrev = (m.affix && m.affix.length)
      ? m.affix.map((a) => {
          const d = (NDX.MONSTER_AFFIXES && NDX.MONSTER_AFFIXES[a]) || { icon: '❖', name: a, desc: '' };
          return { id: a, icon: d.icon || '❖', name: d.name || a };
        })
      : [];
    s.pending.preAnim = {
      tier: _tier,
      nodeType: (node && node.type) || null, // 记录节点类型，用于区分普通战斗与劫难
      phase: 'transition',   // 状态机：transition → entrance → (boss: reveal/aura) → done
      t0: 0,                 // 本阶段起始时间戳（runPreFightAnim 写入）
      done: false,
      mechs: _sealMechPrev,
      seals: _sealPrev,
      affixes: _affixPrev,
      // 当前难号：供入场动画 overlay 显示「第 N 难 · 名称」
      diff: (node && node.diff) || s.diff || s.layer || 1,
      // 劫难场景基调（荒山/洞府/河流等），决定水墨底色调
      scene: (node && node.scene) || (m.boss ? 'guan' : (m.type === 'elite' ? 'cave' : 'wild')),
      // 横版立绘大图接入（V8.27）：把名号与立绘路径透传给 UI 入场秀与战斗大图卡
      monsterName: m.name || '',
      monsterPortrait: m.portrait || '',
    };
    // 战斗胜利后（LOOT 之后）播放按英雄身份的小说段落叙事；失败不播（finishFight 失败直接结算）
    s._narrative = NDX.pickNovel((node && node.diff) || s.diff || s.layer, s.hero);
  };
// STANCE·战前攻守姿态（Shape A）：开场前（intro / 首回合 wait，尚未结算任何回合）可切换，re-resolve 整场预结算
NDX.Game.prototype.setStance = function (st) {
  if (st !== 'ATK' && st !== 'GUARD') return;
  const s = this.state, p = s.pending;
  if (!p || p.kind !== 'fight') return;
  // 仅「未开始结算任何回合」时可改：intro 或 首回合 wait（roundIdx<=0，且非 play/break/finish）
  const _prePlay = (p.phase === 'intro') || (p.phase === 'wait' && p.roundIdx <= 0);
  if (!_prePlay || !p._stanceCtx) return;
  if (s.stance === st) return;
  s.stance = st;
  const c = p._stanceCtx;
  // 复位心魔：先撤销上一次预结算已落账的姿态净量（经唯一入口，非直写），避免 re-resolve 重复累加
  if (c.appliedXm) this.gainXinmo(-c.appliedXm, { cap: false, countGain: false, quota: false, silent: true, source: 'stance' });
  // 克隆 playerObj（纯数据），避免上一次预结算的就地改动污染本次 re-resolve
  const _po = JSON.parse(JSON.stringify(c.playerObj));
  const res = NDX.calcCombat(_po, c.m, { stanceSeq: [st] });
  // 确定性后置修正（与 fight() 内一致）：如意精箍棒 on-hit + 被动法宝 on-hit
  if (c.jinguProcChance > 0) {
    NDX.applyJinguProc(res, { procChance: c.jinguProcChance, physBase: c.physBase, mDr: c.mDr });
  }
  if (c.onHitList && c.onHitList.length) {
    NDX.applyTreasureOnHit(res, c.onHitList, {
      boss: c.boss, playerDao: c.playerDao, sealMechs: c.sealMechs, sutraDaos: c.sutraDaos,
    });
  }
  this._buildFightNarrative(res, c.hero, c.name, c.m.hp, { isBoss: c.isBoss, isTrial: c.isTrial });
  // 落账新姿态心魔净量，并记录实量供下次切换撤销（经唯一入口 gainXinmo）
  c.appliedXm = res.stanceXinmo
    ? this.gainXinmo(res.stanceXinmo, { countGain: false, quota: false, silent: true, source: 'stance' })
    : 0;
  // 覆盖演出状态（尚未开打：回满双方血量、清操作点、回到首拍）
  p.res = res;
  p.win = res.win;
  p.pDebuffs = Object.assign({}, res.pDebuffs || {});
  p.mHp = c.m.hp;
  p.pHp = s.hp;
  p.roundIdx = 0;
  p.lastDetail = null;
  p.awaitOp = -1;
  p.opHandled = [];
  p.opUsed = [];
  p.activeCdAt = { atk: -99, chant: -99, ult: -99 };
  p.ultUsed = false;
  this.pushLog(`【攻守姿态】切换为 ${st === 'GUARD' ? '守势·安心魔（攒势缓）' : '攻势·抬心魔（攒势疾）'}`);
};
NDX.Game.prototype._buildFightNarrative = function _buildFightNarrative(res, hero, foeName, foeMaxHp, ctx) {
    const R = (arr) => arr[NDX._rand(0, arr.length - 1)];
    const ct = ctx || {};
    const isBoss = !!ct.isBoss;
    const isTrial = !!ct.isTrial;
    const H = hero.name, SYM = hero.symbol || '兵刃', FORM = hero.form ? hero.form + '·' : '';
    const foe = ct.bossName || foeName;
    // 对峙开场（含先手提示）
    const firstTip = res.first === 'enemy'
      ? `${foe}势如奔雷，抢得先机——${H}须后发制人。`
      : `${H}金睛一凛，占得先手——${SYM}未出，杀意已锁${foe}。`;
    res.intro = R([
      `${H}收${SYM}，立于${foe}之前。山风骤起，杀机弥漫——两道身影再无转圜。${firstTip}`,
      `「${foe}」拦住去路，獠牙森然。${FORM}${H}眯起眼，将${SYM}攥得更紧。${firstTip}`,
      `前路为${foe}所断。${FORM}${H}吐纳一沉，周身气血与念力同涌，只待一战。${firstTip}`,
    ]);
    // 逐回合叙事
    res.roundsDetail.forEach((d, i) => {
      const parts = [];
      // 先手提示
      if (d.first === 'enemy') parts.push(`${foe}抢先扑来，`);
      // 玩家出手（PLAYER_PHASE）
      if (d.pTurn) {
        const t = d.pTurn;
        if (t.dodged) {
          parts.push(`${H}一击落空，${foe}身形已避让。`);
        } else {
          const big = t.deal >= Math.max(20, foeMaxHp * 0.18);
          const verb = (t.magic >= t.phys)
            ? R(['心念流转，愿力透体', '口诵真言，法相加身', '凝念成锋，直取其魂'])
            : R([`抖${SYM}力劈`, `抡${SYM}横扫`, `踏步一记重斩`]);
          const hit = big ? R(['正中要害，重创', '劈开护体，伤透', '狠狠凿在']) : R(['堪堪擦过', '刺中', '扫在']);
          const lv = big ? R(['鲜血迸溅', '骨裂之声可闻', '妖气一滞']) : R(['皮肉之伤', '只留浅痕', '略见血光']);
          const crit = t.cri ? '【暴击】' : '';
          parts.push(`${crit}${H}${verb}，${hit}${foe}，${lv}（损其 ${t.deal} 气血）。`);
          if (t.dot) parts.push(`裂伤渗入，${foe}又损 ${t.dot}。`);
          if (t.counter) parts.push(`${foe}借势反击，裂缝反弹，伤${H} ${t.counter}。`);
        }
      }
      // 敌方出手（ENEMY_PHASE：含护盾吸收 / 反震 / 护盾碎裂）
      if (d.mTurn) {
        const t = d.mTurn;
        if (t.dodged) {
          parts.push(`${foe}扑身来犯，却被${H}身法一错，扑了个空。`);
          // V9.67 成就累计：闪避次数
          { const _gs = this.state; if (_gs && _gs._runStats) _gs._runStats.dodgeTotal = (_gs._runStats.dodgeTotal || 0) + 1; }
        } else {
          const big = t.deal >= Math.max(20, (res.pMaxHp || 60) * 0.18);
          const hit = big ? R(['反扑得手，利爪加身', '暴起一击，正中肩胛', '妖力贯体，狠狠撞上']) : R(['反扑撩伤', '爪牙擦过', '一击扫中']);
          const lv = big ? R(['气血翻涌', '创口刺骨', '眼前一黑']) : R(['仅受微伤', '皮外擦伤', '不妨大局']);
          parts.push(`${foe}${hit}，${H}${lv}（受创 ${t.deal}）。`);
          // 🆕 格挡 / 反击（V9.60）：与闪避(dodged)是两次独立判定，故可并列出现
          if (t.blocked) parts.push(`${H}举械格架，来势卸去半数。`);
          if (t.absorbed) parts.push(`护盾挡下 ${t.absorbed}。`);
          if (t.reflect) parts.push(`反震 ${t.reflect}，伤及${foe}。`);
          // ⚠ 字段名用 counterRiposte 而非 counter：mTurn.counter 已被「裂缝反弹」占用（敌方视角反击）
          if (t.counterRiposte) parts.push(`${H}趁隙还击，${foe}又损 ${t.counterRiposte}。`);
          if (t.shieldBomb) parts.push(`护盾碎裂，震敌 ${t.shieldBomb}！`);
          // 🆕 V9.61 Boss 专属技能叙事（复活链路）：执行器 log 行已自带【技能名】前缀
          if (t.bossSkillLog && t.bossSkillLog.length) t.bossSkillLog.forEach((l) => parts.push(l));
          // V9.67 成就累计：Boss技能见证
          { const _gs = this.state; if (_gs && _gs._runStats && t.bossSkillName) _gs._runStats.bossSkillsSeen[t.bossSkillName] = true; }
        }
      }
      // 回合结算（TURN_RESOLVE：DOT 持续伤害）
      if (d.resolve && d.resolve.dots.length) {
        d.resolve.dots.forEach((dot) => {
          parts.push((dot.tgt === 'p' ? `${H}` : `${foe}`) + `持续${dot.kind}，又损 ${dot.dmg}。`);
        });
      }
      // 狂暴（CHECK_END → ENRAGE）
      if (d.justEnraged) parts.push(`【狂暴】${foe}目赤气盛，攻势暴涨！`);
      d.narr = parts.join(' ') || `第${i + 1}回合，两相交错，谁也奈何不得谁。`;
    });
    // 收尾点评：按战斗性质（普通 / 劫难 / Boss）扩展多维度收尾文案池
    let winPool = [
      `${foe}嘶吼一声，轰然倒地，妖气尽散。${FORM}${H}按${SYM}而立，前路又通一程。`,
      `${foe}化作一缕青烟散去。${H}收${SYM}，望向来路——这西行，又过了一道劫。`,
      `尘埃落定，${foe}伏诛。${FORM}${H}抹去血迹，气度更沉三分。`,
    ];
    let losePool = [
      `${H}气血见底，眼前一黑，栽倒在${foe}利爪之下……`,
      `${foe}獠牙咬碎最后一口气血，${H}踉跄半步，终究不支倒地。`,
      `念力散尽、肉身崩解，${H}于${foe}咆哮声中阖然——轮回，方才开始。`,
    ];
    if (isTrial && !isBoss) {
      winPool.push(
        `此劫已渡，${foe}化作飞灰。${H}长舒一口浊气，心魔暂歇，步履又轻了几分。`,
        `因果了结，${foe}退去。前路烟尘里，似有旧日的执念随风散了。`,
        `劫数既过，${H}定神回望——这一关，不是靠力，是仗着一口气撑下来的。`
      );
      losePool.push(
        `劫难未渡，${foe}未除。旧日执念又笼上心头，${H}喘息未定，眉间已添新愁。`,
        `此劫失手，${H}踉跄退开——心魔未驯，前路愈发难行。`
      );
    }
    if (isBoss) {
      winPool.push(
        `劲敌授首，${foe}轰然崩塌。${FORM}${H}擎${SYM}而立，妖氛也为之一慑。`,
        `天威尽显，${foe}终伏。这一关隘既破，西行之路又畅一程。`,
        `${foe}偃旗息鼓，关隘洞开。${H}望断来路，只觉肩头轻了千斤。`
      );
      losePool.push(
        `通天之敌未倒，${H}力竭倾颓——宿命如山，此关非一时可越。`,
        `败于${foe}之手，${H}血染征袍。然妖氛未散，这一败，不过是轮回又一圈。`
      );
    }
    res.conclusion = res.win ? R(winPool) : R(losePool);
  };

