// AUTO-GENERATED by _refactor_split.js — domain: core
NDX.Game.prototype.render = function render() {
    // V8.61 反馈接线批：道心档位切换 / 心魔近满 的可感化检查（O(1)，任何状态变化路径必经 render）
    try { if (this._checkPerception) this._checkPerception(); } catch (e) { /* 可感性检查不阻断渲染 */ }
    if (NDX.bus) NDX.bus.emit('render');
  };
NDX.Game.prototype.toast = function toast(msg) { if (NDX.bus) NDX.bus.emit('toast', msg); };
NDX.Game.prototype.setBattleFlags = function setBattleFlags(flags) { this._battleFlags = flags || null; };
NDX.Game.prototype.battleFlagsHint = function battleFlagsHint(flags) {
    if (!flags) return '';
    const om = flags.openingMomentum;
    const drain = flags.drainPct;
    const dmg = flags.dmgMul;
    const inc = flags.incomingDmgMul;
    const parts = [];
    if (om >= 1) parts.push(om === 2 ? '开局二式气势' : `开局气势+${om}`);
    if (drain > 0) parts.push(`每回合自损${Math.round(drain * 100)}%气血`);
    if (dmg != null && dmg < 1) parts.push(`输出约-${Math.round((1 - dmg) * 100)}%`);
    if (inc != null && inc < 1) parts.push(`承伤约-${Math.round((1 - inc) * 100)}%`);
    if (!parts.length) return '';
    let tag = '刚勇';
    if (drain > 0) tag = '逆起';
    else if (dmg != null || inc != null) tag = '护体';
    return `【姿态·${tag}】${parts.join('、')}`;
  };
