// AUTO-GENERATED by _refactor_split.js — domain: vault
NDX.Game.prototype.openVault = function openVault(nodeId) {
    const s = this.state;
    const node = NDX.vaultById(nodeId);
    if (!node) { this.toast('此处成亡遗迹已随山水磨灭'); this.render(); return; }
    const op = NDX.vaultOptions(node);
    if (!op.opts.length) {
      this.toast(node.kind === 'shrine' ? '舍利塔空空——满池无物相赠' : '衣冠冢空空——此行两手空空');
      this.render();
      return;
    }
    // V8.57 成亡节点首次引导：本机首次回访任一衣冠冢/舍利塔时，先弹观音偈语讲解「万世剑冢」，
    // 领受后由 then 重入真正的二选一弹窗（不阻断回访，仅插一层引导）。
    let first = false;
    try {
      if (NDX.storage && NDX.storage.KEYS && NDX.storage.KEYS.VAULT_GUIDE) {
        first = !NDX.SaveSystem.loadBoolean(NDX.storage.KEYS.VAULT_GUIDE, false) && !s._vaultGuideFirst;
        if (first) {
          s._vaultGuideFirst = true; // 本轮确保只插一次引导（防止 then 回环后重复）
          NDX.SaveSystem.saveBoolean(NDX.storage.KEYS.VAULT_GUIDE, true);
        }
      }
    } catch (e) { first = false; }
    if (first) {
      const _shrine = node.kind === 'shrine';
      const _loc = (NDX.ACT_NAMES && NDX.ACT_NAMES[Math.min((node.region || 1), NDX.TOTAL_ACTS) - 1]) || ('第' + (node.region || 1) + '地区');
      s.pending = {
        kind: 'guanyin-msg',
        text: `观音菩萨：「金蝉，前方便是${_shrine ? '舍利塔——返程坐化的前人，骨殖化为舍利，横陈于西来之路' : '衣冠冢——倒在半途的行脚，碑立当道，此冢敛着残甲余血'}。历代行脚在此留下遗珍，供后世拾取：${_shrine ? '可拾 装备 或 经文' : '可拾 装备 或 组件'}，只取其一。${node.pickupCount ? '此冢已被人掀过几回，灵光渐敛，经岁愈衰——但聊胜于无。' : '无人动过的冢，灵光最盛，正宜你去启封。'}」`,
        then: { kind: 'vault-pick', op, chosen: -1 },
      };
      this.render();
      return;
    }
    s.pending = { kind: 'vault-pick', op, chosen: -1 };
    this.render();
  };
NDX.Game.prototype.chooseVault = function chooseVault(i) {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'vault-pick') return;
    const op = p.op;
    const opt = (op && op.opts && op.opts[i]) || null;
    if (!opt) return;
    const node = NDX.vaultById(op.nodeId);
    if (!node) { this.toast('遗迹已磨灭，无从拾取'); s.pending = { kind: 'choices' }; this.render(); return; }
    const mult = op.mult;
    const pool = node.pool || {};
    const label = opt.name || opt.id;
    const _decayTag = mult < 1 ? `（传承已衰·仅留部分属性 ×${mult}）` : '';
    if (opt.kind === 'equip') {
      const src = (pool.equips || []).find((e) => e.id === opt.id);
      if (src) { (s.equips = s.equips || []).push(NDX._stripVaultReward(src, mult)); }
      this.pushLog(`【成亡拾遗】自${node.kind === 'shrine' ? '舍利塔' : '衣冠冢'}得装备「${label}」${_decayTag}`);
    } else if (opt.kind === 'sutra') {
      // V3 §二 自动路由：舍利塔拾得全本同样「入背包 → 立即自动投入主道途生效」
      s.sutras = s.sutras || [];
      s.sutraBackpack = s.sutraBackpack || [];
      if (s.sutras.indexOf(opt.id) < 0 && s.sutraBackpack.indexOf(opt.id) < 0) {
        s.sutraBackpack.push(opt.id);
        if (NDX.routePendingSutras) NDX.routePendingSutras(s);
        if (NDX.recordSutra) NDX.recordSutra(opt.id);
        if (NDX._notifySutra) NDX._notifySutra(s, opt.id);
      }
      if (mult < 1) s._sutraMult[opt.id] = mult;
      this.pushLog(`【成亡拾遗】自舍利塔得经文「${label}」${_decayTag}`);
    } else if (opt.kind === 'mat') {
      const cnt = Math.max(1, Math.round((opt.count || 1) * mult));
      if (NDX.addMaterial) NDX.addMaterial(s, opt.id, cnt); else { s.materials = s.materials || {}; s.materials[opt.id] = (s.materials[opt.id] || 0) + cnt; }
      this.pushLog(`【成亡拾遗】自衣冠冢得${opt.cat}「${label}」×${cnt}${_decayTag}`);
    }
    NDX.bumpVaultPick(op.nodeId);
    this._syncAch();
    s.pending = { kind: 'choices' };
    this.render();
  };
