// AUTO-GENERATED by _refactor_split.js — domain: core
NDX.Game.prototype.enterNode = function enterNode(layer, col) {
    const s = this.state;
    if (s.over) return;
    // V8.58 新手教学触发：第一次进入地图节点时触发地图教学（n4_map_node）
    try {
      if (!s.flags._mapTeachTriggered && NDX.NewbieTeach && NDX.triggerTeach) {
        s.flags._mapTeachTriggered = true;
        NDX.triggerTeach('n4_map_node', { layer: layer, col: col });
      }
    } catch (e) { /* noop */ }
    // V8.52→V8.53 英雄专属装备随章节自动进阶（幂等、不降级；进入每节点时收敛到当前章节 tier）
    // 三槽（法宝/武器/护甲）统一收敛，缺的槽不动。
    if (NDX.upgradeHeroGear) {
      const _ups = ['treasure', 'weapon', 'armor']
        .map((sl) => { try { return NDX.upgradeHeroGear(s, sl); } catch (e) { return null; } })
        .filter(Boolean);
      if (_ups.length) {
        this.pushLog(`【装备进阶】${_ups.map((u) => u.to).join('、')}（原 ${_ups.map((u) => u.from).join('、')}）——随西行渐深而愈发精进。`);
      }
    }
    // 防重入 / 禁止回退：每个节点只能进入一次
    const cell = NDX.LAYERS[layer] && NDX.LAYERS[layer][col];
    if (s.visited.some((v) => v.layer === layer && v.col === col)) {
      this.pushLog(`【行迹】${cell ? cell.name : '旧地'}：已历此难，不可重蹈`);
      return;
    }
    const node = NDX.LAYERS[layer][col];
    // —— 缘分门槛（V8.17）：关隘 Boss 需「渡难/降妖/缘遇」达标方可挑战；未达标即「缘分未到」——
    if (node.type === 'boss' && s.mode === 'outbound' && !s.over) {
      const _gate = NDX.fateGateCheck(s);
      if (!_gate.met) {
        const _miss = _gate.missing.map((m) => `${m.label} ${m.cur}/${m.need}`).join(' · ');
        this.pushLog(`【缘分未到】${node.name || '关隘'}：${_miss}——缘未至，门不开。`);
        this.toast(`缘分未到：还需 ${_miss}，方可叩关。`);
        NDX.bus.emit('render');
        return;
      }
    }
    s.layer = layer;
    s.col = col;
    // 刘洪（第一章关隘·叙事第四难）开战前：观音多步新手引导（减益·气势破除·连招），时长可拉长
    // 须在寿命扣除 / 记入 visited 之前拦截——否则会重复扣寿，且「每节点只进一次」守卫会阻断引导后的重入开战
    // V8.5x 修订：赠宝已在前一层 L4「长安送行」事件节点发放（game.js:1193 songEvent 分支），此处置 gotInitGift=true 后只挂引导链。
    if (node.type === 'boss' && s.act === 1 && !s.flags._liuhongGuideDone) {
      s.flags._liuhongGuideDone = true;
      s.pending = this._liuhongGuide(layer, col);
      this.render();
      return;
    }
    // 土地庙（首入歇脚节点）观音多步新手引导（补血·罪业·其他），时长可拉长
    // 须在寿命扣除 / 记入 visited 之前拦截——否则会重复扣寿，且「每节点只进一次」守卫会阻断引导后的重入开庙
    // 劫印入口（道途层数面板）改为"持有劫印才出现"，由 ui.js 据 s.seals 门控，无需此处 flag
    // #64 刘洪（第一章关隘·难4）结束后首个土地庙：三选一引导（套装自动组合/打坐回寿），选完即退出
    if (node.type === 'rest' && s.trialsPassed && s.trialsPassed.some((t) => t.diff === 4) && !s.flags._tudiPostLiuHongDone) {
      s.flags._tudiPostLiuHongDone = true;
      s.pending = { kind: 'tudi-choice', layer, col };
      this.render();
      return;
    }
    if (node.type === 'rest' && !s.flags._tudiGuideDone) {
      s.flags._tudiGuideDone = true;
      s.pending = this._tudiGuide(layer, col);
      this.render();
      return;
    }
    // V8.48 埋点：节点进入（定位流失 / 卡关）
    if (NDX.telemetry) { try { NDX.telemetry.track('trial_enter', { layer: layer, col: col, type: node ? node.type : '', name: node ? node.name || '' : '' }); } catch (e) {} }
    // —— 六道专职转职（V8.18 §7.1）：进入节点时刷新事件判定点（每节点只弹一个转职事件）——
    if (NDX.ZHUANJIE) { try { NDX.ZHUANJIE.enterNode(s); } catch (e) {} }
    // —— 寿命（阶段一）：去程每进一个节点耗寿；土地庙打坐回寿；见底则大限坐化 ——
    if (s.mode === 'outbound' && !s.over) {
      // 阶段六·高难度收紧寿命：走高难/转世路线时，进入本难耗寿按难度倍率上浮，喂给硬核目标
      let _pay = NDX.lifeCost(node);
      if (_pay > 0 && NDX.lifeTighten) {
        const _t = NDX.lifeTighten(s.diff, (NDX.getCycle ? NDX.getCycle() : 1));
        if (_t.costMul !== 1) _pay = Math.round(_pay * _t.costMul * 100) / 100;
      }
      if (_pay > 0) s.life = Math.max(0, s.life - _pay);
      if (node.type === 'rest') s.life = Math.min(s.lifeMax, s.life + (NDX.LIFE.MEDITATE_REGAIN || 0));
      this._checkLife();
      if (s.over) return; // 大限坐化：不再进入该节点结算
      // V8.31 第三难寿数教学：第一次耗寿时提示
      if (s.diff === 3 && !s._lifeTeachShown && _pay > 0) {
        s._lifeTeachShown = true;
        setTimeout(() => this.toast('🕯 西行耗寿——每进一难寿数减，大限坐化非终局'), 800);
      }
      // V8.61 首次关隘寿命教育（Rev.4 报告 9.1）：Boss 是最贵节点（0.6 岁），把"寿命定价"第一次点透
      if (node.type === 'boss' && _pay > 0 && !(s.flags && s.flags._bossLifeEdu)) {
        s.flags = s.flags || {};
        s.flags._bossLifeEdu = true;
        setTimeout(() => {
          try {
            this.toast('🕯 此关耗去你半年寿数——关隘最贵，命最值钱');
            this.render();
          } catch (e) {}
        }, 800);
        this.pushLog('【寿数】关隘一难过，鬓边一缕霜。关隘耗寿最重（0.6 岁），恶道抉择还要再加——省着点花，你还要走回长安。');
      }
    }
    // 灯油系统已于 V8.27 删除，恶道额外耗资源并入寿命 EVIL_SURCHARGE（见 _gainFate）
    // 难度随节点推进（mob/rest/shop 也按当前层，保证玩家属性随层数成长，不会落后被打）
    s.diff = node.diff || layer;
    s.history.push(`${layer}-${col} ${node.name}`);
    s.visited.push({ layer, col });
    // —— 劫难节点进入提示（V8.26·对标万世剑冢）：每次进入劫难/战斗节点，先提示当前是第几难 ——
    if (['trial', 'compound', 'mob', 'elite'].includes(node.type)) {
      const _n = NDX.globalProgress(s);
      const _actName = NDX.ACT_NAMES[Math.min((s.act || 1), NDX.TOTAL_ACTS) - 1] || ('第 ' + (s.act || 1) + ' 地区');
      this.toast(`第 ${_n}/${NDX.TOTAL_TRIALS} 难 · ${_actName} · ${node.name}`);
    }
    // —— 心魔（六道对应）：满值劫持下一次「进展」劫难为纯惩罚镜像战（战/劫/精英/事件都会踩雷，
    //     休憩处/街市/洞天可喘息，不进拦截）。节点已标记已历，战果作废——你输不起这口气，就老老实实渡化销魔。——
    if (!['rest', 'shop', 'cave', 'treasure'].includes(node.type)) {
      if (this._checkXinmoBurst()) return;
    }
    // —— 关隘必修任务计数（劫难/小怪/精英/事件）：按进入的节点类型一次性计入 ——
    if (!s.mission) s.mission = { trials: 0, mob: 0, elite: 0, events: 0 };
    const _mis = s.mission;
    if (node.type === 'trial') _mis.trials = (_mis.trials || 0) + 1;
    else if (node.type === 'mob') _mis.mob = (_mis.mob || 0) + 1;
    else if (node.type === 'elite') _mis.elite = (_mis.elite || 0) + 1;
    else if (node.type === 'event') _mis.events = (_mis.events || 0) + 1;
    // —— V8.34 地区配额计数：按进入节点类型累计（战斗/精英/休息/融合节点） ——
    // 配额只在启用配额制的地区累计；第一章（act1）不加配额，计数天然为 0 不影响。
    if (NDX.quotaEnabled(s.act)) {
      if (node.type === 'mob' || node.type === 'trial') NDX.addQuota(s, 'battle', 1);
      else if (node.type === 'elite') NDX.addQuota(s, 'elite', 1);
      else if (node.type === 'rest') NDX.addQuota(s, 'rest', 1);
      // S1-4 同族修复：_quotaSix 的 alt2 兜底路径要求 shop/event 计数（夺 alt2{shop:1} 隐 alt2{event:1}），
      // 但全仓原无这两个键的 addQuota 调用，导致 act3~17 共 30 条第三备选路径永不可达。
      else if (node.type === 'shop') NDX.addQuota(s, 'shop', 1);
      else if (node.type === 'event') NDX.addQuota(s, 'event', 1);
      // 融合节点进入时不加 battle（其子难战斗/抉择在复合流程内单独累计，避免重复计）
    }
    // 业镜·本层单层标记的刷新：进入新节点时清除「仅本层有效」的临时业镜效果，
    // 保留整局持续状态（减伤/攻击/护盾/免疫等）。同时结算「进层掉血」。
    if (s.mirror) {
      s.mirror.voidLayer = false;
      s.mirror.noLootLayer = false;
      s.mirror.fateNodeDisabled = false;
      s.mirror.trueDmgLayer = false;
      s.mirror.nextBossAlly = false;
      if (s.mirror.hpLossOnEnterPct) {
        const maxHp = this.stats().ti.maxHp;
        const lost = Math.max(1, Math.round(maxHp * s.mirror.hpLossOnEnterPct));
        s.hp = Math.max(1, s.hp - lost);
        this.pushLog(`【业镜·踏尸】进此层气血损耗 ${lost}（现 ${s.hp}/${maxHp}）。`);
      }
    }
    const st = this.stats();

    // 劫难转事件：story 类劫难以「缘(?)」节点呈现，进入时按固定难号触发剧情劫难（复用 trial 分支）
    if (node.fixedEventTrial) {
      node.type = 'trial';
      node.fixedTrial = node.fixedEventTrial;
    }
    // #64 观音指引·第二章倒数第二难（难8·两界山头）：「取经非目的，须历足够劫难方悟佛法真谛」
    // 指引在左上角「已历 X/Y 难」灯 + 观音指引卡中查看 Boss 刷新条件；链尾 enter-node 重入开战
    if (node.fixedEventTrial === 8 && !s.flags._guanyinBossGateDone) {
      s.flags._guanyinBossGateDone = true;
      const _gg = NDX.fateGateCheck(s);
      const _need = (NDX.MISSION_KINDS || ['trials', 'battle', 'events'])
        .map((k) => `${NDX.MISSION_KIND_LABEL[k] || k} ${_gg.gate[k] || 0}`)
        .join('、');
      s.pending = this._guanyinBossGateGuide(layer, col, _need);
      this.render();
      return;
    }

    switch (node.type) {
      case 'compound': {
        // P4-2 新手指引：首次遇到复合节点时提示
        if (!s.flags._compoundTaught) {
          s.flags._compoundTaught = true;
          this.toast('⚡ 复合劫难：多难合一——连续经历数场子难，中途不可退避，通关后奖励丰厚');
        }
        // 复合节点（多难合并为一个节点）：V8.27 取消路线入口页，默认按「顺命·渡道」直接经历子难。
        // V8.34 融合节点：node.fusionDiffs 优先（两界山 fusions 分布各层），否则回退整章 _comp.diffs。
        // 复用原 _compoundRoute → _compoundNext 推进链（先 c.idx++ 再入子难），保证子难依次推进、最终收束。
        // 若已在本复合节点流程内（s.compound 存在），不再重置 idx，避免反复卡在第一难。
        const _comp = NDX.compoundFor(s.act);
        if (!_comp) { s.pending = { kind: 'choices' }; break; }
        if (!s.compound || s.compound.node !== node) {
          const _diffs = (node && node.fusionDiffs && node.fusionDiffs.length)
            ? node.fusionDiffs.slice()
            : (_comp.diffs ? _comp.diffs.slice() : []);
          s.compound = {
            node,
            diffs: _diffs,
            route: (s.mainDao === '渡' || s.mainDao === '缘') ? '渡' : (s.mainDao === '逆' || s.mainDao === '战' || s.mainDao === '夺' ? '逆' : '渡'),
            bossMul: 0.9,
            idx: 0,
            chechi: (_comp && _comp.chechi) ? { choices: [] } : null,
            // 通天河（act8）终局矩阵：记录子难抉择，供第36难决战收场判定
            tongtian: (_comp && _comp.tongtian) ? { choices: [] } : null,
          };
          if (_comp && _comp.chechi) s.chechiVisited = true;
          if (_comp && _comp.tongtian) s.tongtianVisited = true;
        }
        this._compoundNext();
        break;
      }
      case 'cave': {
        // P4-3 新手指引：首次遇到隐藏洞天
        if (!s.flags._caveTaught) {
          s.flags._caveTaught = true;
          this.toast('🕳 隐藏洞天：逆道秘境——得逆道经文碎片、红装材料与金币，多周目开放更多洞天');
        }
        // 隐藏洞天（三周目全开放）：逆道秘境。进入发放逆道经文碎片 + 红装材料 + 金币。
        // V8.26 命痕砍除：不再发逆道专属命痕，改发「逆道经文碎片」（三周目逆道解锁后更贴题）。
        const got = s.flags.nextGoldDouble ? node.gold * 2 : node.gold;
        s.flags.nextGoldDouble = false;
        s.gold += got;
        if (node.material) node.material.forEach((m) => { s.materials[m] = (s.materials[m] || 0) + 1; });
        this.pushLog(`【洞天】${node.name}——得 ${got} 金、逆道材料 ${node.material ? node.material.join('/') : '无'}`);
        if (NDX.grantNiSutraFrag) {
          const ni = NDX.grantNiSutraFrag(s);
          if (ni && ni.frag) {
            this.pushLog(`【逆道经文】洞天拾得 ${ni.frag.name}（${ni.full.name} ${ni.full.frags.indexOf(ni.frag.id) + 1}/3）`);
            if (ni.combined) this.pushLog(`【逆道经文】${ni.combined.name} 三段集齐，自动合成全本——${ni.combined.desc}`);
          }
        }
        s.pending = { kind: 'choices' };
        this._syncAch();
        NDX.bus.emit('render');
        return;
      }
      case 'tutorial': {
        const eq = NDX.equipById(node.drop);
        s.equips.push(eq);
        this.pushLog(`【教学】${node.name}：获得 ${eq.name}（${eq.desc}）`);
        s.pending = { kind: 'choices' };
        break;
      }
      case 'mob': {
        // 杂兵：弱于正式劫难一档，体/愿双攻；强度随真实难号(1~81)平滑爬升。
        // 连续地图下 s.layer 为全局层，globalProgress = 真实难号，直接据此取怪——
        // 不再叠加「每章 +6 档」的 actBoost（连续地图重复加成会让旧地区节点二次膨胀）。
        const gp = NDX.globalProgress(s);
        const mTier = NDX.monsterAt(Math.max(1, gp - 1));
        const _mobType = NDX.rollMob(s.act || 1); // 按地区抽取小怪类型（名字+阵营标签）
        const m = {
          type: 'mob',                // 普通小怪：固定 3–6 回合节奏保障（见 fight() 内校准）
          name: _mobType.name,        // 小怪专属名（替代"无名数值怪"）
          tags: _mobType.tags,        // 阵营标签（供法宝「克制 counter」命中）
          hp: Math.round(160 + gp * 45),
          atk: Math.round(18 + gp * 4),
          dr: NDX.MONSTER_DR,
          matk: Math.round((mTier.matk || 20) * 0.7),
          mdef: mTier.mdef || 0.05,
        };
        NDX.scaleRunMods(m, s); // 本局劫难抉择即时改变怪物强度（逆强/渡弱）
        const _teachMob = (!s.taught.mob) ? (s.taught.mob = true, 'mob') : null; // 第一小怪：提示怪物掉落永久装备
        const _mobWin = () => {
          const amt = node.gold || 20;
          const got = s.flags.nextGoldDouble ? amt * 2 : amt;
          s.flags.nextGoldDouble = false;
          s.gold += got;
          this.pushLog(`【妖兵】${node.name}：击败，获得 ${got} 金${got > amt ? '（香火翻倍）' : ''}`);
          // 兵（小怪）固定掉落：若 drop 是数组也最多取 1 件，避免一场小怪掉多件
          if (node.drop) {
            const drops = Array.isArray(node.drop) ? node.drop : [node.drop];
            // 战利品识别：装备池 + 法宝字典（NDX.lootById 统一覆盖，修复法宝类掉落被当材料）
            const lootItems = drops.map((id) => NDX.lootById(id)).filter(Boolean);
            const matIds = drops.filter((id) => !NDX.lootById(id));
            const owned = new Set((s.equips || []).map((e) => e.id));
            const baseItems = lootItems.filter((e) => e.setTier === 1 && !owned.has(e.id));
            const otherItems = lootItems.filter((e) => !(e.setTier === 1) && !owned.has(e.id));
            const pickItem = baseItems.length ? baseItems[NDX._rand(0, baseItems.length - 1)]
                          : (otherItems.length ? otherItems[NDX._rand(0, otherItems.length - 1)] : null);
            if (pickItem) {
              this.grantEquip(pickItem);
              this.pushLog(`【掉落】${node.name}：拾得 ${pickItem.name}（${pickItem.desc}）`);
            }
            if (matIds.length && Math.random() < 0.5) {
              const m = matIds[NDX._rand(0, matIds.length - 1)];
              NDX.addMaterial(s, m, 1);
              this.pushLog(`【掉落】${node.name}：获得材料 ${m}`);
              NDX.sfx('colect');
            }
          }
          // 兵（小怪）：小概率 5%~10% 额外掉落「基本装」（通用套装基座 / 廉价散件）
          this._mobBasicLoot(s, node.name);
        };
        this.fight(m, node.name, 'choices', _mobWin, node, false, _teachMob);
        break;
      }
      case 'rest': {
        // 土地庙：二选一——歇息提升气血上限（不回满血） 或 淬炼精进（升级一件基础装备至二阶）
        // V8.26 命痕砍除：涅槃换命仪式已随命痕系统移除（篝火仅剩舍血淬体）
        // P0-4 新手指引：首次进入土地庙时标记，UI 侧展示六子功能引导
        const _firstRest = !s.taught.rest;
        if (_firstRest) s.taught.rest = true;
        s.pending = { kind: 'rest', node, firstRest: _firstRest };
        this.autoCombineShrine(s); // V8.51 进庙即自动熔铸所有可合成链
        break;
      }
      case 'trial': {
        // 劫难 = 杀戮尖塔式「精英怪」：必有战斗（至少可战），且必掉装备
        // 难号体系（八十一难）：全局难号 1~81 按地理段落分九章（ACT_RANGES），第 81 难为终局；
        //   每章 Boss = 该章末难(13/22/31/40/49/58/68/77/81)；隐藏专职前置劫难(HIDDEN_TRIAL_REQ)为「必经固定难号」，
        //   由 _ensureHiddenTrials 注入到对应层；其余劫难节点「走到才触发」，进入时从本章剩余未用难号随机抽。
        // 分配本章全局难号（仅劫难节点消耗难号，非劫节点不占）：
        if (!s.usedTrialDiffs) s.usedTrialDiffs = {};
        const lo = NDX.actStart(s.act) - 1;                   // 本章起始全局难号 - 1
        const hi = NDX.actEnd(s.act);                         // 本章末难（关隘 Boss 难号）
        const gpNatural = NDX.globalProgress(s);              // 该节点所在层的自然全局难号
        const isFixed = NDX._HIDDEN_TRIAL_SET.has(gpNatural); // 是否隐藏职必经劫难（固定难号）
        let assigned;
        if (node.fixedTrial) {
          assigned = node.fixedTrial;                         // 地图固定序章（金蝉遭贬·第一难）：固定难号，跳过随机
        } else if (isFixed) {
          assigned = gpNatural;                               // 必经劫难：固定全局难号（不随机）
        } else {
          // 其余劫难：从本章剩余未用全局难号随机抽（排除已用 + 必经项 + 固定事件难 + 本章 Boss 难号）
          const taken = new Set([
            ...(s.usedTrialDiffs[s.act] || []),
            ...[...NDX._HIDDEN_TRIAL_SET].filter((g) => g > lo && g <= hi),
            ...[...(NDX.FIXED_EVENT_TRIALS || [])].filter((g) => g > lo && g <= hi),
            ...NDX.compoundDiffsFor(s.act), // 复合节点难号（黄风岭三连难）专属，不在地图普通层随机分配
            hi,
          ]);
          const pool = [];
          for (let g = lo + 1; g <= hi; g++) if (!taken.has(g)) pool.push(g);
          assigned = pool.length ? NDX._pick(pool) : gpNatural; // 兜底（极端全占）用自然难号
        }
        if (!s.usedTrialDiffs[s.act]) s.usedTrialDiffs[s.act] = [];
        if (!s.usedTrialDiffs[s.act].includes(assigned)) s.usedTrialDiffs[s.act].push(assigned);
        node.diff = assigned;                                 // 劫难节点全局难号（覆盖局部层）
        s.diff = assigned;
        // 第二难·寿命教学（V8.62 重构）：不再在此处弹 toast；改为在 trial 抉择面板构造完成后，
        // 用两层观音偈语包裹、偈语终点恢复抉择面板（见本函数下方 assigned===2 段），避免教学吞掉选项。
        // 记录「经过的劫难」：进入劫难节点即记为已历（无论后续选战或抉择），
        // 这是隐藏专职/组件合成的前置校验依据——逃课（绕开特定劫难）则无法完成隐藏。
        // 用全局难号记录，与 NDX.HIDDEN_TRIAL_REQ 的难号口径一致。
        const gp = assigned;
        if (!s.trialsPassed) s.trialsPassed = [];
        if (!s.trialsPassed.some((t) => t.diff === gp)) {
          s.trialsPassed.push({ diff: gp, act: s.act, name: node.name });
          // 缘分门槛（V8.17）：本章渡难 +1
          if (!s.fateStats) s.fateStats = { trials: 0, kills: 0, events: 0 };
          s.fateStats.trials = (s.fateStats.trials || 0) + 1;
          // 难簿分卷完成检测：跨过卷边界（20/40/60/81）即解锁该卷难簿成就，
          // 永久微量加成由 globalAchBonus（recalcStats 读取）自动生效。
          if (NDX.VOLUME_BOUNDS && NDX.VOLUME_BOUNDS.indexOf(gp) >= 0) {
            const v = NDX.volumeOf(gp);
            const vr = NDX.volumeRange(v);
            this.toast(`难簿·第${v}卷（第${vr[0]}-${gp}难）功成 —— 卷难簿成就解锁，永久微量加成生效`);
            this.pushLog(`【难簿·分卷】第${v}卷（第${vr[0]}-${gp}难）已录，卷难簿成就解锁，永久微量加成生效`);
            this._syncAch(); // 立即激活该卷难簿成就（永久加成经 globalAchBonus 自动生效）
          }
        }
        // 经过劫难后重算「隐藏职劫难前置」：满足本英雄当前位置前所需特定劫难则解锁隐藏资格
        if (!s.flags.hiddenJobReady) s.flags.hiddenJobReady = {};
        const met = NDX.hiddenTrialsMet(s.hero, s.trialsPassed, s.diff);
        if (met.ok && !s.flags.hiddenJobReady[s.hero]) {
          s.flags.hiddenJobReady[s.hero] = true;
          this.pushLog(`【隐藏资格】你已历经 ${met.req.length} 场关键劫难，本英雄隐藏专职之路已通——此后抉择可觉醒隐藏职`);
          // V8.37 新手引导：首次解锁隐藏职资格时显示教学提示
          if (!s.flags._hiddenJobTaught) {
            s.flags._hiddenJobTaught = true;
            try {
              if (NDX.bus) {
                NDX.bus.emit('toast', '🪷 观音菩萨：「西行大雷音寺，路阻十万八千里。劫难重重——必历八十一难，方证菩提正果。这条路上，每一难皆是修行；你心中所择，将化为自己的法。去吧，金蝉。」');
              }
            } catch (e) { /* 静默失败 */ }
          }
        }
        if (node.skipChoice) { this._resolveSkipChoice(node, assigned); return; }
        let tr = NDX.normalizeTrial(NDX.trialByLayer(assigned, s.hero));
        // 兜底：随机池也可能为空/异常
        if (!tr || !tr.opts || !tr.opts.length) tr = NDX.normalizeTrial(NDX.pickTrial());
        this.pushLog(`【劫】${tr.title}`);
        // 全难伏笔回访（41-80 难对应 1-40 难）：因果回报落地可视化
        if (s.diff >= 41) {
          const _pay = NDX.echoPayoff(s, s.diff);
          if (_pay) {
            NDX.addMaterial(s, _pay.mat, 1);
            this.pushLog(_pay.text);
            this.pushLog(`【伏笔回报】获得材料 ×1：${_pay.mat}`);
          }
        }
        // 前置战斗选项：仅当该劫自身没有任何选项时，才补一个通用「力战」入口兜底
        // （保证"至少可战"）；凡自带选项（含二级 subOptions）的劫难一律不再前置旧版「战·恶」，
        // 战/恶改由选项内 fate:战 / alignEvil 表达，避免压在顺命上方、避免旧字段 evil 残存。
        const _hasAnyOpt = (tr.opts || []).length > 0;
        const fightOpt = (tr.heroLock || _hasAnyOpt) ? null : {
          text: '【战】力战破劫——以杀止劫',
          fight: true,
          fate: '战',
          effect: { alignEvil: 10 },
        };
        s.pending = {
          kind: 'trial',
          node,
          diff: node.diff,
          title: tr.title || '劫难',
          text: tr.text || '',
          opts: fightOpt ? [fightOpt].concat(tr.opts || []) : (tr.opts || []),
          // 掉落：优先用该难专属法宝（treasure.id 需可被 lootById 识别，否则按英雄补专属基座兜底）；
          // 保证"劫难打怪必掉装备"（修复劫难不掉装备的体验问题）
          drop: (tr.treasure && tr.treasure.id && NDX.lootById(tr.treasure.id)) ? tr.treasure.id
                : (NDX.lootById((tr.drop && (Array.isArray(tr.drop) ? tr.drop[0] : tr.drop)) || '') ? tr.drop
                   : (this._heroBaseDrop(s.hero) || tr.drop || null)),
          trialId: tr.id || null,
          fate: tr.fate || null,     // 六道命运·主命运（8.11）
          echo: tr.echo || null,     // 前后呼应（8.11）
          page: 0,
          teach: (!s.taught.trial) ? (s.taught.trial = true, 'trial') : null, // 第一劫抉择：提示选择决定劫印、塑造流派
          // V8.62 第一难简洁卡片模式：从劫难数据传递 sixdaoSelect / simpleDaoCards 标记
          sixdaoSelect: tr.sixdaoSelect || false,
          simpleDaoCards: tr.simpleDaoCards || false,
        };
        // V8.31 新手指引·逐难分授系统（仅第一章前三难触发）：
        //   难1 金蝉遭贬 → 接引使者教学战（攻/经/绝）+ 六道抉择教学
        //   难2 出胎几杀 → 战斗系统提示（combat）
        //   难3 满月抛江 → 劫印系统提示（jieyin）
        // V8.5x 新手指引：难1抉择界面由「观音弹窗+气泡」说明六道（不阻断原文本/选项）
        if (assigned === 1 && !s.taught.sixdao) {
          s.taught.sixdao = true;
          s.pending.teach = 'sixdao';
          s.pending.teachText = '观音菩萨：「西行万法，归于六道——渡·缘·战·夺·隐·逆。先立一种心念姿态，再于其中选定一道。善道（渡/缘/隐）仁厚绵长，恶道（战/夺/逆）威猛却折寿——其中「逆」道尤为凶险，须先炼成一世正果（完美通关）方得入此道。六道印记决定你的命运、装备与这世界如何回应你；择定一道后，将得对应六道装备升级石，可唤醒套装隐藏职。」';
          // V8.62 第一难简洁卡片模式：显式设置标记，确保教学战恢复后仍生效
          s.pending.sixdaoSelect = true;
          s.pending.simpleDaoCards = true;
        }
        // V8.44 接引使者教学战重启用：难1首次进入，先看第一段文字→迎战接引使者→
        // 观音逐回合引导攻/经/绝（绝招前怪物血条不打空，唯绝招可终结）→胜利后回到六道抉择
        if (assigned === 1 && !s._tutorialFought) {
          s._tutorialFought = true;            // 教学战仅打一次；同时隐藏地图「观音指引·渡难」卡
          s._tutorialResume = s.pending;        // 课后恢复第一难抉择（含 teach='sixdao' 观音六道气泡）
          s._tutorialResume.text = '你已识得攻守三键，接引使者让开轮回道口。金蝉踏此第一难，当先立一种心念姿态——六道抉择，定你此世命途。';
          s.pending = {
            kind: 'tutorial-intro',
            node,
            title: '第一难 · 金蝉遭贬',
            // 精简第一段文字至一屏内：观音题词移入教学战场内逐回合引导（teach='tutorial'），
            // 不再于本界面弹出，避免文本+气泡+按钮溢出单屏。
            text: '灵山讲经台上，你问如来："度的是谁？"一声轻慢，判你十世轮回。轮回道口，接引使者持鞭拦路——金蝉子投的胎，还得爷送。',
          };
          this.pushLog('【第一难 · 接引使者】轮回道口，接引使者持鞭拦路——先历此教学战。');
        }
        // V8.62 第二难·寿命教学：首次进入难2（出胎几杀）时，先弹两层观音寿命偈语，
        //   偈语终点直接接回本难的 trial 抉择面板（而非 choices 回地图），教学与抉择两不丢。
        if (assigned === 2 && !s.taught.life) {
          s.taught.life = true;
          const _trialPending = s.pending;   // 已构造好的第2难抉择面板（含3个六道选项）
          s.pending = this._lifeGuide(_trialPending);
        }
        // 8.11 前后呼应系统：记录本难主命运与呼应链，供倒序重构叙事与命运主导线判定
        s.trialFateLog = s.trialFateLog || [];
        if (tr.id && !s.trialFateLog.some((e) => e.diff === tr.id)) {
          s.trialFateLog.push({ diff: tr.id, fate: tr.fate || null, echo: tr.echo || null, title: tr.title || ('第' + (tr.id || s.diff) + '难') });
          // V8.61 六道首印仪式（Rev.4 报告 9.1）：第一次六道抉择落定是全游最重要的身份承诺时刻，给足仪式感
          if (s.trialFateLog.length === 1 && tr.fate) {
            try {
              const _isEvil = NDX.DaoSystem && NDX.DaoSystem.isEvilDao && NDX.DaoSystem.isEvilDao(tr.fate);
              this.pushLog(`【六道】第一印已落——你初行「${tr.fate}」道。${_isEvil ? '此道有力，亦折寿催魔；愿你扛得住。' : '此道养命，亦缓；愿你走得稳。'}`);
              setTimeout(() => { try { this.toast(`☯ 六道第一印 · 初行「${tr.fate}」道`); this.render(); } catch (e) {} }, 900);
            } catch (e) { /* 仪式播报不阻断结算 */ }
          }
        }
        // §3 边框协调：若有顺延的六道转职浮层，进入本劫后补弹（英雄隐藏职已优先在上一节点弹出）
        if (NDX.ZHUANJIE && NDX.ZHUANJIE.drainPromote(s)) {
          this.pushLog(`【转职·补弹】顺延的六道专职于本劫浮现`);
        }
        break;
      }
      case 'elite':
      case 'boss': {
        // 车迟国复合节点收束：依三场斗法抉择决定第31难「车迟三妖·魁首」形态
        if (s.chechiVisited && (node.diff === 31 || (NDX.bossDiffForAct && NDX.bossDiffForAct(s.act) === 31))) {
          if (s.chechiHidden) {
            this.pushLog('【车迟国】你曾避战而去，三妖仍踞车迟国——此战已无必要。');
            if (!s.trialsPassed) s.trialsPassed = [];
            if (!s.trialsPassed.some((t) => t.diff === 31)) s.trialsPassed.push({ diff: 31, act: s.act, name: '车迟三妖·魁首（避战未战）' });
            s.pending = { kind: 'choices' }; this.render(); return;
          }
          if (!s.chechiAllWar) {
            this.pushLog('【车迟国】三妖已被斗法折服/劝归，无需再战。');
            if (!s.trialsPassed) s.trialsPassed = [];
            if (!s.trialsPassed.some((t) => t.diff === 31)) s.trialsPassed.push({ diff: 31, act: s.act, name: '车迟三妖·魁首（斗法降服）' });
            s.pending = { kind: 'choices' }; this.render(); return;
          }
        }
        // 通天河（act8）终局矩阵：子难抉择组合决定第36难金鱼精决战的收场（第二批 §零.4）
        if (s.tongtianVisited && node.diff === 36) {
          if (s.tongtianAllDu) {
            this.pushLog('【通天河】你一路以渡化行——观音持鱼篮现身，金鱼俯首归池，此战已无必要。');
            if (!s.trialsPassed) s.trialsPassed = [];
            if (!s.trialsPassed.some((t) => t.diff === 36)) s.trialsPassed.push({ diff: 36, act: s.act, name: '金鱼精·通天河决战（鱼篮收伏）' });
            s.pending = { kind: 'choices' }; this.render(); return;
          }
          if (s.tongtianAllNi) {
            this.pushLog('【通天河】你一路悖逆而行——河神怨气反噬，金鱼精借势狂化（攻势 +15%）。');
            s.flags.tongtianFury = true;
          }
        }
        // Boss 门禁改「历经足够劫难」：仅缘分管禁（fateGateCheck，game.js:647 提前 return）。
        // 配合 data.js _tailStep 动态尾——任务未达标时地图持续延伸，达标才收敛出 Boss，天然无软锁。
        // （V8.34 地区配额制 quotaCheck 已移除：用户确认 Boss 门槛为「历经足够劫难」而非配额制）
        // 从敌人数据库(enemies.js)取精英/Boss 的权威定义，覆盖 MAP_PLAN 的 drop/material
        const _ed = NDX.enemyDefOf && NDX.enemyDefOf(node);
        if (_ed) {
          if (_ed.drop != null) node.drop = _ed.drop;
          if (_ed.material != null) node.material = _ed.material;
          if (_ed.diff != null) node.diff = _ed.diff;
        }
        s.diff = node.diff;
        // 关隘 Boss 即本章末难（难 9/18/27/.../81）：计入「已历劫难」。
        // _ensureHiddenTrials 不再把 Boss 层替换成 trial 节点，故此处补记，确保第 81 难等必经难号
        // 经 Boss 战同样计入，满足隐藏专职必经判定（wukong/tangseng/shaseng 均需 81）。
        if (!s.trialsPassed) s.trialsPassed = [];
        if (!s.trialsPassed.some((t) => t.diff === s.diff)) {
          s.trialsPassed.push({ diff: s.diff, act: s.act, name: node.name || ('第' + s.diff + '难') });
        }
        // 精英按本节点难号(node.diff=layer)缩放；关隘 Boss 才用 bossDiffForAct（随章递增，终局有压迫感）。
        // 注意：原先 elite/boss 共用同一分支且都用 bossDiffForAct，导致「开局第1层精英 = Boss级怪物」，
        // 英雄（数百血）一撞必死——这是"连第一个劫难/精英都打不过"的真正根因（平衡 V42 修复）。
        const mData = node.type === 'boss'
          ? NDX.monsterAt(NDX.bossDiffForAct(s.act))
          : NDX.monsterAt(node.diff);
        // 车迟国·一打三合体战：三场全战 → 三妖同框合体（改造A）
        if (s.chechiAllWar && NDX.compositeMonster && node.type === 'boss') {
          const _yao = [
            { name: '虎力大仙', hp: 1700, atk: 200, dr: 0.14, matk: 130, mdef: 0.16, tags: ['妖', '道'] },
            { name: '鹿力大仙', hp: 2000, atk: 230, dr: 0.18, matk: 160, mdef: 0.20, tags: ['妖', '道'] },
            { name: '羊力大仙', hp: 2300, atk: 270, dr: 0.22, matk: 190, mdef: 0.24, tags: ['妖', '道'] },
          ];
          const _cm = NDX.compositeMonster(_yao);
          if (_cm) { mData = _cm; s.flags._chechiFused = true; }
        }
        let weak = s.flags.nextWeak || 0;
        // 通天河·河神反噬：全逆路线下金鱼精攻势 +15%（weak 为负值即放大 atk/matk）
        if (s.flags.tongtianFury && node.diff === 36) weak = -0.15;
        s.flags.tongtianFury = false;
        s.flags.nextWeak = 0;
        const m = {
          type: (node.type === 'boss' || !!mData.boss) ? 'boss' : 'elite', // 精英/Boss 标记：1x 锁速 + 回合节奏校准
          hp: mData.hp,
          atk: Math.round(mData.atk * (1 - weak)),
          dr: mData.dr,
          matk: Math.round(mData.matk * (1 - weak)),
          mdef: mData.mdef,
          boss: node.type === 'boss' || !!mData.boss,
        };
        // 关隘 Boss 两相劫：拆为「阶段1 + 阶段2」，总计 ≤20 回合。
        // 每阶段破碎韧性条时弹出限时窗口：仅手动【临阵祭宝】破韧方可领取「阶段厚赏」，
        // 否则超时/跳过仅得「挂机兜底」——以此区分挂机与手动收益（主动操作有明确回报）。
        if ((node.type === 'boss' || !!mData.boss) && !s.flags._chechiFused) {
          // 破韧克制：物理韧性主导(dr≥matk)需物攻真器 bf_bajiao；法术韧性主导需法伤真器 bf_baolu。
          // 仅持此特定法宝方能在破韧窗口临阵破韧击败并领厚赏；否则仅能挂机兜底（本阶段无法击破）。
          m.breakWith = (m.dr >= m.matk) ? 'bf_bajiao' : 'bf_baolu';
          if (node.type === 'boss') {
            // 关隘 Boss：按地区赋予专属名；三段变身 Boss（8 个）走 BOSS_FORMS 装配，其余两段默认
            const bossName = NDX.bossNameForAct(s.act);
            node.name = bossName;
            const setup = NDX.bossStageSetup(bossName, s.fate);
            if (setup) {
              // 三段变身：阶段1 用初相面板，阶段2/3 由 phaseStats/phaseOverrides 逐段覆盖
              const p1 = setup.p1;
              m.hp = m.maxHp = setup.stages[0];
              if (p1) {
                m.atk = p1.atk; m.dr = p1.dr; m.matk = p1.matk; m.mdef = p1.mdef;
                m.affix = m.affix || p1.affix;
              }
              m.stages = setup.stages;
              m.phaseOverrides = setup.phaseOverrides;
              m.phaseStats = setup.phaseStats;
              m.phase2Override = setup.phase2Override;
              m.stageRewards = setup.stageRewards;
              this.pushLog(`【${setup.name}】${setup.descs[0]}`);
              if (setup.fateDao) this.pushLog(`尸魔循你一路所行，化出「${setup.fateDao}」道之相——${setup.fateName}。`);
            } else {
              // 两段默认：阶段1 满血，阶段2 残身（约 62%）
              m.stages = [mData.hp, Math.round(mData.hp * 0.62)];
              m.stageRewards = [
                { claim: { gold: 120, ling: 30, note: '阶段一·厚赏（临阵破韧）' }, idle: { gold: 30, note: '阶段一·挂机兜底' } },
                { claim: { gold: 160, ling: 40, note: '阶段二·厚赏（临阵破韧）' }, idle: { gold: 40, note: '阶段二·挂机兜底' } },
              ];
              this.pushLog(`【两相劫】${node.name || '关隘之主'} 现出二相：阶段1 将抗 ${Math.round(m.stages[0])} 气血，阶段2 残身 ${Math.round(m.stages[1])} 气血；阶段间破韧可领厚赏`);
              // 中后期（逆道开放）两段 Boss：第二阶段附「逆道·裂界」专属词缀，且允许手动法宝连锁 COMBO。
              // 逆道词缀令二阶段更凶（护甲/法伤/狂暴），但韧性条更易被连环祭宝击碎——给熟练玩家连段缩回合的爽点。
              if (s.act >= 10) {
                const p2 = Object.assign({}, m, { affix: (m.affix || []).concat(['nidaobane']) });
                if (NDX.attachAffix) NDX.attachAffix(p2, s);
                m.phase2Override = {
                  dr: p2.dr, matk: p2.matk, enrage: p2.enrage, enrageMul: p2.enrageMul, affix: p2.affix,
                };
                m.comboAllowed = true; // 高难 Boss：手动法宝可连锁（COMBO）压垮韧性条，大幅缩短战斗回合
                m.routine = 3;          // 每 3 回合出一个择机窗口（operationPoint），为连锁 COMBO 提供连段时机
                this.pushLog(`【逆道】第${s.act}地区·逆道侵蚀：关隘二相附「逆道·裂界」词缀，手动法宝连锁 COMBO 可破韧大幅缩回合`);
              }
            }
          } else {
            // 精英级 Boss（高难档 diff≥20）：默认两相
            m.stages = [mData.hp, Math.round(mData.hp * 0.62)];
            m.stageRewards = [
              { claim: { gold: 120, ling: 30, note: '阶段一·厚赏（临阵破韧）' }, idle: { gold: 30, note: '阶段一·挂机兜底' } },
              { claim: { gold: 160, ling: 40, note: '阶段二·厚赏（临阵破韧）' }, idle: { gold: 40, note: '阶段二·挂机兜底' } },
            ];
          }
        }
        NDX.scaleRunMods(m, s); // 本局劫难抉择即时改变怪物强度（逆强/渡弱）
        const afterKind = node.type === 'boss' ? 'bossreward'
          : (node.type === 'trial' ? 'trialreward' : 'elitereward');
        // P0-3 新手指引：首次精英战/关隘Boss战分别触发机制教学
        const _teachElite = (!s.taught.elite && node.type !== 'boss') ? (s.taught.elite = true, 'elite') : null; // 首次精英：词缀机制
        const _teachBoss = (!s.taught.boss && node.type === 'boss') ? (s.taught.boss = true, 'boss') : null; // 首次关隘：韧性双条+破韧
        // V8.5x 第一章Boss（刘洪）气势教学：不阻断开战，改由战斗画面内「观音气泡」指引气势/识破
        const _newbieBoss = (node.type === 'boss' && s.act === 1 && !s.flags._boss1TeachDone)
          ? (s.flags._boss1TeachDone = true, 'newbie-boss') : null;
        // 逆道谈判 · 以经为质（《竞品借鉴》§3）：主攻道=逆 + 妖王精英/Boss + 佛经积累 → 弹谈判面板
        const _negF = NDX.followerForEnemy ? NDX.followerForEnemy(node) : null;
        if (_negF && NDX.canNegotiate && NDX.canNegotiate(s, node)) {
          const _chance = NDX.negotiateChance(s, node);
          const _fragN = Object.keys(s.sutraFrags || {}).reduce((a, k) => a + (s.sutraFrags[k] || 0), 0);
          s.pending = {
            kind: 'negotiate',
            node,
            follower: _negF,
            chance: _chance,
            m,
            afterKind,
            teach: _newbieBoss || _teachElite || _teachBoss,
            title: '以经为质 · ' + node.name,
            text: node.name + ' 拦路，妖气冲天。你自怀中取出经卷——佛经为质，或可劝其臣服，免此一战。\n成功率 ' + Math.round(_chance * 100) + '%（佛经全本 ' + (s.sutras || []).length + '·散件 ' + _fragN + '·心魔 ' + Math.floor((s.xinmo || 0) / 10) + ' 层·逆经 ' + (s.niSutras || []).length + '·恶值 ' + Math.floor((s.evil || 0) / 10) + '）',
            opts: [
              { key: 'negotiate', label: '【谈判】以经为质，劝' + _negF.name + '臣服（成功率 ' + Math.round(_chance * 100) + '%）' },
              { key: 'fight', label: '【开战】妖王冥顽，唯刀兵相见' },
            ],
          };
          this.render();
          return;
        }
        this.fight(m, node.name, afterKind, null, node, false, _newbieBoss || _teachElite || _teachBoss);
        break;
      }
      case 'event': {
        // V8.31 长安送行事件节点：前三难完成后必经之路，触发五步互动教学（装备+法宝+地图）
        if (node.songEvent) {
          const _g = s.flags.gotInitGift || (s.flags.gotInitGift = {});
          if (!_g[s.hero]) {
            // 进入前先弹观音新手指引（机缘寄语），确认后再弹出合并单窗口的送行赠宝
            s.pending = {
              kind: 'guanyin-msg',
              text: '观音菩萨：「前面便是长安送行。此去西行十万八千里，沿途多有奇遇机缘——赠宝赐法、点化授业之处，莫要错过。每遇问号之地，皆是因缘。」',
              then: { kind: 'song-gift', grantHero: s.hero }
            };
          } else {
            s.pending = { kind: 'choices' };
          }
          this.render(); return;
        }
        // 缘(?)：杀戮尖塔式随机事件节点
        // 保底机制：每次以 p = 10% + 10%×连续未遇战次数 概率「遭遇战」(小怪/劫)，
        //   遇战即重置；否则触发一个【奇遇事件】(回血/得宝/善恶抉择/可战可避)。
        //   为路线规划提供「稳妥 vs 赌一把」的核心博弈。
        const roll = NDX.rollYuan(s);
        if (roll === 'mob') {
          // 保底触发为小怪：直接开打（逻辑同 case 'mob'）
          this.pushLog(`【缘】天意弄人——问号中竟跳出拦路小妖！（保底累计 ${s.eventPity}）`);
          const sub = Object.assign({}, node, { type: 'mob', name: '缘中妖兵', diff: node.diff || layer });
          NDX.LAYERS[layer][col] = sub;
          const gp = NDX.globalProgress(s);
          const mTier = NDX.monsterAt(Math.max(1, gp - 1));
          const _mobType2 = NDX.rollMob(s.act || 1); // 按地区抽取小怪类型（名字+阵营标签）
          const m = {
            type: 'mob',                // 普通小怪（事件触发）：同样纳入 3–6 回合节奏保障
            name: _mobType2.name,       // 小怪专属名
            tags: _mobType2.tags,       // 阵营标签（供法宝克制命中）
            hp: Math.round(160 + gp * 45),
            atk: Math.round(18 + gp * 4),
            dr: NDX.MONSTER_DR,
            matk: Math.round((mTier.matk || 20) * 0.7),
            mdef: mTier.mdef || 0.05,
          };
          NDX.scaleRunMods(m, s); // 本局劫难抉择即时改变怪物强度（逆强/渡弱）
          this.fight(m, sub.name, 'choices', () => {
            const amt = sub.gold || 20;
            const got = s.flags.nextGoldDouble ? amt * 2 : amt;
            s.flags.nextGoldDouble = false;
            s.gold += got;
            this.pushLog(`【缘·妖兵】击败，获得 ${got} 金`);
            this._mobBasicLoot(s, sub.name);
          });
          return;
        }
        if (roll === 'elite') {
          // 保底触发为劫(精英)：直接开打（逻辑同 case 'elite'）
          this.pushLog(`【缘】天意弄人——问号中竟是一场劫难！（保底累计 ${s.eventPity}）`);
          const sub = Object.assign({}, node, { type: 'elite', name: '缘中劫数', diff: node.diff || layer });
          // 若 ELITE_TABLE 中存在同名定义则合并掉落（默认保底精英无掉落）
          const _eds = NDX.enemyDefOf && NDX.enemyDefOf(sub);
          if (_eds) {
            if (_eds.drop != null) sub.drop = _eds.drop;
            if (_eds.material != null) sub.material = _eds.material;
          }
          NDX.LAYERS[layer][col] = sub;
          const mData = NDX.monsterAt(sub.diff || layer);
          const weak = s.flags.nextWeak || 0;
          s.flags.nextWeak = 0;
          const m = {
            hp: mData.hp,
            atk: Math.round(mData.atk * (1 - weak)),
            dr: mData.dr,
            matk: Math.round(mData.matk * (1 - weak)),
            mdef: mData.mdef,
            boss: !!mData.boss,
          };
          this.fight(m, sub.name, 'elitereward', null, sub);
          return;
        }
        // 未遇战 → 奇遇事件：从 EVENTS 池随机抽一个具体内容（地图只标?，进入才揭晓）
        // 问号节点保底收益：先得一笔金，再弹事件窗（事件内可选回血/得宝/善恶抉择/战）
        const got = Math.round(NDX.TREASURE_GOLD(layer) * 0.5);
        s.gold += got;
        this.pushLog(`【缘】未遇妖劫，反得一桩奇遇——先得 ${got} 金（保底已升至 ${Math.round((0.10 + 0.10 * s.eventPity) * 100)}%）`);
        // —— 送行事件强制插入：英雄历经特定劫难(initTrial)后、且尚未获得送行礼时，
        // 进入问号(?)节点优先触发「送行」事件，赠予三件初始装备+法宝(见 INIT_GIFT_EVENTS)。
        // 判定依据为「已通过劫难集合 s.trialsPassed 中是否存在 ≥ initTrial 的难号」，
        // 确保是「经过该难之后」的下一问号节点才触发，而非开局即给。
        const heroDefQ = NDX.HEROES[s.hero];
        const passedSomeInit = heroDefQ && heroDefQ.initTrial
          && (s.trialsPassed || []).some((t) => t.diff >= heroDefQ.initTrial);
        let ev, grantHero = null;
        if (passedSomeInit && !s.flags.gotInitGift[s.hero]) {
          const songEv = NDX.INIT_GIFT_EVENTS[(s.hero) + '_song'];
          if (songEv) { ev = { data: songEv }; grantHero = s.hero; }
        }
        // —— 灵兽进化劫难（宠物修订版 V8.17 §七）：问号节点中以约 35% + 保底
        //    判定命中「本章指定进化」→ 优先于通用奇遇弹出专属进化事件（见 equipment.js）。——
        if (!ev && NDX.rollPetEvolution) {
          const _evEvol = NDX.rollPetEvolution(s, s.act || (node && node.act) || layer);
          if (_evEvol) ev = { data: _evEvol };
        }
        // —— 双线事件池（V8.27 经文系统 / V8.53 分池+加权+保底）：
        //    渡线善系/逆线叛逆，独立问号节点；分池判定(30%装备池/70%普通池)，
        //    装备池内顶级×1.5加权，六道属性对应side加权；连续3问号未出装备则保底强制装备池。——
        if (!ev && NDX.sutraEventPool) {
          var _act = s.act || (node && node.act) || layer;
          var _gearPool = NDX.sutraGearPool ? NDX.sutraGearPool(s, _act) : [];
          var _normalPool = NDX.sutraNormalPool ? NDX.sutraNormalPool(s, _act) : [];
          var _allPool = _gearPool.concat(_normalPool);
          if (_allPool.length) {
            // ③保底：连续3个问号未出装备事件，下一个100%触发且强制装备池
            var _miss = s._gearEventMiss || 0;
            var _forceGear = (_miss >= 3) && (_gearPool.length > 0);
            var _triggerChance = _forceGear ? 1.0 : 0.5;
            if (Math.random() < _triggerChance) {
              // ④分池判定：保底强制装备池 / 30%装备池 / 70%普通池
              var _pickPool;
              if (_forceGear) {
                _pickPool = _gearPool;
              } else if (_gearPool.length > 0 && Math.random() < 0.3) {
                _pickPool = _gearPool;
              } else {
                _pickPool = _normalPool.length > 0 ? _normalPool : _gearPool;
              }
              if (_pickPool.length === 0) _pickPool = _allPool;
              // ①+②加权随机选事件
              var evt = NDX.weightedSutraPick ? NDX.weightedSutraPick(_pickPool, s) : _pickPool[Math.floor(Math.random() * _pickPool.length)];
              if (evt) {
                ev = { data: { title: evt.name, text: evt.text, opts: evt.opts.map(function (o) { return Object.assign({}, o, { _sutraEvId: evt.id }); }) } };
                if (NDX.sutraEventDone) NDX.sutraEventDone(s, evt.id);
                // ③保底计数：出了装备事件reset，否则++
                var _isGear = NDX._isGearEvent ? NDX._isGearEvent(evt) : !!(evt.opts && evt.opts.some(function (o) { return o && o.gear; }));
                s._gearEventMiss = _isGear ? 0 : ((s._gearEventMiss || 0) + 1);
              }
            } else {
              // 未触发双线事件池，也算一次miss
              s._gearEventMiss = (s._gearEventMiss || 0) + 1;
            }
          }
        }
        if (!ev) ev = NDX.pickEvent(s.act || (node && node.act) || 1, s);
        this.pushLog(`【缘·奇遇】${ev.data.title}`);
        // 缘分门槛（V8.17）：本章缘遇 +1（仅计真正奇遇，遇战不计）
        if (!s.fateStats) s.fateStats = { trials: 0, kills: 0, events: 0 };
        s.fateStats.events = (s.fateStats.events || 0) + 1;
        // 节点资源隔离：缘（?）节点只给金 + 奇遇事件（回血/得宝/善恶抉择/战），
        // 不再注入命痕——命痕严格只产于精英 / Boss，避免玩家走「缘线」也能补机制、
        // 弱化「劫难 vs 精英」的核心博弈取舍。
        s.pending = {
          kind: 'event',
          node,
          diff: node.diff || layer,
          title: ev.data.title,
          text: ev.data.text,
          opts: ev.data.opts,
          page: 0,
          then: null,
          grantHero: grantHero || undefined,
        };
        break;
      }
      case 'treasure': {
        // 宝窟：只产法宝、不产兵甲，与装备彻底区分（见 NDX.rollFabao）。
        // 取 2 件候选法宝，玩家任选其一；法宝已尽数在手则温养一件补满充能。
        const gold = node.gold || NDX.TREASURE_GOLD(layer);
        s.gold += gold;
        const fabaos = NDX.rollFabao(2, s, s.act);
        if (!fabaos.length) {
          // 可取法宝皆已持有：宝窟转而温养一件未圆满的法宝，补满充能
          const ownT = (s.equips || []).filter((e) => e.treasure && !e.noRecharge && (e.chargesLeft == null ? e.charges : e.chargesLeft) < (e.charges || 0));
          if (ownT.length) {
            const pick = ownT[NDX._rand(0, ownT.length - 1)];
            pick.chargesLeft = pick.charges || 0;
            this.pushLog(`【宝】${node.name}：开启得 ${gold} 金，并温养 ${pick.name}（充能补满）`);
          } else {
            this.pushLog(`【宝】${node.name}：开启得 ${gold} 金，法宝尽数圆满，宝窟再无可取。`);
          }
          s.pending = { kind: 'choices' };
          break;
        }
        this.pushLog(`【宝】${node.name}：开启得 ${gold} 金，可取一法宝`);
        // P3-1 新手指引：首次进入宝窟标记
        const _firstTreasure = !s.taught.treasure;
        if (_firstTreasure) s.taught.treasure = true;
        s.pending = {
          kind: 'gift',
          title: '宝窟 · 取一法宝',
          text: `宝窟幽深，金光满室。你拾得 ${gold} 金，于琳琅法宝中任取其一——此间只藏法宝，不藏兵甲。`,
          items: fabaos,
          firstTreasure: _firstTreasure,
        };
        break;
      }
      case 'branch': {
        const br = NDX.BRANCHES[node.branchId];
        s.pending = { kind: 'branch', title: br.title, opts: br.opts, branchId: node.branchId, page: 0 };
        break;
      }
      case 'shop': {
        let price = NDX.shopPrice(node.priceTier);
        // V8.58 朝代特色：商朝商店价格-10%（NDX.dynastyAdjust统一接口）
        if (NDX.dynastyAdjust) price = Math.round(NDX.dynastyAdjust(price, 'shop'));
        // 进坊市先检查可合成（材料换装备，强化随机性）
        const recs = NDX.availableRecipes(s);
        if (recs.length) {
          // P3-3 新手指引：首次遇到可合成配方时提示
          if (!s.flags._craftTaught) {
            s.flags._craftTaught = true;
            this.toast('⚒ 坊市合成：材料可合成为装备——集齐套装组件后坊市自动检测可合成配方，优先合成而非购买');
          }
          s.pending = { kind: 'craft', recipes: recs, hint: NDX.setProgressHint(s).join('；') };
          break;
        }
        const shopItems = NDX.rollEquips(2, s);
        if (!shopItems.length) {
          s.pending = { kind: 'choices' };
          break;
        }
        const shopPending = {
          kind: 'shop',
          tier: node.priceTier,
          items: shopItems.map((e) => ({ ...e, price: price })),
        };
        // §6.2 坊市兜底：未获「当前主导道」专属遗物时，坊市固定摆出其残片（确定性获取之一，幂等）。
        // 以 _relic 标记交由 buyShop 走 giveRelic（材料入库），避免误入 grantEquip。
        try {
          if (NDX.ZHUANJIE) {
            const _domDao = NDX.ZHUANJIE.dominantDao(s);
            const _r = NDX.ZHUANJIE.relicOf(_domDao);
            if (_r && !NDX.ZHUANJIE.haveRelic(s, _domDao)) {
              shopPending.items.push({ id: 'relic_' + _domDao, _relic: { dao: _domDao }, name: _r.name,
                ded: _r.route, price: price, desc: _r.name + '——' + _r.route });
            }
          }
        } catch (e) { console.error('坊市遗物 fail', e); }
        // 节点资源隔离：坊市只卖兵甲装备（纯资源），不附赠命痕——
        // 命痕严格只产于精英 / Boss，避免「坊市既补面板又补机制」破坏博弈。
        // P1-1 新手指引：首次进入坊市标记
        const _firstShop = !s.taught.shop;
        if (_firstShop) s.taught.shop = true;
        shopPending.firstShop = _firstShop;
        s.pending = shopPending;
        break;
      }
      case 'mirror': {
        // P4-4 新手指引：首次遇到业镜节点
        if (!s.flags._mirrorTaught) {
          s.flags._mirrorTaught = true;
          this.toast('🔮 业镜·轮回殿投影：照见前世今生——抉择可获特殊奖励或改变命运，谨慎选择');
        }
        // 业镜节点：天道劫中的轮回殿投影。调 NDX.buildMirror 动态构建抉择（按层/碎片/无尽）
        const data = NDX.buildMirror(node, layer, s);
        this.pushLog(`【业镜】${data.title}——${data.sub}`);
        if (data.fiveKey) s.flags._mirrorFivePending = data.fiveKey;
        s.pending = { kind: 'mirror', title: data.title, sub: data.sub, opts: data.opts, node, mirrorMeta: data };
        break;
      }
      default:
        s.pending = { kind: 'choices' };
    }
    // V8.35 离线存档：进入新节点结算完毕（pending 已就位）后自动落盘，退出可继续西行
    if (!s.over) this.autoSave();
  };
