// AUTO-GENERATED by _refactor_split.js — domain: sutra
// ============================================================
// 方案X1·持诵位（2026-09-05）：经匣内可将已合成全本设为持诵，
// 诵经技能随持诵经 chantSkill 变更；未设持诵回退本命/戾骨献祭。
// 存储：s.chantSutra = 全本 id（渡/逆皆可），本局内有效。
// ============================================================
NDX.Game.prototype.setChantSutra = function setChantSutra(fullId) {
  const s = this.state;
  if (!s) return;
  if (!NDX.canChantSutra(s, fullId)) {
    this.pushLog('【持诵】此经尚未合成全本，不可持诵。');
    return;
  }
  const f = NDX.sutraFullById(fullId) || NDX.niSutraFullById(fullId);
  const sk = (f && f.chantSkill) || null;
  s.chantSutra = fullId;
  this.pushLog(`【持诵】你将 ${f.name} 奉于舌端——诵经已易为「${sk ? sk.name : '本命诵经'}」${sk ? '：' + sk.desc : ''}。`);
  if (NDX.bus) { try { NDX.bus.emit('chant-sutra', { id: fullId, name: f.name }); } catch (e) {} }
  if (NDX.recordSutra) { try { NDX.recordSutra(fullId); } catch (e) {} }
};
NDX.Game.prototype.clearChantSutra = function clearChantSutra() {
  const s = this.state;
  if (!s || !s.chantSutra) return;
  this.pushLog('【持诵】你合上经卷，诵经归于本命。');
  s.chantSutra = null;
  if (NDX.bus) { try { NDX.bus.emit('chant-sutra', { id: null }); } catch (e) {} }
};
NDX.Game.prototype.chooseSutra = function chooseSutra(id) {
    const s = this.state;
    if (!NDX.sutraSystemUnlocked || !NDX.sutraSystemUnlocked(s)) {
      this.pushLog('【佛经】经卷蒙尘，尚缺「自取西经·逆天改命」之缘，全本难成。');
      s.pending = { kind: 'choices' };
      return;
    }
    const full = NDX.sutraFullById(id);
    if (!full) { s.pending = { kind: 'choices' }; return; }
    if ((s.sutras || []).indexOf(full.id) >= 0 || (s.sutraBackpack || []).indexOf(full.id) >= 0) {
      this.pushLog(`【佛经】${full.name} 已合成，毋庸再铸。`);
      s.pending = { kind: 'choices' };
      return;
    }
    // P5-4 新手指引：首次合成经文全本时提示
    if (!s.flags._sutraFullTaught) {
      s.flags._sutraFullTaught = true;
      this.toast(`📜 经文合本：${full.name}——散件集齐铸成全本，经义自动投入主道途生效（气血·攻伐·法伤·御念·自愈）`);
    }
    const frags = s.sutraFrags || {};
    if (!full.frags.every((fid) => (frags[fid] || 0) >= 1)) {
      this.pushLog(`【佛经合成失败】${full.name} 散件未齐。`);
      s.pending = { kind: 'choices' };
      return;
    }
    // 消耗碎片（每部全本各需 1 段）
    full.frags.forEach((fid) => { frags[fid] -= 1; if (frags[fid] <= 0) delete frags[fid]; });
    // V3 §二 自动路由：合成入背包 → 立即按当前主道自动投入生效
    NDX.sutraBackpackOf(s).push(full.id);
    NDX.routePendingSutras(s);
    this.pushLog(`【佛经合成】散件归一经卷成——《${full.name}》！${full.desc}`);
    if (NDX.bus) NDX.bus.emit('loot', { name: full.name, desc: full.desc, mode: 'sutra' });
    // 仍可继续合成其他全本则停留在佛经面板；否则（通关态）进入结局
    if (NDX.availableSutras(s).length) s.pending = { kind: 'sutra' };
    else if (s.over && s.over.win) s.pending = { kind: 'gameover' };
    else s.pending = { kind: 'choices' };
    this._syncAch();
  };
NDX.Game.prototype.dropSutraFrag = function dropSutraFrag(opt) {
    const s = this.state;
    if (!(NDX.sutraSystemUnlocked && NDX.sutraSystemUnlocked(s))) return;
    const cycle = (typeof NDX.getCycle === 'function') ? NDX.getCycle() : (s.flags.cycle || 1);
    if (cycle < 2) return; // 一周目锁掉落
    const all = NDX.SUTRA_FRAGS || [];
    if (!all.length) return;
    const fate = (opt && opt.fate) || null;
    const prob = fate === '逆' ? 0.7 : 0.15; // 逆道高概率 / 其它低概率
    if (Math.random() > prob) return;
    s.sutraFrags = s.sutraFrags || {};
    // V9.6 六道主干（GDD §2.2 经文池）：渡片抽取出「按试炼序轮转」改为「六道数量 × 主道」加权，
    //   使经文碎片出现概率与其他池同口径受六道偏置（软饱和）；无信号时回落均匀随机（零回归）。
    const _fragDao = (frag) => (NDX.SUTRA_DAO_TAG && frag && frag.sutra) ? NDX.SUTRA_DAO_TAG['su_full_' + frag.sutra] : null;
    const _mainD = (NDX.DaoSystem && NDX.DaoSystem.getMainDao) ? NDX.DaoSystem.getMainDao(s) : null;
    const _wOf = (frag) => {
      let w = 1;
      const d = _fragDao(frag);
      if (d && NDX.daoPoolMult) w *= NDX.daoPoolMult(s, d);
      if (d && _mainD && d === _mainD) w *= (NDX.DAO_EQUIP_W || 4);
      return w;
    };
    const _wi = NDX.runWeightedPick ? NDX.runWeightedPick(all.map(_wOf)) : Math.floor(NDX.runRandom() * all.length);
    const idx = (_wi < 0 || _wi >= all.length) ? Math.floor(NDX.runRandom() * all.length) : _wi;
    const fid = all[idx].id;
    if (!s.sutraFrags[fid]) {
      s.sutraFrags[fid] = 1;
      if (NDX.addSutraPiece) NDX.addSutraPiece(s, 'ferry'); // 模块八·拼篇累计（渡侧）
      const f = NDX.sutraFragById(fid);
      this.pushLog(`【佛经散件】沿途拾得 ${f.name}（${f.note}）`);
    }
  };
