// AUTO-GENERATED by _refactor_split.js — domain: core
NDX.Game.prototype._tryRevive = function _tryRevive() {
    const s = this.state;
    const st = this.stats();
    const eq = (s.equips || []).find((e) => {
      if (!e.treasure) return false;
      const T = NDX.TREASURES && NDX.TREASURES[e.treasureId];
      if (!T || !T.effect) return false;
      // 救命毫毛：effect.revive 标记；涅槃莲等：phase=dead + auto 自动触发
      if (!T.effect.revive && !(T.phase === 'dead' && T.auto)) return false;
      // V8.28：护身法宝也须在法宝栏内方可替劫复活
      if (NDX.isEquipActive && !NDX.isEquipActive(s, e.id)) return false;
      const ch = e.chargesLeft == null ? (e.charges || 0) : e.chargesLeft;
      return ch > 0;
    });
    if (!eq) return false;
    const T = NDX.TREASURES && NDX.TREASURES[eq.treasureId];
    // P6-1 新手指引：首次触发复活替劫时提示
    if (!s.flags._reviveTaught) {
      s.flags._reviveTaught = true;
      this.toast('🪶 替劫复活：护身法宝(救命毫毛/涅槃莲)自动消耗一次充能，满血重生继续战斗——法宝栏内的护身法宝方可替劫');
    }
    const chBefore = eq.chargesLeft == null ? (eq.charges || 0) : eq.chargesLeft;
    eq.chargesLeft = chBefore - 1;
    s.hp = st.ti.maxHp; // 复活满血
    // 区分法宝类型输出日志
    if (T && T.treasureId === 'np_lian' || (eq.treasureId === 'np_lian')) {
      this.pushLog(`【涅槃莲】莲瓣合拢，业火焚身——你于涅槃中满血重生，继续迎战！（余 ${eq.chargesLeft} 次）`);
      if (eq.chargesLeft <= 0) this.pushLog(`【涅槃莲】莲瓣已尽，再无涅槃可期，珍重。`);
    } else {
      this.pushLog(`【救命毫毛】南海观世音所赐三根救命毫毛之一根飘落，替你挡下死劫——你于满血中重生，继续迎战！（余 ${eq.chargesLeft} 根）`);
      if (eq.chargesLeft <= 0) this.pushLog(`【救命毫毛】三根已尽，再无毫毛可替你挡劫，珍重。`);
    }
    return true;
  };
NDX.Game.prototype.resolveHudBurst = function resolveHudBurst() {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'fight' || !p.res || !p.res.roundsDetail) return false;
    if (p.awaitOp > 0) return false;          // 已在择机窗口：改走操作点面板
    if (p.awaitStageBreak > 0) return false;  // 破韧窗口不点爆发
    // 允许自动战斗中手动点击爆发倾泻气势：与 main.js op-burst-hud 的「自动中手动点击爆发」意图对齐
    // （自动仅代点攻/经，关键时刻仍由玩家手动掌握爆发节奏 —— 破爆发玩法核心）
    const atRound = p.roundIdx + 1;
    const rd = p.res.roundsDetail[p.roundIdx];
    const tier = (rd && rd.momentumTier) || 0;
    if (tier <= 0) return false;              // 当前回合无气势
    try {
      NDX.applyMomentumBurst(p.res, atRound);
      const opRd = p.res.roundsDetail[p.roundIdx];
      if (opRd) { p.pHp = opRd.pHpAfter; p.mHp = opRd.mHpAfter; }
      // 若该回合恰为操作点回合，爆发后记账防 driveFight 二次弹窗
      p.opHandled = p.opHandled || [];
      if (rd.operationPoint && !p.opHandled.includes(atRound)) p.opHandled.push(atRound);
      const tierName = ['', '一势', '二势', '三势'][tier] || '';
      this.pushLog(`【气势爆发·瞬时】第 ${atRound} 合，倾泻${tierName}气势——爆发重创！`);
      try { if (NDX.bus) NDX.bus.emit('battle-fx', { type: 'opaction', action: 'burst' }); } catch (e) {}
    } catch (e) {
      this.pushLog(`【气势爆发·瞬时】结算异常：${e && e.message ? e.message : e}（已跳过）`);
      return false;
    }
    return true;
  };
NDX.Game.prototype.resolveManualActive = function resolveManualActive(kind, style) {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'fight' || !p.res) return false;
    if (p.awaitOp > 0 || p.awaitStageBreak > 0) return false; // 择机/破韧窗口内不抢操作
    const roundIdx = p.roundIdx >= 0 ? p.roundIdx : 0;
    const last = (p.activeCdAt || {})[kind] != null ? p.activeCdAt[kind] : -99;
    const heroId0 = s.hero || 'tangseng';
    const probe = NDX.activeSkill({ ti: s.bonusTi, yuan: s.bonusYuan }, { maxHp: 1 }, kind, s);
    const cdNeed = probe ? probe.cd : 2;
    if (roundIdx - last < cdNeed) {
      this.pushLog(`【${kind === 'atk' ? '攻击' : kind === 'chant' ? '诵经' : '绝招'}】气机未复（还需 ${cdNeed - (roundIdx - last)} 拍），暂不可发`);
      return false;
    }
    const heroId = s.hero || 'tangseng';
    const player = { ti: s.bonusTi, yuan: s.bonusYuan, maxHp: (s.bonusTi && s.bonusTi.maxHp) || 0 };
    // V8.40 技能进阶：检测「全部持有」劫印组合（V3 §1.1 全量自动生效），解锁技能进阶
    const _seals = ((s && s.seals) || []).filter((x) => x && x.dao);
    const _daoCount = {};
    (_seals || []).forEach((sl) => { if (sl && sl.dao) _daoCount[sl.dao] = (_daoCount[sl.dao] || 0) + 1; });
    const _skillAdvance = { atk: null, atkStyles: [], chant: null, ult: null };
    if ((_daoCount['战'] || 0) >= 3) { _skillAdvance.atkStyles.push('combo'); _skillAdvance.atk = 'combo'; }
    if ((_daoCount['夺'] || 0) >= 3) { _skillAdvance.atkStyles.push('burst'); if (!_skillAdvance.atk) _skillAdvance.atk = 'burst'; }
    if ((_daoCount['逆'] || 0) >= 3) { _skillAdvance.atkStyles.push('pierce'); if (!_skillAdvance.atk) _skillAdvance.atk = 'pierce'; }
    // 持久化到 pending，供 UI 渲染多风格切换按钮（atkStyles）
    p._atkStyles = _skillAdvance.atkStyles.slice();
    // 诵经进阶改由 combat.js activeSkill 依据「已装备劫印」实时判定（同源、避免囤印冲突），此处不再重复计算
    const _ultTier = NDX.ultimateTier ? NDX.ultimateTier(s) : 0;
    if (_ultTier >= 3) _skillAdvance.ult = 'lifesteal';
    else if (_ultTier >= 2) _skillAdvance.ult = 'shield';
    else if (_ultTier >= 1) _skillAdvance.ult = 'execute';
    player._skillAdvance = _skillAdvance;
    // 方案X2·六道攻式（手动三键）：透传当前主要道途攻式（activeSkill 消费）
    player.daoAtk = NDX.daoAtkStyleOf ? NDX.daoAtkStyleOf(s) : null;
    // 隐道·影遁必杀：本回合玩家攻击前若已闪避蓄势（roundsDetail 预演算快照），手动攻击继承必爆
    const _rdNow = (p.res && p.res.roundsDetail) ? p.res.roundsDetail[roundIdx] : null;
    if (_rdNow) player.daoEvadeReady = !!_rdNow.daoEvadeBefore;
    const monster = { maxHp: p.res.maxMHp || 1, dr: (p.res.monsterDr != null ? p.res.monsterDr : 0), boss: !!(p.res.monsterTags && p.res.monsterTags.includes('boss')), hp: p.mHp || 0 };
    // V8.45 手动连招：玩家指定 atk 风格（需已解锁于 atkStyles）时，临时覆盖本次 atk 风格
    if (kind === 'atk' && style && _skillAdvance.atkStyles.indexOf(style) >= 0) {
      player._skillAdvance.atk = style;
    }
    const act = NDX.activeSkill(player, monster, kind, s);
    if (!act) return false;
    // V8.47 战斗完善：状态堆叠协同 / 易伤标记 / 连段分层 / 搓招奥义 / 怪物叠甲·Boss控制免疫 /
    // 气势联动 / 宠物协同 / 夺盾反转。数值真源全在 combat.js（NDX.cfx*），此处仅薄接线施加倍率。
    const _now = Date.now();
    const _isManual = !p.autoFight;
    const _fx = p.combatFx || (NDX.cfxInit ? NDX.cfxInit(p.monster) : {});
    p.combatFx = _fx;
    // 1) 基础连击链（含连段分层递增 3/6/9）
    let _crit = false, _comboMul = 1, _tier = 0;
    if (kind === 'atk' || kind === 'chant') {
      const _step = NDX.comboBasicStep ? NDX.comboBasicStep(p, _isManual, _now) : { mul: 1, crit: false, tier: 0 };
      _comboMul = _step.mul; _crit = _step.crit; _tier = _step.tier;
      if (_crit) {
        this.pushLog('【连击】连续基础攻击达成，触发暴击！' + (_tier > 1 ? ('（连段×' + _tier + '，伤害×' + _comboMul.toFixed(2) + '）') : ('本次伤害 ×' + _comboMul.toFixed(2))));
        if (NDX.bus) { try { NDX.bus.emit('battle-fx', { type: 'crit', side: 'you' }); } catch (e) {} }
      }
    }
    // 2) 搓招序列：atk→atk→chant → 蓄力奥义就绪；本次为 atk 且就绪则倾泻奥义
    let _qiaoMul = 1;
    if (NDX.cfxQiaoStep) {
      NDX.cfxQiaoStep(p, kind);
      if (kind === 'atk' && p.combatFx.qiaoReady) {
        _qiaoMul = NDX.CFX_QIAO_MUL || 2.5; p.combatFx.qiaoReady = false;
        this.pushLog('【奥义】搓招连携·蓄力奥义倾泻！本次伤害 ×' + _qiaoMul);
      }
    }
    // 3) 手动风格串联（combo→burst→pierce）：手操深度奖励；达成时对非 Boss 施加冻结控制
    let _chainMul = 1, _chainTrig = false;
    if (kind === 'atk' && style && _skillAdvance.atkStyles.indexOf(style) >= 0) {
      p.comboChain = p.comboChain || [];
      p.comboChain.push(style);
      const _chain = NDX.comboChainBonus ? NDX.comboChainBonus(p.comboChain) : { mul: 1, triggered: false };
      _chainMul = _chain.mul; _chainTrig = _chain.triggered;
      if (_chainTrig) {
        p.comboChain = [];
        this.pushLog('【连招】连击→连爆→透骨 一气呵成！本次伤害 ×' + _chainMul);
        const _ctl = NDX.cfxApplyDebuff ? NDX.cfxApplyDebuff(_fx, 'frozen', 1) : null;
        if (_ctl) this.pushLog(_ctl);
      }
    }
    // 4) 攻击风格附带 debuff（手操策略）：透骨(逆)破防施加易伤；缘→业火施加标记
    if (_isManual && kind === 'atk' && style === 'pierce') { const _t = NDX.cfxApplyDebuff ? NDX.cfxApplyDebuff(_fx, 'vuln', 3) : null; if (_t) this.pushLog(_t); }
    if (kind === 'chant' && act.dot) { const _t = NDX.cfxApplyDebuff ? NDX.cfxApplyDebuff(_fx, 'mark', 1) : null; if (_t) this.pushLog(_t); }
    // 5) 综合进攻倍率（状态堆叠协同 + 易伤 + 标记 + 冻结 + 沉默 - 怪物叠甲）
    const _off = NDX.cfxOffenseMul ? NDX.cfxOffenseMul(_fx) : { mul: 1, parts: [] };
    const _total = _comboMul * _qiaoMul * _chainMul * _off.mul;
    if (_total > 1) {
      act.dmg = Math.max(1, Math.round((act.dmg || 0) * _total));
      act.trueDmg = Math.max(1, Math.round((act.trueDmg || 0) * _total));
      act.note = (act.note || '') + (_crit ? ('·暴击×' + _comboMul.toFixed(2)) : '') + (_qiaoMul > 1 ? ('·奥义×' + _qiaoMul) : '') + (_chainTrig ? ('·连招×' + _chainMul) : '') + _off.parts.join('');
      act.crit = _crit || _qiaoMul > 1;
    }
    // 6) 夺盾反转：奥义击穿怪物叠甲 → 反射真伤并清空甲
    if (_qiaoMul > 1 && _fx.armor > 0) {
      const _ref = Math.round((act.dmg || 0) * (NDX.CFX_SHIELD_REV_STEP || 0.3) * _fx.armor);
      act.trueDmg = Math.max(1, (act.trueDmg || 0) + _ref); _fx.armor = 0;
      this.pushLog('【夺盾反转】破甲反射真伤 +' + _ref);
    }
    // 7) 气势-连招联动：连击暴击为后续回合积攒气势
    if (_crit && p.res) { NDX.cfxBumpMomentum && NDX.cfxBumpMomentum(p.res, roundIdx, 1); }
    // 8) 宠物连招协同：连击暴击时灵宠追加小额真伤
    if (_crit && NDX.cfxPetSynergy) { const _ps = NDX.cfxPetSynergy(s); if (_ps > 0) { act.trueDmg = Math.max(1, (act.trueDmg || 0) + _ps); this.pushLog('【灵宠协同】灵宠趁机袭扰真伤 +' + _ps); } }
    // 9) 怪物叠甲累积（血量尚足时每次玩家行动 +1）
    if (NDX.cfxMonsterArmorTick) { const _mr = (p.monster && p.monster.maxHp) ? (p.mHp / (p.monster.maxHp || 1)) : 1; NDX.cfxMonsterArmorTick(_fx, _mr); }
    // 10) 计时类 debuff 衰减
    if (NDX.cfxTickDown) NDX.cfxTickDown(_fx);
    // V8.44 接引使者教学战：绝招前怪物血条近乎满格（血条无上限），攻/经无法击杀——唯绝招强制终结
    if (p.teach === 'tutorial' && kind === 'ult' && p.res) {
      act.dmg = Math.max(act.dmg || 0, p.res.maxMHp || 0);
    }
    // 戾骨献祭每场限 1 次
    if (act.kind === 'chant' && act.name === '戾骨献祭' && p.ultUsed) {
      this.pushLog('【戾骨献祭】本场已用过一次，逆经之刀已钝');
      return false;
    }
    NDX.applyActiveIntervention(p.res, roundIdx + 1, act);
    const opRd = p.res.roundsDetail[roundIdx];
    if (opRd) { p.pHp = opRd.pHpAfter; p.mHp = opRd.mHpAfter; }
    p.activeCdAt = p.activeCdAt || { atk: -99, chant: -99, ult: -99 };
    p.activeCdAt[kind] = roundIdx;
    if (act.name === '戾骨献祭') {
      p.ultUsed = true;
      // V8.63 P1-6 论道存留线门槛：局级累计戾骨献祭使用次数（了断之世不带火气）
      const _ls = (this.state.lundaoStats = this.state.lundaoStats || {});
      _ls.liguUsed = (_ls.liguUsed || 0) + 1;
    }
    // 戾骨代价：清气势 + 本场承伤 +20%（就地修正后续玩家承伤）
    if (act.cost && act.cost.momentum === 'clear') {
      const list = p.res.roundsDetail || [];
      for (let i = Math.max(0, roundIdx); i < list.length; i++) { list[i].momentum = 0; list[i].momentumTier = 0; }
      if (act.cost.incomingDmgMul) { p.incomingDmgMul = (p.incomingDmgMul || 1) + act.cost.incomingDmgMul; }
    }
    this.pushLog(`【${act.name}】${act.note}`);
    // V8.58 修复：渡道 alt 路径 'chant' 配额计数——玩家使用诵经技能时累计 chant 配额
    // 原配额配置 alt:{chant:N+1} 但全仓无 addQuota('chant') 调用，导致替代达标线永不可达
    try {
      if (kind === 'chant' && NDX.quotaEnabled && NDX.quotaEnabled(s.act) && NDX.addQuota) {
        NDX.addQuota(s, 'chant', 1);
      }
    } catch (e) { /* noop */ }
    // 三键发声：诵经走梵呗 worship，绝招走专用 ult（P1-7），攻击走 skill；回血、护盾各配一音
    NDX.sfx(kind === 'chant' ? 'worship' : kind === 'ult' ? 'ult' : 'skill');
    if (act.heal > 0) { this.pushLog(`【${act.name}】回血 +${act.heal}`); NDX.sfx('heal'); }
    if (act.shield > 0) { this.pushLog(`【${act.name}】护盾 +${act.shield}`); NDX.sfx('guard'); }
    // V8.40 战意/经力系统：通过统一模块NDX.BattleResource更新资源
    const BR = NDX.BattleResource;
    if (kind === 'atk') {
      const oldZY = p.zhanYi || 0;
      const oldOv = p.zhanYiOverflow || 0;
      if (BR && typeof BR.gainZhanYi === 'function') {
        BR.gainZhanYi(p);
      } else {
        const gain = Math.max(1, Math.round((p.zhanYiGain || 1) * 10) / 10);
        p.zhanYi = Math.min(p.zhanYiMax, (p.zhanYi || 0) + gain);
      }
      if ((p.zhanYi || 0) > oldZY) {
        setTimeout(() => {
          const el = document.querySelector('.fb-resource.zhanyi');
          if (el) { el.classList.add('gain'); setTimeout(() => el.classList.remove('gain'), 500); }
        }, 50);
      }
      // P2-1 战意昂扬（满而不溢）：战意已满时溢出攒层，绝招时每层 +15% 伤害
      if ((p.zhanYiOverflow || 0) > oldOv) {
        this.pushLog(`【战意昂扬】战意已满，溢出化为昂扬×${p.zhanYiOverflow}（绝招时每层 +15% 伤害）`);
      }
    } else if (kind === 'chant') {
      const oldJL = p.jingLi || 0;
      let triggered = false;
      if (BR && typeof BR.gainJingLi === 'function') {
        const result = BR.gainJingLi(p);
        triggered = result.triggered;
      } else {
        if (p.jingLiReady) {
          p.jingLi = 0;
          p.jingLiReady = false;
          triggered = true;
        } else {
          const gain = Math.max(1, Math.round((p.jingLiGain || 1) * 10) / 10);
          p.jingLi = Math.min(p.jingLiMax, (p.jingLi || 0) + gain);
          if (p.jingLi >= p.jingLiMax) p.jingLiReady = true;
        }
      }
      if (triggered) {
        this.pushLog('【金刚经】经力圆满，诵经触发金刚降世！');
      } else if ((p.jingLi || 0) > oldJL) {
        setTimeout(() => {
          const el = document.querySelector('.fb-resource.jingli');
          if (el) { el.classList.add('gain'); setTimeout(() => el.classList.remove('gain'), 500); }
        }, 50);
        if (p.jingLiReady) this.pushLog('【经力圆满】下次诵经将触发金刚经！');
      }
      // P2-1 经力化雨（满而不溢）：溢流经力已由 combat.js 按层加成本次诵经回血，此处消耗层数并播报
      const _jyOv = p.jingLiOverflow || 0;
      if (_jyOv > 0) {
        p.jingLiOverflow = 0;
        this.pushLog(`【经力化雨】溢流经力尽数化雨，${_jyOv} 层济生回血！`);
      }
    } else if (kind === 'ult') {
      const totalPower = (p.zhanYi || 0) + (p.jingLi || 0);
      if (totalPower > 0) {
        // P0-1：此前此处为 totalPower × rate × 100，把资源层数也乘进百分比，20 层资源 × 0.25 会显示「+500%」。
        // ultBonusPerLayer 本身即伤害加成比率，直接 ×100 才是正确百分比。
        const bonus = p.ultBonusPerLayer ? `，额外伤害+${Math.round((p.ultBonusPerLayer || 0) * 100)}%` : '';
        this.pushLog(`【绝招】消耗战意${p.zhanYi || 0}层+经力${p.jingLi || 0}层，威力大增${bonus}！`);
      }
      if (BR && typeof BR.consumeForUlt === 'function') {
        const cu = BR.consumeForUlt(p);
        if (cu && cu.overflow > 0) this.pushLog(`【战意昂扬】满溢战意×${cu.overflow} 尽数倾注绝招，每层 +15% 伤害！`);
      } else {
        p.zhanYi = 0;
        p.jingLi = 0;
        p.jingLiReady = false;
      }
    }
    // 表现层：震屏 + 刀光 + 台词
    if (NDX.bus) {
      NDX.bus.emit('battle-fx', { type: act.kind === 'ult' ? 'burst' : 'slash', kind: act.kind, dmg: act.dmg, text: act.name });
    }
    return true;
  };
NDX.Game.prototype.aiAutoSkill = function aiAutoSkill(roundIdx) {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'fight' || !p.res) return 'atk';
    const at = p.activeCdAt || {};
    const rIdx = roundIdx >= 0 ? roundIdx : 0;
    const heroId = s.hero || 'tangseng';
    const isBoss = !!(p.res.monsterTags && p.res.monsterTags.includes('boss'));
    const isElite = !!(p.monster && p.monster.type === 'elite');
    // 探测各键 CD
    const probeUlt = NDX.ultimateOf ? NDX.ultimateOf(heroId, NDX.ultimateTier ? NDX.ultimateTier(s) : 1) : null;
    const cdUlt = probeUlt ? probeUlt.cd : 5;
    const cdChant = 1;  // V8.38 诵经CD 2→1，加快战斗节奏
    const lastUlt = at.ult != null ? at.ult : -99;
    const lastChant = at.chant != null ? at.chant : -99;
    const ultReady = (rIdx - lastUlt) >= cdUlt && !p.ultUsed;
    const chantReady = (rIdx - lastChant) >= cdChant;
    // V8.46 自动战斗仅代点基础攻击（atk / chant）；绝招与法宝一律不自动，须玩家手动触发。
    // 基础攻击连续命中可累积暴击链（与手动同源，自动也出暴击提示），即「自动战斗的优势在于 comb 链」。
    const hpRatio = (p.maxHp || 1) ? (p.pHp || 0) / (p.maxHp || 1) : 1;
    // Boss/精英血量危急时自动诵经（禅光·回血护身），仍属基础攻击范畴
    if ((isBoss || isElite) && chantReady && hpRatio < 0.6) return { kind: 'chant' };
    // C5 自动极简连招：在玩家已解锁的 atk 风格间轮换（combo->burst->pierce），使挂机真正用上道途投资的解锁风格，
    // 并因此累积连招加成（resolveManualActive 的 _isManual 大门已对「显式传入 style」放开）。
    const _styles = (p._atkStyles && p._atkStyles.length) ? p._atkStyles : null;
    if (_styles) {
      if (p._autoStyleCursor == null) p._autoStyleCursor = 0;
      const _st = _styles[p._autoStyleCursor % _styles.length];
      p._autoStyleCursor = (p._autoStyleCursor + 1) % _styles.length;
      return { kind: 'atk', style: _st };
    }
    return { kind: 'atk' };
  };
NDX.Game.prototype.skipOp = function skipOp() {
    const s = this.state;
    const p = s.pending;
    if (!p || p.kind !== 'fight' || p.awaitOp < 0) return false;
    const r = p.awaitOp;
    p.opHandled = p.opHandled || [];
    p.opHandled.push(r);
    p.awaitOp = -1;
    p.opInfo = null; // 操作点倒计时自清理
    this.pushLog(`【临阵】第 ${r} 合，你按兵不动，静观其变`);
    return true;
  };
NDX.Game.prototype._yezangluOnWin = function _yezangluOnWin(p, wnode) {
    const s = this.state;
    const m = p.monster || {};
    const name = m.name || (wnode && wnode.name) || '';
    const isTJ = NDX.isTianJie();
    const isBoss = !!(wnode && (wnode.boss || wnode.type === 'boss' || wnode.mirrorBoss)) || !!m.boss;
    // 怪物名 -> 拓印 id 模糊匹配
    const matchRub = (nm) => {
      for (const id in NDX.MONSTER_RUBBING) {
        if (nm.indexOf(NDX.MONSTER_RUBBING[id].name) >= 0) return id;
      }
      return null;
    };
    const rubId = matchRub(name);
    if (rubId) {
      // 天道劫：必掉当前战斗神将/大妖拓印；普通战斗：低概率掉小妖拓印
      const small = NDX.MONSTER_RUBBING[rubId].group === 'yaomo_fan';
      if (isTJ || isBoss || !small || Math.random() < 0.15) {
        if (NDX.addMonsterRubbing(rubId)) {
          const def = NDX.MONSTER_RUBBING[rubId];
          this.pushLog(`【业藏录·拓印】获得「${def.name}」拓印（${def.group === 'tianting_gods' ? '天庭诸神图' : def.group === 'yaojun_wang' ? '大妖魔君谱' : '山野妖魔录'}）。`);
          // P3-2 新手指引：首次获得业藏录拓印时提示
          if (!s.flags._yezangTaught) {
            s.flags._yezangTaught = true;
            this.toast('📖 业藏录：伏妖即拓印——收齐妖物图鉴可阅其业障纪事，图鉴进度提供永久微量加成');
          }
        }
      }
    }
    // 传记解锁：首次击败 Boss/大妖/天将，按序解锁一篇未阅的「业障纪事」
    if (isBoss || isTJ) {
      const bios = Object.keys(NDX.YEZANG_BIOGRAPHY);
      const yz = NDX.yezangluState();
      const next = bios.find((b) => !yz.bio[b]);
      if (next) {
        const r = NDX.readBiography(next);
        if (r.ok) {
          const b = NDX.YEZANG_BIOGRAPHY[next];
          this.pushLog(`【业藏录·纪事】初破强敌，解锁《${b.name}》——前往业藏录可阅其业障纪事。`);
        }
      }
    }
  };
NDX.Game.prototype.chooseNext = function chooseNext(layer, col) {
    this.state.pending = null;
    this.enterNode(layer, col);
  };
NDX.Game.prototype.isTsSetComplete = function isTsSetComplete() {
    const s = this.state;
    const need = ['ts_robe_top', 'ts_staff_top', 'ts_bowl_top'];
    return need.every((id) => s.equips.some((e) => e.id === id));
  };
NDX.Game.prototype.autoCombineShrine = function autoCombineShrine(s) {
    s = s || this.state;
    if (!NDX.autoCombineShrine) return;
    const r = NDX.autoCombineShrine(s);
    if (r && r.count) {
      const names = r.made.map((id) => (NDX.lootById(id) || { name: id }).name);
      s._autoCombineMade = names;
      this.pushLog(`【自动合成】土地庙炉火自燃，熔铸进阶装备 ${r.count} 件：${names.join('、')}`);
      NDX.sfx && NDX.sfx('craft');
    } else {
      s._autoCombineMade = [];
    }
  };
NDX.Game.prototype._openFailSettlement = function _openFailSettlement() {
    const s = this.state;
    try {
      const node = NDX.registerVault(s, 'tomb', s.act);
      if (node) {
        const _dyn = (NDX.getDynasty ? NDX.getDynasty() : { name: '唐' }).name || '唐';
        const _loc = (NDX.ACT_NAMES && NDX.ACT_NAMES[Math.min((s.act || 1) - 1, (NDX.ACT_NAMES || []).length - 1)]) || ('第' + (s.act || 1) + '地区');
        s._tombAt = _loc; // V8.61：死亡结算页「衣冠冢立于何处」预告消费
        this.pushLog(`【衣冠冢】你倒于${_loc}——碑立当道。${_dyn}诸世行脚历此，可回访拾遗（装备/组件 二选一，次数越丰衰减越盛）。`);
      }
    } catch (e) { /* noop */ }
    s.pending = { kind: 'gameover' };
    this.render();
  };
NDX.Game.prototype._chapterOpenNarration = function _chapterOpenNarration(s, relic) {
    // 用「当前实龄」起笔（s.life 为连续岁数的寿命），而非从 20 岁硬算，
    // 让每地区开局的「主角目前 XX 岁 XX 月」随本局真实消耗而变化。
    const lf = Math.max(0, (s && s.life) || NDX.LIFE.START);
    const _yrs = Math.floor(lf), _mo = Math.round((lf - _yrs) * 12);
    const _name = (s && s.heroName) || '取经人';
    const prevRegion = NDX.ACT_NAMES[Math.min(Math.max(1, s.act - 1), NDX.TOTAL_ACTS) - 1] || `第 ${s.act - 1} 地区`;
    const relicLine = relic ? `${prevRegion}关隘的残魂化作一枚遗物沉入体内——「${relic.name}」自此随行。` : '';
    const names = (s.relics || []).map((rid) => ((NDX.BOSS_RELICS || []).find((r) => r.id === rid) || {}).name).filter(Boolean);
    // —— 每难必过：不再设观音任务门（V8.26 起取消观音指引），通过当前地区全部劫难即自动进入下一地区 ——
    const passNote = `\n\n西行至此，劫难桩桩件件皆是必经——无有指引，唯向前叩关；历尽本区群难，自会踏入下一程。`;
    return `师徒四人寻了处背风处，进得一副汤火，瘴雨暂歇——众人各自休整了几日。${_name}临水理了理裂袈裟，眼前又浮起那一句句劫文。西行至今，${_name}已 ${_yrs} 岁 ${_mo} 月。\n\n${relicLine}\n前路仍是满纸妖劫，四人整束行装，继续踏上西行之路。${names.length ? `（随身遗物：${names.join('、')}）` : ''}${passNote}`;
  };
NDX.Game.prototype.choices = function choices() {
    const s = this.state;
    // 未完成当前节点的选择（劫难/缘/体愿/分支/坊市/歇脚等面板仍开启）时，禁止前进。
    // 只有 pending 为空或已是"已结算可继续"状态，才允许点击下一节点。
    const pending = s.pending;
    const canAdvance = !pending || pending.kind === 'choices';
    if (!canAdvance) return [];
    const raw = NDX.nextNodes(s.layer, s.col);
    if (raw.length) {
      // 任务驱动关隘：下一跳若含「未达标的关隘 Boss」→ 不让它可战，改由随机补充路径延伸，
      // 玩家可一直走下去、顺带补足任务；任务全达标后才收敛 Boss。
      if (!NDX.fateGateCheck(s).met && raw.some((n) => {
        const nd = NDX.LAYERS[n.layer] && NDX.LAYERS[n.layer][n.col];
        return nd && nd.type === 'boss';
      })) {
        s._tailOpen = true;
        return NDX._tailStep(s);
      }
      return raw;
    }
    // 已到地图末端（动态尾）：依任务是否达标决定「再补一节随机寻缘」或「收敛为 Boss」
    if (s._tailOpen || !NDX.fateGateCheck(s).met) {
      s._tailOpen = true;
      return NDX._tailStep(s);
    }
    return raw;
  };
